/*Copyright (c) 2011-2013 Moat Inc. All Rights Reserved.*/
try{(function(q,u){function X(){for(var a in r)r.hasOwnProperty(a)&&l.e.i(r[a]);for(a=0;a<N.length;a++)window.clearTimeout(N[a]);for(a=0;a<O.length;a++)window.clearInterval(O[a]);l.f.k()}var l={};(function(a){function h(a){return a&&a.document&&a.location&&a[b+d]&&a[e+f]}function g(a){if(null==a||h(a))return!1;var b=a.length;return 1===a.nodeType&&b?!0:"string"===typeof a||c(a)||0===b||"number"===typeof b&&0<b&&b-1 in a}function c(b){return"[object Array]"===a.a.v.toString.call(b)}a.a={};a.a.a=3E3;
a.a.b=function(){var a=/Firefox\/(\d+)/.exec(navigator.userAgent);return a?14<parseInt(a[1],10):!1}();a.a.c=function(){var b;b=/^(?:[a-z]+:\/\/|:?\/?\/)?(?:www\.)?([^\/:]*)/i;b=!a.b.a&&a.b.b?(b=a.b.b.match(b))&&b[1]?b[1]:a.b.c.location.hostname:a.b.c.location.hostname;var d=b.match(/.*\.([^\.]*\..*)/i);return d&&d[1]?decodeURIComponent(d[1]):decodeURIComponent(b)};a.a.d=function(){var b=a.a.e();return 5===b||6===b||7===b};a.a.e=function(){if(!navigator)return null;var a=navigator.userAgent;return"Microsoft Internet Explorer"==
navigator.appName?parseInt(a.replace(/^.*MSIE (\d+).*$/,"$1"),10):"Netscape"==navigator.appName&&(a=a.match(/Trident\/.*rv:(\d+)/))?parseInt(a[1],10):null};a.a.f=function(a,b){for(var d=0;d<a.length;d++)if(a[d]===b)return!0;return!1};a.a.g=function(a){return new q-a.de};a.a.h=function(a){return a.replace(/^http:/,"").replace(/^\/\//,"").replace(/^www[^.]*\./,"").split("/")[0]};a.a.i=function(){return null!==/iPad|iPhone|iPod|Silk|Kindle|Android|BlackBerry|PlayBook|BB10|Windows Phone/.exec(navigator.userAgent)};
a.a.j=function(){return null!==/iPhone|iPod/.exec(navigator.userAgent)};a.a.k=function(){var a=navigator.userAgent;return a.match(/iPhone|iPod|iPad/)&&!a.match(/Safari/i)};a.a.l=function(){var a=window;try{return"undefined"!==typeof a.external&&"undefined"!==typeof a.external.InPrivateFilteringEnabled&&a.external.InPrivateFilteringEnabled()||"undefined"!==typeof a.external&&"undefined"!==typeof a.external.msTrackingProtectionEnabled&&a.external.msTrackingProtectionEnabled()||"undefined"!==typeof a._gaUserPrefs&&
a._gaUserPrefs.ioo&&a._gaUserPrefs.ioo()||"undefined"!==typeof navigator.doNotTrack&&("yes"===navigator.doNotTrack||!0===navigator.doNotTrack)||"undefined"!==typeof a._gaUserPrefs&&!0===a._gaUserPrefs}catch(b){return!1}};a.a.getAttribute=function(a,b){return a[b]||a.getAttribute(b)};a.a.m=function(a){var b=0,d;for(d in a)a.hasOwnProperty(d)&&(b+=1);return b};a.a.n=function(b,d){return a.a.o(b)&&!0!==b[v]?!0:!1};a.a.o=function(b){return b.offsetWidth*b.offsetHeight>=a.a.a};a.a.p=function(a,b){var d=
!1,c=b.body,e=c&&c.firstChild;c&&e&&(c.insertBefore(a,e),d=!0);return d};a.a.q=function(){var a;return function(){if(!a)a:{for(var b=document.getElementsByTagName("script"),d=b.length-1;-1<d;d--)if((a=b[d])&&a.src&&a.src.indexOf&&-1!==a.src.indexOf(aa+"/moatad.js")&&("undefined"===typeof a[v]||!0!==a[v])){a[v]=!0;break a}a=void 0}return a?(a[v]=!0,a):null}}();a.a.r=function(a){try{return-1!==(a.src||a.getAttribute("src")).indexOf("psd=1")}catch(b){return!1}};a.a.s=function(a){for(var b=[],d=0;d<a.length;d++)b.push(a[d]);
return b};a.a.previousElementSibling=function(a){if(a.previousElementSibling)return a.previousElementSibling;for(;a=a.previousSibling;)if(1===a.nodeType)return a};a.a.t=function(a,b,d){"undefined"!==typeof d&&(a[b]=d)};a.a.filter=function(a,b){for(var d=[],c=0;c<a.length;c++)b(a[c])&&d.push(a[c]);return d};a.a.u=function(a,b){for(var d=[],c=0;c<b.length;c++)d.push(a(b[c]));return d};var b="ale",d="rt",e="setInte",f="rval";a.a.v={};a.a.w=c;a.a.x=h;a.a.y=g;a.a.forEach=function(a,b,d){var c;if(a)if("function"===
typeof a)for(c in a){if("prototype"!=c&&"length"!=c&&"name"!=c&&(!a.hasOwnProperty||a.hasOwnProperty(c))){var e=b.call(d,a[c],c);if("boolean"===typeof e&&!e)break}}else if("function"===typeof a.every)a.every(function(a,c,s){a=b.call(d,a,c);return!("boolean"===typeof a&&!a)});else if(g(a))for(c=0;c<a.length&&(e=b.call(d,a[c],c),"boolean"!==typeof e||e);c++);else for(c in a)if(a.hasOwnProperty(c)&&(e=b.call(d,a[c],c),"boolean"===typeof e&&!e))break;return a}})(l);(function(a){function h(a){try{var b=
typeof a.location.toString;if("undefined"===b||"unknown"===b)return!0;var d=typeof a.document;return"undefined"===d||"unknown"===d?!0:!1}catch(e){return!0}}a.b={};a.b.d="MoatSuperV4";a.b.e=0;a.b.f=0<Object.prototype.toString.call(window.HTMLElement).indexOf("Constructor");a.b.g=-1!==navigator.userAgent.toLowerCase().indexOf("firefox");a.b.h=-1!==navigator.userAgent.indexOf("MSIE");a.b.i=(new q).getTime();a.b.protocol=function(){var a;try{a=window.location.protocol}catch(b){a=document.createElement("a"),
a.href="",a=a.protocol}return a}();a.b.j=("https:"===a.b.protocol?"z":"js")+".moatads.com";a.b.k=window!=window.parent;var g=h(window.parent);a.b.l=a.b.k&&!g;a.b.a=g?!1:!h(window.top);a.b.c=a.b.a?window.top:a.b.l?window.parent:window;a.b.b=a.b.c.document.referrer})(l);(function(a){function h(a){return function(){var b=!1;return function(d){try{a(d)}catch(e){if(!b){b=!0;d=e.name+" in callback: "+e.message+", stack="+e.stack;try{var f="//v3.moatads.com/pixel.gif?e=24&d=data%3Adata%3Adata%3Adata&i="+
escape("AKQAPR2")+"&ac=1&k="+escape(d)+"&ar="+escape("099702a-clean")+"&j="+escape(document.referrer)+"&cs="+(new q).getTime();(new Image(1,1)).src=f}catch(k){}}}}}()}a.c={};var g={};a.c.a=g;a.c.b=function(a,b,d,e){d=h(d);a.addEventListener?a.addEventListener(b,d,!1):a.attachEvent("on"+b,d);!1!==e&&(g[b+e]=d)};a.c.c=function(a,b,d,e){var f=b+e;d=!1!==e?g[f]:d;try{a&&a.removeEventListener?a.removeEventListener(b,d,!1):a&&a.detachEvent&&a.detachEvent("on"+b,d)}catch(k){}delete g[f]};a.c.d=function(a,
b){a=h(a);var d=setInterval(a,b);O.push(d);return d};a.c.e=function(a,b){a=h(a);var d=setTimeout(a,b);N.push(d);return d};a.c.f=function(c,b,d,e){var f=0,k=function(){f+=1;!0!==c()&&(f<b?a.c.e(k,d):"function"===typeof e&&e())};k()};a.c.g=h})(l);(function(a){function h(){this.height=this.width=this.absTop=this.absLeft=0;this.update=function(a){this.absLeft=a.left+e("left",a.win);this.absTop=a.top+e("top",a.win);this.width=a.width;this.height=a.height}}function g(b,d){var c=b.zr;k.hasOwnProperty(c)||
(k[c]=new h);var e=d||new a.d.h(b.aa);k[c].update(e)}function c(a,b){for(var d=[],c=0;c<b.length;c++)d.push(a(b[c]));return d}function b(b){var d,e=a.e.b(b.el,b.win),e=c(function(b){return new a.d.h(b)},e);e.unshift(b);var k=e.length;b=new a.d.h(b.el,a.b.c);for(var f=0;f<k;f++){var g=e[f];0===f?d=g:(d.changeReferenceFrame(g),b.changeReferenceFrame(g));g=g.getViewportRect(f<k-1?e[f+1]:!1);d=a.d.j(d,g)}return{visibleRect:d,cumulRect:b,parentArea:e[e.length-1].calcArea()}}function d(a,b,d,c){a=u.max(a,
d);b=u.min(b,c);return b>a?[a,b]:[0,0]}function e(a,b){b||(b=window);var d=b.document.documentElement,c=b.document.body;return"left"===a?b.pageXOffset||d&&d.scrollLeft||c&&c.scrollLeft:b.pageYOffset||d&&d.scrollTop||c&&c.scrollTop}a.d={};var f=a.b.a,k={};a.d.a=0.5;a.d.b=0.3;a.d.c=236425;a.d.d=function(d,c){var e;e=new a.d.h(d.aa,c);g(d,e);var f=e.height,k=e.width,h=e.calcArea();if(0===h)e={area:h,percv:0};else{var s=b(e),F=s.visibleRect.calcArea(),G=F/h,l;b:{var w=s.cumulRect,y=s.cumulRect.getViewportRect();
if(0>w.top&&0<w.bottom)l=-w.top;else if(0<=w.top&&w.top<=y.height)l=0;else{l={yMin:-1,yMax:-1};break b}if(0<=w.bottom&&w.bottom<=y.height)w=w.height;else if(w.bottom>y.height&&w.top<y.height)w=w.height-(w.bottom-y.height);else{l={yMin:-1,yMax:-1};break b}l={yMin:l,yMax:w}}e={area:h,visibleArea:F,percv:G,yMinMax:l,elGeo:{elHeight:f,elWidth:k,foldTop:s.cumulRect.top,totalArea:s.parentArea},rect:e.rect}}f=a.d.e(e,d);e.isVisible=e.percv>=f;e.elGeo&&(e.elGeo.threshold=f);return e};a.d.e=function(b,d){return b.area>=
a.d.c?(d.viewstats.isBigAd=!0,a.d.b):a.d.a};a.d.f=function(){return f};a.d.g=function(a,b){f&&k.hasOwnProperty(b)||g(a);return k[b]};a.d.i=function(a){var b,d,c,e=0,f=0;try{b=a.document,d=b.documentElement,c=b.body}catch(s){return{width:e,height:f,left:0,right:e,top:0,bottom:f}}"undefined"!==typeof a.innerWidth?(e=a.innerWidth,f=a.innerHeight):"CSS1Compat"===b.compatMode&&5!==b.documentMode||!c||"undefined"===typeof c.clientWidth?d&&"undefined"!==typeof d.clientWidth&&(e=d.clientWidth,f=d.clientHeight):
(e=c.clientWidth,f=c.clientHeight);return{width:e,height:f,left:0,right:e,top:0,bottom:f}};a.d.h=function(b,d,c){this.rect=c||b.getBoundingClientRect();c=["left","right","top","bottom"];for(var e=0;e<c.length;e++){var f=c[e];this[f]=this.rect[f]}this.width=this.right-this.left;this.height=this.bottom-this.top;this.el=b;this.win=d||b&&a.e.a(b);this.changeReferenceFrame=function(a){this.left+=a.left;this.right+=a.left;this.top+=a.top;this.bottom+=a.top};this.calcArea=function(){return(this.right-this.left)*
(this.bottom-this.top)};this.getViewportRect=function(b){var d=a.d.i(this.win);b&&(b.width<d.width&&(d.width=b.width,d.right=d.left+d.width),b.height<d.height&&(d.height=b.height,d.bottom=d.top+d.height));return d}};a.d.j=function(b,c){var e=d(b.left,b.right,c.left,c.right),f=d(b.top,b.bottom,c.top,c.bottom);return new a.d.h(void 0,void 0,{left:e[0],right:e[1],top:f[0],bottom:f[1]})}})(l);(function(a){function h(b){a.focus.pageIsVisible(!0)&&((new q).getTime()-k>=Q&&e?(a.f.k(),a.f.i(r[G])):m||(m=
!0,a.c.e(function(){m=!1;h()},s)))}function g(){a.f.o=(new q).getTime();a.c.f(function(){var b=d.getElementById("moatPx"+G),s=d.getElementById("moatPxEmbed"+G);c(b)?(e=b,f=b.parentNode):c(s)&&(e=s,f=b.parentNode);if(!1!==e){a.f.g?a.f.d=e.setConfig(w):a.f.f?a.f.d=e.setConfig(w):e.setConfig(P);a.f.b&&(a.f.b="off"===a.f.d);if(8===z&&"iescope"===a.f.d){var F=function(){try{var b=parseInt(e.style.top,10);e.style.top=0>b?b+1E4+"px":b-1E4+"px";a.c.e(F,100)}catch(d){}};a.c.e(F,16)}return!0}},v,R)}function c(a){try{return a&&
(a.getStats||"undefined"!==typeof a.getStats||a.getStats())&&!0}catch(b){return!1}}function b(a,b,d){var c=document.createElement("param");c.setAttribute("name",b);c.setAttribute("value",d);a.appendChild(c)}a.f={};a.f.a=function(){function a(b){b=b.match(/[\d]+/g);b.length=3;return b.join(".")}var b=!1,d="";if(navigator.plugins&&navigator.plugins.length){var c=navigator.plugins["Shockwave Flash"];c&&(b=!0,c.description&&(d=a(c.description)));navigator.plugins["Shockwave Flash 2.0"]&&(b=!0,d="2.0.0.11")}else if(navigator.mimeTypes&&
navigator.mimeTypes.length)(b=(c=navigator.mimeTypes["application/x-shockwave-flash"])&&c.enabledPlugin)&&(d=a(c.enabledPlugin.description));else try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),b=!0,d=a(c.GetVariable("$version"))}catch(e){try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),b=!0,d="6.0.21"}catch(s){try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),b=!0,d=a(c.GetVariable("$version"))}catch(F){}}}return b?d:"0"}();a.f.b=!1;a.f.c="";a.f.d="default";var d,e=!1,
f,k=0,m=!1,z=a.a.e(),n=null!==z,l=-1!==navigator.userAgent.indexOf("Chrome"),B=6.2<=function(){var a=navigator.appVersion.match(/Windows NT (\d\.\d)/);return a?parseFloat(a[1]):-1}(),Q=1E3,s=200,F=a.b.protocol+"//"+a.b.j,G=!1;a.f.e=0<Object.prototype.toString.call(window.HTMLElement).indexOf("Constructor");a.f.f=!1;a.f.g=!1;var P={"default":{targetVersion:"*",lo:""}},w={iescope:{targetVersion:"*",lo:">="}};try{var y=a.a.e();if(7==y||8==y||9==y||10==y||11==y)a.f.g=!0}catch(u){}var R=10,v=500,L=!0,
x;a.f.h=function(){if(e&&e.getStats)try{"iescope"===a.f.d&&(L&&(L=!1,x=e.style.width),e.style.width=x!==e.style.width?x:parseInt(x,10)+1+"px");var b=e&&e.getStats();if(b&&b.ok)return"off"!==a.f.d&&(a.f.b=!0),a.f.c=b.rev,b}catch(d){}return!1};a.f.i=function(c){if(a.f.j()){var e=c.zr;try{var s=F+"/swf/p5.v1e.swf",f,m;m=n?f=2:f=1;var w=a.d.g(c,e),l="position: absolute; width: "+f+"px; height: "+m+"px; z-index: -9999;";a.f.f&&(l+="-webkit-transform: translate3d(0, 0, 0);");var y=l+"left: "+w.absLeft+
"px; top: "+(w.absTop+w.height/2)+"px;",l=l+"left: 0px; top: 0px;";c.ed.x=w.absLeft;c.ed.y=w.absTop;w="ym"+e;G=e;t.yl||(t.yl={});t.yl[w]=function(){g()};var K=c.aa.ownerDocument;("defaultView"in K?K.defaultView:K.parentWindow)[a.b.d]=t;var P="ol="+a.b.d+".yl."+w+"&db=false";d=K;if(B&&n&&10<=z)var r=function(){var a="moatPx"+e,d=K.createElement("OBJECT");d.setAttribute("data",s);d.setAttribute("id",a);d.setAttribute("name",a);d.setAttribute("style",y);d.setAttribute("width",f+"");d.setAttribute("height",
m+"");b(d,"flashvars",P);b(d,"wmode","transparent");b(d,"bgcolor","");b(d,"allowscriptaccess","always");var a=K.body,c=K.createElement("div");c.id="moatPxDiv"+e;c.style.width="0px";c.style.height="0px";a.insertBefore(c,a.firstChild);c.appendChild(d);return!0};else var Q='<object type="application/x-shockwave-flash" classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0" width="'+f+'" height="'+m+'" style="'+
y+'" id="moatPx'+e+'"><param name="allowScriptAccess" value="always" /><param name="allowFullScreen" value="false" /><param name="movie" value="'+s+'" /><param name="quality" value="low" /><param name="hasPriority" value="true" /><param name="FlashVars" value="'+P+'" /><param name="bgcolor" value="" /><param name="wmode" value="transparent" /><embed type="application/x-shockwave-flash" src="'+s+'" quality="low" flashvars="'+P+'" bgcolor="" wmode="transparent" width="'+f+'" height="'+m+'" id="moatPxEmbed'+
e+'" name="moatPx'+e+'" style="'+l+'" hasPriority="true" allowscriptaccess="always" allowFullScreen="false" type="application/x-shockwave-flash" pluginspage="http://www.adobe.com/go/getflashplayer" /></object>',r=function(){var b=K.createElement("div");b.id="moatPxDiv"+e;b.style.width="0px";b.style.height="0px";if(!0===a.a.p(b,d)){b.innerHTML=Q;try{b.getElementsByTagName("object")}catch(c){}return!0}return!1};k=(new q).getTime();a.c.f(r,10,100);B&&n&&10<=z&&a.focus.supportsPageVisAPI()&&a.c.b(d,a.focus.visibilitychange,
h,e)}catch(u){}}};a.f.l=function(b,d){var c=a.f.m,e=b.aa.ownerDocument.getElementById("moatPx"+d);if(e){var s=e.parentNode;if(0!==s.id.indexOf("moatPxDiv")){var f=document.getElementById("moatPxDiv"+d);s.removeChild(e);f.appendChild(e)}s=a.d.g(b,d);s={left:s.absLeft+s.width/2,top:s.absTop+s.height/2};c(s,b.ed)&&(e.style.left=s.left+"px",e.style.top=s.top+"px",b.ed.x=s.left,b.ed.y=s.top)}};a.f.k=function(){f&&f.parentNode&&(a.c.c(d,a.focus.visibilitychange,h,G),e.parentNode.removeChild(e),f.parentNode.removeChild(f),
d=f=e=!1)};a.f.n=function(b){a.f.l(b,b.zr);isVisible=(b=a.f.h())?b.iv:!1;return{isVisible:isVisible}};a.f.j=function(){return n||a.b.k&&!a.b.l&&l||a.f.f};a.f.m=function(a,b){return a&&(a.left!==b.x||a.top!==b.y)}})(l);(function(a){function h(a,b,d){a.IR5.MIN[d]=u.min(b,a.IR5.MIN[d])||b||1;a.IR5.MAX[d]=u.max(b,a.IR5.MAX[d])||b}function g(a,b){b.be=u.max("undefined"!==typeof b.be?b.be:0,a-b.bf);"undefined"===typeof b.by&&b.be>=r&&(b.by=b.bk)}function c(b){b.az===a.g.a.d.a?b.az=a.g.a.d.b:b.az===a.g.a.d.b&&
(b.az=a.g.a.d.a)}function b(b){b.ba===a.g.a.d.a?b.ba=a.g.a.d.b:b.ba===a.g.a.d.b&&(b.ba=a.g.a.d.a)}function d(b){b.ax===a.g.a.b.a?b.ax=a.g.a.b.b:b.ax===a.g.a.b.b&&(b.ax=a.g.a.b.a)}function e(b){b.ay===a.g.a.c.a?b.ay=a.g.a.c.b:b.ay===a.g.a.c.b&&(b.ay=a.g.a.c.a)}function f(a,b){"undefined"===typeof b.bk&&(b.bk=0);b.bk+=a-b.bo;b.bo=a}function k(a,b){"undefined"===typeof b.bl&&(b.bl=0);b.bl+=a-b.bp;b.bp=a}function m(a,b){"undefined"===typeof b.bg&&(b.bg=0);"undefined"===typeof b.bc&&(b.bc=0);b.bu=a-b.bs;
b.bu>b.bc&&(b.bc=b.bu);b.bg+=a-b.bq;b.bc>=B&&"undefined"===typeof b.bw&&(b.bk+=a-b.bo,b.bw=b.bk);b.bq=a}function z(a,b){"undefined"===typeof b.bh&&(b.bh=0);"undefined"===typeof b.bd&&(b.bd=0);b.bv=a-b.bt;b.bv>b.bd&&(b.bd=b.bv);b.bh+=a-b.br;b.bd>=B&&"undefined"===typeof b.bx&&(b.bl+=a-b.bp,b.bx=b.bl);b.br=a}a.g={};var n=500,l=3E3,B=500,r=500;a.g.a={};a.g.a.a={};a.g.a.a.a=0;a.g.a.a.b=1;a.g.a.b={};a.g.a.b.a=0;a.g.a.b.b=1;a.g.a.c={};a.g.a.c.a=0;a.g.a.c.b=1;a.g.a.d={};a.g.a.d.a=0;a.g.a.d.b=1;a.g.a.e={};
a.g.a.e.a=0;a.g.a.e.b=1;a.g.a.f={};a.g.a.f.a=0;a.g.a.f.b=1;a.g.a.f.c=2;a.g.b=function(a){h(a,a.aj,"x");h(a,a.ak,"y");a.IR5.AREA=(a.IR5.MAX.x-a.IR5.MIN.x)*(a.IR5.MAX.y-a.IR5.MIN.y)};a.g.c=function(b){function d(){(new q).getTime()-S>=n&&(a.g.d({type:"park"},b),clearInterval(e),b.au=a.g.a.a.a)}var c=b.au;if(c===a.g.a.a.a){S=(new q).getTime();var e=a.c.d(d,50);b.au=a.g.a.a.b}else c===a.g.a.a.b&&(S=(new q).getTime())};a.g.e=function(b){function d(){(new q).getTime()-T>=l&&(a.g.f({type:"park"},b),clearInterval(e),
b.av=a.g.a.a.a)}var c=b.av;if(c===a.g.a.a.a){T=(new q).getTime();var e=a.c.d(d,50);b.av=a.g.a.a.b}else c===a.g.a.a.b&&(T=(new q).getTime())};a.g.g=function(b,d){var e=b.type;if(d.az===a.g.a.d.a){if("mouseover"===e||"mousemove"===e)d.bo=(new q).getTime(),c(d)}else if(d.az===a.g.a.d.b){"mousemove"===e&&f((new q).getTime(),d);if("mouseout"===e||"blur"===e)f((new q).getTime(),d),c(d);"scooper"===e&&f((new q).getTime(),d)}};a.g.h=function(d,c){var e=d.type;if(c.ba===a.g.a.d.a){if("mouseover"===e||"mousemove"===
e)c.bp=(new q).getTime(),b(c)}else if(c.ba===a.g.a.d.b){"mousemove"===e&&k((new q).getTime(),c);if("mouseout"===e||"blur"===e)k((new q).getTime(),c),b(c);"scooper"===e&&k((new q).getTime(),c)}};a.g.d=function(b,c){if(2!=c.an){var e=b.type;if(c.ax===a.g.a.b.a){if("mouseover"===e||"mousemove"===e)c.bq=(new q).getTime(),c.bs=(new q).getTime(),d(c)}else c.ax===a.g.a.b.b&&("mousemove"!==e&&"mouseout"!==e||m((new q).getTime(),c),"park"===e&&m((new q).getTime()-n,c),"mouseout"!==e&&"park"!==e||d(c))}};a.g.f=
function(b,d){if(2!=d.an){var c=b.type;if(d.ay===a.g.a.c.a){if("mouseover"===c||"mousemove"===c)d.br=(new q).getTime(),d.bt=(new q).getTime(),e(d)}else d.ay===a.g.a.c.b&&("mousemove"!==c&&"mouseout"!==c||z((new q).getTime(),d),"park"===c&&z((new q).getTime()-l,d),"mouseout"!==c&&"park"!==c||e(d))}};a.g.i=function(b,d){var c=b.type;if(d.bb==a.g.a.e.a){if("mouseover"==c||"mousemove"==c)d.bf=(new q).getTime(),d.bb=a.g.a.e.b}else d.bb==a.g.a.e.b&&("mouseout"==c?(g((new q).getTime(),d),d.bb=a.g.a.e.a):
"mousemove"!=c&&"scooper"!=c||g((new q).getTime(),d))}})(l);(function(a){function h(b){if(!a.focus.pageIsPrerendered()){a.c.c(document,m,h,"pr");for(var d in r)r.hasOwnProperty(d)&&a.e.c(r[d])}}function g(a){"undefined"==typeof e&&(e=a)}a.focus={};var c=navigator.userAgent,c=-1<c.indexOf("Safari")&&-1==c.indexOf("Chrome")&&-1==c.indexOf("Chromium")&&!I,b=(eval("/*@cc_on!@*/false")||document.documentMode)&&!I,d="undefined"!==typeof document.hasFocus,e,f={visible:0,hidden:1,prerender:2},k,m,z,n;"undefined"!==
typeof document.hidden?(k="hidden",m="visibilitychange"):"undefined"!==typeof document.mozHidden?(k="mozHidden",m="mozvisibilitychange"):"undefined"!==typeof document.msHidden?(k="msHidden",m="msvisibilitychange"):"undefined"!==typeof document.webkitHidden&&(k="webkitHidden",m="webkitvisibilitychange");for(var l=["v","mozV","msV","webkitV"],B=0;B<l.length;B++){var Q=l[B]+"isibilityState";if("undefined"!==typeof document[Q]){z=Q;break}}n="undefined"!==typeof k;var s,F;"undefined"!==typeof window.requestAnimationFrame?
s="requestAnimationFrame":"undefined"!==typeof window.webkitRequestAnimationFrame&&(s="webkitRequestAnimationFrame");F=c&&"string"==typeof s&&!n;var G=(new q).getTime();F&&function y(){G=(new q).getTime();window[s](y)}();a.focus.getFocusMethod=function(){return e};a.focus.visibilitychange=m;a.focus.setFocusListeners=function(){"Microsoft Internet Explorer"===navigator.appName?(a.c.b(x.document,"focusout",function(){t.yd()},!1),a.c.b(x.document,"focusin",function(){t.ye()},!1)):(a.c.b(x,"blur",function(){t.yd()},
!1),a.c.b(x,"focus",function(){t.ye()},!1))};a.focus.getQueryString=function(a){a={};a.em=e;P&&(a.eo=1);"undefined"!=typeof z&&(a.en=f[document[z]]);return a};a.focus.supportsPageVisAPI=function(){return n};a.focus.pageIsVisible=function(){if(a.focus.supportsPageVisAPI())return g(0),!document[k];if(F)return g(1),100>(new q).getTime()-G;if(b&&d)return g(2),document.hasFocus();g(3);return!0};a.focus.pageIsPrerendered=function(){return"undefined"!==typeof z?"prerender"==document[z]:!1};a.focus.pageIsVisible();
a.focus.pageIsPrerendered()&&a.c.b(document,m,h,"pr");var P=a.focus.pageIsPrerendered();a.focus.windowHasFocus=function(){return t.v}})(l);(function(a){function h(b,d,c,e,f){("remove"===f?a.c.c:a.c.b)(b,d,function(d){d=d||this.event;var e=d.currentTarget||b,f=r[e[U]];if(f){var k;k=d;var m=e.getBoundingClientRect();k=-1!=k.type.indexOf("touch")?{x:parseInt(k.changedTouches[0].clientX-m.left,10),y:parseInt(k.changedTouches[0].clientY-m.top,10)}:{x:parseInt(k.clientX-m.left,10),y:parseInt(k.clientY-
m.top,10)};f.aj=k.x;f.ak=k.y;f.dm||(f.cb=2==a.focus.getFocusMethod()?f.counters.laxDwell.tCur:f.counters.strictDwell.tCur,f.dm=1);c.call(b,d,e,f)}},e)}function g(a,e,f){h(a,"click",n,e,f);h(a,"mousedown",b,e,f);I?h(a,"touchstart",d,e,f):(h(a,"mousemove",c,e,f),h(a,"mouseover",m,e,f),h(a,"mouseout",z,e,f))}function c(b,d,c){I||c.aj===c.al&&c.ak===c.am||(a.g.d(b,c),a.g.f(b,c),a.g.g(b,c),a.g.i(b,c),a.g.h(b,c),a.g.b(c),a.g.c(c),a.g.e(c),0===c.ar.length&&(c.ai=B(c)),c.ar.push(c.aj),c.as.push(c.ak),c.at.push(a.a.g(c)),
c.al=c.aj,c.am=c.ak);c.ai!==B(c)&&1<c.ar.length&&l(c,"onMouseMove")}function b(b,d,c){b={e:2};b.q=c.aq[2]++;b.x=c.aj;b.y=c.ak;a.i.a(c,b)}function d(b,d,c){b={e:23};b.q=c.aq[23]++;b.x=c.aj;b.y=c.ak;d=(new q).getTime();if("undefined"===typeof c.ct)c.ct=d;else{var e=d-c.ct;c.ct=d;c.cu=u.min(c.cu,e)||e}b.bz=void 0;a.i.a(c,b)}function e(b,d,c){if(2==b.an){var e=d.e,m=b.ck;m==a.g.a.f.a&&6===e?(f(b,0),b.cl=a.a.g(b),b.ck=a.g.a.f.b):m==a.g.a.f.b?22===e?(k(b,d),f(b,c),b.cl=a.a.g(b)):7===e&&(1E3<a.a.g(b)-b.cl?
(clearTimeout(b.cm),d.e=22,k(b,d),b.cn=0,b.ck=a.g.a.f.a):b.ck=a.g.a.f.c):m==a.g.a.f.c&&(6==e?(1E3<a.a.g(b)-b.cl&&(clearTimeout(b.cm),b.cn=0,b.cl=a.a.g(b),f(b,0)),b.ck=a.g.a.f.b):22==e&&(k(b,d),b.ck=a.g.a.f.a,b.cn=0))}}function f(b,d){var c=5>b.cn?1E3:2*d,f={e:22};b.cm=a.c.e(function(){e(b,f,c)},c)}function k(b,d){d.q=b.aq[d.e]++;d.m=a.a.g(b);b.cl=d.m;a.i.a(b,d);b.cn++}function m(b,d,c){a.g.d(b,c);a.g.f(b,c);a.g.g(b,c);a.g.i(b,c);a.g.h(b,c);e(c,{e:6},0)}function z(b,d,c){a.g.d(b,c);a.g.f(b,c);a.g.g(b,
c);a.g.i(b,c);a.g.h(b,c);e(c,{e:7},0)}function n(b,d,c){b={e:3};b.q=c.aq[3]++;b.x=c.aj;b.y=c.ak;a.i.a(c,b)}function l(b,d){b.ai=B(b);var c={e:1};c.q=b.aq[1]++;c.x=b.ar.join("a");c.y=b.as.join("a");for(var e=a.a.g(b),f=b.at,k=[],m=0;m<f.length;m++)isNaN(f[m])||k.push(u.abs(f[m]-e));c.c=k.join("a");c.m=e;a.i.a(b,c);b.ar=[];b.as=[];b.at=[]}function B(b){return u.floor(a.a.g(b)/t)}a.h={};var t=1E3;a.h.a=function(a,b){if(!0===a.isSkin)for(var d=0;d<a.elements.length;d++)g(a.elements[d],a.zr+"-"+d,b);else g(a.aa,
a.zr,b)};a.h.b=function(b){for(var d in r)r.hasOwnProperty(d)&&(b=r[d])&&(a.g.g({type:"scooper"},b),a.g.i({type:"scooper"},b),a.g.h({type:"scooper"},b),1<b.ar.length&&b.ai!==B(b)&&l(b,"scooper"))}})(l);(function(a){a.j={};var h="undefined"!==typeof window.devicePixelRatio,g=h&&u.round(1E3*window.devicePixelRatio),c=a.b.a&&h&&"undefined"!==typeof window.innerHeight&&"undefined"!==typeof window.outerHeight&&u.round(window.devicePixelRatio*(a.b.c.outerHeight-a.b.c.innerHeight)),b="undefined"!==typeof window.mozInnerScreenX&&
"undefined"!==typeof window.screenX;a.j.a=function(b,c){var f;try{var k,m=b.aa.getBoundingClientRect(),g=c||b.WINDOW||a.e.a(b.aa),n=a.d.i(g),l=a.d.j(m,n),q=g.mozInnerScreenX,r=g.mozInnerScreenY,s=window.screenX,t=window.screenY,u=a.d.j({left:l.left+q,right:l.right+q,top:l.top+r,bottom:l.bottom+r},{left:s,right:s+window.outerWidth,top:t+117/(h?window.devicePixelRatio:1),bottom:t+window.outerHeight}),v=m.width*m.height;k={area:v,percv:(u.right-u.left)*(u.bottom-u.top)/v};var w=a.d.e(k,b);f=k.percv>=
w}catch(y){f=!1}return{isVisible:f}};a.j.b=function(){return b};a.j.c=function(){var a={};a.dl=Number(b);"number"!==typeof g||isNaN(g)||(a.dm=g);"number"!==typeof c||isNaN(c)||(a.dn=c);return a}})(l);(function(a){function h(a){var b=0,f;return function(){var k=(new q).getTime();k-b>c&&(f=a.apply(this,arguments),b=k);return f}}function g(b,c,f,k){var m=0,g=0,n=0,h=(new q).getTime(),l=!1,r=!1,s,t,v,x=0,w=0,y=0,C=0,R=!1,I=a.b.a,L;if(0===k)var A="as",D="ag",E="an",J="ck",M="kw",N="ah",O="aj",S="pg",T=
"pf",R=!0;else 1===k?(A="cc",D="bw",E="bx",J="ci",M="jz",N="bu",O="dj"):2===k&&(A="cg",D="ce",E="cf",J="cj",M="ts",N="ah",O="dk");this.hadOTS=function(){return r};this.hadVideo2SecOTS=function(){return _hadVideo2SecOts};this.getInViewTime=function(){return m};this.visible=function(){return l};this.update=function(g){var z=!1,C=b(g);g.elementRect=C.rect;var A=C.isVisible,D=c(g),E=(new q).getTime(),H=u.max(u.min(E-h,1E3),0);h=E;E=!f||a.focus.pageIsVisible(2===k);if((A=A&&E&&!D)&&l)m+=H,n+=H;else if(A||
l)H=u.round(H/2),m+=H,n+=H;!r&&1E3<=n&&(z=r=!0,t=m,this.timeToView=s=g.counters.query()[N]);"undefined"===typeof v&&(1E3>=g.counters.query().bu?A&&(v=!0):v=!1);if((g.FOLDMEASURABLE=I)&&"undefined"===typeof L&&2!==k&&C.elGeo){var H=a.b.c,D=H.document,J=C.elGeo.threshold*C.elGeo.elHeight;_isBTFCheck=(void 0!==H.pageYOffset?H.pageYOffset:(D.documentElement||D.body.parentNode||D.body).scrollTop)+C.elGeo.foldTop>a.k.a()-J;0<C.elGeo.totalArea&&(L=_isBTFCheck,g.BELOWTHEFOLDAD=L)}g=C.yMinMax;R&&E&&"undefined"!==
typeof g&&C.elGeo&&0<=g.yMax&&0<=g.yMin&&0<C.visibleArea&&(x=u.max(g.yMax,x),w=u.min(g.yMin,w),y=u.min(1,u.max((x-w)/C.elGeo.elHeight,y)));A||(n=0);l=A;return z};this.getQS=function(a){g>m&&(g=m);a[A]=Number(r);a[D]=m;a[E]=g;"undefined"!==typeof t&&(a[J]=t);"undefined"!==typeof s&&(a[M]=s);"undefined"!==typeof v&&(a[O]=Number(v));if(!0===R){var b=u.round(100*y),c=u.round(100*C);a[S]=b;a[T]=c;C=y}"undefined"!==typeof L&&(a.ib=Number(L));g=m}}a.k={};var c=150,b={};a.k.a=function(){return I?a.d.i(a.b.c).height:
750};a.k.b=function(c){var e=c.zr;b[e]={};c.viewstats={isBigAd:!1};if(a.d.f()){var f=h(a.d.d),k;k=new g(f,a.e.d,!0,0);b[e].strict=k;f=new g(f,a.e.d,!1,1);b[e].lax=f}!0!==c.isSkin&&a.j&&a.j.b()?(c=new g(a.j.a,a.e.d,!0,2),b[e].pscope=c):a.f&&a.f.j()&&(c=new g(a.f.n,a.e.d,!0,2),b[e].pscope=c)};a.k.c=function(c){var e=b[c.zr],f,k;for(k in e)e.hasOwnProperty(k)&&e[k].update(c)&&(f=!0);f&&a.e.e(c);a.l.a(c)&&a.e.f(c)};a.k.d=function(b,c,f){"unefined"==typeof f&&(f=!1);var k=a.k&&a.k.e(b.zr);b=(a.j&&a.j.b()||
a.f&&a.f.b)&&k&&k.pscope.getInViewTime()>=c;c=f?a.d&&a.d.f()&&k&&k.strict&&k.strict.getInViewTime()>=c:a.d&&a.d.f()&&k&&k.lax&&k.lax.getInViewTime()>=c;return a.b.a?c:b};a.k.f=function(a){delete b[a]};a.k.e=function(a){return b[a]};a.k.g=function(a){var c={},f=b[a],k;for(k in f)f.hasOwnProperty(k)&&f[k].getQS(c);(a=r[a])&&a.viewstats.isBigAd&&(c.el=1);return c}})(l);(function(a){a.m={};a.m.a=function(a,g){var c;g.outerHTML?c=g.outerHTML:(c=document.createElement("div"),c.appendChild(g.cloneNode(!0)),
c=c.innerHTML);c=[/flashvars\s*=\s*(".*?"|'.*?')/i.exec(c),/name\s*=\s*["']flashvars["']\s*value\s*=\s*(".*?"|'.*?')/i.exec(c),/value\s*=\s*(".*?"|'.*?')\s*name\s*=\s*["']flashvars["']/i.exec(c),a];for(var b,d,e={},f=0;f<c.length;f++){if((b=c[f])&&"object"===typeof b&&b[1])b=b[1].replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/^"/g,"").replace(/"$/g,"").replace(/^'/g,"").replace(/'$/g,"");else if("string"===typeof b)b=b.split("?")[1];else continue;if(b){b=b.split("&");for(var k=0;k<b.length;k++)d=
b[k].split("="),2>d.length||"function"==d[0].slice(0,8)||(e[d[0]]=[d[1]])}}return e}})(l);(function(a){function h(b){var c={window:0,transparent:1,opaque:2,direct:3,gpu:4};if("EMBED"===b.tagName)var e=a.a.getAttribute(b,"wmode");else if("OBJECT"===b.tagName){b=b.getElementsByTagName("param");for(var f=0;f<b.length;f++){var k=b[f],m=a.a.getAttribute(k,"name"),k=a.a.getAttribute(k,"value");if("wmode"===m){e=k;break}}}return e&&c[e.toLowerCase()]||5}function g(b){var d=b.el,e=b.url,f=b.flashVars,k=b.adIds,
m=b.opt_props;(new q).getTime();this.ao=k;this.FIND_AD_TRIES=k.numTries||0;var g;try{if(d){var n=d,l;"DIV"===n.tagName&&((n=d.getElementsByTagName("EMBED")[0])||(n=d.getElementsByTagName("OBJECT")[0]),n||(n=d.getElementsByTagName("IMG")[0]),n||(n=d));if("OBJECT"===n.tagName){for(var u=0;u<n.children.length;u++)if("movie"===n.children[u].name||"Movie"===n.children[u].name)l=n.children[u].value;n.object&&n.object.Movie?l=n.object.Movie:n.data&&-1!==n.data.indexOf("swf")&&(l=n.data)}"EMBED"!==n.tagName&&
"IMG"!==n.tagName||!n.src||(l=n.src);var v=a.m.a(l,n);g={adURL:l,flashVars:v}}else g=!1}catch(s){g=!1}if(g&&g.adURL&&f)for(p in g.flashVars)g.flashVars.hasOwnProperty(p)&&(f[p]=g.flashVars[p]);g&&g.flashVars&&(f=g.flashVars);if("string"!==typeof e||"DIV"===e)e=g&&g.adURL||"-";e&&0!==e.toLowerCase().indexOf("http:")&&0!==e.toLowerCase().indexOf("https:")&&("/"===e[0]?e=window.location.protocol+"//"+window.location.host+e:(g=window.location.pathname.split("/").slice(0,-1).join("/"),e=window.location.protocol+
"//"+window.location.host+"/"+g+(g?"/":"")+e));"IFRAME"!==d.tagName&&"IMG"!==d.tagName&&-1===e.indexOf("googlesyndication")&&(e=e.split("?")[0]);this.zr=k.adNum;r[this.zr]=this;a.l.d(this.zr,[d]);this.ae=e;this.aa=d;this.WINDOW=a.e.a(this.aa);this.INITIAL_WIDTH=d.offsetWidth;this.INITIAL_HEIGHT=d.offsetHeight;"undefined"===typeof f&&(f={});t.i[D]=!0;this.eg=[];this.ee={};m&&m.IS_PAGE_LEVEL||(this.ed={},a.f.i(this));a.e.g(this);this.ag=f;this.ah=void 0;this.ai=0;this.an=this.am=this.al=this.ak=this.aj=
void 0;this.ar=[];this.as=[];this.at=[];this.av=this.au=a.g.a.a.a;this.ax=a.g.a.b.a;this.ay=a.g.a.c.a;this.ba=this.az=a.g.a.d.a;this.bb=a.g.a.e.a;this.by=this.bx=this.bw=this.bv=this.bu=this.bt=this.bs=this.br=this.bq=this.bp=this.bo=this.bm=this.bl=this.bk=this.bi=this.bh=this.bg=this.bf=this.be=this.bd=this.bc=void 0;this.ca=this.bz=!1;this.cb=this.cu=this.ct=void 0;this.cc=+new q+12E4;this.BEACON_LAST_SENT_AT=+new q;this.cl=this.cm=void 0;this.cn=0;this.ck=a.g.a.f.a;this.cd=!1;this.cy=void 0;this.dt=
!1;this.db=void 0;this.cf=this.ce=!1;this.af=Number(this.ef);this.eq=!1;this.ds=this.ch=this.dr=this.cg=0;this.dq=this.bn=void 0;this.IR5={MIN:{x:void 0,y:void 0},MAX:{x:void 0,y:void 0},AREA:0};a.k.b(this);this.dm=0;this.ep=this.dd=!1;this.aq={};this.aq.g=0;this.aq[1]=0;this.aq[2]=0;this.aq[3]=0;this.aq[13]=0;this.aq[0]=0;this.aq[4]=0;this.aq[5]=0;this.aq[6]=0;this.aq[7]=0;this.aq[9]=0;this.aq[8]=0;this.aq[15]=0;this.aq[16]=0;this.aq[21]=0;this.aq[22]=0;this.aq[23]=0;this.INVIEW_TIME_THRESHHOLDS=
[5,10,15,30,60];this.DWELL_TIME_THRESHHOLDS=[5,10,15,30,60];this.an=b.adType||c(d);0===this.an&&(this.WMODE=h(d));a.l.c(this)}function c(a){return"IFRAME"===a.tagName?2:"IMG"===a.tagName?1:"EMBED"===a.tagName||"OBJECT"===a.tagName?0:3}a.l={};a.l.b=function(b,d,e,f,k,m,l){var n;n=1==arguments.length?arguments[0]:{el:b,url:d,flashVars:f,adIds:k,opt_props:l};if(m){if("function"===typeof m)return m(b,d,f,k);new q;m.em=!0;r[m.zr]=m;b[U]=m.zr;b[v]=!0;m.aa=b;m.INITIAL_WIDTH=b.offsetWidth;m.INITIAL_HEIGHT=
b.offsetHeight;m.ae=d;m.an=c(b);0===m.an&&(m.WMODE=h(b));m.ag=f||{};a.h.a(m);n={e:0};n.q=m.aq[0]++;a.i.a(m,n);return m}return new g(n)};a.l.c=function(b){b.de=b.ao.startTime;b.RAND=b.ao.rand;(new q).getTime();b.dd=!0;a.k.c(b);var c={e:0};c.q=b.aq[0]++;a.i.a(b,c);a.h.a(b)};a.l.a=function(b){var c=+new q,e=c-b.BEACON_LAST_SENT_AT;if(0<b.DWELL_TIME_THRESHHOLDS.length){var f=1E3*b.DWELL_TIME_THRESHHOLDS[0];if(b.counters.strictDwell.tCur>=f){b.DWELL_TIME_THRESHHOLDS.shift();var k=b.INVIEW_TIME_THRESHHOLDS.length?
b.INVIEW_TIME_THRESHHOLDS[0]:60;if(f<k)return!1;if(5E3<e)return!0}}return 0<b.INVIEW_TIME_THRESHHOLDS.length&&(k=1E3*b.INVIEW_TIME_THRESHHOLDS[0],a.k.d(b,k))?(b.INVIEW_TIME_THRESHHOLDS.shift(),!0):0===b.DWELL_TIME_THRESHHOLDS.length&&c>b.cc?(b.cc*=2,!0):!1};a.l.d=function(a,c){for(var e=0;e<c.length;e++){var f=c[e];f[U]=a;f[v]=!0}}})(l);(function(a){function l(b,c,f){if(!b)return!1;var k=a.a.e(),k=null!==k&&11>k;if(!k)for(var g=b.getElementsByTagName("embed"),h=0;h<g.length;h++){var n=g[h];if(!0!==
n[v]&&-1===n.id.indexOf("moatPx")&&a.a.n(n)&&n.getAttribute("src")){var q=n.getAttribute("src"),k=a.m.a(q,n);return a.l.b(n,q,!1,k,c,f)}}n=b.getElementsByTagName("object");for(h=0;h<n.length;h++)if(g=n[h],a.a.n(g)&&("undefined"===typeof g[v]||!0!==g[v])&&-1==g.id.indexOf("moatPx")){for(b=0;b<g.children.length;b++)if("movie"===g.children[b].name||"Movie"===g.children[b].name)for(q=g.children[b].value,h=0;h<g.children.length;h++){if(!k&&"EMBED"===g.children[h].tagName){n=g.children[h];if("undefined"!==
typeof n[v]&&!0===n[v]||-1!=n.id.indexOf("moatPx"))continue;if(a.a.n(n))return k=a.m.a(q,n),a.l.b(n,q,!1,k,c,f)}if("OBJECT"===g.children[h].tagName&&(n=g.children[h],a.a.n(n)&&!0!==n[v]&&-1===n.id.indexOf("moatPx")))return a.l.b(n,void 0,!1,void 0,c,f)}g.object&&g.object.Movie?q=g.object.Movie:g.data&&(q=g.data);k=a.m.a(q,g);return a.l.b(g,q,!1,k,c,f)}if(q=a.n.g(b,c,f))return q;q=b.getElementsByTagName("img");for(h=0;h<q.length;h++)if(k=q[h],"undefined"===typeof k[v]||!0!==k[v]){if(a.a.n(k)&&""!==
k.src&&-1===document.location.href.indexOf(k.src))return a.l.b(k,k.getAttribute("src"),!1,void 0,c,f);E["1"]=k.offsetWidth+"x"+k.offsetHeight+":"+k.src}return!1}function g(d,e){for(var f=[],g=d.getElementsByTagName("iframe"),m,h=0;h<g.length;h++)if(m=g[h],!m[v]&&a.a.n(m)){var l=a.o.b(m)?!1:!0;(e===c&&l||e===b&&!l)&&f.push(m)}return f}a.n={};var c=1,b=2;a.n.a=function(b,c,f,g,m){var h=a.n.b,l=0;a.c.f(function(){c.numTries=l++;return h(b,c,f,g)&&!0},a.n.c,500,m)};a.n.g=function(b,e,f){b=g(b,c);if(b[0])return a.l.b(b[0],
b[0].src,!1,void 0,e,f)};a.n.f=function(b,c,f){var g;b=a.n.e(b,a.n.h);for(var m=0;m<b.length;m++)if(g=b[m],g=a.o.b(g))if(g=l(g.documentElement,c,f))return g};a.n.i=function(b,c,f){var g,m;b=a.n.e(b,a.n.h);for(var q=0;q<b.length;q++)if(m=b[q],m=a.o.b(m)){if(g=m.getElementById("flite-1"))if(g=a.l.b(g,g.nodeName,!1,void 0,c,f))return g;if(g=l(m.documentElement,c,f))return g}};a.n.d=l;a.n.b=function(b,c,f,g){var m=a.n.d;if("undefined"===typeof b)return!1;if("HEAD"===b.tagName){var h=b.parentNode;"HTML"===
h.tagName&&(h=h.getElementsByTagName("body"),0<h.length&&(b=h[0]))}return(h=m(b,c,f))||(h=a.n.f(b,c,f))||(ba||g)&&(g=g||a.o.a(b))&&(!a.b.a||"BODY"!==g.nodeName||a.e.a(g)!=a.b.c)&&(h=m(g,c,f))?h:!1};a.n.e=g;a.n.j=c;a.n.h=b;a.n.k=500;a.n.c=20;a.n.l={object:1,embed:1,img:1,iframe:1}})(l);(function(a){function h(a,c){for(var b={},d=a.split("&"),e=0;e<d.length;e++){var f=d[e].split("=");if("string"===typeof f[1]){var k=f,h,l=h=f[1];try{for(var n=0;100>n&&(h=decodeURIComponent(h),l!=h);n++)l=h}catch(q){}h=
h.replace(/(^\s+|\s+$)/g,"");k[1]=h}else f[1]="";b[f[0]]=f[1]}"undefined"!==typeof c&&(b.clientZone="undefined"!==c?c:"");return b}a.p={};a.p.a=function(a){"undefined"===typeof a.startTime&&(a.startTime=(new q).getTime());"undefined"===typeof a.rand&&(a.rand=u.floor(u.random()*u.pow(10,8)));a.adNum=t.zr;t.zr++};a.p.b=function(a){try{var c=a.className,b=a.getAttribute("src");c.split("\n").join(" ");if(-1!==c.indexOf("moatfooter"))return!1;var d=b.split("?");1==d.length&&(d=b.split("#"));return 1<d.length?
h(d[1],"undefined"):!1}catch(e){return!1}};a.p.c=function(a){try{var c=a&&a.className.replace("amp;","").split("?")[1];return c&&h(c)}catch(b){return!1}};a.p.d=function(a){try{var c=zoneRegEx.exec(a.innerHTML);0<c.length&&(zone=c[1]);return zone}catch(b){}};a.p.e=function(a){return(a=unescape(unescape(unescape(unescape(a.innerHTML)))).match(/~fdr=(\d*).*?\/.*?;(\d*)/))?{adid:a&&a[1]||"-",cid:a&&a[2]||"-"}:!1};a.p.f=function(a,c){return c||{}}})(l);(function(a){function h(c,b){var d,e=[],f,g=a.a.d()?
2048:7750,h=b||{};f={};for(d in c)c.hasOwnProperty(d)&&(1!=c.e||"x"!==d&&"y"!==d&&"c"!==d?e.push(encodeURIComponent(d)+"="+encodeURIComponent(c[d])):f[d]=c[d].split("a"));d=e.join("&");var e=g-d.length,l=0;if("undefined"!==typeof f.x){for(var n=0,q=0;q<f.x.length;q++)if(n+=f.x[q].length+(f.y[q]?f.y[q].length:0)+(f.c[q]?f.c[q].length:0),n<e)l++;else break;0<l&&(d+="&x="+f.x.slice(0,l-1).join("a"),d+="&y="+f.y.slice(0,l-1).join("a"),d+="&c="+f.c.slice(0,l-1).join("a"))}for(var r in h)h.hasOwnProperty(r)&&
(f="&"+encodeURIComponent(r)+"="+encodeURIComponent(h[r]),f.length+d.length<g&&(d+=f));return d}function g(a,b){for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d])}a.i={};a.i.b=function(c,b){a.p.a(b);var d={};d.e=c;d.i=J;if(11===c){var e=[],f;for(f in E)E.hasOwnProperty(f)&&e.push(f+"="+E[f]);d.k=e.join("&")}d.e in Y||(d.bq=a.b.e,d.f=Number(!M),d.j=a.b.b,d.o=3,d.t=b.startTime,d.de=b.rand,d.m=0,d.ar=Z,a.a.t(d,"ai",t.z),d.q=t.m++,d.cb=I?1:0,d.cu=V,d.r=a.f.a,g(d,a.focus.getQueryString()),a.p.f(b,d),"undefined"!==
typeof b&&(d.d=b.moatClientLevel1+":"+b.moatClientLevel2+":"+b.moatClientLevel3+":-",d.zMoatADV=b.moatClientLevel1||"-",d.d=b.moatClientLevel2+":"+b.moatClientSlicer1+":"+b.moatClientSlicer2+":"+b.moatClientLevel3,d.bo=b.moatClientSlicer1,d.bd=b.moatClientSlicer2),d.ac=1,d.it=a.n.k,d=h(d),t.yh.yi(d+"&cs=0",W,$))};a.i.c=function(c){!0!==c.em&&(delete r[c.zr],clearTimeout(c.cc),a.n.a(A.parentNode,c.ao,c))};a.i.a=function(c,b){if(!c||!0===c.ep)return!1;if(!a.e.h(c))return a.e.i(c),!1;if("undefined"!==
typeof c.ao&&(2!==c.an||1!==b.e&&3!==b.e)&&!(b.e in Y)){b.lo=c.FIND_AD_TRIES;b.ak=c.ae;c.ah&&(b.a=c.ah);var d=c.ag,e={};if(9===b.e&&2===b.q||25===b.e){for(var f in d)d.hasOwnProperty(f)&&""!==f&&"undefined"!==typeof d[f]&&-1===f.indexOf("dvContains")&&-1===f.indexOf("indexOf")&&-1===f.toLowerCase().indexOf("clicktag")&&(e["z"+f]=d[f]);b.e=25}0===c.an&&(b.dc=c.WMODE);0!==b.e&&a.e.j(c);c.bi>c.bg&&(c.bg=c.bi);c.bm>c.bk&&(c.bk=c.bm);b.i=J;b.bq=a.b.e;b.g=c.aq.g++;d=c.INITIAL_WIDTH;b.h=c.INITIAL_HEIGHT;
b.w=d;b.f=Number(!M);b.j=a.b.b;b.o=3;b.t=c.de;b.de=c.RAND;b.cu=V;b.m=b.m||a.a.g(c);b.ar=Z;b.cb=I?1:0;b.r=a.f.a;g(b,a.j.c());a.j&&a.j.b()?b.ch=1:a.f&&a.f.b?(b.ch=1,b.ct=a.f.c,"undefined"!==typeof a.f.o&&c&&c.ao&&c.ao.startTime&&!isNaN(c.ao.startTime)&&(d=a.f.o-c.ao.startTime,b.fg=0<=d?d:0)):b.ch=0;g(b,a.k.g(c.zr));g(b,a.focus.getQueryString());g(b,c.counters.getQs());a.a.t(b,"ai",t.z);a.a.t(b,"ap",c.cb);a.a.t(b,"ax",c.bg);a.a.t(b,"ay",c.bi);a.a.t(b,"az",c.bk);a.a.t(b,"ba",c.bm);a.a.t(b,"aw",c.bc);
a.a.t(b,"bg",c.bd);a.a.t(b,"be",c.be);a.a.t(b,"bc",c.bw);a.a.t(b,"bf",c.by);a.a.t(b,"bh",c.bx);a.a.t(b,"bz",c.cu);b.cl=u.round(100*c.IR5.AREA/(b.w*b.h));b.au=c.aq[2]-1;b.av=c.aq[3]-1;b.by=c.aq[23]-1;b.at=c.dm;a.p.f(c.ao,b);b.d=c.ao.moatClientLevel1+":"+c.ao.moatClientLevel2+":"+c.ao.moatClientLevel3+":-";b.zMoatADV=c.ao.moatClientLevel1||"-";b.d=c.ao.moatClientLevel2+":"+c.ao.moatClientSlicer1+":"+c.ao.moatClientSlicer2+":"+c.ao.moatClientLevel3;b.bo=c.ao.moatClientSlicer1;b.bd=c.ao.moatClientSlicer2;
b.ab=c.an;b.ac=1;b.it=a.n.k;c.bi=c.bg;c.bm=c.bk;e=h(b,e);t.yh.yi(e+"&cs=0",W,$)}};a.i.d=function(a,b){if(2!==a.an||1!==b.e&&3!==b.e){var d=ca;(new Image(1,1)).src=d}};a.i.e=function(a,b){return h(a,b)};a.i.f=function(c){var b={e:16};b.q=c.aq[16]++;a.i.a(c,b)}})(l);(function(a){function h(a,b,d,e){var f=(new q).getTime();this.tLast=this.tCur=0;this.update=function(b){var d=(new q).getTime();a(b)&&(b=u.min(d-f,1E3),this.tCur+=b,"number"===typeof e&&this.tCur>e&&(this.tCur=e));f=d};this.getQs=function(a){data=
this.query(a);this.tLast=this.tCur;return data};this.query=function(a){a=a||{};this.tLast>this.tCur&&(this.tLast=this.tCur);a[b]=this.tCur;a[d]=this.tLast;return a}}function g(){if(a.focus.pageIsVisible()&&"undefined"===typeof t.z){t.z=new q-V;a:{var c=void 0,b;for(b in r)if(r.hasOwnProperty(b)&&(c=r[b])&&"undefined"!==typeof c.ao){if(c.ce)break a;var d={e:4};d.q=c.aq[4]++;d.ai=t.z;a.i.a(c,d);c.ce=!0}a.c.c(x,"scroll",g,"onScroll")}}}a.e={};a.e.k=function(){a.c.b(x,"scroll",g,"onScroll");a.focus.setFocusListeners()};
a.e.h=function(c,b){try{var d=c.aa;b=b||c.WINDOW||a.e.a(d);return d&&b&&(d.parentNode||d.parentElement)?!0:!1}catch(e){return!1}};a.e.j=function(){var c,b;for(b in r)r.hasOwnProperty(b)&&(c=r[b],a.e.h(c,c.WINDOW)?c.counters.update(c):a.e.i(c))};a.e.i=function(c){clearTimeout(c.cc);c.ep=!0;delete r[c.zr];a.h.a(c,"remove");a.k.f(c.zr);c.aa=null};a.e.e=function(c){c.eq||(c.eq=!0);var b={e:5};b.q=c.aq[5]++;a.i.a(c,b)};a.e.d=function(c){var b;c.elementRect?(b=c.elementRect.right-c.elementRect.left,c=c.elementRect.bottom-
c.elementRect.top):(b=c.aa.offsetWidth,c=c.aa.offsetHeight);return 3>b||3>c||a.focus.pageIsPrerendered()?!0:!1};a.e.l=function(a){var b=1;screen.deviceXDPI?b=screen.deviceXDPI/screen.systemXDPI:a.devicePixelRatio&&"undefined"!==typeof a.mozInnerScreenX&&(b=a.devicePixelRatio);return{w:b*screen.width,h:b*screen.height}};a.e.a=function(a){try{var b=a&&a.ownerDocument;return b&&(b.defaultView||b.parentWindow)}catch(d){return!1}};a.e.g=function(c){c.counters={};c.counters.laxDwell=new h(function(){return!a.focus.pageIsPrerendered()},
"bu","cd");c.counters.strictDwell=new h(a.focus.pageIsVisible,"ah","am");c.counters.query=function(){var a={},c;for(c in this)if(this.hasOwnProperty(c)){var e=this[c];"function"===typeof e.query&&e.query(a)}return a};c.counters.getQs=function(){var a={},c;for(c in this)if(this.hasOwnProperty(c)){var e=this[c];"function"===typeof e.getQs&&e.getQs(a)}return a};c.counters.update=function(a){for(var c in this)if(this.hasOwnProperty(c)){var e=this[c];"function"===typeof e.update&&e.update(a)}}};a.e.b=
function(c,b){for(var d=[],e,f=0;f<da;f++)if(b!=b.parent){if(e=a.o.c(c,b))d.push(e);else break;b=b.parent;c=e}else break;return d};a.e.m=function(){for(var c in r)if(r.hasOwnProperty(c)){var b=r[c];if(b){var d={e:21};d.q=b.aq[21]++;a.i.a(b,d)}}};a.e.f=function(c){var b={e:9};b.q=c.aq[9]++;c.BEACON_LAST_SENT_AT=+new q;a.i.a(c,b)}})(l);(function(a){a.o={};a.o.b=function(h){try{if(h.moatHostileIframe)return null;if(h.src&&h.src.slice&&"http"===h.src.slice(0,4)&&a.a.h(h.src)!=a.a.h(x.location.toString()))return h.moatHostileIframe=
!0,null;var g=h&&(h.contentDocument||h.contentWindow&&h.contentWindow.document);if(g&&"string"===typeof g.location.toString())return g;h.moatHostileIframe=!0;return null}catch(c){return h.moatHostileIframe=!0,null}};a.o.c=function(h,g){g=g||a.e.a(h);try{return g&&g.frameElement}catch(c){return!1}};a.o.a=function(h){return(h=a.o.c(h))?h.parentNode:null}})(l);(function(a){a.q={};a.q.a=function(h){h[a.b.d]=h[a.b.d]||{zs:!1,zr:0,h:0,m:0,i:{}};var g=h[a.b.d];"undefined"===typeof g.v&&(g.v=M?"undefined"===
typeof h.document.hasFocus||I?!0:h.document.hasFocus():!0);g.ye||(g.ye=function(){this.v=!0});g.yd||(g.yd=function(){this.v=!1})}})(l);(function(a){var h=function(a,c){function b(a,b,c){a&&h.push({qs:a,jsd:b,fld:c});if(0===l&&0<h.length)if(l+=1,a=h.shift(),a.fld&&r&&n&&n.sendMessage)try{n.sendMessage(a)}catch(d){r=!1,e(a)}else e(a)}function d(){try{return new u(1,1)}catch(a){var b=window.document.createElement("img");b.height=1;b.width=1;return b}}function e(a){var b=d();b.toSend=a;b.onerror=function(){var a=
this.toSend;q+=1;var b=(a.jsd+"/pixel.gif?"+a.qs).length;2>q?e(a):v&&b>x&&f()};b.onload=function(){f()};b.src=a.jsd+"/pixel.gif?"+a.qs}function f(){0<l&&(l-=1,b())}var h=[],l=0,q=0,n=!1,r=!1,u,t=c[a];t.yh={};t=t.yh;u=c.Image;t.yi=function(a,c,d){b(a,c,d)};t.yk=function(b){n=!0;var c=a+".yh.",d={},e;try{e=window.location.protocol}catch(f){e=document.createElement("a"),e.href="",e=e.protocol}d.src="https:"===e?"https://z.moatads.com/swf/MessageSenderV2.swf":"http://s.moatads.com/swf/MessageSenderV2.swf";
d.flashVars="r="+c+"zb&s="+c+"zc&e="+c+"zd&td="+b;return d};t.yj=function(){return!1===n};t.zb=function(){try{if(!0===n){var a=c.document.getElementById("moatMessageSender");a&&!a.sendMessage&&(a=c.document.getElementById("moatMessageSenderEmbed"));a&&a.sendMessage&&(r=!0,n=a)}}catch(b){}};t.zc=function(){try{f()}catch(a){}};t.zd=function(a){try{r=!1,a&&a.jsd&&h.push(a),f()}catch(b){}};var s,v,x=2083;try{s=document.createElement("div"),s.innerHTML="\x3c!--[if IE 8]>x<![endif]--\x3e",v="x"===s.innerHTML}catch(A){v=
!1}}.toString();a.r={};a.r.a=function(g){if(!t.yh)if("undefined"!==typeof g.eval)g.eval("("+h+")('"+a.b.d+"',window)");else{var c=g.document.createElement("script");c.type="text/javascript";c.text="("+h+")('"+a.b.d+"',window)";g.document.body.insertBefore(c,g.document.body.childNodes[0])}}})(l);if(l.a.l())return!1;var J="AKQAPR2",aa="akqapointroll38472721",Z="099702a-clean",V=l.b.i,v="moatFound"+J,U="__moat__"+J,ca="",ba=l.b.l,M=l.b.a,$="afs.moatads.com",W,D=0,S,T,E={},da=50,N=[],O=[],r={},Y=
{15:"",12:"",6:"",7:""};W="//v3.moatads.com";var x=l.b.c;l.q.a(x);var t=x[l.b.d];window[l.b.d]=t;l.r.a(x);l.a.h(M?x.location.href:x.document.referrer)||l.a.h(window.location.href);var A=l.a.q();if(!A)return!1;l.s=A;l.a.r(A);var I=l.a.i();(function(a){D=t.h;t.h++;t.i[D]=!1;!1===t.zs&&(l.e.k(),t.zs=!0);l.c.d(function(){l.e.j();for(var a in r)r.hasOwnProperty(a)&&l.k.c(r[a])},200);var h=!1;l.c.b(window,"unload",function(){h||(l.e.m(),h=!0)},!1);l.c.b(window,"beforeunload",function(){h||(l.e.m(),h=!0)},
!1);l.c.d(l.h.b,100);l.a.d()&&l.c.e(X,3E5);"undefined"===typeof a&&(a=l.p.b(A));var g=A.parentNode;l.c.e(function(){!1===t.i[D]&&(l.i.b(11,a),X())},1E4);l.i.b(17,a);l.n.a(g,a)})()})(Date,Math)}catch(e$$47){var msg=e$$47.name+" in closure: "+e$$47.message+", stack="+e$$47.stack;try{var pxSrc="//v3.moatads.com/pixel.gif?e=24&d=data%3Adata%3Adata%3Adata&i="+escape("AKQAPR2")+"&ac=1&k="+escape(msg)+"&ar="+escape("099702a-clean")+"&j="+escape(document.referrer)+"&cs="+(new Date).getTime(),px=new Image(1,
1);px.src=pxSrc}catch(e$$48){}};
