// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 1
(function(w,g){w[g]=w[g]||{};w[g].e=function(s){return eval(s);};})(window,'google_tag_manager');(function(){
var m=this,aa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b},ba=null;/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var ca=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,da=function(a){if(null==a)return String(a);var b=ca.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},ea=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},fa=function(a){if(!a||"object"!=da(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!ea(a,"constructor")&&!ea(a.constructor.prototype,"isPrototypeOf"))return!1}catch(b){return!1}for(var c in a);return void 0===
c||ea(a,c)};var ga=function(){},w=function(a){return"function"==typeof a},A=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},ha=function(a){return"number"==da(a)&&!isNaN(a)},ia=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},ja=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},B=function(a){return Math.round(Number(a))||0},ka=function(a){var b=[];if(A(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));
return b},C=function(){this.prefix="gtm.";this.na={}};C.prototype.set=function(a,b){this.na[this.prefix+a]=b};C.prototype.get=function(a){return this.na[this.prefix+a]};C.prototype.contains=function(a){return void 0!==this.get(a)};
var la=function(a,b,c){try{return a["1"](a,b||ga,c||ga)}catch(d){}return!1},ma=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=ja(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},na=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},oa=function(a){for(var b=0;b<a.length;b++)a[b]()},pa=(new Date).getTime(),qa=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c};var D=window,F=document,ra=navigator,G=function(a,b){var c=D[a],d="var "+a+";";if(m.execScript)m.execScript(d,"JavaScript");else if(m.eval)if(null==ba&&(m.eval("var _et_ = 1;"),"undefined"!=typeof m._et_?(delete m._et_,ba=!0):ba=!1),ba)m.eval(d);else{var e=m.document,f=e.createElement("script");f.type="text/javascript";f.defer=!1;f.appendChild(e.createTextNode(d));e.body.appendChild(f);e.body.removeChild(f)}else throw Error("goog.globalEval not available");D[a]=void 0===c?b:c;return D[a]},K=function(a,
b,c,d){return(d||"http:"!=D.location.protocol?a:b)+c},sa=function(a){var b=F.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)},ta=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},L=function(a,b,c){var d=F.createElement("script");d.type="text/javascript";d.async=!0;d.src=a;ta(d,b);c&&(d.onerror=c);sa(d)},ua=function(a,b){var c=F.createElement("iframe");c.height="0";c.width="0";c.style.display=
"none";c.style.visibility="hidden";sa(c);ta(c,b);void 0!==a&&(c.src=a);return c},k=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},O=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},P=function(a){D.setTimeout(a,0)},va=!1,wa=[],xa=function(a){if(!(a&&"readystatechange"==a.type&&"interactive"!=F.readyState&&"complete"!=F.readyState||va)){va=!0;for(var b=0;b<wa.length;b++)wa[b]()}},
ya=0,za=function(){if(!va&&140>ya){ya++;try{F.documentElement.doScroll("left"),xa()}catch(a){D.setTimeout(za,50)}}},Ba=function(a){var b=F.getElementById(a);if(b&&Aa(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(Aa(document.all[a][c],"id")==a)return document.all[a][c];return b},Aa=function(a,b){return a&&b&&a.attributes[b]?a.attributes[b].value:null},Ca=function(a){return a.target||a.srcElement||{}},Da=function(a,b){for(var c={},d=0;d<b.length;d++)c[b[d]]=!0;for(var e=a,d=0;e&&!c[String(e.tagName).toLowerCase()]&&
100>d;d++)e=e.parentElement;e&&!c[String(e.tagName).toLowerCase()]&&(e=null);return e},Ea=!1,Fa=[],Ga=function(){if(!Ea){Ea=!0;for(var a=0;a<Fa.length;a++)Fa[a]()}},Ha=function(a){a=a||D;var b=a.location.href,c=b.indexOf("#");return 0>c?"":b.substring(c+1)};var Ja=new C,Ka={},La=ga,Ma=[],Na=!1,Qa={set:function(a,b){Oa(Pa(a,b),Ka)},get:function(a){return R(a,2)}},Ra=function(a){var b=!1;return function(){!b&&w(a)&&P(a);b=!0}},Sa=function(){for(var a=!1;!Na&&0<Ma.length;){Na=!0;var b=Ma.shift();if(w(b))try{b.call(Qa)}catch(c){}else if(A(b))e:{var d=b;if("string"==da(d[0])){for(var e=d[0].split("."),f=e.pop(),g=d.slice(1),h=Ka,q=0;q<e.length;q++){if(void 0===h[e[q]])break e;h=h[e[q]]}try{h[f].apply(h,g)}catch(n){}}}else{var l;var r=b,p=void 0;for(p in r)if(r.hasOwnProperty(p)){var s=
p,z=r[p];Ja.set(s,z);Oa(Pa(s,z),Ka)}var E=r.event;if(E){var u=Ra(r.eventCallback),M=r.eventTimeout;M&&D.setTimeout(u,Number(M));l=La(E,u)}else l=!1;a=l||a}Na=!1}return!a},R=function(a,b){if(2==b){for(var c=Ka,d=a.split("."),e=0;e<d.length;e++){if(void 0===c[d[e]])return;c=c[d[e]]}return c}return Ja.get(a)},Pa=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c},Oa=function(a,b){for(var c in a)if(ea(a,c)){var d=a[c];A(d)?(A(b[c])||(b[c]=[]),Oa(d,
b[c])):fa(d)?(fa(b[c])||(b[c]={}),Oa(d,b[c])):b[c]=d}};var Ta={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},Ua={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels","customScripts","html","nonGoogleScripts","nonGoogleIframes"],
nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},Va=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},Wa=function(){var a=R("gtm.whitelist"),b=a&&Va(ka(a),Ta),c=R("gtm.blacklist")||R("tagTypeBlacklist"),d=c&&Va(ka(c),Ua),e={};return function(f){var g=f&&f["1"];if(!g)return!0;if(void 0!==e[g.a])return e[g.a];var h=!0;if(a)e:{if(0>ia(b,g.a))if(g.b&&0<g.b.length)for(var q=0;q<g.b.length;q++){if(0>
ia(b,g.b[q])){h=!1;break e}}else{h=!1;break e}h=!0}var n=!1;if(c){var l;if(!(l=0<=ia(d,g.a)))e:{for(var r=g.b||[],p=new C,s=0;s<d.length;s++)p.set(d[s],!0);for(s=0;s<r.length;s++)if(p.get(r[s])){l=!0;break e}l=!1}n=l}return e[g.a]=!h||n}};var Xa=null;var _e=function(){return Xa};_e.a="e";_e.b=["google"];var _v=function(a){var b=R(a["3"].replace(/\\\./g,"."),a[""]);return void 0!==b?b:a[""]};_v.a="v";_v.b=["google"];var _f=function(){return String(R("gtm.referrer")||F.referrer)};_f.a="f";_f.b=["google"];
var Ya=F.createElement("a"),Za=function(a){var b=D.location,c=b.hash?b.href.replace(b.hash,""):b.href,d=R("gtm.url");d&&(Ya.href=c=String(d),b=Ya);var e=(b.protocol.replace(":","")||D.location.protocol.replace(":","")).toLowerCase();switch(a["0"]){case "protocol":c=e;break;case "host":c=(b.hostname||D.location.hostname).split(":")[0].toLowerCase();break;case "port":c=String(1*(b.hostname?b.port:D.location.port)||("http"==e?80:"https"==e?443:""));break;case "path":c="/"==b.pathname.substr(0,1)?b.pathname:"/"+b.pathname;
break;case "query":c=b.search.replace("?","");break;case "fragment":c=b.hash.replace("#","")}
return c},_u=Za;_u.a="u";_u.b=["google"];var _eq=function(a){return String(a[""])==String(a[""])};_eq.a="eq";_eq.b=["google"];var db=function(a,b){return a<b?-1:a>b?1:0};var eb;e:{var fb=m.navigator;if(fb){var ib=fb.userAgent;if(ib){eb=ib;break e}}eb=""}var S=function(a){return-1!=eb.indexOf(a)};var jb=S("Opera")||S("OPR"),T=S("Trident")||S("MSIE"),kb=S("Gecko")&&-1==eb.toLowerCase().indexOf("webkit")&&!(S("Trident")||S("MSIE")),lb=-1!=eb.toLowerCase().indexOf("webkit"),mb=function(){var a=m.document;return a?a.documentMode:void 0},nb=function(){var a="",b;if(jb&&m.opera){var c=m.opera.version;return"function"==aa(c)?c():c}kb?b=/rv\:([^\);]+)(\)|;)/:T?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:lb&&(b=/WebKit\/(\S+)/);if(b)var d=b.exec(eb),a=d?d[1]:"";if(T){var e=mb();if(e>parseFloat(a))return String(e)}return a}(),
ob={},U=function(a){var b;if(!(b=ob[a])){for(var c=0,d=String(nb).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(d.length,e.length),g=0;0==c&&g<f;g++){var h=d[g]||"",q=e[g]||"",n=RegExp("(\\d*)(\\D*)","g"),l=RegExp("(\\d*)(\\D*)","g");do{var r=n.exec(h)||["","",""],p=l.exec(q)||["","",""];if(0==r[0].length&&0==p[0].length)break;c=db(0==r[1].length?0:parseInt(r[1],10),0==p[1].length?0:parseInt(p[1],10))||db(0==r[2].length,0==p[2].length)||
db(r[2],p[2])}while(0==c)}b=ob[a]=0<=c}return b},pb=m.document,qb=pb&&T?mb()||("CSS1Compat"==pb.compatMode?parseInt(nb,10):5):void 0;if(kb||T){var rb;if(rb=T)rb=T&&9<=qb;rb||kb&&U("1.9.1")}T&&U("9");var wb=function(a,b){var c="";T&&!sb(a)&&(c='<script>document.domain="'+document.domain+'";\x3c/script>'+c);var d="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+c+"</head><body>"+b+"</body></html>";if(tb)a.srcdoc=d;else if(ub){var e=a.contentWindow.document;e.open("text/html","replace");e.write(d);e.close()}else vb(a,d)},tb=lb&&"srcdoc"in document.createElement("iframe"),ub=kb||lb||T&&U(11),vb=function(a,b){T&&U(7)&&!U(10)&&6>xb()&&yb(b)&&(b=zb(b));var c=function(){a.contentWindow.goog_content=
b;a.src="javascript:window.goog_content"};T&&!sb(a)?Ab(a,c):c()},xb=function(){var a=navigator.userAgent.match(/Trident\/([0-9]+.[0-9]+)/);return a?parseFloat(a[1]):0},sb=function(a){try{var b;var c=a.contentWindow;try{b=!!c&&null!=c.location.href}catch(d){b=!1}return b}catch(e){return!1}},Bb=0,Ab=function(a,b){var c="goog_rendering_callback"+Bb++;window[c]=b;T&&U(6)&&!U(7)?a.src="javascript:'<script>window.onload = function() { document.write(\\'<script>(function() {document.domain = \""+document.domain+
'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation()})()<\\\\/script>\\');document.close();};\x3c/script>'":a.src="javascript:'<script>(function() {document.domain = \""+document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation();})()\x3c/script>'"},yb=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},zb=function(a){for(var b=unescape(encodeURIComponent(a)),c=Math.floor(b.length/2),d=[],e=0;e<c;++e)d[e]=
String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(d[c]=b.charAt(b.length-1));return d.join("")};/*
 Copyright (c) 2013 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */
var Jb=function(a,b,c,d){return function(e){e=e||D.event;var f=Ca(e),g=!1;if(3!==e.which||"CLICK"!=a&&"LINK_CLICK"!=a)if(2!==e.which&&(null!=e.which||4!=e.button)||"LINK_CLICK"!=a)if("LINK_CLICK"==a&&(f=Da(f,["a"]),g=!f||!f.href||e.ctrlKey||e.shiftKey||e.altKey||!0===e.metaKey),e.defaultPrevented||!1===e.returnValue||e.Q&&e.Q()){if(!c&&f){var h={simulateDefault:!1};V(a,f,h,d)}}else{var q=/(iPad|iPhone|iPod)/g.test(ra.userAgent);if(f){var h={},n=V(a,f,h,d);h.simulateDefault=!n&&b&&!g;if(h.simulateDefault){var l=
Ib(f).toLowerCase();switch(l){case "_blank":q?(h.simulateDefault=!1,g=!0):(h.targetWindowName="gtm_autoEvent_"+(new Date).getTime(),h.targetWindow=D.open("",h.targetWindowName));break;case "":h.targetWindow=D.frames.self;break;case "_self":case "_parent":case "_top":h.targetWindow=D.frames[l.substring(1)];break;default:q&&!D.frames[l]?(h.simulateDefault=!1,g=!0):(D.frames[l]||(h.targetWindowName=l),h.targetWindow=D.frames[l]||D.open("",l))}!g&&e.preventDefault&&e.preventDefault()}e.returnValue=n||
!b||g;return e.returnValue}return!0}}},V=function(a,b,c,d){var e=d||2E3,f={"gtm.element":b,"gtm.elementClasses":b.className,"gtm.elementId":b["for"]||Aa(b,"id")||"","gtm.elementTarget":b.formTarget||b.target||""};switch(a){case "LINK_CLICK":f.event="gtm.linkClick";f["gtm.elementUrl"]=b.href;f.eventTimeout=e;f.eventCallback=Kb(b,c);break;case "FORM_SUBMIT":f.event="gtm.formSubmit";f["gtm.elementUrl"]=Lb(b);c.jsFormSubmit?c.waitForTags&&(f.eventTimeout=e,f.eventCallback=function(){F.gtmSubmitFormNow=
!0;Nb(b).call(b)}):(f.eventTimeout=e,f.eventCallback=Mb(b,c));break;case "CLICK":f.event="gtm.click";f["gtm.elementUrl"]=b.formAction||b.action||b.href||b.src||b.code||b.codebase||"";break;default:return!0}return D["dataLayer"].push(f)},Lb=function(a){var b=a.action;b&&b.tagName&&(b=a.cloneNode(!1).action);return b},Ib=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "form":b="_self"}return b},Kb=function(a,b,c){return function(){b.simulateDefault&&(b.targetWindow?
b.targetWindow.location.href=a.href:(c=c||(new Date).getTime(),500>(new Date).getTime()-c&&D.setTimeout(Kb(a,b,c),25)))}},Mb=function(a,b,c){return function(){if(b.simulateDefault)if(b.targetWindow){var d;b.targetWindowName&&(d=a.target,a.target=b.targetWindowName);F.gtmSubmitFormNow=!0;Nb(a).call(a);b.targetWindowName&&(a.target=d)}else c=c||(new Date).getTime(),500>(new Date).getTime()-c&&D.setTimeout(Mb(a,b,c),25)}},Ob=function(a,b,c,d){var e,f;switch(a){case "CLICK":if(F.gtmHasClickListenerTag)return;
F.gtmHasClickListenerTag=!0;e="click";f=function(a){var b=Ca(a);b&&V("CLICK",b,{},d);return!0};break;case "LINK_CLICK":if(F.gtmHasLinkClickListenerTag)return;F.gtmHasLinkClickListenerTag=!0;e="click";f=Jb(a,b||!1,c||!1,d);break;case "FORM_SUBMIT":if(F.gtmHasFormSubmitListenerTag)return;F.gtmHasFormSubmitListenerTag=!0;e="submit";f=Jb(a,b||!1,c||!1,d);break;default:return}O(F,e,f,!1)},Nb=function(a){try{if(a.constructor&&a.constructor.prototype)return a.constructor.prototype.submit}catch(b){}if(a.gtmReplacedFormSubmit)return a.gtmReplacedFormSubmit;
F.gtmFormElementSubmitter||(F.gtmFormElementSubmitter=document.createElement("form"));return F.gtmFormElementSubmitter.submit};var Rb,Sb;
var bc=function(a){return function(){}},cc=function(a){return function(){}};var nc=function(a){var b=D||m,c=b.onerror,d=!1;lb&&!U("535.3")&&(d=!d);b.onerror=function(b,f,g,h,q){c&&c(b,f,g,h,q);a({message:b,fileName:f,Ta:g,kb:h,error:q});return d}};var Lc=function(){this.f=[]};Lc.prototype.set=function(a,b){this.f.push([a,b]);return this};Lc.prototype.A=function(a,b){for(var c={},d=0;d<this.f.length;d++){var e=Y(this.f[d][0],a,b),f=Y(this.f[d][1],a,b);c[e]=f}return c};var Mc=function(a){this.index=a};Mc.prototype.A=function(a,b){var c=Nc[this.index];if(c&&!b(c)){var d=c["2"];if(a){if(a.get(d))return;a.set(d,!0)}c=Y(c,a,b);a&&a.set(d,!1);return la(c)}};
for(var _M=function(a){return new Mc(a)},Pc=function(a){this.A=function(b,c){for(var d=[],e=0;e<a.length;e++)d.push(Y(Oc[a[e]],b,c));return d.join("")}},_T=function(a){return new Pc(arguments)},Qc=function(a){function b(b){for(var d=1;d<a.length;d++)if(a[d]==b)return!0;return!1}this.A=function(c,d){if(a[0]instanceof Mc&&b(8)&&b(16))return'google_tag_manager["GTM-PQJDGJ"].macro('+
a[0].index+")";for(var e=String(Y(a[0],c,d)),f=1;f<a.length;f++)e=X[a[f]](e);return e}},_E=function(a,b){return new Qc(arguments)},Y=function(a,b,c){var d=a;if(a instanceof Mc||a instanceof Lc||a instanceof Pc||a instanceof Qc)return a.A(b,c);if(A(a))for(var d=[],e=0;e<a.length;e++)d[e]=Y(a[e],b,c);else if(a&&"object"==typeof a){var d={},f;for(f in a)a.hasOwnProperty(f)&&(d[f]=Y(a[f],b,c))}return d},Rc=function(a,b){var c=b[a],d=c;if(c instanceof Mc||c instanceof Qc||c instanceof Pc)d=c;else if(A(c))for(var d=
[],e=0;e<c.length;e++)d[e]=Rc(c[e],b);else if("object"==typeof c){var d=new Lc,f;for(f in c)c.hasOwnProperty(f)&&d.set(b[f],Rc(c[f],b))}return d},Uc=function(a,b){for(var c=b?b.split(","):[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");0==a&&(e[1]=Oc[e[1]]);if(1==a)for(var f=Sc(e[0]),e=c[d]={},g=0;g<f.length;g++){var h=Tc[f[g]];e[h[0]]=h[1]}if(2==a)for(g=0;4>g;g++)e[g]=Sc(e[g])}return c},Sc=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<Vc;c+=6,d++){var e=a&&a.charCodeAt(d)||
65;if(65!=e){var f=0,f=65<e&&90>=e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:62;1&f&&b.push(c);2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},Vc=21,Wc=[_v,'element target','gtm.elementTarget','element id','gtm.elementId','element classes','gtm.elementClasses','element','gtm.element',_e,'event',_f,'referrer',_u,'url path','path','url hostname','host','url','element url','gtm.elementUrl'],Xc=[],Yc=0;Yc<Wc.length;Yc++)Xc[Yc]=Rc(Yc,Wc);var Oc=Xc,Tc=Uc(0,"1:0,2:1,3:2,2:3,3:4,2:5,3:6,2:7,3:8,1:9,2:10,1:11,2:12,1:13,2:14,0:15,2:16,0:17,2:18,2:19,3:20"),Nc=Uc(1,"H,Z,hB,BG,AY,AgB,AAO,AAy,AACB,BAAG"),Zc=Uc(1,""),$=Uc(1,""),$c=Uc(2,"");var hd=function(){var a=this;this.p=!1;this.t=[];this.K=[];this.la=function(){a.p||oa(a.t);a.p=!0};this.ka=function(){a.p||oa(a.K);a.p=!0};this.L=ga},id=function(){this.h=[];this.Z={};this.M=[];this.n=0};id.prototype.addListener=function(a){this.M.push(a)};var jd=function(a,b,c,d){if(!c.p){a.h[b]=c;void 0!==d&&(a.Z[b]=d);a.n++;var e=function(){0<a.n&&a.n--;0<a.n||oa(a.M)};c.t.push(e);c.K.push(e)}};var kd=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=Zc[b]&&Y(Zc[b],new C,c);a[b]=[d&&la(d),d]}return a[b]}},ld=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.i(c[d],a.c)[0])return!1;for(var e=b[2],d=0;d<e.length;d++)if(a.i(e[d],a.c)[0])return!1;return!0},md=function(a,b){return function(){a["4"]=b.la;a["5"]=b.ka;la(a,b.la,b.ka)}},La=function(a,b){Xa=a;R("tagTypeBlacklist");for(var c={name:a,Ha:b||ga,v:Sc(),w:Sc(),i:kd(),c:Wa()},d=
0;d<$c.length;d++)if(ld(c,$c[d])){for(var e=c,f=$c[d],g=f[1],h=0;h<g.length;h++)e.v[g[h]]=!0;for(var q=f[3],h=0;h<q.length;h++)e.w[q[h]]=!0}var n=[];for(var l=0;l<Vc;l++)if(c.v[l]&&!c.w[l])if(c.c($[l])){}else{n[l]=Y($[l],new C,c.c);}c.O=
n;for(var r=new id,p=0;p<Vc;p++)if(c.v[p]&&!c.w[p]&&!c.c($[p])){var s=c.O[p],z=new hd;z.t.push(bc(s));z.K.push(cc(s));z.L=md(s,z);jd(r,p,z,s[""])}r.addListener(c.Ha);for(var E=[],u=0;u<r.h.length;u++){var M=r.h[u];if(M){var H=r.Z[u];void 0!==H?H!=u&&r.h[H]&&r.h[H].t.push(M.L):E.push(u)}}for(u=0;u<E.length;u++)r.h[E[u]].L();0<r.n||oa(r.M);Xa=null;return 0<c.O.length};var nd={macro:function(a){var b;if(b=Nc[a]){var c=_M(a),d=Wa();b=Y(c,new C,d)}return b},Ua:function(){var a=D.google_tag_manager;a||(a=D.google_tag_manager={});a["GTM-PQJDGJ"]||(a["GTM-PQJDGJ"]=nd)}};nd.Ua();
(function(){var a=G("dataLayer",[]),b=G("google_tag_manager",{}),b=b["dataLayer"]=b["dataLayer"]||{};wa.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});Fa.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(Ma.push.apply(Ma,b);300<this.length;)this.shift();return Sa()};Ma.push.apply(Ma,a.slice(0));P(Sa)})();
if("interactive"==F.readyState||"complete"==F.readyState)xa();else{O(F,"DOMContentLoaded",xa);O(F,"readystatechange",xa);if(F.createEventObject&&F.documentElement.doScroll){var od=!0;try{od=!D.frameElement}catch(pd){}od&&za()}O(D,"load",xa)}"complete"===F.readyState?Ga():O(D,"load",Ga);var _vs="res_ts:1390865472431000,srv_cl:64313264,ds:live,cv:1";
})()
