/*Copyright (c) 2011-2014 Moat Inc. All Rights Reserved.*/
try{(function(n,q){function ca(){for(var a in t)t.hasOwnProperty(a)&&m.c.i(t[a]);for(a=0;a<P.length;a++)window.clearTimeout(P[a]);for(a=0;a<Q.length;a++)window.clearInterval(Q[a])}var m={};(function(a){function h(a){var c=new RegExp("(^| )"+a+"($| )");return function(a){return a&&a.className&&a.className.match(c)}}function g(a){return a&&a.document&&a.location&&a[c+d]&&a[e+k]}function f(a){if(null==a||g(a))return!1;var c=a.length;return 1===a.nodeType&&c?!0:"string"===typeof a||b(a)||0===c||"number"===
typeof c&&0<c&&c-1 in a}function b(c){return"[object Array]"===a.a.ab.toString.call(c)}a.a={};a.a.a=3E3;a.a.b=function(){var a=/Firefox\/(\d+)/.exec(navigator.userAgent);return a?14<parseInt(a[1],10):!1}();a.a.c=function(){var c;c=/^(?:[a-z]+:\/\/|:?\/?\/)?(?:www\.)?([^\/:]*)/i;c=!a.b.a&&a.b.b?(c=a.b.b.match(c))&&c[1]?c[1]:a.b.c.location.hostname:a.b.c.location.hostname;var b=c.match(/.*\.([^\.]*\..*)/i);return b&&b[1]?decodeURIComponent(b[1]):decodeURIComponent(c)};a.a.d=function(a,c){for(var b=
[a],d=1;d<=c;d++)b.push(a+d),b.push(a-d);b=b[q.floor(q.random()*b.length)];d=q.floor(q.random()*b);return{multiplier:b,sample:0==d}};a.a.e=function(c,b){var d=a.a.d(c,b);a.a.e=function(){return d};return d};a.a.f=function(){var c=a.a.g();return 5===c||6===c||7===c};a.a.g=function(){if(!navigator)return null;var a=navigator.userAgent;return"Microsoft Internet Explorer"==navigator.appName?parseInt(a.replace(/^.*MSIE (\d+).*$/,"$1"),10):"Netscape"==navigator.appName&&(a=a.match(/Trident\/.*rv:(\d+)/))?
parseInt(a[1],10):null};a.a.h=function(a,c){for(var b=0;b<a.length;b++)if(a[b]===c)return!0;return!1};a.a.i=function(){function a(c){c=c.match(/[\d]+/g);c.length=3;return c.join(".")}var c=!1,b="";if(navigator.plugins&&navigator.plugins.length){var d=navigator.plugins["Shockwave Flash"];d&&(c=!0,d.description&&(b=a(d.description)));navigator.plugins["Shockwave Flash 2.0"]&&(c=!0,b="2.0.0.11")}else if(navigator.mimeTypes&&navigator.mimeTypes.length)(c=(d=navigator.mimeTypes["application/x-shockwave-flash"])&&
d.enabledPlugin)&&(b=a(d.enabledPlugin.description));else try{d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),c=!0,b=a(d.GetVariable("$version"))}catch(f){try{d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),c=!0,b="6.0.21"}catch(e){try{d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),c=!0,b=a(d.GetVariable("$version"))}catch(k){}}}return c?b:"0"};a.a.getElementsByClassName=function(a,c,b){c=c||"*";b=b||document;if(b.getElementsByClassName){var d=[],f=b.getElementsByClassName(a);
if("*"!==c){a=0;for(b=f.length;a<b;a++){var e=f[a];e.tagName===c&&d.push(e)}return d}return f}f=[];c=b.getElementsByTagName(c);b=h(a);e=c.length;for(a=0;a<e;a++)d=c[a],b(d)&&f.push(d);return f};a.a.j=h;a.a.k=function(a){return new n-a.de};a.a.l=function(a){return a.replace(/^http:/,"").replace(/^\/\//,"").replace(/^www[^.]*\./,"").split("/")[0]};a.a.m=function(c,b){var d=[c];a.a.forEach("number"===typeof b?b:50,function(){if(c.parentNode&&1==c.parentNode.nodeType)c=c.parentNode,d.push(c);else return!1});
return d};a.a.n=function(c,b){var d="number"===typeof b?b:50,f=[],e=a.c.a(c);if(e)f.push(e);else return f;a.a.forEach(d,function(){var b=a.d.a(c,e);return b&&(e=a.c.a(b))?(f.push(e),!0):!1});return f};a.a.o=function(){return null!==/iPad|iPhone|iPod|Silk|Kindle|Android|BlackBerry|PlayBook|BB10|Windows Phone/.exec(navigator.userAgent)};a.a.p=function(){return null!==/iPhone|iPod/.exec(navigator.userAgent)};a.a.q=function(){var a=navigator.userAgent;return a.match(/iPhone|iPod|iPad/)&&!a.match(/Safari/i)};
a.a.r=function(){var a=window;try{return"undefined"!==typeof a.external&&"undefined"!==typeof a.external.InPrivateFilteringEnabled&&a.external.InPrivateFilteringEnabled()||"undefined"!==typeof a.external&&"undefined"!==typeof a.external.msTrackingProtectionEnabled&&a.external.msTrackingProtectionEnabled()||"undefined"!==typeof a._gaUserPrefs&&a._gaUserPrefs.ioo&&a._gaUserPrefs.ioo()||"undefined"!==typeof navigator.doNotTrack&&("yes"===navigator.doNotTrack||!0===navigator.doNotTrack)||"undefined"!==
typeof a._gaUserPrefs&&!0===a._gaUserPrefs}catch(c){return!1}};a.a.getAttribute=function(a,c){return a[c]||a.getAttribute(c)};a.a.s=function(a){var c=0,b;for(b in a)a.hasOwnProperty(b)&&(c+=1);return c};a.a.t=function(c,b){return a.a.u(c)&&!0!==c[v]?!0:!1};a.a.u=function(c){return c.offsetWidth*c.offsetHeight>=a.a.a};a.a.v=function(a,c){if("string"!==typeof a||!c||!c.insertBefore||!c.ownerDocument)return!1;var b=c.ownerDocument.createElement("script");b.type="text/javascript";b.async=!0;c.insertBefore(b,
c.childNodes[0]);b.src=a;return!0};a.a.w=function(){var a;return function(){if(!a)a:{for(var c=document.getElementsByTagName("script"),b=c.length-1;-1<b;b--)if((a=c[b])&&a.src&&a.src.indexOf&&-1!==a.src.indexOf(ha+"/moatad.js")&&("undefined"===typeof a[v]||!0!==a[v])){a[v]=!0;break a}a=void 0}return a?(a[v]=!0,a):null}}();a.a.x=function(a){try{return-1!==(a.src||a.getAttribute("src")).indexOf("psd=1")}catch(c){return!1}};a.a.y=function(a){for(var c=[],b=0;b<a.length;b++)c.push(a[b]);return c};a.a.previousElementSibling=
function(a){if(a.previousElementSibling)return a.previousElementSibling;for(;a=a.previousSibling;)if(1===a.nodeType)return a};a.a.z=function(a,c,b){"undefined"!==typeof b&&(a[c]=b)};a.a.filter=function(a,c){for(var b=[],d=0;d<a.length;d++)c(a[d])&&b.push(a[d]);return b};a.a.aa=function(a,c){for(var b=[],d=0;d<c.length;d++)b.push(a(c[d]));return b};a.a.bind=function(a,c){return function(){a[c].apply(a,arguments)}};var c="ale",d="rt",e="setInte",k="rval";a.a.ab={};a.a.ac=function(a,c){if(a&&c&&c.childNodes){var b=
c.childNodes;0<b.length?c.insertBefore(a,b[0]):c.appendChild(a)}};a.a.ad=function(a,c){if("undefined"===typeof a)return!1;for(var b=0,d=c.length;b<d;b++)if("string"==typeof c[b]&&(a=a[c[b]],"undefined"===typeof a))return!1;return a};a.a.ae=function(a){return encodeURIComponent(a.moatClientLevel1+":"+a.moatClientLevel2+":"+a.moatClientLevel3+":"+a.moatClientLevel4)};a.a.af=b;a.a.ag=g;a.a.ah=f;a.a.forEach=function(a,c,b,d){var e,k=typeof a;if(a)if("function"===k)for(e in a){if("prototype"!=e&&"length"!=
e&&"name"!=e&&(d||!a.hasOwnProperty||a.hasOwnProperty(e))&&(k=c.call(b,a[e],e),"boolean"===typeof k&&!k))break}else if("number"===k)for(e=0;e<a&&(k=c.call(b,a,e),"boolean"!==typeof k||k);e++);else if("function"===typeof a.every)a.every(function(a,d,e){a=c.call(b,a,d);return!("boolean"===typeof a&&!a)});else if(f(a))for(e=0;e<a.length&&(k=c.call(b,a[e],e),"boolean"!==typeof k||k);e++);else for(e in a)if(d||a.hasOwnProperty(e))if(k=c.call(b,a[e],e),"boolean"===typeof k&&!k)break;return a}})(m);(function(a){function h(a){try{var b=
typeof a.location.toString;if("undefined"===b||"unknown"===b)return!0;var c=typeof a.document;return"undefined"===c||"unknown"===c?!0:!1}catch(d){return!0}}a.b={};a.b.d="MoatSuperV4";a.b.e=0;a.b.f=0<Object.prototype.toString.call(window.HTMLElement).indexOf("Constructor");a.b.g=-1!==navigator.userAgent.toLowerCase().indexOf("firefox");a.b.h=-1!==navigator.userAgent.indexOf("MSIE");a.b.i=(new n).getTime();a.b.protocol=function(){var a;try{a=window.location.protocol}catch(b){a=document.createElement("a"),
a.href="",a=a.protocol}return a}();a.b.j=("https:"===a.b.protocol?"z":"js")+".moatads.com";a.b.k=window!=window.parent;var g=h(window.parent);a.b.l=a.b.k&&!g;a.b.a=g?!1:!h(window.top);a.b.c=a.b.a?window.top:a.b.l?window.parent:window;a.b.b=a.b.c.document.referrer})(m);(function(a){function h(a){return function(){var b=!1;return function(c){try{a(c)}catch(d){if(!b){b=!0;c=(new n).getTime();window["Moat#ETS"]||(window["Moat#ETS"]=c);window["Moat#EMC"]||(window["Moat#EMC"]=0);var e=36E5<=c-window["Moat#ETS"],
k=d.name+" in closure: "+d.message+", stack="+d.stack;if(!e&&10>window["Moat#EMC"]){window["Moat#EMC"]++;try{var l="//v4.moatads.com/pixel.gif?e=24&d=data%3Adata%3Adata%3Adata&i="+escape("POLARNTV2")+"&ac=1&k="+escape(k)+"&ar="+escape("5d61d2b-clean")+"&j="+escape(document.referrer)+"&cs="+(new n).getTime(),r=new Image(1,1);r.src=l}catch(D){}}else if(e){window["Moat#EMC"]=1;window["Moat#ETS"]=c;try{l="//v4.moatads.com/pixel.gif?e=24&d=data%3Adata%3Adata%3Adata&i="+escape("POLARNTV2")+"&ac=1&k="+
escape(k)+"&ar="+escape("5d61d2b-clean")+"&j="+escape(document.referrer)+"&cs="+(new n).getTime(),r=new Image(1,1),r.src=l}catch(K){}}}}}}()}a.e={};var g={};a.e.a=g;a.e.b=function(f,b){if(!f||"string"!==typeof b||!f[b]||f==window)return!1;if("string"===typeof f.nodeName&&("OBJECT"===f.nodeName||"EMBED"===f.nodeName)){var c=a&&a.f&&a.f[b];if(c&&c!==f[b])return c}return!1};a.e.c=function(f,b,c,d){c=h(c);var e;f.addEventListener?(e=a.e.b(f,"addEventListener"))?e.call(f,b,c,!1):f.addEventListener(b,c,
!1):(e=a.e.b(f,"attachEvent"))?e.call(f,"on"+b,c):f.attachEvent("on"+b,c);!1!==d&&(g[b+d]=c)};a.e.d=function(f,b,c,d){var e=b+d,k;c=!1!==d?g[e]:c;try{f&&f.removeEventListener?(k=a.e.b(f,"removeEventListener"))?k.call(f,b,c,!1):f.removeEventListener(b,c,!1):f&&f.detachEvent&&((k=a.e.b(f,"detachEvent"))?k.call(f,"on"+b,c):f.detachEvent("on"+b,c))}catch(l){}delete g[e]};a.e.e=function(a,b){a=h(a);var c=setInterval(a,b);Q.push(c);return c};a.e.f=function(a,b){a=h(a);var c=setTimeout(a,b);P.push(c);return c};
a.e.g=function(f,b,c,d){var e=0,k=function(){e+=1;!0!==f()&&(e<b?a.e.f(k,c):"function"===typeof d&&d())};k()};a.e.h=h})(m);(function(a){function h(a,b){for(var e=[],f=0;f<b.length;f++)e.push(a(b[f]));return e}function g(c){var b,e=a.c.b(c.el,c.win),e=h(function(c){return new a.g.g(c)},e);e.unshift(c);var f=e.length;c=new a.g.g(c.el,a.b.c);for(var l=0;l<f;l++){var r=e[l];0===l?b=r:(b.changeReferenceFrame(r),c.changeReferenceFrame(r));r=r.getViewportRect(l<f-1?e[l+1]:!1);b=a.g.i(b,r)}return{visibleRect:b,
cumulRect:c,parentArea:e[e.length-1].calcArea()}}function f(a,b,e,f){a=q.max(a,e);b=q.min(b,f);return b>a?[a,b]:[0,0]}a.g={};var b=a.b.a;a.g.a=.5;a.g.b=.3;a.g.c=236425;a.g.d=function(c,b){var e;e=new a.g.g(c.aa,b);var f=e.height,l=e.width,r=e.calcArea();if(0===r)e={area:r,percv:0};else{var D=g(e),K=D.visibleRect.calcArea(),h=K/r,x;b:{var u=D.cumulRect,H=D.cumulRect.getViewportRect();if(0>u.top&&0<u.bottom)x=-u.top;else if(0<=u.top&&u.top<=H.height)x=0;else{x={yMin:-1,yMax:-1};break b}if(0<=u.bottom&&
u.bottom<=H.height)u=u.height;else if(u.bottom>H.height&&u.top<H.height)u=u.height-(u.bottom-H.height);else{x={yMin:-1,yMax:-1};break b}x={yMin:x,yMax:u}}e={area:r,visibleArea:K,percv:h,yMinMax:x,elGeo:{elHeight:f,elWidth:l,foldTop:D.cumulRect.top,totalArea:D.parentArea},rect:e.rect}}f=a.g.e(e,c);e.isVisible=e.percv>=f;e.isFullyVisible=1==e.percv;e.elGeo&&(e.elGeo.threshold=f);return e};a.g.e=function(c,b){return c.area>=a.g.c?(b.viewstats.isBigAd=!0,a.g.b):a.g.a};a.g.f=function(){return b};a.g.h=
function(a){var b,e,f,l=0,r=0;try{b=a.document,e=b.documentElement,f=b.body}catch(D){return{width:l,height:r,left:0,right:l,top:0,bottom:r}}"undefined"!==typeof a.innerWidth?(l=a.innerWidth,r=a.innerHeight):"CSS1Compat"===b.compatMode&&5!==b.documentMode||!f||"undefined"===typeof f.clientWidth?e&&"undefined"!==typeof e.clientWidth&&(l=e.clientWidth,r=e.clientHeight):(l=f.clientWidth,r=f.clientHeight);return{width:l,height:r,left:0,right:l,top:0,bottom:r}};a.g.g=function(c,b,e){this.rect=e||c.getBoundingClientRect();
e=["left","right","top","bottom"];for(var f=0;f<e.length;f++){var l=e[f];this[l]=this.rect[l]}this.width=this.right-this.left;this.height=this.bottom-this.top;this.el=c;this.win=b||c&&a.c.a(c);this.changeReferenceFrame=function(a){this.left+=a.left;this.right+=a.left;this.top+=a.top;this.bottom+=a.top};this.calcArea=function(){return(this.right-this.left)*(this.bottom-this.top)};this.getViewportRect=function(c){var b=a.g.h(this.win);c&&(c.width<b.width&&(b.width=c.width,b.right=b.left+b.width),c.height<
b.height&&(b.height=c.height,b.bottom=b.top+b.height));return b}};a.g.i=function(b,d){var e=f(b.left,b.right,d.left,d.right),k=f(b.top,b.bottom,d.top,d.bottom);return new a.g.g(void 0,void 0,{left:e[0],right:e[1],top:k[0],bottom:k[1]})};a.g.j=function(a,b){b||(b=window);var e=b.document.documentElement,f=b.document.body;return"left"===a?b.pageXOffset||e&&e.scrollLeft||f&&f.scrollLeft:b.pageYOffset||e&&e.scrollTop||f&&f.scrollTop}})(m);(function(a){function h(a,b,c){a.IR5.MIN[c]=q.min(b,a.IR5.MIN[c])||
b||1;a.IR5.MAX[c]=q.max(b,a.IR5.MAX[c])||b}function g(a,b){b.be=q.max("undefined"!==typeof b.be?b.be:0,a-b.bf);"undefined"===typeof b.by&&500<=b.be&&(b.by=b.bk)}function f(b){b.az===a.h.a.d.a?b.az=a.h.a.d.b:b.az===a.h.a.d.b&&(b.az=a.h.a.d.a)}function b(b){b.ba===a.h.a.d.a?b.ba=a.h.a.d.b:b.ba===a.h.a.d.b&&(b.ba=a.h.a.d.a)}function c(b){b.ax===a.h.a.b.a?b.ax=a.h.a.b.b:b.ax===a.h.a.b.b&&(b.ax=a.h.a.b.a)}function d(b){b.ay===a.h.a.c.a?b.ay=a.h.a.c.b:b.ay===a.h.a.c.b&&(b.ay=a.h.a.c.a)}function e(a,b){"undefined"===
typeof b.bk&&(b.bk=0);b.bk+=a-b.bo;b.bo=a}function k(a,b){"undefined"===typeof b.bl&&(b.bl=0);b.bl+=a-b.bp;b.bp=a}function l(a,b){"undefined"===typeof b.bg&&(b.bg=0);"undefined"===typeof b.bc&&(b.bc=0);b.bu=a-b.bs;b.bu>b.bc&&(b.bc=b.bu);b.bg+=a-b.bq;500<=b.bc&&"undefined"===typeof b.bw&&(b.bk+=a-b.bo,b.bw=b.bk);b.bq=a}function r(a,b){"undefined"===typeof b.bh&&(b.bh=0);"undefined"===typeof b.bd&&(b.bd=0);b.bv=a-b.bt;b.bv>b.bd&&(b.bd=b.bv);b.bh+=a-b.br;500<=b.bd&&"undefined"===typeof b.bx&&(b.bl+=
a-b.bp,b.bx=b.bl);b.br=a}a.h={};a.h.a={};a.h.a.a={};a.h.a.a.a=0;a.h.a.a.b=1;a.h.a.b={};a.h.a.b.a=0;a.h.a.b.b=1;a.h.a.c={};a.h.a.c.a=0;a.h.a.c.b=1;a.h.a.d={};a.h.a.d.a=0;a.h.a.d.b=1;a.h.a.e={};a.h.a.e.a=0;a.h.a.e.b=1;a.h.a.f={};a.h.a.f.a=0;a.h.a.f.b=1;a.h.a.f.c=2;a.h.b=function(a){h(a,a.aj,"x");h(a,a.ak,"y");a.IR5.AREA=(a.IR5.MAX.x-a.IR5.MIN.x)*(a.IR5.MAX.y-a.IR5.MIN.y)};a.h.c=function(b){function c(){500<=(new n).getTime()-z&&(a.h.d({type:"park"},b),clearInterval(e),b.au=a.h.a.a.a)}var d=b.au;if(d===
a.h.a.a.a){z=(new n).getTime();var e=a.e.e(c,50);b.au=a.h.a.a.b}else d===a.h.a.a.b&&(z=(new n).getTime())};a.h.e=function(b){function c(){3E3<=(new n).getTime()-A&&(a.h.f({type:"park"},b),clearInterval(e),b.av=a.h.a.a.a)}var d=b.av;if(d===a.h.a.a.a){A=(new n).getTime();var e=a.e.e(c,50);b.av=a.h.a.a.b}else d===a.h.a.a.b&&(A=(new n).getTime())};a.h.g=function(b,c){var d=b.type;if(c.az===a.h.a.d.a){if("mouseover"===d||"mousemove"===d)c.bo=(new n).getTime(),f(c)}else if(c.az===a.h.a.d.b){"mousemove"===
d&&e((new n).getTime(),c);if("mouseout"===d||"blur"===d)e((new n).getTime(),c),f(c);"scooper"===d&&e((new n).getTime(),c)}};a.h.h=function(c,d){var e=c.type;if(d.ba===a.h.a.d.a){if("mouseover"===e||"mousemove"===e)d.bp=(new n).getTime(),b(d)}else if(d.ba===a.h.a.d.b){"mousemove"===e&&k((new n).getTime(),d);if("mouseout"===e||"blur"===e)k((new n).getTime(),d),b(d);"scooper"===e&&k((new n).getTime(),d)}};a.h.d=function(b,d){if(2!=d.an){var e=b.type;if(d.ax===a.h.a.b.a){if("mouseover"===e||"mousemove"===
e)d.bq=(new n).getTime(),d.bs=(new n).getTime(),c(d)}else d.ax===a.h.a.b.b&&("mousemove"!==e&&"mouseout"!==e||l((new n).getTime(),d),"park"===e&&l((new n).getTime()-500,d),"mouseout"!==e&&"park"!==e||c(d))}};a.h.f=function(b,c){if(2!=c.an){var e=b.type;if(c.ay===a.h.a.c.a){if("mouseover"===e||"mousemove"===e)c.br=(new n).getTime(),c.bt=(new n).getTime(),d(c)}else c.ay===a.h.a.c.b&&("mousemove"!==e&&"mouseout"!==e||r((new n).getTime(),c),"park"===e&&r((new n).getTime()-3E3,c),"mouseout"!==e&&"park"!==
e||d(c))}};a.h.i=function(b,c){var d=b.type;if(c.bb==a.h.a.e.a){if("mouseover"==d||"mousemove"==d)c.bf=(new n).getTime(),c.bb=a.h.a.e.b}else c.bb==a.h.a.e.b&&("mouseout"==d?(g((new n).getTime(),c),c.bb=a.h.a.e.a):"mousemove"!=d&&"scooper"!=d||g((new n).getTime(),c))}})(m);(function(a){function h(b){if(!a.focus.pageIsPrerendered()){a.e.d(document,l,h,"pr");for(var c in t)t.hasOwnProperty(c)&&a.c.c(t[c])}}function g(a){"undefined"==typeof d&&(d=a)}a.focus={};var f=navigator.userAgent,f=-1<f.indexOf("Safari")&&
-1==f.indexOf("Chrome")&&-1==f.indexOf("Chromium")&&!B,b=(eval("/*@cc_on!@*/false")||document.documentMode)&&!B,c="undefined"!==typeof document.hasFocus,d,e={visible:0,hidden:1,prerender:2},k,l,r,D;"undefined"!==typeof document.hidden?(k="hidden",l="visibilitychange"):"undefined"!==typeof document.mozHidden?(k="mozHidden",l="mozvisibilitychange"):"undefined"!==typeof document.msHidden?(k="msHidden",l="msvisibilitychange"):"undefined"!==typeof document.webkitHidden&&(k="webkitHidden",l="webkitvisibilitychange");
for(var m=["v","mozV","msV","webkitV"],q=0;q<m.length;q++){var x=m[q]+"isibilityState";if("undefined"!==typeof document[x]){r=x;break}}D="undefined"!==typeof k;var u,H;"undefined"!==typeof window.requestAnimationFrame?u="requestAnimationFrame":"undefined"!==typeof window.webkitRequestAnimationFrame&&(u="webkitRequestAnimationFrame");H=f&&"string"==typeof u&&!D;var da=(new n).getTime();H&&function R(){da=(new n).getTime();window[u](R)}();a.focus.getFocusMethod=function(){return d};a.focus.visibilitychange=
l;a.focus.setFocusListeners=function(){"Microsoft Internet Explorer"===navigator.appName?(a.e.c(w.document,"focusout",function(){s.yd()},!1),a.e.c(w.document,"focusin",function(){s.ye()},!1)):(a.e.c(w,"blur",function(){s.yd()},!1),a.e.c(w,"focus",function(){s.ye()},!1))};a.focus.getQueryString=function(a){a={};a.em=d;ia&&(a.eo=1);"undefined"!=typeof r&&(a.en=e[document[r]]);return a};a.focus.supportsPageVisAPI=function(){return D};a.focus.pageIsVisible=function(){if(a.focus.supportsPageVisAPI())return g(0),
!document[k];if(H)return g(1),100>(new n).getTime()-da;if(b&&c)return g(2),document.hasFocus();g(3);return!0};a.focus.pageIsPrerendered=function(){return"undefined"!==typeof r?"prerender"==document[r]:!1};a.focus.pageIsVisible();a.focus.pageIsPrerendered()&&a.e.c(document,l,h,"pr");var ia=a.focus.pageIsPrerendered();a.focus.windowHasFocus=function(){return s.v}})(m);(function(a){function h(b,c,d,e,f){("remove"===f?a.e.d:a.e.c)(b,c,function(c){c=c||this.event;var e=c.currentTarget||b,f=t[e[I]];if(f){var k;
k=c;var l=e.getBoundingClientRect();k=-1!=k.type.indexOf("touch")?{x:parseInt(k.changedTouches[0].clientX-l.left,10),y:parseInt(k.changedTouches[0].clientY-l.top,10)}:{x:parseInt(k.clientX-l.left,10),y:parseInt(k.clientY-l.top,10)};f.aj=k.x;f.ak=k.y;f.dm||(f.cb=2==a.focus.getFocusMethod()?f.counters.laxDwell.tCur:f.counters.strictDwell.tCur,f.dm=1);d.call(b,c,e,f)}},e)}function g(a,d,e){h(a,"click",m,d,e);h(a,"mousedown",b,d,e);B?h(a,"touchstart",c,d,e):(h(a,"mousemove",f,d,e),h(a,"mouseover",l,d,
e),h(a,"mouseout",r,d,e))}function f(b,c,d){B||d.aj===d.al&&d.ak===d.am||(a.h.d(b,d),a.h.f(b,d),a.h.g(b,d),a.h.i(b,d),a.h.h(b,d),a.h.b(d),a.h.c(d),a.h.e(d),0===d.ar.length&&(d.ai=s(d)),d.ar.push(d.aj),d.as.push(d.ak),d.at.push(a.a.k(d)),d.al=d.aj,d.am=d.ak);d.ai!==s(d)&&1<d.ar.length&&K(d,"onMouseMove")}function b(b,c,d){b={e:2};b.q=d.aq[2]++;b.x=d.aj;b.y=d.ak;a.j.a(d,b)}function c(b,c,d){b={e:23};b.q=d.aq[23]++;b.x=d.aj;b.y=d.ak;c=(new n).getTime();if("undefined"===typeof d.ct)d.ct=c;else{var e=
c-d.ct;d.ct=c;d.cu=q.min(d.cu,e)||e}b.bz=void 0;a.j.a(d,b)}function d(b,c,d){if(2==b.an){var f=c.e,l=b.ck;l==a.h.a.f.a&&6===f?(e(b,0),b.cl=a.a.k(b),b.ck=a.h.a.f.b):l==a.h.a.f.b?22===f?(k(b,c),e(b,d),b.cl=a.a.k(b)):7===f&&(1E3<a.a.k(b)-b.cl?(clearTimeout(b.cm),c.e=22,k(b,c),b.cn=0,b.ck=a.h.a.f.a):b.ck=a.h.a.f.c):l==a.h.a.f.c&&(6==f?(1E3<a.a.k(b)-b.cl&&(clearTimeout(b.cm),b.cn=0,b.cl=a.a.k(b),e(b,0)),b.ck=a.h.a.f.b):22==f&&(k(b,c),b.ck=a.h.a.f.a,b.cn=0))}}function e(b,c){var e=5>b.cn?1E3:2*c,f={e:22};
b.cm=a.e.f(function(){d(b,f,e)},e)}function k(b,c){c.q=b.aq[c.e]++;c.m=a.a.k(b);b.cl=c.m;a.j.a(b,c);b.cn++}function l(b,c,e){a.h.d(b,e);a.h.f(b,e);a.h.g(b,e);a.h.i(b,e);a.h.h(b,e);d(e,{e:6},0)}function r(b,c,e){a.h.d(b,e);a.h.f(b,e);a.h.g(b,e);a.h.i(b,e);a.h.h(b,e);d(e,{e:7},0)}function m(b,c,d){b={e:3};b.q=d.aq[3]++;b.x=d.aj;b.y=d.ak;a.j.a(d,b)}function K(b,c){b.ai=s(b);var d={e:1};d.q=b.aq[1]++;d.x=b.ar.join("a");d.y=b.as.join("a");for(var e=a.a.k(b),f=b.at,k=[],l=0;l<f.length;l++)isNaN(f[l])||
k.push(q.abs(f[l]-e));d.c=k.join("a");d.m=e;a.j.a(b,d);b.ar=[];b.as=[];b.at=[]}function s(b){return q.floor(a.a.k(b)/1E3)}a.i={};a.i.a=function(a,b){if(!0===a.isSkin)for(var c=0;c<a.elements.length;c++)g(a.elements[c],a.zr+"-"+c,b);else g(a.aa,a.zr,b)};a.i.b=function(b){for(var c in t)t.hasOwnProperty(c)&&(b=t[c])&&(a.h.g({type:"scooper"},b),a.h.i({type:"scooper"},b),a.h.h({type:"scooper"},b),1<b.ar.length&&b.ai!==s(b)&&K(b,"scooper"))}})(m);(function(a){function h(a){var b=0,e;return function(){var f=
(new n).getTime();150<f-b&&(e=a.apply(this,arguments),b=f);return e}}function g(b,d,e,k){var l=[],r=0,g=0,h=0,m=0,x=0,u=0,s=(new n).getTime(),t=!1,v=!1,T=!1,R=!1,w,aa,B,G=0,J=0,F=0,N=0,M=!1,O=a.b.a,S;if(0===k)var y="as",U="ag",V="an",W="ck",X="kw",Y="ah",Z="aj",P="pg",Q="pf",z="gi",A="gf",I="gg",M=!0;else 1===k?(y="cc",U="bw",V="bx",W="ci",X="jz",Y="bu",Z="dj"):2===k?(y="cg",U="ce",V="cf",W="cj",X="ts",Y="ah",Z="dk",z="gj",A="gb",I="ge"):3===k&&(y="cg",U="ce",V="cf",W="cj",X="ts",Y="ah",Z="dk",z=
"gi",A="gf",I="gg");this.addListener=function(a){l.push(a)};this.hadOTS=function(){return T};this.hadVideo2SecOTS=function(){return _hadVideo2SecOts};this.getInViewTime=function(){return r};this.visible=function(){return t};this.fullyVisible=function(){return v};this.update=function(h){var m=r||0,K=g||0,$=!1,C=b(h);h.elementRect=C.rect;var y=C.isVisible,z=C.isFullyVisible,E=d(h),A=(new n).getTime(),L=q.max(q.min(A-s,1E3),0);s=A;A=!e||a.focus.pageIsVisible(2===k||3===k);y=y&&A&&!E;z=z&&A&&!E;if(y&&
t)r+=L,x+=L;else if(y||t)E=q.round(L/2),r+=E,x+=E;if(z&&v)g+=L,u+=L;else if(z||v)E=q.round(L/2),g+=E,u+=E;!T&&1E3<=x&&($=T=!0,aa=r,this.timeToView=w=h.counters.query()[Y]);!R&&1E3<=u&&($=R=!0);"undefined"===typeof B&&(1E3>=h.counters.query().bu?y&&(B=!0):B=!1);if((h.FOLDMEASURABLE=O)&&"undefined"===typeof S&&2!==k&&3!==k&&C.elGeo){var E=f().y+C.elGeo.foldTop,I=C.elGeo.threshold*C.elGeo.elHeight;_isBTFCheck=E>a.k.a()-I;0<C.elGeo.totalArea&&(S=_isBTFCheck,h.BELOWTHEFOLDAD=S)}h=C.yMinMax;M&&A&&"undefined"!==
typeof h&&C.elGeo&&0<=h.yMax&&0<=h.yMin&&0<C.visibleArea&&(G=q.max(h.yMax,G),J=q.min(h.yMin,J),F=q.min(1,q.max((G-J)/C.elGeo.elHeight,F)));y||(x=0);z||(u=0);t=y;v=z;a.a.forEach(l,function(a){if(a.onInViewTimeCount)a.onInViewTimeCount(L,r-m);if(a.onFullyInViewTimeCount)a.onFullyInViewTimeCount(L,g-K)});return $};this.getQS=function(a){h>r&&(h=r);m>g&&(m=g);a[y]=Number(T);a[U]=r;a[V]=h;if(0===k||2===k||3===k)R&&(a[z]=1),a[A]=g,a[I]=m;"undefined"!==typeof aa&&(a[W]=aa);"undefined"!==typeof w&&(a[X]=
w);"undefined"!==typeof B&&(a[Z]=Number(B));if(!0===M){var b=q.round(100*F),c=q.round(100*N);a[P]=b;a[Q]=c;N=F}"undefined"!==typeof S&&(a.ib=Number(S));h=r;m=g}}function f(){var b=a.b.c,d=b.document;return{y:void 0!==b.pageYOffset?b.pageYOffset:(d.documentElement||d.body.parentNode||d.body).scrollTop}}a.k={};var b={};a.k.a=function(){return B?a.g.h(a.b.c).height:750};a.k.b=function(c){var d=c.zr;b[d]={};c.viewstats={isBigAd:!1};if(a.g.f()){var e=h(a.g.d),f;f=new g(e,a.c.d,!0,0);b[d].strict=f;e=new g(e,
a.c.d,!1,1);b[d].lax=e}!0!==c.isSkin&&a.l&&a.l.a()?(c=new g(a.l.b,a.c.d,!0,3),b[d].pscope=c):a.m&&a.m.a()&&(c=new g(a.m.b,a.c.d,!0,2),b[d].pscope=c)};a.k.c=function(c){var d=b[c.zr],e,f;for(f in d)d.hasOwnProperty(f)&&d[f].update(c)&&(e=!0);e&&a.c.e(c);a.n.a(c)&&a.c.f(c)};a.k.d=function(b,d,e){"unefined"==typeof e&&(e=!1);var f=a.k&&a.k.e(b.zr);b=(a.l&&a.l.a()||a.m&&a.m.c)&&f&&f.pscope.getInViewTime()>=d;d=e?a.g&&a.g.f()&&f&&f.strict&&f.strict.getInViewTime()>=d:a.g&&a.g.f()&&f&&f.lax&&f.lax.getInViewTime()>=
d;return a.b.a?d:b};a.k.f=function(a){delete b[a]};a.k.e=function(a){return b[a]};a.k.g=function(a){var d=null;(a=b[a])&&a.strict?d=a.strict:a&&a.pscope&&(d=a.pscope);return d};a.k.h=function(a){var d={},e=b[a],f;for(f in e)e.hasOwnProperty(f)&&e[f].getQS(d);(a=t[a])&&a.viewstats.isBigAd&&(d.el=1);return d}})(m);(function(a){a.o={};a.o.a=function(a,g){var f;g.outerHTML?f=g.outerHTML:(f=document.createElement("div"),f.appendChild(g.cloneNode(!0)),f=f.innerHTML);f=[/flashvars\s*=\s*(".*?"|'.*?')/i.exec(f),
/name\s*=\s*["']flashvars["']\s*value\s*=\s*(".*?"|'.*?')/i.exec(f),/value\s*=\s*(".*?"|'.*?')\s*name\s*=\s*["']flashvars["']/i.exec(f),a];for(var b,c,d={},e=0;e<f.length;e++){if((b=f[e])&&"object"===typeof b&&b[1])b=b[1].replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/^"/g,"").replace(/"$/g,"").replace(/^'/g,"").replace(/'$/g,"");else if("string"===typeof b)b=b.split("?")[1];else continue;if(b){b=b.split("&");for(var k=0;k<b.length;k++)c=b[k].split("="),2>c.length||"function"==c[0].slice(0,
8)||(d[c[0]]=[c[1]])}}return d}})(m);(function(a){function h(b){var c={window:0,transparent:1,opaque:2,direct:3,gpu:4};if("EMBED"===b.tagName)var d=a.a.getAttribute(b,"wmode");else if("OBJECT"===b.tagName){b=b.getElementsByTagName("param");for(var e=0;e<b.length;e++){var f=b[e],l=a.a.getAttribute(f,"name"),f=a.a.getAttribute(f,"value");if("wmode"===l){d=f;break}}}return d&&c[d.toLowerCase()]||5}function g(b){var c=b.el,d=b.url,e=b.flashVars,k=b.adIds;(new n).getTime();this.ao=k;this.FIND_AD_TRIES=
k.numTries||0;var l;try{if(c){var g=c,m;"DIV"===g.tagName&&((g=c.getElementsByTagName("EMBED")[0])||(g=c.getElementsByTagName("OBJECT")[0]),g||(g=c.getElementsByTagName("IMG")[0]),g||(g=c));1===g.nodeType&&"IMG"!==g.nodeName&&"EMBED"!==g.nodeName&&"OBJECT"!==g.nodeName&&(g=c.getElementsByTagName("EMBED")[0]||c.getElementsByTagName("OBJECT")[0]||c.getElementsByTagName("IMG")[0]||c);if("OBJECT"===g.tagName){for(var q=0;q<g.children.length;q++)if("movie"===g.children[q].name||"Movie"===g.children[q].name)m=
g.children[q].value;g.object&&g.object.Movie?m=g.object.Movie:g.data&&-1!==g.data.indexOf("swf")&&(m=g.data)}"EMBED"!==g.tagName&&"IMG"!==g.tagName||!g.src||(m=g.src);var v=a.o.a(m,g);l={adURL:m,flashVars:v}}else l=!1}catch(x){l=!1}if(l&&l.adURL&&e)for(p in l.flashVars)l.flashVars.hasOwnProperty(p)&&(e[p]=l.flashVars[p]);l&&l.flashVars&&(e=l.flashVars);if("string"!==typeof d||"DIV"===d)d=l&&l.adURL||"-";d&&0!==d.toLowerCase().indexOf("http:")&&0!==d.toLowerCase().indexOf("https:")&&("/"===d[0]?d=
window.location.protocol+"//"+window.location.host+d:(l=window.location.pathname.split("/").slice(0,-1).join("/"),d=window.location.protocol+"//"+window.location.host+"/"+l+(l?"/":"")+d));"IFRAME"!==c.tagName&&"IMG"!==c.tagName&&-1===d.indexOf("googlesyndication")&&(d=d.split("?")[0]);this.zr=k.adNum;t[this.zr]=this;a.n.d(this.zr,[c]);this.ae=d;this.aa=c;this.WINDOW=a.c.a(this.aa);this.INITIAL_WIDTH=c.offsetWidth;this.INITIAL_HEIGHT=c.offsetHeight;"undefined"===typeof e&&(e={});s.i[N]=!0;this.eg=
[];this.ee={};a.c.g(this);this.ag=e;this.ah=void 0;this.ai=0;this.an=this.am=this.al=this.ak=this.aj=void 0;this.ar=[];this.as=[];this.at=[];this.av=this.au=a.h.a.a.a;this.ax=a.h.a.b.a;this.ay=a.h.a.c.a;this.ba=this.az=a.h.a.d.a;this.bb=a.h.a.e.a;this.by=this.bx=this.bw=this.bv=this.bu=this.bt=this.bs=this.br=this.bq=this.bp=this.bo=this.bm=this.bl=this.bk=this.bi=this.bh=this.bg=this.bf=this.be=this.bd=this.bc=void 0;this.ca=this.bz=!1;this.cb=this.cu=this.ct=void 0;this.cc=+new n+12E4;this.BEACON_LAST_SENT_AT=
+new n;this.cl=this.cm=void 0;this.cn=0;this.ck=a.h.a.f.a;this.cd=!1;this.cy=void 0;this.dt=!1;this.db=void 0;this.cf=this.ce=!1;this.af=Number(this.ef);this.eq=!1;this.ds=this.ch=this.dr=this.cg=0;this.dq=this.bn=void 0;this.IR5={MIN:{x:void 0,y:void 0},MAX:{x:void 0,y:void 0},AREA:0};a.k.b(this);this.dm=0;this.ep=this.dd=!1;this.aq={};this.aq.g=0;this.aq[1]=0;this.aq[2]=0;this.aq[3]=0;this.aq[13]=0;this.aq[0]=0;this.aq[4]=0;this.aq[5]=0;this.aq[6]=0;this.aq[7]=0;this.aq[9]=0;this.aq[8]=0;this.aq[15]=
0;this.aq[16]=0;this.aq[21]=0;this.aq[22]=0;this.aq[23]=0;this.INVIEW_TIME_THRESHHOLDS=[5,10,15,30,60];this.DWELL_TIME_THRESHHOLDS=[5,10,15,30,60];this.an=b.adType||f(c);0===this.an&&(this.WMODE=h(c));a.n.c(this)}function f(a){return"IFRAME"===a.tagName?2:"IMG"===a.tagName?1:"EMBED"===a.tagName||"OBJECT"===a.tagName?0:3}a.n={};a.n.b=function(b,c,d,e,k,l,r){var m;m=1==arguments.length?arguments[0]:{el:b,url:c,flashVars:e,adIds:k,opt_props:r};if(l){if("function"===typeof l)return l(b,c,e,k);new n;l.em=
!0;t[l.zr]=l;b[I]=l.zr;b[v]=!0;l.aa=b;l.INITIAL_WIDTH=b.offsetWidth;l.INITIAL_HEIGHT=b.offsetHeight;l.ae=c;l.an=f(b);0===l.an&&(l.WMODE=h(b));l.ag=e||{};a.i.a(l);m={e:0};m.q=l.aq[0]++;a.j.a(l,m);return l}return new g(m)};a.n.c=function(b){b.de=b.ao.startTime;b.RAND=b.ao.rand;(new n).getTime();b.dd=!0;a.k.c(b);var c={e:0};c.q=b.aq[0]++;a.j.a(b,c);a.i.a(b)};a.n.a=function(b){var c=+new n,d=c-b.BEACON_LAST_SENT_AT;if(0<b.DWELL_TIME_THRESHHOLDS.length){var e=1E3*b.DWELL_TIME_THRESHHOLDS[0];if(b.counters.strictDwell.tCur>=
e){b.DWELL_TIME_THRESHHOLDS.shift();var f=b.INVIEW_TIME_THRESHHOLDS.length?b.INVIEW_TIME_THRESHHOLDS[0]:60;if(e<f)return!1;if(5E3<d)return!0}}return 0<b.INVIEW_TIME_THRESHHOLDS.length&&(f=1E3*b.INVIEW_TIME_THRESHHOLDS[0],a.k.d(b,f))?(b.INVIEW_TIME_THRESHHOLDS.shift(),!0):0===b.DWELL_TIME_THRESHHOLDS.length&&c>b.cc?(b.cc*=2,!0):!1};a.n.d=function(a,c){for(var d=0;d<c.length;d++){var e=c[d];e[I]=a;e[v]=!0}}})(m);(function(a){function h(f,b,c){if(!f)return!1;var d=a.a.g(),d=null!==d&&11>d;if(!d)for(var e=
f.getElementsByTagName("embed"),k=0;k<e.length;k++){var g=e[k];if(!0!==g[v]&&-1===g.id.indexOf("moatPx")&&a.a.t(g)&&g.getAttribute("src")){var h=g.getAttribute("src"),d=a.o.a(h,g);return a.n.b(g,h,!1,d,b,c)}}g=f.getElementsByTagName("object");for(k=0;k<g.length;k++)if(e=g[k],a.a.t(e)&&("undefined"===typeof e[v]||!0!==e[v])&&-1==e.id.indexOf("moatPx")){for(f=0;f<e.children.length;f++)if("movie"===e.children[f].name||"Movie"===e.children[f].name)for(h=e.children[f].value,k=0;k<e.children.length;k++){if(!d&&
"EMBED"===e.children[k].tagName){g=e.children[k];if("undefined"!==typeof g[v]&&!0===g[v]||-1!=g.id.indexOf("moatPx"))continue;if(a.a.t(g))return d=a.o.a(h,g),a.n.b(g,h,!1,d,b,c)}if("OBJECT"===e.children[k].tagName&&(g=e.children[k],a.a.t(g)&&!0!==g[v]&&-1===g.id.indexOf("moatPx")))return a.n.b(g,void 0,!1,void 0,b,c)}e.object&&e.object.Movie?h=e.object.Movie:e.data&&(h=e.data);d=a.o.a(h,e);return a.n.b(e,h,!1,d,b,c)}if(h=a.p.g(f,b,c))return h;h=f.getElementsByTagName("img");for(k=0;k<h.length;k++)if(d=
h[k],"undefined"===typeof d[v]||!0!==d[v]){if(a.a.t(d)&&""!==d.src&&-1===document.location.href.indexOf(d.src))return a.n.b(d,d.getAttribute("src"),!1,void 0,b,c);M["1"]=d.offsetWidth+"x"+d.offsetHeight+":"+d.src}return!1}function g(f,b){for(var c=[],d=f.getElementsByTagName("iframe"),e,g=0;g<d.length;g++)if(e=d[g],!e[v]&&a.a.t(e)){var l=a.d.c(e)?!1:!0;(1===b&&l||2===b&&!l)&&c.push(e)}return c}a.p={};a.p.a=function(f,b,c,d,e){var g=a.p.b,l=0;a.e.g(function(){b.numTries=l++;return g(f,b,c,d)&&!0},
a.p.c,500,e)};a.p.g=function(f,b,c){f=g(f,1);if(f[0])return a.n.b(f[0],f[0].src,!1,void 0,b,c)};a.p.f=function(f,b,c){var d;f=a.p.e(f,a.p.h);for(var e=0;e<f.length;e++)if(d=f[e],(d=a.d.c(d))&&d.documentElement&&(d=h(d.documentElement,b,c)))return d};a.p.i=function(f,b,c){var d,e;f=a.p.e(f,a.p.h);for(var g=0;g<f.length;g++)if(e=f[g],(e=a.d.c(e))&&e.documentElement){if(d=e.getElementById("flite-1"))if(d=a.n.b(d,d.nodeName,!1,void 0,b,c))return d;if(d=h(e.documentElement,b,c))return d}};a.p.d=h;a.p.b=
function(f,b,c,d){if("undefined"===typeof f)return!1;"HEAD"===f.tagName&&(d=f.parentNode,"HTML"===d.tagName&&(d=d.getElementsByTagName("body"),0<d.length&&(f=d[0])));for(var e,g=0;9>g&&!/mediavoice-ad-begin/.test(f.className);)d=f.offsetHeight*f.offsetWidth,0<d&&(e=f),f=a.a.previousElementSibling(f),g++;return e?b=a.n.b(e,"DIV",!1,void 0,b,c):!1};a.p.e=g;a.p.j=1;a.p.h=2;a.p.k=500;a.p.c=20;a.p.l={object:1,embed:1,img:1,iframe:1}})(m);(function(a){function h(a,f){for(var b={},c=a.split("&"),d=0;d<c.length;d++){var e=
c[d].split("=");if("string"===typeof e[1]){var k=e,l,h=l=e[1];try{for(var m=0;100>m&&(l=decodeURIComponent(l),h!=l)&&!l.match(/^http(s)?\:/);m++)h=l}catch(n){}l=l.replace(/(^\s+|\s+$)/g,"");k[1]=l}else e[1]="";b[e[0]]=e[1]}"undefined"!==typeof f&&(b.clientZone="undefined"!==f?f:"");return b}a.q={};a.q.a=function(a){"undefined"===typeof a.startTime&&(a.startTime=(new n).getTime());"undefined"===typeof a.rand&&(a.rand=q.floor(q.random()*q.pow(10,8)));a.adNum=s.zr;s.zr++};a.q.b=function(g){if(!g)return!1;
var f;f=/^(?:[a-z]+:\/\/|:?\/?\/)?(?:www\.)?([^\/:]*)/i;f=!a.b.a&&a.b.b?(f=a.b.b.match(f))&&f[1]?f[1]:a.b.c.location.hostname:a.b.c.location.hostname;var b=f.match(/.*\.([^\.]*\..*)/i);g.moatClientSlicer1=b&&b[1]?decodeURIComponent(b[1]):decodeURIComponent(f);g.moatClientSlicer2=decodeURIComponent(f);return g};a.q.c=function(g){return a.q.d(g)};a.q.d=function(a){try{var f=a.className,b=a.getAttribute("src");f.split("\n").join(" ");if(-1!==f.indexOf("moatfooter"))return!1;var c=b.split("?");1==c.length&&
(c=b.split("#"));if(1<c.length){var d=h(c[1],"undefined");d&&(d.moatClientLevel4=d.moatClientLevel4.replace(/:/g," -"));return d}return!1}catch(e){return!1}};a.q.e=function(a){try{var f=a&&a.className.replace("amp;","").split("?")[1];return f&&h(f)}catch(b){return!1}};a.q.f=function(a){try{var f=zoneRegEx.exec(a.innerHTML);0<f.length&&(zone=f[1]);return zone}catch(b){}};a.q.g=function(a){return(a=unescape(unescape(unescape(unescape(a.innerHTML)))).match(/~fdr=(\d*).*?\/.*?;(\d*)/))?{adid:a&&a[1]||
"-",cid:a&&a[2]||"-"}:!1};a.q.h=function(a,f){return f||{}}})(m);(function(a){function h(b,c){var d,e=[],f,g=a.a.f()?2048:7750,h=c||{};f={};for(d in b)b.hasOwnProperty(d)&&(1!=b.e||"x"!==d&&"y"!==d&&"c"!==d?e.push(encodeURIComponent(d)+"="+encodeURIComponent(b[d])):f[d]=b[d].split("a"));d=e.join("&");var e=g-d.length,m=0;if("undefined"!==typeof f.x){for(var n=0,q=0;q<f.x.length;q++)if(n+=f.x[q].length+(f.y[q]?f.y[q].length:0)+(f.c[q]?f.c[q].length:0),n<e)m++;else break;0<m&&(d+="&x="+f.x.slice(0,
m-1).join("a"),d+="&y="+f.y.slice(0,m-1).join("a"),d+="&c="+f.c.slice(0,m-1).join("a"))}for(var t in h)h.hasOwnProperty(t)&&(f="&"+encodeURIComponent(t)+"="+encodeURIComponent(h[t]),f.length+d.length<g&&(d+=f));return d}function g(a,c){for(var d in c)c.hasOwnProperty(d)&&(a[d]=c[d])}a.j={};var f={34:"bd.moatads.com"};a.j.b=function(b,c,d){a.q.a(c);var e={};e.e=b;g(e,d);e.i=O;if(11===b){d=[];for(var k in M)M.hasOwnProperty(k)&&d.push(k+"="+M[k]);e.k=d.join("&")}e.e in ea||(e.bq=a.b.e,e.f=Number(!J),
e.j=a.b.b,e.o=3,e.t=c.startTime,e.de=c.rand,e.m=0,e.ar=fa,a.a.z(e,"ai",s.z),e.q=s.m++,e.cb=B?1:0,e.cu=ba,g(e,a.focus.getQueryString()),a.q.h(c,e),"undefined"!==typeof c&&(e.d=c.moatClientLevel1+":"+c.moatClientLevel2+":"+c.moatClientLevel3+":"+c.moatClientLevel4,e.bd=c.moatClientSlicer1),e.ac=1,e.it=a.p.k,c=h(e),s.yh.yi(c+"&cs=0",f[b]?a.b.protocol+"//"+f[b]:F,ga))};a.j.c=function(b){!0!==b.em&&(delete t[b.zr],clearTimeout(b.cc),a.p.a(G.parentNode,b.ao,b))};a.j.a=function(b,c){if(!b||!0===b.ep)return!1;
if(!a.c.h(b))return a.c.i(b),!1;if("undefined"!==typeof b.ao&&(2!==b.an||1!==c.e&&3!==c.e)&&!(c.e in ea)){c.lo=b.FIND_AD_TRIES;c.ak="string"===typeof b.ae?700>=b.ae.length?b.ae:b.ae.slice(0,700):"-";b.ah&&(c.a=b.ah);var d=b.ag,e={};if(9===c.e&&2===c.q||25===c.e){for(var k in d)d.hasOwnProperty(k)&&""!==k&&"undefined"!==typeof d[k]&&-1===k.indexOf("dvContains")&&-1===k.indexOf("indexOf")&&-1===k.toLowerCase().indexOf("clicktag")&&(e["z"+k]=d[k]);c.e=25}0===b.an&&(c.dc=b.WMODE);0!==c.e&&a.c.j(b);b.bi>
b.bg&&(b.bg=b.bi);b.bm>b.bk&&(b.bk=b.bm);c.i=O;c.bq=a.b.e;c.g=b.aq.g++;d=b.INITIAL_WIDTH;c.h=b.INITIAL_HEIGHT;c.w=d;c.f=Number(!J);c.j=a.b.b;c.o=3;c.t=b.de;c.de=b.RAND;c.cu=ba;c.m=c.m||a.a.k(b);c.ar=fa;c.cb=B?1:0;a.b.a&&(c.gh=1);a.l&&a.l.a()?(c.ch=1,c.gh=1):a.m&&a.m.c?(c.ct=a.m.d,b&&b.periscopeManager?(b.periscopeManager.measurable&&(c.ch=1),b.periscopeManager.fullyMeasurable&&b.ao&&!b.ao.skin&&(c.ga=1)):c.ch=1,"undefined"!==typeof a.m.e&&b&&b.ao&&b.ao.startTime&&!isNaN(b.ao.startTime)&&(d=a.m.e-
b.ao.startTime,c.fg=0<=d?d:0)):c.ch=0;g(c,a.k.h(b.zr));g(c,a.focus.getQueryString());g(c,b.counters.getQs());a.a.z(c,"ai",s.z);a.a.z(c,"ap",b.cb);a.a.z(c,"ax",b.bg);a.a.z(c,"ay",b.bi);a.a.z(c,"az",b.bk);a.a.z(c,"ba",b.bm);a.a.z(c,"aw",b.bc);a.a.z(c,"bg",b.bd);a.a.z(c,"be",b.be);a.a.z(c,"bc",b.bw);a.a.z(c,"bf",b.by);a.a.z(c,"bh",b.bx);a.a.z(c,"bz",b.cu);c.cl=q.round(100*b.IR5.AREA/(c.w*c.h));c.au=b.aq[2]-1;c.av=b.aq[3]-1;c.by=b.aq[23]-1;c.at=b.dm;a.q.h(b.ao,c);c.d=b.ao.moatClientLevel1+":"+b.ao.moatClientLevel2+
":"+b.ao.moatClientLevel3+":"+b.ao.moatClientLevel4;c.bd=b.ao.moatClientSlicer1;c.ab=b.an;c.ac=1;c.it=a.p.k;b.bi=b.bg;b.bm=b.bk;e=h(c,e);s.yh.yi(e+"&cs=0",f[c.e]?a.b.protocol+"//"+f[c.e]:F,ga)}};a.j.d=function(a,c){if(2!==a.an||1!==c.e&&3!==c.e){var d=ja;(new Image(1,1)).src=d}};a.j.e=function(a,c){return h(a,c)};a.j.f=function(b){var c={e:16};c.q=b.aq[16]++;a.j.a(b,c)}})(m);(function(a){function h(a,b,c,d){var e=(new n).getTime();this.tLast=this.tCur=0;this.update=function(b){var c=(new n).getTime();
if(a(b)){b=q.min(c-e,1E3);var g=typeof d;this.tCur+=b;"number"===g?this.tCur>d&&(this.tCur=d):"function"===g&&(b=d(),"number"===typeof b&&this.tCur>b&&(this.tCur=b))}e=c};this.getQs=function(a){data=this.query(a);this.tLast=this.tCur;return data};this.query=function(a){a=a||{};this.tLast>this.tCur&&(this.tLast=this.tCur);a[b]=this.tCur;a[c]=this.tLast;return a}}function g(){if(a.focus.pageIsVisible()&&"undefined"===typeof s.z){s.z=new n-ba;a:{var f=void 0,b;for(b in t)if(t.hasOwnProperty(b)&&(f=t[b])&&
"undefined"!==typeof f.ao){if(f.ce)break a;var c={e:4};c.q=f.aq[4]++;c.ai=s.z;a.j.a(f,c);f.ce=!0}a.e.d(w,"scroll",g,"onScroll")}}}a.c={};a.c.k=function(){a.e.c(w,"scroll",g,"onScroll");a.focus.setFocusListeners()};a.c.h=function(f,b){try{var c=f.aa;b=b||f.WINDOW||a.c.a(c);return c&&b&&(c.parentNode||c.parentElement)?!0:!1}catch(d){return!1}};a.c.j=function(){var f,b;for(b in t)t.hasOwnProperty(b)&&(f=t[b],a.c.h(f,f.WINDOW)?f.counters.update(f):a.c.i(f))};a.c.i=function(f){clearTimeout(f.cc);f.ep=
!0;delete t[f.zr];a.i.a(f,"remove");a.k.f(f.zr);f.aa=null};a.c.e=function(f){f.eq||(f.eq=!0);var b={e:5};b.q=f.aq[5]++;a.j.a(f,b)};a.c.d=function(f){var b,c;c=f.aa;f.elementRect?(b=f.elementRect.right-f.elementRect.left,f=f.elementRect.bottom-f.elementRect.top):(b=c.offsetWidth,f=c.offsetHeight);return 3>b||3>f||a.focus.pageIsPrerendered()?!0:!1};a.c.l=function(a){var b=1;screen.deviceXDPI?b=screen.deviceXDPI/screen.systemXDPI:a.devicePixelRatio&&"undefined"!==typeof a.mozInnerScreenX&&(b=a.devicePixelRatio);
return{w:b*screen.width,h:b*screen.height}};a.c.a=function(a){try{var b=a&&a.ownerDocument;return b&&(b.defaultView||b.parentWindow)}catch(c){return!1}};a.c.g=function(f){f.counters={};f.counters.laxDwell=new h(function(){return!a.focus.pageIsPrerendered()},"bu","cd");f.counters.strictDwell=new h(a.focus.pageIsVisible,"ah","am");f.counters.query=function(){var a={},c;for(c in this)if(this.hasOwnProperty(c)){var d=this[c];"function"===typeof d.query&&d.query(a)}return a};f.counters.getQs=function(){var a=
{},c;for(c in this)if(this.hasOwnProperty(c)){var d=this[c];"function"===typeof d.getQs&&d.getQs(a)}return a};f.counters.update=function(a){for(var c in this)if(this.hasOwnProperty(c)){var d=this[c];"function"===typeof d.update&&d.update(a)}}};a.c.b=function(f,b){for(var c=[],d,e=0;e<ka;e++)if(b!=b.parent){if(d=a.d.a(f,b))c.push(d);else break;b=b.parent;f=d}else break;return c};a.c.m=function(){for(var f in t)if(t.hasOwnProperty(f)){var b=t[f];if(b){a.r&&a.r.a&&a.r.a(b);var c={e:21};c.q=b.aq[21]++;
a.j.a(b,c)}}};a.c.f=function(f){var b={e:9};b.q=f.aq[9]++;f.BEACON_LAST_SENT_AT=+new n;a.j.a(f,b)}})(m);(function(a){a.d={};a.d.c=function(h){try{if(h.moatHostileIframe)return null;if(h.src&&h.src.slice&&"http"===h.src.slice(0,4)&&a.a.l(h.src)!=a.a.l(w.location.toString()))return h.moatHostileIframe=!0,null;var g=h&&(h.contentDocument||h.contentWindow&&h.contentWindow.document);if(g&&"string"===typeof g.location.toString())return g;h.moatHostileIframe=!0;return null}catch(f){return h.moatHostileIframe=
!0,null}};a.d.a=function(h,g){g=g||a.c.a(h);try{return g&&g.frameElement}catch(f){return!1}};a.d.b=function(h){return(h=a.d.a(h))?h.parentNode:null}})(m);(function(a){a.s={};a.s.a=function(h){h[a.b.d]=h[a.b.d]||{zs:!1,zr:0,h:0,m:0,i:{}};var g=h[a.b.d];"undefined"===typeof g.v&&(g.v=J?"undefined"===typeof h.document.hasFocus||B?!0:h.document.hasFocus():!0);g.ye||(g.ye=function(){this.v=!0});g.yd||(g.yd=function(){this.v=!J})}})(m);(function(a){var h=function(a,f){function b(a,b,c){a&&k.push({qs:a,
jsd:b,fld:c});if(0===h&&0<k.length)if(h+=1,a=k.shift(),a.fld&&q&&n&&n.sendMessage)try{n.sendMessage(a)}catch(e){q=!1,d(a)}else d(a)}function c(){try{return new t(1,1)}catch(a){var b=window.document.createElement("img");b.height=1;b.width=1;return b}}function d(a){var b=c();b.toSend=a;b.onerror=function(){var a=this.toSend;m+=1;var b=(a.jsd+"/pixel.gif?"+a.qs).length;2>m?d(a):v&&b>w&&e()};b.onload=function(){e()};b.src=a.jsd+"/pixel.gif?"+a.qs}function e(){0<h&&(h-=1,b())}var k=[],h=0,m=0,n=!1,q=!1,
t,s=f[a];s.yh={};s=s.yh;t=f.Image;s.yi=function(a,c,d){b(a,c,d)};s.yk=function(b){n=!0;var c=a+".yh.",d={},e;try{e=window.location.protocol}catch(f){e=document.createElement("a"),e.href="",e=e.protocol}d.src="https:"===e?"https://z.moatads.com/swf/MessageSenderV2.swf":"http://s.moatads.com/swf/MessageSenderV2.swf";d.flashVars="r="+c+"zb&s="+c+"zc&e="+c+"zd&td="+b;return d};s.yj=function(){return!1===n};s.zb=function(){try{if(!0===n){var a=f.document.getElementById("moatMessageSender");a&&!a.sendMessage&&
(a=f.document.getElementById("moatMessageSenderEmbed"));a&&a.sendMessage&&(q=!0,n=a)}}catch(b){}};s.zc=function(){try{e()}catch(a){}};s.zd=function(a){try{q=!1,a&&a.jsd&&k.push(a),e()}catch(b){}};var u,v,w=2083;try{u=document.createElement("div"),u.innerHTML="\x3c!--[if IE 8]>x<![endif]--\x3e",v="x"===u.innerHTML}catch(y){v=!1}}.toString();a.t={};a.t.a=function(){return"undefined"!==typeof w.eval&&(w.eval("(function(win){ win['Moat#EVA'] = true; })(window)"),"undefined"!==typeof w["Moat#EVA"])?!0:
!1};a.t.b=function(g){if(!s.yh)if(a.t.a())g.eval("("+h+")('"+a.b.d+"',window)");else{var f=g.document.createElement("script");f.type="text/javascript";f.text="("+h+")('"+a.b.d+"',window)";g.document.body.insertBefore(f,g.document.body.childNodes[0])}}})(m);if(m.a.r())return!1;var O="POLARNTV2",ha="polar822lQSh10",fa="5d61d2b-clean",ba=m.b.i,v="moatFound"+O,I="__moat__"+O,ja="",J=m.b.a,ga="afs.moatads.com",F,N=0,z,A,M={},ka=50,P=[],Q=[],t={},y=!1,ea={15:"",12:"",6:"",7:""};"string"===typeof m.b.protocol&&
(F=("https:"===m.b.protocol?m.b.protocol:"http:")+"//v4.moatads.com");F||(F="//v4.moatads.com");var w=m.b.c;m.s.a(w);var s=w[m.b.d];window[m.b.d]=s;m.t.b(w);m.a.l(J?w.location.href:w.document.referrer)||m.a.l(window.location.href);var G=m.a.w();if(!G)return!1;m.f=G;m.a.x(G);var B=m.a.o();(function(a){N=s.h;s.h++;s.i[N]=!1;!1===s.zs&&(m.c.k(),s.zs=!0);m.e.e(function(){m.c.j();for(var a in t)t.hasOwnProperty(a)&&m.k.c(t[a])},200);m.e.c(window,"unload",function(){y||(m.c.m(),y=!0)},!1);m.e.c(window,
"beforeunload",function(){y||(m.c.m(),y=!0)},!1);m.e.e(m.i.b,100);m.a.f()&&m.e.f(ca,3E5);"undefined"===typeof a&&(a=m.q.c(G));var h=G;m.e.f(function(){!1===s.i[N]&&(m.j.b(11,a),ca())},1E4);m.j.b(17,a);m.p.a(h,a)})()})(Date,Math)}catch(e$$40){var ct=(new Date).getTime();window["Moat#ETS"]||(window["Moat#ETS"]=ct);window["Moat#EMC"]||(window["Moat#EMC"]=0);var et=ct-window["Moat#ETS"],hourElapsed=36E5<=et,msg=e$$40.name+" in closure: "+e$$40.message+", stack="+e$$40.stack;if(!hourElapsed&&10>window["Moat#EMC"]){window["Moat#EMC"]++;
try{var pxSrc="//v4.moatads.com/pixel.gif?e=24&d=data%3Adata%3Adata%3Adata&i="+escape("POLARNTV2")+"&ac=1&k="+escape(msg)+"&ar="+escape("5d61d2b-clean")+"&j="+escape(document.referrer)+"&cs="+(new Date).getTime(),px=new Image(1,1);px.src=pxSrc}catch(e$$41){}}else if(hourElapsed){window["Moat#EMC"]=1;window["Moat#ETS"]=ct;try{pxSrc="//v4.moatads.com/pixel.gif?e=24&d=data%3Adata%3Adata%3Adata&i="+escape("POLARNTV2")+"&ac=1&k="+escape(msg)+"&ar="+escape("5d61d2b-clean")+"&j="+escape(document.referrer)+
"&cs="+(new Date).getTime(),px=new Image(1,1),px.src=pxSrc}catch(e$$42){}}};
