/*!CK:3586935385!*//*1395061016,178137887*/

if (self.CavalryLogger) { CavalryLogger.start_js(["GwVzT"]); }




self.__DEV__=self.__DEV__||0;



if(JSON.stringify(["\u2028\u2029"])==='["\u2028\u2029"]')JSON.stringify=function(a){var b=/\u2028/g,c=/\u2029/g;return function(d,e,f){var g=a.call(this,d,e,f);if(g){if(-1<g.indexOf('\u2028'))g=g.replace(b,'\\u2028');if(-1<g.indexOf('\u2029'))g=g.replace(c,'\\u2029');}return g;};}(JSON.stringify);



(function(a){a.__m=function(b,c){b.__SMmeta=c;return b;};})(this);
if(!String.prototype.startsWith)String.prototype.startsWith=function(a){"use strict";if(this==null)throw TypeError();var b=String(this),c=arguments.length>1?(Number(arguments[1])||0):0,d=Math.min(Math.max(c,0),b.length);return b.indexOf(String(a),c)==d;};if(!String.prototype.endsWith)String.prototype.endsWith=function(a){"use strict";if(this==null)throw TypeError();var b=String(this),c=b.length,d=String(a),e=arguments.length>1?(Number(arguments[1])||0):c,f=Math.min(Math.max(e,0),c),g=f-d.length;if(g<0)return false;return b.lastIndexOf(d,g)==g;};if(!String.prototype.contains)String.prototype.contains=function(a){"use strict";if(this==null)throw TypeError();var b=String(this),c=arguments.length>1?(Number(arguments[1])||0):0;return b.indexOf(String(a),c)!=-1;};if(!String.prototype.repeat)String.prototype.repeat=function(a){"use strict";if(this==null)throw TypeError();var b=String(this);a=Number(a)||0;if(a<0||a===Infinity)throw RangeError();if(a===1)return b;var c='';while(a){if(a&1)c+=b;if((a>>=1))b+=b;}return c;};


__t=function(a){return a[0];};__w=function(a){return a;};

(function(a){if(a.require)return;var b=Object.prototype.toString,c={},d={},e={},f=0,g=1,h=2,i=Object.prototype.hasOwnProperty;function j(t){this.name='ModuleError';this.message=t;}j.prototype=new Error();j.prototype.constructor=j;function k(t){if(a.ErrorUtils&&!a.ErrorUtils.inGuard())return ErrorUtils.applyWithGuard(k,this,arguments);var u=c[t],v,w,x;if(!c[t]){x='Requiring unknown module "'+t+'"';throw new j(x);}if(u.hasError)throw new j('Requiring module "'+t+'" which threw an exception');if(u.waiting){x='Requiring module "'+t+'" with unresolved dependencies';throw new j(x);}if(!u.exports){var y=u.exports={},z=u.factory;if(b.call(z)==='[object Function]'){var aa=[],ba=u.dependencies,ca=ba.length,da;if(u.special&h)ca=Math.min(ca,z.length);try{for(w=0;w<ca;w++){v=ba[w];aa.push(v==='module'?u:(v==='exports'?y:k.call(null,v)));}try{da=z.apply(u.context||a,aa);}catch(ea){if(c.ex&&c.erx){var fa=k.call(null,'ex'),ga=k.call(null,'erx'),ha=ga(ea.message);if(ha[0].indexOf(' from module "%s"')<0){ha[0]+=' from module "%s"';ha[ha.length]=t;}ea.message=fa.apply(null,ha);}throw ea;}}catch(ea){u.hasError=true;throw ea;}if(da)u.exports=da;}else u.exports=z;}if(u.refcount--===1)delete c[t];return u.exports;}function l(t,u,v,w,x,y){if(u===undefined){u=[];v=t;t=o();}else if(v===undefined){v=u;if(b.call(t)==='[object Array]'){u=t;t=o();}else u=[];}var z={cancel:m.bind(this,t)},aa=c[t];if(aa){if(y)aa.refcount+=y;return z;}else if(!u&&!v&&y){e[t]=(e[t]||0)+y;return z;}else{aa={id:t};aa.refcount=(e[t]||0)+(y||0);delete e[t];}aa.factory=v;aa.dependencies=u;aa.context=x;aa.special=w;aa.waitingMap={};aa.waiting=0;aa.hasError=false;c[t]=aa;q(t);return z;}function m(t){if(!c[t])return;var u=c[t];delete c[t];for(var v in u.waitingMap)if(u.waitingMap[v])delete d[v][t];for(var w=0;w<u.dependencies.length;w++){v=u.dependencies[w];if(c[v]){if(c[v].refcount--===1)m(v);}else if(e[v])e[v]--;}}function n(t,u,v){return l(t,u,undefined,g,v,1);}function o(){return '__mod__'+f++;}function p(t,u){if(!t.waitingMap[u]&&t.id!==u){t.waiting++;t.waitingMap[u]=1;d[u]||(d[u]={});d[u][t.id]=1;}}function q(t){var u=[],v=c[t],w,x,y;for(x=0;x<v.dependencies.length;x++){w=v.dependencies[x];if(!c[w]){p(v,w);}else if(c[w].waiting)for(y in c[w].waitingMap)if(c[w].waitingMap[y])p(v,y);}if(v.waiting===0&&v.special&g)u.push(t);if(d[t]){var z=d[t],aa;d[t]=undefined;for(w in z){aa=c[w];for(y in v.waitingMap)if(v.waitingMap[y])p(aa,y);if(aa.waitingMap[t]){aa.waitingMap[t]=undefined;aa.waiting--;}if(aa.waiting===0&&aa.special&g)u.push(w);}}for(x=0;x<u.length;x++)k.call(null,u[x]);}function r(t,u){c[t]={id:t};c[t].exports=u;}r('module',0);r('exports',0);r('define',l);r('global',a);r('require',k);r('requireDynamic',k);r('requireLazy',n);l.amd={};a.define=l;a.require=k;a.requireDynamic=k;a.requireLazy=n;k.__debug={modules:c,deps:d};var s=function(t,u,v,w){l(t,u,v,w||h);};a.__d=function(t,u,v,w){u=['global','require','requireDynamic','requireLazy','module','exports'].concat(u);s(t,u,v,w);};})(this);
__d("DeadImage",[],function(a,b,c,d,e,f){window.addEventListener('error',function(g){if(g.target&&g.target.nodeName=='IMG')g.target.src='data:image/gif;base64,'+'R0lGODlhAQABAID/AMDAwAAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==';},true);});
__d("StratcomManager",[],function(a,b,c,d,e,f){var g;function h(o){g=o;}var i=[],j=function(o){i.push(o);if(g){var p=i;i=[];for(var q=0;q<p.length;++q){var r=p[q];g.dispatch(r);}}else{var s=o.srcElement||o.target;if(s&&(o.type in {click:1,submit:1})&&s.getAttribute&&s.getAttribute('data-mustcapture')==='1'){o.returnValue=false;o.preventDefault&&o.preventDefault();document.body.id='event_capture';return false;}}};function k(o,p){o.addEventListener(p,j,true);}var l=['click','change','submit','keypress','mousedown','mouseover','mouseout','mouseup','keyup','keydown','input','drop','dragenter','dragleave','dragover','touchstart','touchmove','touchend','touchcancel'],m;for(m=0;m<l.length;++m)k(document.documentElement,l[m]);var n=[('onpagehide' in window)?'pagehide':'unload','resize','focus','blur','popstate','hashchange'];for(m=0;m<n.length;++m)k(window,n[m]);var f={injectStratcom:h,enableDispatch:k};e.exports=f;});
__d("javelin-magical-init",["StratcomManager"],function(a,b,c,d,e,f,g){if(!a.JX)a.JX={};a.JX.__allowedEvents=g.allowedEvents;a.JX.enableDispatch=g.enableDispatch;e.exports={'JX.__allowedEvents':g.allowedEvents,'JX.enableDispatch':g.enableDispatch};});
__d("MPrelude",["DeadImage","StratcomManager","javelin-magical-init"],function(a,b,c,d,e,f){b('DeadImage');b('StratcomManager');b('javelin-magical-init');});