if(typeof GEL=="undefined"||!GEL)GEL={util:{},env:{}};
(function(){Base64={key:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",decode:function(a){a=a||this;var h=Base64.key,f="",j,e,g="",d,b="",c=0;for(a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");c<a.length;){j=h.indexOf(a.charAt(c++));e=h.indexOf(a.charAt(c++));d=h.indexOf(a.charAt(c++));b=h.indexOf(a.charAt(c++));j=j<<2|e>>4;e=(e&15)<<4|d>>2;g=(d&3)<<6|b;f+=String.fromCharCode(j);if(d!=64)f+=String.fromCharCode(e);if(b!=64)f+=String.fromCharCode(g)}return f},encode:function(a){a=a||this;
var h=Base64.key,f=new String,j,e,g="",d,b,c="",i=0;do{j=a.charCodeAt(i++);e=a.charCodeAt(i++);g=a.charCodeAt(i++);d=j>>2;j=(j&3)<<4|e>>4;b=(e&15)<<2|g>>6;c=g&63;if(isNaN(e))b=c=64;else if(isNaN(g))c=64;f=f+h.charAt(d)+h.charAt(j)+h.charAt(b)+h.charAt(c)}while(i<a.length);return f}};String.prototype.base64encode=Base64.encode;String.prototype.base64decode=Base64.decode;GEL.namespace("util.Base64");String.prototype.base64encode=GEL.util.Base64.encode=Base64.encode;String.prototype.base64decode=GEL.util.Base64.decode=
Base64.decode})();
GEL.util.Cookie=function(a,h,f){function j(){b.isencoded="isencoded"in d?d.isencoded:null;b.isescaped="isescaped"in d?d.isescaped:null;b.expires="expires"in d?d.expires:null;if(b.expires&&typeof b.expires=="object")b.expires=b.expires.toGMTString();b.maxage="maxage"in d?d["max-age"]:null;b.path="path"in d?d.path:"/";b.domain="domain"in d?d.domain:null}function e(){var c={};c[b.name]=g;if(b.path)c.path=b.path;if(b.domain)c.domain=b.domain;if(b.expires)c.expires=b.expires instanceof Date?b.expires.toGMTString():
b.expires;if(b.maxage)c["max-age"]=b.maxage;return c}var g=h,d=this.options=f||{},b=this;if(typeof GEL.env.cookies!="undefined"&&GEL.env.cookies.exists(a))return GEL.env.cookies.get(a);this.name=a;j();this.getRawValue=function(){return g};this.setRawValue=function(c){g=c};this.getValue=function(){var c=g;if(this.isencoded)c=c.base64decode();if(this.isescaped)c=unescape(c);return c};this.setValue=function(c){if(this.isencoded)c=c.base64encode();if(this.isescaped)c=escape(c);g=c;return this.set()};
this.set=function(){if(!this.name)return null;var c=e();c=GEL.objectUtil.join(c,"=",";");GEL.log("setting "+c);document.cookie=c;return this};this.remove=function(){var c=new Date,i=this.name+"=";if(this.path)i+=";path="+this.path;if(this.domain)i+=";domain="+this.domain;i+=";expires="+c.toGMTString();document.cookie=i;GEL.env.cookies.remove(this.name);return this}};GEL.util.Cookie.prototype.toString=function(){return this.value};GEL.extend(GEL.util.Cookie,GEL.event.Publisher);
GEL.util.MetaCookie=function(a,h){function f(){var e={},g=function(){var k=a.getValue();return j.ignoredelimiter?k.substr(k.lastIndexOf(j.ignoredelimiter)+1,k.length):k}(),d="",b=j.keydelim,c=[],i=0;for(c=g.split(j.delimiter);i<c.length;i++)if(c[i]){d=c[i].split(b);if(d[0])e[d[0]]=d[1]}return e}var j=this;GEL.util.MetaCookie.superclass.constructor.apply(this,arguments);h=h||{};this.cookie=a;this.delimiter=a.delimiter="delimiter"in h?h.delimiter:this.delimiter||"&";this.format="format"in h?h.format:
this.format||"";this.keydelim=a.keydelim="keydelim"in h?h.keydelim:this.keydelim||"=";this.ignoredelimiter="ignore"in h?h.ignore:this.ignoredelimiter||null;this.refresh=function(){this.values=f()};this.valmap="valmap"in h?h.valmap:{};this.refresh()};
GEL.extend(GEL.util.MetaCookie,GEL.event.Publisher,{setRawValue:function(a){this.cookie.setRawValue(a);this.refresh();return this},getRawValue:function(){return this.cookie.getRawValue()},getValue:function(a){a=a in this.valmap?this.valmap[a]:a;return a==null?this.cookie.getValue():this.values[a]},deleteValue:function(a){if((a=a in this.valmap?this.valmap[a]:a)&&a in this.values){delete this.values[a];this.set()}return this},setValue:function(a,h){this.values[a in this.valmap?this.valmap[a]:a]=h;
this.set();return this},set:function(){var a=GEL.objectUtil.join(this.values,this.keydelim,this.delimiter);if(this.expires)this.cookie.expires=this.expires;this.cookie.setValue(a);return this},remove:function(){this.cookie.remove();return this}});
GEL.env.cookies=function(){function a(b){b in g||(g[b]=new GEL.util.Cookie(b,""));return g[b]}function h(b){return b in g}function f(b,c){g[b]=c;return g[b]}function j(b){delete g[b]}function e(){var b={},c=document.cookie,i,k,l;if(!c)return b;c=c.split(/;\s*/);for(var n={},m=0;m<c.length;m++){k=c[m].indexOf("=");i=c[m].slice(0,k);k=c[m].slice(k+1,c[m].length);n[i]=true;if(i in g)l=g[i];else{l=new GEL.util.Cookie(i,k);g[i]=l}l.setRawValue(k)}for(i in g)i in n||g[i].setRawValue("");return b}var g=
{},d={refresh:e,get:a,getCookie:a,exists:h,replace:f,remove:j};GEL.cookies=g;e();return d}();GEL.env.cookies.pluck=function(){var a=GEL.env.cookies.get("at");a.isencoded=false;a.isescaped=true;a.domain="."+GEL.env.domain;a=new GEL.util.MetaCookie(a,{delimiter:"&",keydelim:"=",domain:"."+GEL.env.domain,valmap:{username:"a",uid:"u",email:"e",gender:"g",info:"s",time:"t",logintime:"t",uid:"u",hash:"h"}});return GEL.env.cookies.replace("at",a)}();
GEL.env.cookies.gcionsn=function(){var a=GEL.env.cookies.get("GCIONSN");a.isencoded=true;a.isescaped=false;a.domain="."+GEL.env.domain;a=new GEL.util.MetaCookie(a,{delimiter:"~",keydelim:":",valmap:{status:"sts",state:"sta"}});return GEL.env.cookies.replace("GCIONSN",a)}();
GEL.env.cookies.gcionpn=function(){var a=GEL.env.cookies.get("GCIONPN");a.isencoded=true;a.isescaped=false;a=new GEL.util.MetaCookie(a,{delimiter:"~",keydelim:":",valmap:{seg:"segments"}});a.expires=new Date((new Date).getTime()+31536E7);return GEL.env.cookies.replace("GCIONPN",a)}();
GEL.env.cookies.gcionid=function(){var a=GEL.env.cookies.get("GCIONID"),h=[];a.expires=new Date(Number(new Date)+31536E6);a.isencoded=true;a.isescaped=false;a.domain="."+GEL.env.domain;var f=new GEL.util.MetaCookie(a,{delimiter:"|",keydelim:":",ignore:"~",domain:"."+GEL.env.domain,valmap:{email:"adr",autologin:"aln",avatar:"ava",country:"cou",gender:"gen",lastname:"lnm",state:"sta",username:"usr",companysize:"siz",industry:"ind",occupation:"job",sessions:"ses",site:"sit",hash:"hsh",logintime:"tim"}}),
j=f.refresh;f.refresh=function(){j.call(f);var e=a.getValue();h=e=e.slice(0,e.lastIndexOf("~")).split("~");f.values.gcionid=e[0];f.values.version=e[1];f.values.datecreated=e[2];f.values.status=e[3]};f.set=function(){var e=h.join("~")+"~"+GEL.objectUtil.join(this.values,this.keydelim,this.delimiter);if(this.expires)this.cookie.expires=this.expires;this.cookie.setValue(e);return this};f.refresh();return GEL.env.cookies.replace("GCIONID",f)}();GEL.env.persistentcache=GEL.env.cookies.gcionpn;
GEL.env.sessioncache=GEL.env.cookies.gcionsn;
GEL.env.user=function(){var a=new GEL.event.Publisher,h=(new Date).getYear()+1900,f=GEL.env.cookies.pluck,j=GEL.env.cookies.gcionsn,e=GEL.env.cookies.gcionid,g={};g={username:f,email:f,uid:f,gender:function(){var d=e.getValue("gender");if(!d)return d;return d==2?"male":"female"},zip:e,yob:e,autologin:e,state:e,country:e,loginstate:function(){return f.getValue()},isloggedin:function(){return this.getValue("loginstate")?true:false},at:function(){return f.getValue()},uid:f,age:function(){var d=this.getValue("yob")||
0;return d?h-d:null},companysize:e,industry:e,occupation:e,sessions:e,site:e,logintime:[e,f],hash:[e,f],loginduration:function(){var d=new Date,b=d.getTimezoneOffset()*6E4;b=new Date(e.getValue("tim")*1E3+b);d=d.getTime()-b.getTime();return parseInt(d/1E3)},segments:GEL.env.persistentcache};a.init=function(){var d,b;for(b in g){d=this.getValue(b);this[b]=d}};a.refresh=function(){GEL.env.cookies.refresh();e.refresh();f.refresh();j.refresh();this.init()};a.setValue=function(d,b){var c=this.getValue(d);
c={attribute:d,oldValue:c,newValue:b};var i=d in g?g[d]:e;i instanceof Array||(i=[i]);for(var k=0,l=i.length;k<l;k++)i[k].setValue(d,b);this.fire("attributechanged",this,c)};a.getValue=function(d){var b=e;if(d in g){b=g[d];if(b instanceof Array)b=b[0]}return typeof b=="function"?b.call(this):d?b.getValue(d):b.getValue()};a.onLogin=function(){this.refresh();this.fire("login",this)};a.onLogout=function(){GEL.env.cookies.refresh();e.refresh();f.refresh();j.refresh();this.refresh();this.fire("logout",
this)};a.zagupdate=function(){GEL.env.cookies.refresh();e.refresh();this.init()};a.init();return a}();(function(){if(typeof window.GDN=="undefined"||typeof window.GDN.Cookie=="undefined"){var a;a=typeof window.GDN=="undefined"?(window.GDN={}):window.GDN;a.Cookie={Exists:function(h){return GEL.env.cookies.exists(h)}};a.Cookies={GCION:{Name:"GCIONID",Get:function(){return{Yob:function(){return GEL.env.user.yob},Gender:function(){return GEL.env.user.gender},Zip:function(){return GEL.env.user.zip}}}}}}})();