if(typeof GEL=="undefined"||!GEL)var GEL={};GEL.log=function(a){typeof YAHOO=="object"&&typeof YAHOO.log=="function"&&YAHOO.log(a);typeof console!="undefined"&&typeof console.log!="undefined"&&console.log(a)};GEL.logEx=GEL.logException=function(a){GEL.log(["Exception Details:",'\tType: "'+a.name,'\tMessage: "'+a.message,'\tFile: "'+a.fileName,'\t\tLine: "'+a.lineNumber].join("\n"))};String.prototype.endsWith=function(a){return this.match(new RegExp(a+"$","i"))!=null};
GEL.extend=function(a,c,b){if(!c||!a){a="extend failed, missing definition of ";a+=!c?" super class ":" subclass ";a+="please check that all dependencies are included.";throw new Error(a);}var d=function(){};d.prototype=c.prototype;a.prototype=new d;a.prototype.constructor=a;a.superclass=c.prototype;if(c.prototype.constructor==Object.prototype.constructor)c.prototype.constructor=c;if(b)for(var e in b)a.prototype[e]=b[e]};
GEL.namespace=function(){var a=arguments,c=null,b,d,e;for(b=0;b<a.length;b+=1){e=a[b].split(".");c=GEL;for(d=e[0]=="GEL"?1:0;d<e.length;d+=1){c[e[d]]=c[e[d]]||{};c=c[e[d]]}}return c};GEL.namespace("env","util","config","widget");
GEL.arrayUtil={copy:function(a,c){if(this.length)a=this;if(typeof a=="undefined"||!a||!a.length)return[];for(var b=0,d=[];b<a.length;b++)typeof c=="function"&&!c.call(a[b])||d.push(a[b]);return d},toObject:function(a,c){var b={};c=typeof c=="undefined"?true:c;for(var d=0,e=a.length,f=a[d];d<e;f=a[++d])b[f]=c;return b}};
GEL.objectUtil={keys:function(a){var c=[],b;for(b in a)c.push(b);return c},values:function(a){var c=[],b;for(b in a)c.push(a[b]);return c},copy:function(a){var c={};for(var b in a)c[b]=a[b];return c},join:function(a,c,b){var d="",e="",f=0,g;for(e in a){g=[e,c,a[e]];f++>0&&g.unshift(b);d+=g.join("")}return d},isEqual:function(a,c){if(a===c)return true;var b,d;for(b in a){d=c[b];if(d!=a[b])return false}return true},toArray:function(a){var c=[];for(var b in a)c.push(b,a[b]);return c}};
(function(){if(typeof GELConfig!="undefined"){var a=GEL.namespace("config"),c=GELConfig;for(var b in c)b in a||(GEL.config[b]=GELConfig[b])}})();
(function(){for(var a=GEL.namespace("config.init"),c="",b,d,e=window.location.search.split("&"),f=0;f<e.length;f++)if(!(e[f].indexOf("GEL.config.init=")<0)){c=e[f].split("=");c=c[1];c=c.split(";");for(var g=0;g<c.length;g++){b=c[g].substr(0,1);d=c[g].substr(1,c[g].length);if(!(d in a)){if(d=="*")d="_default";a[d]=b=="+"?true:false}}}"_default"in a||(a._default=true);"timers"in a||(a.timers=false);return{_default:true,timers:false}})();
GEL.elementUtil=function(){var a=window,c=document,b={get:function(d){switch(typeof d){case "string":return c.getElementById(d);case "object":case "function":return d;default:return null}},hasClassName:function(d,e){d=b.get(d);if(!d||!d.className)return false;d=d.className.split(/\s+/);for(var f=0;f<d.length;f++)if(d[f]==e)return true;return false},addClassName:function(d,e){if(d=b.get(d))GEL.elementUtil.hasClassName(e)||(d.className+=" "+e)},removeClassName:function(d,e){if(d=b.get(d))if(GEL.elementUtil.hasClassName(d,
e)){var f,g=0,h;e=e.toLowerCase();for(f=d.className.split(" ");g<f.length;g++){h=f[g];h.toLowerCase()==e&&f.splice(g,1)}d.className=f.join(" ")}},attachEventListener:function(){function d(g,h,i){g=b.get(g);if(!("attachEvent"in g))return f(g,h,i);if(!(!h||typeof h!="string")){h=h.toLowerCase();if(h.indexOf("on")!=0)h="on"+h;g.attachEvent(h,i)}}function e(g,h,i){g=b.get(g);if(!(!h||typeof h!="string")){if(typeof g=="undefined"||!g)return null;g.addEventListener(h,i,false)}}function f(g,h,i){g=b.get(g);
if(!(!h||typeof h!="string")){h=h.toLowerCase();if(typeof g=="undefined"||!g)return null;h="on"+h;g[h]=i}}return a.attachEvent?d:a.addEventListener?e:f}(),detachEventListener:function(){function d(g,h,i){g=b.get(g);if(!g.detachEvent)return f(g,h,i);if(h.indexOf("on")!=0)h="on"+h;try{return g.detachEvent(h,i,false)}catch(j){GEL.logException(j)}}function e(g,h,i){g=b.get(g);try{return g.removeEventListener(h,i,false)}catch(j){GEL.logException(j)}}function f(g,h){g=b.get(g);if(h.indexOf("on")!=0)h="on"+
h;try{g[h]=null;delete g[h]}catch(i){g[h]=new Function}}if(a.detachEvent)return d;return a.removeEventListener?e:f}(),purge:function(d){if(GEL.env.ua.ie){d=b.get(d);if(!d)return null;for(var e=d.attributes,f="",g="",h=0;h<e.length;h++){f=e[h].name;try{g=typeof d[f]}catch(i){}if(g=="function")d[f]=null}return d}},remove:function(d){function e(j){j=j.childNodes;for(var k=null,n=null;j.length>0;){k=j[0];k.id&&(n=GEL.cachemgr.get(k.id))?n.removeElement():b.remove(k)}}d=b.get(d);if(!d)return null;var f=
d.parentNode,g=d.childNodes,h=GEL.elementUtil.purge;g&&g.length>0&&e(d);if(d.nodeType==1)try{h(d)}catch(i){}f&&f.removeChild(d);return null},getFragmentFromHTML:function(d){var e=c.createDocumentFragment(),f=c.createElement("DIV"),g=[];if(GEL.env.ua.ie){f.style.display="none";f.style.visibility="hidden";document.body.insertBefore(f,document.body.firstChild)}f.innerHTML=d;d=0;for(var h=f.childNodes.length;d<h;d++)g[d]=f.childNodes[d];d=0;for(h=g.length;d<h;d++)e.appendChild(g[d]);f.parentNode&&f.parentNode.removeChild(f);
return e}};return b}();
GEL.env.ua=function(){var a={ie:0,opera:0,gecko:0,webkit:0,mobile:null,air:0},c=navigator.userAgent,b;if(/KHTML/.test(c))a.webkit=1;if((b=c.match(/AppleWebKit\/([^\s]*)/))&&b[1]){a.webkit=parseFloat(b[1]);if(/ Mobile\//.test(c))a.mobile="Apple";else if(b=c.match(/NokiaN[^\/]*/))a.mobile=b[0];if(b=c.match(/AdobeAIR\/([^\s]*)/))a.air=b[0]}if(!a.webkit)if((b=c.match(/Opera[\s\/]([^\s]*)/))&&b[1]){a.opera=parseFloat(b[1]);if(b=c.match(/Opera Mini[^;]*/))a.mobile=b[0]}else if((b=c.match(/MSIE\s([^;]*)/))&&
b[1])a.ie=parseFloat(b[1]);else if(b=c.match(/Gecko\/([^\s]*)/)){a.gecko=1;if((b=c.match(/rv:([^\s\)]*)/))&&b[1])a.gecko=parseFloat(b[1])}return a}();GEL.env.ua.ie&&typeof document.execCommand=="function"&&document.execCommand("BackgroundImageCache",false,true);
GEL.env.os=function(){var a=navigator.platform.toLowerCase(),c={win:false,mac:false,unix:false,linux:false,unknown:true};if(a.indexOf("win")>=0){c.unknown=false;c.win=true}else if(a.indexOf("mac")>=0){c.unknown=false;c.mac=true}else if(a.indexOf("linux")>=0){c.unknown=false;c.linux=true}else if(a.indexOf("x11")>=0){c.unknown=false;c.unix=true}return c}();
GEL.tracker=function(){function a(n,l,m){m=typeof m!="undefined"?m:false;if(typeof l!="function"||typeof n!="function")throw new Error("GEL.tracker.add(finderFn, foundFn): ");var q="idx_"+h++;e[q]=[n,l,0,m];b();return q}function c(n){var l;try{l=n()}catch(m){throw new Error("GEL.tracker: Your function, "+n.toString()+",  generated an error");}return l}function b(){var n=false,l=null;clearTimeout(k);for(var m in e){l=e[m];if(n=c(l[0])){d(m);l[1](n)}else l[2]++;l[2]>f&&!l[3]&&d(m)}if(i(e).length>0)k=
setTimeout(b,j)}function d(n){delete e[n]}var e={},f=25,g={},h=0,i=GEL.objectUtil.keys,j=100,k=0;g.add=a;g.remove=d;g.tracking=e;return g}();GEL.namespace("event");
GEL.event.DOMEvent=function(a){function c(){if(e)return e;if(a.target)return e=a.target;else if(a.srcElement)e=a.srcElement;return e}function b(){if(a.preventDefault)return a.preventDefault();else a.returnValue=false}function d(){if(a.stopPropagation)a.stopPropagation();else a.cancelBubble=true}var e=null;this.getTarget=c;this.preventDefault=b;this.stopPropagation=d;this.domevent=a};
GEL.event.Publisher=function(){this._subscribers={};this.subscribe=function(){return this.on.apply(this,arguments)};this.off=function(){return this.unsubscribe.apply(this,arguments)}};
GEL.event.Publisher.prototype={on:function(a,c){if(!this._subscribers)this._subscribers={};a=a.toLowerCase();if(typeof c!="function")throw new Error("Must pass function, not "+typeof c);a in this._subscribers||(this._subscribers[a]=[]);this._subscribers[a].push(c);return this},unsubscribe:function(a,c){a=a.toLowerCase();a=this._subscribers[a];var b=null;if(!a)return null;for(var d=0;d<a.length;d++){b=a[d];if(b==c){_f=true;break}}if(_f)return a.splice(d,1)},fire:function(a,c){if(!this._subscribers)this._subscribers=
{};a=a.toLowerCase();if(!(a in this._subscribers))return null;var b=GEL.arrayUtil.copy.call(this._subscribers[a]),d=GEL.arrayUtil.copy.call(arguments);d.shift();d.shift();d.unshift(a);c||(c=this);for(var e=0;e<b.length;e++)try{b[e].apply(c,d)}catch(f){GEL.log("Firing event "+a+" and function, "+b[e].toString()+" failed. Details follow:\n");GEL.logEx(f);if(f.name=="RangeError")debugger}return true},getsubscribers:function(a,c){if(!this._subscribers)this._subscribers={};if(!(a in this._subscribers))return null;
a=this._subscribers[a];var b=0;if(typeof c!="function")return a;for(b=0;b<a.length;b++)if(c==a[b])return a[b]}};
(function(){function a(d,e){var f;f=typeof d==="object"?d.nodeName:d;if(typeof f=="undefined"||!f)return new GEL.Element.Base(d);f=f.toUpperCase();e=e||{};return f in b?new b[f](d,e):new GEL.Element.Base(d,e)}var c=0,b={};GEL.Element=GEL.ement=function(d,e){var f=null;if(d instanceof GEL.Element.Base)f=d;else if(f=GEL.cachemgr.get(d))return f;else if(typeof d=="string"&&typeof e=="object"){if(!("id"in e))e.id="__gelement_"+c++;f=a(d,{attributes:e,transitionMapOverrides:{preattach:GEL.Element.StateManager.PreAttach.Null}})}else if(typeof d==
"string")f=a({id:d});else if(typeof d=="object")f=a(d,{transitionMapOverrides:{preattach:GEL.Element.StateManager.PreAttach.ImmediateTransition}});return f};GEL.Element.register=GEL.registerElement=function(d,e){d=d.toUpperCase();if(typeof e=="string"||typeof e=="function")b[d]=e;else throw new Error("Invalid type map constructor "+e);};GEL.Element.Base=function(d,e){function f(){var o=n;for(var p in o){delete o[p];l.registerDOMEvent(p)}}function g(){for(var o in n)l.unregisterDOMEvent(o)}function h(o,
p){var r=l.getStateFactory().createStateManager(p.newstate);l.getStateManager().type.toLowerCase();var u=r.type.toLowerCase();l["is"+u]=true;l.fire(o,l,p);l.fire(p.newstate,l,p);l.setStateManager(r)}function i(o){this.element&&this.element!==o&&g();if(!o)throw new Error("You cannot set an element without passing one ");var p="";if(o.id)this.id=o.id;else{p="__gelement_"+c++;try{o.setAttribute("id",p)}catch(r){}this.id=p}this.element=o}function j(o,p){o=[(new Date).getTime(),": ","(",this.id,"/",this.tagName(),
') moved from "',p.oldstate,'" to new state "',p.newstate,'"'];p=this.getElement();p.readyState&&o.push("; readyState= '",p.readyState,"'","  and is ready= ",this.isready);GEL.log(o.join(""))}var k=GEL.Element.Base.superclass.constructor;e=e||{};var n={},l=this;k.call(this);if(typeof d=="string"||!d){k=e.attributes||{};var m="";for(var q in k){m=k[q];delete k[q];k[q.toLowerCase()]=m}d=this.makeElement(d,k)}this.id=d.id;this.domEvents=n;this.setAttacher("dom");this.getElement=function(){return this.element};
this.onTransition=h;this.unregisterDOMEvents=g;this.setElement=i;GEL.config.logtransitions&&this.on("loadstatetransition",j);this.on("ready",f);if("stateFactory"in e)this.stateFactoryClass=e.stateFactory;if("transitionMapOverrides"in e)this.transitionMapOverrides=e.transitionMapOverrides;d&&this.setElement(d);this.getStateFactory();this.setAnimator();GEL.addGELement(this);return this}})();
(function(){var a=function(){for(var b="blur,focus,resize,scroll,click,dblclick,mousedown,mouseup,mousemove,mouseover,mouseout,mouseenter,mouseleave,change,select,submit,keydown,keypress,keyup".split(","),d={},e=0;e<b.length;e++)d[b[e]]=true;return d}(),c=document;document.getElementsByTagName("head");GEL.extend(GEL.Element.Base,GEL.event.Publisher,{on:function(b,d){b=b.toLowerCase();if("attached"==b)b="attach";var e=this.getsubscribers(b);GEL.event.Publisher.prototype.on.apply(this,arguments);if(b in
a&&(!e||e.length==0))this.registerDOMEvent(b);else this["is"+b]&&d.call(this,b);return this},attachToElement:document.getElementsByTagName("head")[0],stateFactoryClass:"GEL.Element.StateManagerFactory",insertBefore:function(b){this.attachToElement=b=b||this.attachToElement;this.setAttacher(new GEL.Element.Attacher.DOM.InsertBefore);this.isattach?this.attacher.attach(this):this.attach();return this},insertAfter:function(b){this.attachToElement=b=b||this.attachToElement;this.setAttacher(new GEL.Element.Attacher.DOM.InsertAfter);
this.isattach?this.attacher.attach(this):this.attach();return this},getStateFactory:function(){if(typeof this.stateFactory!="undefined"&&this.stateFactory)return this.stateFactory;var b=this.stateFactoryClass,d=null,e=null;try{d=eval(b)}catch(f){throw new Error('Error: Invalid stateFactoryClass defined: "'+b+'"');}e=this.stateFactory=new d(this);for(var g in this.transitionMapOverrides)e.transitionMap[g]=this.transitionMapOverrides[g];e.makeManagers();this.setStateManager(e.createStateManager("preattach"));
return e},each:function(b){b.call(this)},setTransitionMap:function(){var b=this.getStateFactory();for(var d in this.transitionMapOverrides)b.transitionMap[d]=this.transitionMapOverrides[d]},getDOMEventHandler:function(b){var d=this;return function(e){e=new GEL.event.DOMEvent(e);d.fire(b,d,e)}},setAnimator:function(b){b||(b=new GEL.anim.SimpleAnimator(this));if(!this.animator)return this.animator=b;return this.animator=b},getAnimator:function(){return this.animator},tagName:function(){var b=this.getElement();
return b&&b.nodeName?b.nodeName:b&&b.tagName?typeof b.tagName=="function"?b.tagName():b.tagName:"unknown"},attachEventListener:function(){var b=GEL.elementUtil.attachEventListener;return function(d,e){return b(this.getElement(),d,e)}}(),detachEventListener:function(){var b=GEL.elementUtil.detachEventListener;return function(d,e){b(this.getElement(),d,e)}}(),unregisterDOMEvent:function(b){return this.stateManager.unregisterDOMEvent(b)},registerDOMEvent:function(b){this.stateManager.registerDOMEvent(b)},
getStateManager:function(){return this.stateManager},setStateManager:function(b){if(!(b instanceof GEL.Element.StateManager))throw new TypeError("GEL.Element.Base.setStateManager(GEL.Element.StateManager)");this.stateManager&&this.stateManager.unsubscribe("loadstatetransition",this.onTransition);this.stateManager=b;this.stateManager.on("loadstatetransition",this.onTransition);this.stateManager.begin()},setAttacher:function(b){if(b instanceof GEL.Element.Attacher){this.attacher=b;return this}else b=
typeof b=="string"?b.toLowerCase():"";this.attacher=GEL.Element.Attacher.get(b,this);return this},attach:function(b){this.attachToElement=b||this.attachToElement;this.fire("beforeAttach",this);return this.stateManager.attach()},write:function(){(new GEL.Element.Attacher.Writer).attach(this)},asHTML:function(){var b=this.getElement();if(!b)return new String;return b.outerHTML?b.outerHTML:function(){var d=c.createElement("div");d.appendChild(b);return d.innerHTML}()},setHTML:function(b){this.clearElement();
this.appendHTML(b);return this},removeElement:function(){this.unregisterDOMEvents();GEL.elementUtil.remove(this.getElement());GEL.rmGELement(this);this.setElement({id:this.id});return this},purgeElement:function(){GEL.elementUtil.purge(this.getElement())},clearElement:function(){var b=this.getElement(),d,e,f=GEL.elementUtil.remove;if(!("childNodes"in b))return this;for(;b.childNodes.length>0;){d=b.childNodes[0];d.id&&(e=GEL.cachemanager.get(d.id))?e.removeElement():f(d)}return this},appendChild:function(b){if(!(typeof b==
"undefined"||!b)){if(b instanceof GEL.Element.Base){b.attachToElement=this.getElement();b.attach()}else{var d=this.getElement();if(!d)debugger;d.appendChild(b)}return this}},appendHTML:function(b){var d=c.createDocumentFragment(),e=c.createElement("DIV");if(GEL.env.ua.ie){e.style.display="none";e.style.visibility="hidden";document.body.appendChild(e)}for(e.innerHTML=b;e.childNodes.length>0;)d.appendChild(e.childNodes[0]);this.getElement().appendChild(d);e.parentNode&&e.parentNode.removeChild(e);return this},
hasClassName:function(b){var d=this.getElement();if(!d||!d.className)return false;d=d.className.split(/\s+/);for(var e=0;e<d.length;e++)if(d[e]==b)return true;return false},addClassName:function(b){var d=this.getElement();if(d)this.hasClassName(b)||(d.className+=" "+b)},removeClassName:function(b){if(this.hasClassName(b)){var d=this.getElement(),e,f=0,g;if(d){b=b.toLowerCase();for(e=d.className.split(" ");f<e.length;f++){g=e[f];g.toLowerCase()==b&&e.splice(f,1)}d.className=e.join(" ")}}},isLocal:function(b){if(typeof b!=
"undefined"||this.islocal)return this.islocal=b;b=this.getElement();var d="getSource"in this?this.getSource():b.src;return typeof d!="undefined"&&d&&!b.getAttribute("DEFER")?false:typeof b.nodeName=="string"&&b.nodeName.toUpperCase()=="LINK"?false:true},width:function(){return this.getElement().clientWidth},height:function(){return this.getElement().clientHeight},offset:function(){var b="getElement"in this?this.getElement():this,d=0,e=0;do{d+=b.offsetLeft||0;e+=b.offsetTop||0}while(b=b.offsetParent);
return{left:d,top:e}},makeElement:function(b,d){var e=null,f,g;g=GEL.elementUtil.addClassName;try{e=c.createElement(b)}catch(h){throw h;}if("classname"in d){b=d.classname.split(/\s+/);for(var i=0,j=b.length;i<j;i++)g(e,b[i]);delete d.classname}if("class"in d&&GEL.env.ua.ie<8){b=d["class"].split(/\s+/);i=0;for(j=b.length;i<j;i++)g(e,b[i]);delete d["class"]}for(f in d){g=d[f];if(typeof g=="number")g=String(g);else if(typeof g!="string")continue;try{e.setAttribute(f,g)}catch(k){GEL.log("Failed to set attribute "+
f+" to "+g);e[f]=g}}return e},getStyle:function(){var b=window;return function(d){if(this._computedStyle)return this._computedStyle[d];if(b.getComputedStyle){this._computedStyle=b.getComputedStyle(this.getElement(),null);return this._computedStyle[d]}else return this.getElement().style[d]}}(),css:function(b){if(typeof b=="object"){var d=this.getElement();if(d){try{for(var e in b)d.style[e]=b[e]}catch(f){}return this}}},toString:function(){return this.id+"/"+this.tagName()},forceRender:function(){var b=
document;return function(){var d=this.getElement(),e=null;if(d.nodeType){try{e=b.createTextNode(" ");d.appendChild(e);d.removeChild(e)}catch(f){}return this}}}()});GEL.Element.Base.prototype.clear=GEL.Element.Base.prototype.clearElement})();(function(){for(var a=["moveTo","moveBy","show","hide","toggle","slideIn","slideOut","isVisible","fadeOut","fadeIn"],c=0;c<a.length;c++){var b=a[c];GEL.Element.Base.prototype[b]=function(){return function(){return this.animator[b].apply(this.animator,arguments)}}()}})();
GEL.Element.Script=function(){var a=GEL.Element.Script.superclass.constructor;this._url="";a.apply(this,arguments)};
GEL.extend(GEL.Element.Script,GEL.Element.Base,{stateFactoryClass:"GEL.Element.StateManagerFactory.Remote",toString:function(){var a=GEL.Element.Script.superclass.toString.call(this);if(this.isLocal())return a;a+="/"+this.getElement().src;return a},setScriptText:function(a){this.getElement().text=a;return this},getScriptText:function(){return this.getElement().text},attach:function(){var a=GEL.Element.Script.superclass.attach;if(!("setSource"in this))return a.apply(this,arguments);this.setSource();
a=a.apply(this,arguments);this.setSource();return a},getSource:function(){return this._url},setSource:function(a,c){if(a)this._url=a;if(this.element){a=this._url;var b=this.getElement().src;if(a===b)return this;if(c||!GEL.env.ua.webkit||this.isattach){if(!("setAttribute"in this.getElement()))return this;this.getElement().setAttribute("src",a);this._url=this.getElement().src}return this}},makeElement:function(a,c){var b=GEL.Element.Script.superclass.makeElement;if("src"in c&&GEL.env.ua.webkit){this.setSource(c.src);
delete c.src}else this.setSource(c.src);return b.call(this,a,c)},executeScript:function(){if(!this.isLocal())return this.attach();if(GEL.env.ua.gecko||GEL.env.ua.opera){var a=this.getElement(),c=this.getScriptText();if(a.language&&a.language.toLowerCase()!="javascript"||a.type&&a.type.toLowerCase().indexOf("javascript")<0)return this.attach();try{window.eval(c)}catch(b){a=['FAiled to execute local script: "\nScript Body: "',c,'"'].join("");GEL.log(a);GEL.logEx(b)}this.setScriptText("")}this.attach();
GEL.env.ua.ie||this.stateManager.stateTransitionHandler()},attachToElement:document.getElementsByTagName("HEAD")[0]});GEL.Element.register("SCRIPT",GEL.Element.Script);
GEL.Element.Document=function(){var a=null;return function(){if(a)return a;a=this;var c=GEL.Element.Document.superclass.constructor,b=window,d=GEL,e=d.elementUtil.attachEventListener,f=d.elementUtil.detachEventListener,g=false,h=this;this.element=document;this.element.id="D";c.apply(this,arguments);e(b,"onunload",function(){h.fire("unload",h);f(b,"onunload",arguments.callee);"CollectGarbage"in b&&b.CollectGarbage()});GEL.Element.Document=function(){return h};this.fireLoadHandlers=new Function;this.setLoadHandlerQueueing=
function(i){if(typeof i=="boolean"){g=i;return this}};this.overrideLoadHandlers=function(){var i=GEL.env.ua.ie,j=h.loadHandlers=[],k=i?"attachEvent":"addEventListener",n=[window,document],l=function(){var m=h.loadEvents;return function(q,o){if(q in m&&this in m[q])g?j.push([o,this,m[q][this]]):o.call(this,m[q][this]);else return arguments.length>2?this["_"+k](q,o,arguments[2]):this["_"+k](q,o);return this}};return function(){for(var m=0,q=n.length,o=n[m];m<q;o=n[++m]){o["_"+k]=o[k];o[k]=l(o)}this.overrideLoadHandlers=
new Function;this.fireLoadHandlers=function(){GEL.log("firing load handler callback for "+j.length+" functions");for(var p=null;p=j.shift();)p[0].call(p[1],p[2])}}}()}}();
GEL.extend(GEL.Element.Document,GEL.Element.Base,{loadEvents:function(){var a=document,c=window,b=GEL.env.ua.ie;return{DOMContentLoaded:b?false:[a,c],readystatechange:b?[a]:false,load:[c]}}(),stateFactoryClass:"GEL.Element.StateManagerFactory.Document",tagName:function(){return"#DOCUMENT"},element:document,purgeElement:new Function,setElement:new Function,attachToElement:null});GEL.Element.register("#DOCUMENT",GEL.Element.Document);GEL.Element.register("BODY",GEL.Element.Document);
GEL.MetaElement=GEL.Element.Meta=GEL.Element.MetaElement=function(){var a=0;return function(c){GEL.MetaElement.superclass.constructor.apply(this,arguments);this.superon=this.on;var b=0;this.id="__metagelement_"+a++;this.gelements=[];this.setAttacher();if(c instanceof Array)for(;b<c.length;b++)this.addElement(c[b])}}();
GEL.extend(GEL.MetaElement,GEL.event.Publisher,{on:function(a,c){a=a.toLowerCase();if(this["is"+a])return c.call(this,a);return GEL.event.Publisher.prototype.on.apply(this,arguments)},get:function(a){return typeof a!="number"?null:a<0||a>=this.gelements.length?null:this.gelements[a]},each:function(a){if(typeof a!="function")return false;for(var c=null,b=0;b<this.gelements.length;b++){c=this.gelements[b];c.each(a)}return true},addElement:function(a){if(!(a instanceof GEL.Element.Base)&&!(a instanceof
GEL.MetaElement)&&!("attach"in a))a=GEL.ement(a);var c=this.elementExists(a);if(c>=0)return c;c=this.gelements.push(a);c--;this.fire("elementAdded",this,new GEL.event.MetaElement.elementAdded(this,a,c));this.attacher.addElement(a);return c},addElements:function(a){if(a instanceof Array){for(var c=0;c<a.length;c++)this.addElement(a[c]);return this.gelements.length-1}},elementExists:function(a){if(!(a instanceof GEL.Element.Base)&&!(a instanceof GEL.MetaElement)&&a.nodeName)a=GEL.ement(a);for(var c=
0,b=this.gelements;c<b.length;c++)if(b[c]==a)return c;return-1},removeElement:function(a){for(var c=0,b=this.gelements;c<b.length;c++)if(b[c]==a){b.splice(c,1);this.fire("elementRemoved",this,new GEL.event.MetaElement.elementRemoved(this,a,c));break}},getElement:function(a){var c;switch(typeof a){case "number":c=a<this.gelements.length&&a>=0?this.gelements[a]:null;break;case "object":c=this.getElement(this.elementExists(a));break;case "default":c=this.elements[0]}return c},setAnimator:function(a){var c=
0,b=this.gelements,d;if(typeof a!="function")a=a.constructor;for(;c<b.length;c++){d=b[c];d.setAnimator(new a(d))}},setAttacher:function(a){if(typeof a=="object"){this.attacher=a;return this}if(typeof a=="string")a=a.toLowerCase();this.attacher=a=="sync"?new GEL.Element.Attacher.MetaAttacher.Synchronized:a=="inline"?new GEL.Element.Attacher.MetaAttacher.Inline:new GEL.Element.Attacher.MetaAttacher;this.each(function(c){return function(){c.attacher.addElement(this)}}(this))},write:function(){this.each(function(){this.write()});
return this},size:function(){return this.gelements.length},attach:function(){var a=this;this.attacher.on("ready",function(c){this.unsubscribe(c,arguments.callee);a.isready=true;a.fire("ready",a)});this.fire("beforeAttach",this);this.attacher.attach()},childIndex:function(){}});GEL.event.MetaElement={};GEL.event.MetaElement.elementAdded=function(a,c,b){this.meta=a;this.newGelement=c;this.newIndex=b;this.newSize=this.meta.size();return this};
GEL.event.MetaElement.elementRemoved=function(a,c,b){this.meta=a;this.removedGelement=c;this.removedIndex=b;this.newSize=this.meta.size();return this};GEL.Element.Attacher=function(){GEL.Element.Attacher.superclass.constructor.call(this)};
GEL.extend(GEL.Element.Attacher,GEL.event.Publisher,{attach:function(a){return this.attachNodeToDOM(a,a.attachToElement)},attachNodeToDOM:function(){throw new Error("I am an abstract method and must be implemented by subclasses");},addElement:function(a){this.gelement=a}});GEL.Element.Attacher.Writer=function(){GEL.Element.Attacher.Writer.superclass.constructor.apply(this,arguments)};
GEL.extend(GEL.Element.Attacher.Writer,GEL.Element.Attacher,{attachNodeToDOM:function(a){if(a.isattach)return a.element;"setSource"in a&&a.setSource(null,true);var c=a.asHTML();document.writeln(c);a.setAttacher();return document.getElementById(a.id)}});GEL.Element.Attacher.DOM=function(){GEL.Element.Attacher.DOM.superclass.constructor.apply(this,arguments)};
GEL.extend(GEL.Element.Attacher.DOM,GEL.Element.Attacher,{attachNodeToDOM:function(){var a=document.getElementsByTagName("HEAD")[0];return function(c,b){b=b||a;c=c.getElement();b.appendChild(c);b.appendChild(document.createTextNode("\n"));return c}}()});GEL.Element.Attacher.DOM.InsertBefore=function(){GEL.Element.Attacher.DOM.InsertBefore.superclass.constructor.apply(this,arguments)};
GEL.extend(GEL.Element.Attacher.DOM.InsertBefore,GEL.Element.Attacher,{attachNodeToDOM:function(a,c){var b=null;a=a.getElement();c=c instanceof GEL.Element.Base?c.getElement():c;b=c.parentNode;b.insertBefore(a,c);return a}});GEL.Element.Attacher.DOM.InsertAfter=function(){GEL.Element.Attacher.DOM.InsertAfter.superclass.constructor.apply(this,arguments)};
GEL.extend(GEL.Element.Attacher.DOM.InsertAfter,GEL.Element.Attacher,{attachNodeToDOM:function(a,c){a=a.getElement();c=c instanceof GEL.Element.Base?c.getElement():c;var b=document.createTextNode("");if(c.nextSibling){c.parentNode.insertBefore(a,c.nextSibling);c.parentNode.insertBefore(b,a)}else{c.parentNode.appendChild(a);c.parentNode.appendChild(b)}return a}});
(function(){var a={dom:GEL.Element.Attacher.DOM,inline:GEL.Element.Attacher.Writer,_default:GEL.Element.Attacher.DOM};GEL.Element.Attacher.get=function(c,b){c=c in a?a[c]:a._default;if(typeof c=="string")try{c=eval(c)}catch(d){throw d;}return new c(b)}})();
(function(){GEL.Element.Attacher.MetaAttacher=function(){function a(){this.unsubscribe("ready",arguments.callee);this.unsubscribe("error",arguments.callee);delete b[this.id];if(d(b).length<=0){c.fire("ready",c);c.isready=true}else f.length>0&&e&&c.attach()}var c=this,b={},d=GEL.objectUtil.keys,e=true,f=[];GEL.Element.Attacher.MetaAttacher.superclass.constructor.apply(this,arguments);this.elements=[];this.type="asynchronous";this.getQueueSize=function(){return{needload:d(b).length,pending:f.length}};
this.attach=function(){var g=0,h=[];g=null;if(e){for(;g=f.shift();){h.push(g);g.on("ready",a);g.on("error",a)}for(g=0;g<h.length;g++)h[g].attach();e=false;if(d(b).length<=0){this.isready=true;this.fire("ready",this)}return this}};this.addElement=function(g){this.elements.push(g);f.push(g);b[g.id]=g;this.isready=false;e=true}};GEL.extend(GEL.Element.Attacher.MetaAttacher,GEL.event.Publisher)})();
GEL.Element.Attacher.MetaAttacher.Synchronized=function(){var a=function(){function c(){this.unsubscribe("error",arguments.callee);this.unsubscribe("ready",arguments.callee);d=false;return b.length<=0?e.finishHandler():e.attach()}var b=[],d=false,e=this;GEL.Element.Attacher.MetaAttacher.Synchronized.superclass.constructor.apply(this,arguments);this.elements=[];this.type="synchronous";this.getQueueSize=function(){return{pending:b.length,running:d}};this.attach=function(){if(!d){if(b.length<=0)return e.finishHandler();
var f=b.shift();d=true;f.on("ready",c);f.on("error",c);f.attach()}};this.finishHandler=function(){this.isready=true;return this.fire("ready",this)};this.addElement=function(f){this.elements.push(f);b.push(f);this.isready=false}};GEL.extend(a,GEL.event.Publisher);return a}();
GEL.Element.Attacher.MetaAttacher.Inline=function(){var a=GEL.objectUtil.keys,c=1,b=function(){function d(i){i.on("ready",e);i.on("error",e)}function e(){delete f[this.id];if(!(a(f).length>0)){g.isready=true;g.fire("ready",g)}}var f={},g=this,h=[];this.attach=function(){for(var i=null,j=0;j<h.length;j++){i=h[j];d(i);i.setAttacher("inline");i.attach();if(GEL.env.ua.gecko)i.stateManager.stateTransitionHandler();else for(;!i.isready;)i.stateManager.stateTransitionHandler()}if(GEL.env.ua.gecko){i=GEL.ement("SCRIPT",
{});j="element_"+c++;GEL.ElementLoader=GEL.ElementLoader||{};GEL.ElementLoader[j]=h;GEL.ElementLoader[j].readify=function(){for(var k=0,n=this.length;k<n;k++)for(;!this[k].isready;)this[k].stateManager.stateTransitionHandler()};i.setScriptText("GEL.ElementLoader."+j+".readify();");i.attach()}};this.addElement=function(i){h.push(i);f[i.id]=true;this.isready=false}};GEL.extend(b,GEL.event.Publisher);return b}();
(function(){function a(e){if(typeof e=="string")return e;if(e.base==="relative")return e.path;var f=window.location.protocol,g=GEL.env.gelpath,h=g.qsv;g=e.type=="skin"?d.skinbase:g.path;var i="";i=e.path.toLowerCase().indexOf("http://")==0||e.path.indexOf("/")==0?e.path:g.indexOf("/")==0||g.indexOf("://")>=0?g+"/"+e.path:f+"://"+g;return h?i+"?"+h:i}function c(e,f){if(typeof e!="object"||e.length<=0||!(f in e))return null;var g=0,h=null;h=null;e=e[f];for(f=new GEL.MetaElement;g<e.length;g++){h=e[g];
h=GEL.util.importer.require(h);f.addElement(h)}return f}function b(e,f,g){if(typeof f=="string"&&!(f=GEL.util.importer.getnamespace(f)))throw new Error("Cannot add Requirement to namespace that does not exist");typeof g=="string"&&!(g in d.namespaces)&&GEL.register(g,{path:g,type:"script"});f[e]=f[e]||[];f[e].push(g)}var d={scriptbase:(GEL.env.gelpath=function(){var e=document.getElementsByTagName("SCRIPT"),f=e[e.length-1].src;e=f.indexOf("core/core");var g=f.slice(0,e),h=f.indexOf("?"),i=h>=0?f.substr(h+
1):"";f={};h=g.indexOf("://");if(e<0){f.path="/gel/lib";f.qsv=i;return f}f=h<0?function(){var j=g;if(j.charAt(j.length-1)==="/")j=j.slice(0,j.length-1);return{hostname:window.location.host,basepath:j,qsv:i,proto:window.location.protocol}}():function(){var j=g.slice(g.indexOf("//")+2,g.length-1),k=j.indexOf("/");j=j.slice(0,k>0?j.indexOf("/"):j.length-1);k=g.slice(g.indexOf(j)+j.length);var n=g.slice(0,g.indexOf("://")+1);if(k.charAt(k.length-1)==="/")k=k.slice(0,k.length-1);return{proto:n,hostname:j,
qsv:i,basepath:k}}();f.path=f.proto+"//"+f.hostname+f.basepath;return f}()).path||"/gel/lib",skinbase:"/gel/skins",namespaces:{"skin.Palette91":{name:"gel-skin-go4",type:"skin",path:"palette91/palette91.css"},"skin.YUISkinSam":{name:"yui-skin-sam",type:"skin",path:"http://yui.yahooapis.com/2.7.0/build/logger/assets/skins/sam/logger.css"},"legacy.GDN":{path:"legacy/GDN/GDN.js",type:"script",requires:["util.Cookie"]},"legacy.SiteLife":{path:"legacy/GMTISiteLife.js",type:"script",requires:["util.Cookie",
"com.Pluck","util.Selector"]},"org.Prototype":{name:"org.Prototype",path:"3rdparty/prototype/prototype-1.6.1.js",type:"script"},"org.JSON":{name:"GDN.org.JSON",path:"3rdparty/json/json.js",type:"script"},"org.PorkIframe":{name:"GDN.org.PorkIframe",path:"3rdparty/porkiframe/pork.iframe.js",type:"script"},"org.jQuery":{name:"GDN.org.jQuery",path:"3rdparty/jquery/jquery-1.3.2.js",type:"script"},"com.Pluck":{name:"GDN.com.Pluck",path:"vendor/pluck/pluck.js",type:"script",requires:["org.PorkIframe","org.YUI.json"]},
"anim.YUIAnimator":{path:"anim/yuianimator.js",type:"script",requires:["util.Selector"]},"org.YUI.logger":{path:"3rdparty/yui/logger-min.js",depends:["org.YUI","org.YUI.domevent"],type:"script"},"org.YUI":{path:"3rdparty/yui/yahoo-min.js",type:"script"},"org.YUI.json":{path:"3rdparty/yui/json-min.js",type:"script",requires:[],depends:["org.YUI"]},"org.YUI.domevent":{path:"3rdparty/yui/yahoo-dom-event.js",requires:["org.YUI"],type:"script"},"org.YUI.animation":{path:"3rdparty/yui/animation-min.js",
type:"script",requires:["org.YUI.domevent"]},"org.YUI.selector":{path:"3rdparty/yui/selector-min.js",depends:["org.YUI"],type:"script"},"widget.GELTabs":{path:"widgets/tabs/geltabs.js",requires:["util.Selector"],depends:["widget"],type:"script"},widget:{path:"widgets/widget.js",requires:[],depends:[],type:"script"},"widget.Conveyor":{path:"widgets/conveyor/conveyor.js",type:"script",depends:["widget.GELTabs"]},"widget.Console":{path:"widgets/console/console.js",skin:"skin.YUISkinSam",type:"script",
requires:["org.YUI.logger"]},"widget.AdBanner":{path:"widgets/banner/banner.js",requires:["remoting","util.Cookie","util.Selector"],type:"script"},"util.Selector":{name:"util.Selector",path:"selector/selector.js",type:"script"},remoting:{name:"remoting",path:"remoting/remoting.js",requires:[],type:"script"},"widget.Menu":{name:"widget.Menu",path:"widgets/menu/menu.js",requires:["util.Selector"],type:"script"},"widget.Video":{path:"video/video.js",requires:["remoting","widget.AdBanner"],type:"script"},
"widget.Video.BrightcoveAPIModules":{path:"http://admin.brightcove.com/js/APIModules_all.js",requires:["http://admin.brightcove.com/js/BrightcoveExperiences.js"],type:"script"},"widget.Video.gReactions":{path:"video/GReactions.js",requires:[],type:"script"},"util.Cookie":{path:"cookie/cookie.js",type:"script"},"util.Flash":{path:"flashutil/flashutil.js",type:"script"},analytics:{name:"analytics",type:"script",path:"analytics/analytics.js",requires:["util.Cookie","remoting"]},"widget.ArticleTools":{name:"widget.ArticleTools",
type:"script",path:"widgets/articletools/articletools.js",depends:["widget"],requires:["util.Selector"]},custom:{path:"/scripts/custom/custom.js",requires:[],depends:["widget"],type:"script"}}};GEL.register=function(e,f){function g(){var m=d.namespaces,q={path:i,requires:j,depends:k,name:e,type:"script",skin:n};if(typeof l!="undefined"&&l)q.base=l;return m[e]=q}function h(){var m={path:i,type:"skin",name:e};return d.namespaces[e]=m}var i=f.path||null,j=f.requires||[],k=f.depends||[],n=f.skin||null,
l=f.base||null;f=f.type||"script";if(!i)throw new Error("You must provide a path to your namespace");return f=="script"?g():h()};GEL.util.importer={register:GEL.register,require:function(e){var f=null,g=null;if(typeof e=="undefined"||!e)throw new Error("You must require() a namespace");if(e in d.namespaces)f=d.namespaces[e];else{g=e.indexOf("http://");var h=e.indexOf("/");if(g!=0&&h!=0)throw new Error('Cannot find namespace "'+e+'", perhaps you need to register it? ');f={path:e,type:"script"}}var i=
"__gel_ns"+f.type+"_"+e;g=GEL.cachemgr.get(i);if(f.type==="skin")return g?g:new GEL.Element("LINK",{href:a(f),rel:"stylesheet",id:i});h=new GEL.MetaElement;g=g?g:GEL.Element("SCRIPT",{src:a(f),id:i});i=c(f,"depends");var j=c(f,"requires");if(typeof f.skin=="string"){f=GEL.util.importer.require(f.skin);h.addElement(f)}j instanceof GEL.MetaElement&&j.size()>0&&h.addElement(j);if(typeof i=="object"&&i instanceof GEL.MetaElement&&i.size()>0){f=new GEL.MetaElement([i,g]);f.setAttacher("sync");h.addElement(f)}else h.addElement(g);
g._namespace=e;h.id=h._namespace=e+":metawrap";return h}};GEL.use=function(){var e=GEL.util.importer;return function(f,g){f=f;var h=new GEL.MetaElement,i;f instanceof Array||(f=[f]);h=new GEL.MetaElement;for(var j=0;j<f.length;j++){try{i=e.require(f[j])}catch(k){GEL.log('ERROR: GEL.use(): Exception obtaining namespace "'+f[j]+'" \n'+k.message);continue}h.addElement(i)}typeof g=="function"&&h.on("ready",g);h.attach();return h}}();GEL.util.importer.getnamespace=function(e){return e in d.namespaces?
d.namespaces[e]:null};GEL.util.importer.addRequires=GEL.util.importer.addRequirement=function(e,f){return b("requires",e,f)};GEL.util.importer.addDepends=GEL.util.importer.addDependency=function(e,f){return b("depends",e,f)}})();
(function(){var a=["attach","installTransitionDetector","registerDOMEvent","unregisterDOMEvent"],c=GEL.Element.StateManager=function(e){c.superclass.constructor.call(this);this.gelement=e;if(!this.gelement)return null};GEL.extend(GEL.Element.StateManager,GEL.event.Publisher,{begin:function(){this.installTransitionDetector()},stateTransitionHandler:function(e){this.fire("loadstatetransition",this,{oldstate:this.type,newstate:e,gelement:this.gelement})}});for(var b=0;b<a.length;b++){var d=a[b];c.prototype[d]=
function(e){return function(){throw new Error("GEL.Element.StateManager."+e+"() is abstract and must be implemented");}}(d)}})();
(function(){var a=GEL.Element.StateManager.PreAttach=function(){GEL.Element.StateManager.PreAttach.superclass.constructor.apply(this,arguments)};GEL.extend(a,GEL.Element.StateManager,{type:"preattach",attach:function(){var c=this.gelement.attacher.attach(this.gelement);if(c)this.stateTransitionHandler(c);else{GEL.log("got no element for "+this.gelement.id+", installing local transition detector");a.prototype.installTransitionDetector.apply(this)}},registerDOMEvent:function(c){var b=this.gelement.domEvents;
if(c in b)return false;return b[c]=true},unregisterDOMEvent:function(c){var b=this.gelement.domEvents;return c in b?delete b[c]:false},installTransitionDetector:function(){var c=this.gelement.id,b=this,d=null,e=document,f=function(){var h=e.getElementById(c);return typeof h=="object"?h:false},g=function(h){b.stateTransitionHandler(h)};if(d=f())g(d);else this.trackid=GEL.tracker.add(f,g)},stateTransitionHandler:function(c){GEL.tracker.remove(this.trackid);var b=this.gelement;b=typeof b!="undefined"?
b.getElement():null;typeof c!="undefined"&&c&&b!==c&&this.gelement.setElement(c);GEL.Element.StateManager.PreAttach.superclass.stateTransitionHandler.call(this,"attach")}})})();GEL.Element.StateManager.PreAttach.Null=function(){GEL.Element.StateManager.PreAttach.Null.superclass.constructor.apply(this,arguments)};GEL.extend(GEL.Element.StateManager.PreAttach.Null,GEL.Element.StateManager.PreAttach,{installTransitionDetector:function(){}});
GEL.Element.StateManager.PreAttach.ImmediateTransition=function(){GEL.Element.StateManager.PreAttach.ImmediateTransition.superclass.constructor.apply(this,arguments)};GEL.extend(GEL.Element.StateManager.PreAttach.ImmediateTransition,GEL.Element.StateManager.PreAttach,{installTransitionDetector:function(){return this.stateTransitionHandler()}});
(function(){var a=GEL.Element.StateManager.Attached=function(){GEL.Element.StateManager.Attached.superclass.constructor.apply(this,arguments)};GEL.extend(a,GEL.Element.StateManager,{type:"attach",attach:function(){var c=this.gelement.getElement(),b=this.gelement.attachToElement;b=b instanceof GEL.Element.Base?b.getElement():b;c.parentNode!==b&&this.gelement.attacher.attach(this.gelement)},unregisterDOMEvent:function(c){var b=this.gelement,d=b.domEvents;if(!(c in d))return false;d=d[c];b.detachEventListener(c,
d);return d},registerDOMEvent:function(c){var b=this.gelement.domEvents;this.gelement.getElement();if(c in b)return false;var d=this.gelement.getDOMEventHandler(c);b[c]=d;this.gelement.attachEventListener(c,d);return true},installTransitionDetector:function(){var c=this,b=function(){c.stateTransitionHandler("ready")},d=this.gelement,e=function(){var f=d.element;if(f.readyState&&(f.readyState=="loaded"||f.readyState=="complete"))return f;return f.nextSibling?f:false};if(e())b();else this.trackid=GEL.tracker.add(e,
b)},stateTransitionHandler:function(){GEL.tracker.remove(this.trackid);GEL.Element.StateManager.Attached.superclass.stateTransitionHandler.call(this,"ready")}});GEL.Element.StateManager.Attached.Null=function(){GEL.Element.StateManager.Ready.superclass.constructor.apply(this,arguments)};GEL.extend(GEL.Element.StateManager.Attached.Null,GEL.Element.StateManager.Attached,{installTransitionDetector:function(){this.stateTransitionHandler("ready")}})})();
(function(){var a=GEL.Element.StateManager.Ready=function(){GEL.Element.StateManager.Ready.superclass.constructor.apply(this,arguments)};GEL.extend(a,GEL.Element.StateManager.Attached,{type:"ready",installTransitionDetector:function(){},stateTransitionHandler:function(){}})})();
(function(){var a=GEL.Element.StateManager.Error=function(){GEL.Element.StateManager.Error.superclass.constructor.apply(this,arguments)};GEL.extend(a,GEL.Element.StateManager.Attached,{type:"error",installTransitionDetector:function(){},registerDOMEvent:function(){GEL.log("ERROR: This element is in an error state")},stateTransitionHandler:function(){}})})();GEL.Element.StateManager.PreAttach.Document=function(){GEL.Element.StateManager.PreAttach.Document.superclass.constructor.apply(this,arguments)};
GEL.extend(GEL.Element.StateManager.PreAttach.Document,GEL.Element.StateManager.PreAttach,{installTransitionDetector:function(){function a(){return!!("body"in c&&c.body&&"nodeType"in c.body.firstChild)}var c=document;return function(){var b=this;if(a())return this.stateTransitionHandler();else this.trackid=GEL.tracker.add(a,function(){b.stateTransitionHandler()})}}()});
GEL.Element.StateManager.Attached.Document=function(){var a=GEL.env.ua,c=false;return function(){function b(){var e=GEL,f=document,g=window,h=GEL.env.ua.ie,i=d.gelement.loadEvents,j=e.objectUtil.copy,k=e.elementUtil.attachEventListener,n=e.elementUtil.detachEventListener;e=function(r,u){return function(A){if(!(u=="readystatechange"&&r.readyState!="complete"&&r.readyState!="loaded")){n(r,u,arguments.callee);c=true;if(!("readyState"in r))r.readyState="complete";i[u][r]=h?j(A):A}}};for(var l in i)if(i[l])for(var m=
i[l],q=0,o=m.length,p=m[q];q<o;p=m[++q])k(p,l,e(p,l));if(typeof f.readyState!="undefined"&&f.readyState==="complete")c=true;else if(a.ie)if(f.documentElement.doScroll&&g==g.top){g=function(){if(c)return c;try{f.documentElement.doScroll("left")}catch(r){return false}return c=true};g()||GEL.tracker.add(g,new Function)}}var d=this;GEL.Element.StateManager.Attached.Document.superclass.constructor.apply(this,arguments);this.installTransitionDetector=function(){var e=false;return function(){if(c){GEL.tracker.remove(d.trackid);
d.stateTransitionHandler();d.gelement.overrideLoadHandlers()}else if(!e){e=true;d.trackid=GEL.tracker.add(arguments.callee,new Function)}return c}}();b()}}();GEL.extend(GEL.Element.StateManager.Attached.Document,GEL.Element.StateManager.Attached);
GEL.Element.StateManager.Attached.Remote=function(){var a=GEL.elementUtil.attachEventListener,c=GEL.elementUtil.detachEventListener;return function(){function b(){g(j)}function d(){var l=i.getElement();if(l){if(!(l.readyState&&l.readyState!="complete"&&l.readyState!="loaded")){f(i.getElement());n.stateTransitionHandler("ready")}}else j&&f(j)}function e(){f(i.getElement());n.fire("loadstatetransition",n,{oldstate:n.type,newstate:"error",element:n.gelement.element,gelement:n.gelement})}function f(l){var m=
l.readyState?"readystatechange":"load";c(l,"error",e);c(l,m,d)}function g(l){var m=GEL.env.ua.ie||GEL.env.ua.opera?"readystatechange":"load";a(l,"error",e);a(l,m,d)}function h(){var l=this.gelement.tagName(),m=this.gelement.getElement();if(k)j!==m&&f(j);else g(m);j=m;m.readyState&&d();if(l.toUpperCase()=="LINK"&&(k||GEL.env.ua.gecko))return this.stateTransitionHandler("ready")}GEL.Element.StateManager.Attached.Remote.superclass.constructor.apply(this,arguments);this.gelement.tagName().toLowerCase();
var i=this.gelement,j=i.getElement(),k=GEL.env.ua.webkit,n=this;k&&b();this.installTransitionDetector=h}}();GEL.extend(GEL.Element.StateManager.Attached.Remote,GEL.Element.StateManager.Attached);
(function(){GEL.Element.StateManagerFactory=function(a){this.gelement=a;this.managers={};if(typeof this.transitionMap=="undefined")this.transitionMap={ready:GEL.Element.StateManager.Ready,error:GEL.Element.StateManager.Error,preattach:GEL.Element.StateManager.PreAttach,attach:GEL.Element.StateManager.Attached}};GEL.Element.StateManagerFactory.prototype={createStateManager:function(a){if(a in this.transitionMap)if(a in this.managers)return this.managers[a];else throw new Error("did you reinstall a transition map for "+
a+"?");else throw new Error("Cannot transition to state of type "+a);},makeManagers:function(){var a;for(var c in this.transitionMap){try{a=new this.transitionMap[c](this.gelement)}catch(b){GEL.log("ERROR: Unable to create statemanager for type "+c);continue}this.managers[c]=a}return this}};GEL.Element.StateManagerFactory.NullPreAttach=function(){GEL.Element.StateManagerFactory.NullPreAttach.superclass.constructor.apply(this,arguments);this.transitionMap.preattach=GEL.Element.StateManager.PreAttach.Null;
this.name="NullPreAttach"};GEL.extend(GEL.Element.StateManagerFactory.NullPreAttach,GEL.Element.StateManagerFactory);GEL.Element.StateManagerFactory.Remote=function(){var a=GEL.Element.StateManagerFactory.Remote.superclass;GEL.Element.StateManagerFactory.Remote.superclass.constructor.apply(this,arguments);this.transitionMap.attach=this.gelement.isLocal()&&a.transitionMap&&"attach"in a.transitionMap?a.transitionMap.attach:GEL.Element.StateManager.Attached.Remote;this.name="Remote"};GEL.extend(GEL.Element.StateManagerFactory.Remote,
GEL.Element.StateManagerFactory);GEL.Element.StateManagerFactory.Document=function(){GEL.Element.StateManagerFactory.Document.superclass.constructor.apply(this,arguments);this.transitionMap.preattach=GEL.Element.StateManager.PreAttach.Document;this.transitionMap.attach=GEL.Element.StateManager.Attached.Document;this.name="Document"};GEL.extend(GEL.Element.StateManagerFactory.Document,GEL.Element.StateManagerFactory)})();GEL.namespace("anim");
GEL.anim.SimpleAnimator=function(a,c){GEL.anim.SimpleAnimator.superclass.constructor.call(this);this.gelement=a;this.options=c||{};this.HIDE_CLASS=this.hideClass="hideclass"in this.options?this.options.hideclass:"gel-hidden"};
GEL.extend(GEL.anim.SimpleAnimator,GEL.event.Publisher,{isVisible:function(){return this.gelement.hasClassName(this.HIDE_CLASS)?false:true},show:function(){this.gelement.removeClassName(this.HIDE_CLASS);this.fire("animationComplete",this)},hide:function(){this.gelement.addClassName(this.HIDE_CLASS);this.fire("animationComplete",this)},toggle:function(){this.gelement.hasClassName(this.HIDE_CLASS)?this.show():this.hide()}});
(function(){var a={};GEL.cachemanager=GEL.cachemgr={};GEL.cachemgr.get=function(c){switch(typeof c){case "string":return c in a?a[c]:null;case "object":return"id"in c&&c.id?GEL.cachemgr.get(c.id):null;case "default":return null}};GEL.cachemgr.__CACHE=a;GEL.addGELement=function(c){c.id in a||(a[c.id]=c)};GEL.rmGELement=function(c){if(typeof c==="string")return delete a[c];else c.id in a&&delete a[c.id]};GEL.thepage=new GEL.Element.Document(document);GEL.thepage.on("ready",function(){GEL.Element.Base.prototype.attachToElement=
document.body});GEL.thepage.on("unload",function(){var c;for(var b in a){c=a[b];try{c.purgeElement()}catch(d){GEL.log("failed to purge element "+c.id)}try{GEL.rmGELement(b)}catch(e){GEL.log("failed to remove element "+c.id)}}})})();GEL.namespace("env.url");GEL.env.url.qsv=function(a){a=a.split("&");for(var c={},b,d=0;d<a.length;d++)if(a[d]){b=a[d].split("=");c[b[0]]=b[1]?b[1]:true}return c}(window.location.search.substr(1));
GEL.env.domain=function(){var a=window.location.hostname.split(".");return a.slice(a.length-2).join(".")}();
GEL.thepage.initializer=function(){function a(h){h=h||{};var i=h.namespace,j=h.callback,k=h.name;h="priority"in h&&typeof h.priority=="number"?h.priority:100;if(typeof j!="function")throw new Error("Error creating callback for "+k+":callback argument must be function reference");if(typeof k!="string")throw new Error("name argument must be present");this.initRoutines.push({name:k,priority:h,namespace:i,callback:j})}function c(){function h(){if(q.length<=0){m.fire("complete",m);GEL.thepage.timerList.display()}else{var s=
k(q.shift());m.addElement(s);g=d();if(g>0)u=setTimeout(i,g);m.attach()}}function i(){h()}function j(){clearTimeout(u);q.length<=0&&m.unsubscribe(arguments[0],arguments.callee);h()}function k(s){var v=null,w,x=new GEL.MetaElement,y=GEL.config.init,z=null,B=[],t="";x.on("preAttach",function(){for(var C=0;C<B.length;C++)B[C].start()});for(var D=0;D<s.length;D++){v=s[D];t=v.name;if(!(t in y&&!y[t]))if(t in y||y._default){z=(new GEL.util.benchmark.Timer(v.priority+":"+t+"(lib)")).start();B.push(z);GEL.thepage.timerList.addTimer(z);
w=e(v.namespace);w.on("ready",n(v.callback,x,t,z));x.addElement(w)}}return x}function n(s,v,w,x){return function(y){x.end();this.unsubscribe(y,arguments.callee);if(typeof s=="function"){var z=(new GEL.util.benchmark.Timer(w)).start();try{s.apply(v,arguments)}catch(B){GEL.log("ERROR running callback for "+w);GEL.logEx(B)}setTimeout(function(t){return function(){t.end();GEL.thepage.timerList.addTimer(t);GEL.thepage.timerList.display()}}(z),10)}}}for(var l=this.initRoutines.sort(b),m=this,q=[],o=[],
p,r,u=0,A=-1,E=0;E<l.length;E++){p=l[E];r=parseInt(p.priority/10,10);if(r!=A){o=[];q.push(o);A=r}o.push(p)}m.addInitRoutine=m.add=function(s){GEL.use(s.namespace,s.callback)};m.on("ready",j);h()}function b(h,i){return h.priority<=i.priority?-11:1}function d(){var h=g;if(!("tierTimeout"in GEL.config))return h;h=parseInt(GEL.config.tierTimeout,10);if(h<1E3)h*=1E3;return h}function e(h){var i=new GEL.MetaElement,j;if(h instanceof Array)for(var k=0;k<h.length;k++){try{j=GEL.util.importer.require(h[k])}catch(n){GEL.log("Cannot find namespace: "+
n.message);continue}i.addElement(j)}else{try{j=GEL.util.importer.require(h)}catch(l){return i}i.addElement(j)}return i}var f=new GEL.MetaElement,g=0;f.initRoutines=[];f.init=f.initialize=f.load=c;f.add=f.addInitRoutine=a;return f}();
(function(){function a(){GEL.namespace("util.benchmark");GEL.util.benchmark.Timer=GEL.util.benchmark.TimerList=function(){};for(var b="start,stop,end,addTimer,getTimer,display".split(","),d=function(){return this},e="getStop,getStart,getEnd".split(","),f=function(){return new Function},g=0;g<b.length;g++)GEL.util.benchmark.Timer.prototype[b[g]]=GEL.util.benchmark.TimerList.prototype[b[g]]=d;for(g=0;g<e.length;g++)GEL.util.benchmark.Timer.prototype[e[g]]=GEL.util.benchmark.TimerList.prototype[e[g]]=
f;GEL.thepage.timerList=new GEL.util.benchmark.TimerList}var c=null;if(GEL.config.init.timers){GEL.register("benchmark",{name:"benchmark",type:"script",path:"benchmark/benchmark.js"});c=GEL.util.importer.require("benchmark");c.setAttacher("inline");c.attach()}else a();if(GEL.config.init.debug)GEL.thepage.on("attach",function(){GEL.use("widget.Console",function(){new GEL.widget.Console})});else GEL.widget.Console=new Function})();