/*Copyright (c) 2011-2013 Moat Inc. All Rights Reserved.*/
try{(function(n,q){function X(){for(var a in t)t.hasOwnProperty(a)&&m.f.i(t[a]);for(a=0;a<N.length;a++)window.clearTimeout(N[a]);for(a=0;a<O.length;a++)window.clearInterval(O[a]);m.g.k()}var m={};(function(a){function h(a){var b=RegExp("(^| )"+a+"($| )");return function(a){return a&&a.className&&a.className.match(b)}}function g(a){return a&&a.document&&a.location&&a[d+e]&&a[l+f]}function c(a){if(null==a||g(a))return!1;var c=a.length;return 1===a.nodeType&&c?!0:"string"===typeof a||b(a)||0===c||"number"===
typeof c&&0<c&&c-1 in a}function b(k){return"[object Array]"===a.a.v.toString.call(k)}a.a={};a.a.a=3E3;a.a.b=function(){var a=/Firefox\/(\d+)/.exec(navigator.userAgent);return a?14<parseInt(a[1],10):!1}();a.a.c=function(){var k;k=/^(?:[a-z]+:\/\/|:?\/?\/)?(?:www\.)?([^\/:]*)/i;k=!a.b.a&&a.b.b?(k=a.b.b.match(k))&&k[1]?k[1]:a.b.c.location.hostname:a.b.c.location.hostname;var b=k.match(/.*\.([^\.]*\..*)/i);return b&&b[1]?decodeURIComponent(b[1]):decodeURIComponent(k)};a.a.d=function(){var k=a.a.e();
return 5===k||6===k||7===k};a.a.e=function(){if(!navigator)return null;var a=navigator.userAgent;return"Microsoft Internet Explorer"==navigator.appName?parseInt(a.replace(/^.*MSIE (\d+).*$/,"$1"),10):"Netscape"==navigator.appName&&(a=a.match(/Trident\/.*rv:(\d+)/))?parseInt(a[1],10):null};a.a.f=function(a,b){for(var c=0;c<a.length;c++)if(a[c]===b)return!0;return!1};a.a.getElementsByClassName=function(a,b,c){b=b||"*";c=c||document;if(c.getElementsByClassName){var d=[],e=c.getElementsByClassName(a);
if("*"!==b){a=0;for(c=e.length;a<c;a++){var f=e[a];f.tagName===b&&d.push(f)}return d}return e}e=[];b=c.getElementsByTagName(b);c=h(a);f=b.length;for(a=0;a<f;a++)d=b[a],c(d)&&e.push(d);return e};a.a.g=function(a){return new n-a.de};a.a.h=function(a){return a.replace(/^http:/,"").replace(/^\/\//,"").replace(/^www[^.]*\./,"").split("/")[0]};a.a.i=function(){return null!==/iPad|iPhone|iPod|Silk|Kindle|Android|BlackBerry|PlayBook|BB10|Windows Phone/.exec(navigator.userAgent)};a.a.j=function(){return null!==
/iPhone|iPod/.exec(navigator.userAgent)};a.a.k=function(){var a=navigator.userAgent;return a.match(/iPhone|iPod|iPad/)&&!a.match(/Safari/i)};a.a.l=function(){var a=window;try{return"undefined"!==typeof a.external&&"undefined"!==typeof a.external.InPrivateFilteringEnabled&&a.external.InPrivateFilteringEnabled()||"undefined"!==typeof a.external&&"undefined"!==typeof a.external.msTrackingProtectionEnabled&&a.external.msTrackingProtectionEnabled()||"undefined"!==typeof a._gaUserPrefs&&a._gaUserPrefs.ioo&&
a._gaUserPrefs.ioo()||"undefined"!==typeof navigator.doNotTrack&&("yes"===navigator.doNotTrack||!0===navigator.doNotTrack)||"undefined"!==typeof a._gaUserPrefs&&!0===a._gaUserPrefs}catch(b){return!1}};a.a.getAttribute=function(a,b){return a[b]||a.getAttribute(b)};a.a.m=function(a){var b=0,c;for(c in a)a.hasOwnProperty(c)&&(b+=1);return b};a.a.n=function(b,c){return a.a.o(b)&&!0!==b[v]?!0:!1};a.a.o=function(b){return b.offsetWidth*b.offsetHeight>=a.a.a};a.a.p=function(a,b){var c=!1,d=b.body,e=d&&d.firstChild;
d&&e&&(d.insertBefore(a,e),c=!0);return c};a.a.q=function(){var a;return function(){if(!a)a:{for(var b=document.getElementsByTagName("script"),c=b.length-1;-1<c;c--)if((a=b[c])&&a.src&&a.src.indexOf&&-1!==a.src.indexOf(ba+"/moatad.js")&&("undefined"===typeof a[v]||!0!==a[v])){a[v]=!0;break a}a=void 0}return a?(a[v]=!0,a):null}}();a.a.r=function(a){try{return-1!==(a.src||a.getAttribute("src")).indexOf("psd=1")}catch(b){return!1}};a.a.s=function(a){for(var b=[],c=0;c<a.length;c++)b.push(a[c]);return b};
a.a.previousElementSibling=function(a){if(a.previousElementSibling)return a.previousElementSibling;for(;a=a.previousSibling;)if(1===a.nodeType)return a};a.a.t=function(a,b,c){"undefined"!==typeof c&&(a[b]=c)};a.a.filter=function(a,b){for(var c=[],d=0;d<a.length;d++)b(a[d])&&c.push(a[d]);return c};a.a.u=function(a,b){for(var c=[],d=0;d<b.length;d++)c.push(a(b[d]));return c};var d="ale",e="rt",l="setInte",f="rval";a.a.v={};a.a.w=b;a.a.x=g;a.a.y=c;a.a.forEach=function(a,b,d){var e;if(a)if("function"===
typeof a)for(e in a){if("prototype"!=e&&"length"!=e&&"name"!=e&&(!a.hasOwnProperty||a.hasOwnProperty(e))){var f=b.call(d,a[e],e);if("boolean"===typeof f&&!f)break}}else if("function"===typeof a.every)a.every(function(a,c,e){a=b.call(d,a,c);return!("boolean"===typeof a&&!a)});else if(c(a))for(e=0;e<a.length&&(f=b.call(d,a[e],e),"boolean"!==typeof f||f);e++);else for(e in a)if(a.hasOwnProperty(e)&&(f=b.call(d,a[e],e),"boolean"===typeof f&&!f))break;return a}})(m);(function(a){function h(a){try{var b=
typeof a.location.toString;if("undefined"===b||"unknown"===b)return!0;var d=typeof a.document;return"undefined"===d||"unknown"===d?!0:!1}catch(e){return!0}}a.b={};a.b.d="MoatSuperV4";a.b.e=0;a.b.f=0<Object.prototype.toString.call(window.HTMLElement).indexOf("Constructor");a.b.g=-1!==navigator.userAgent.toLowerCase().indexOf("firefox");a.b.h=-1!==navigator.userAgent.indexOf("MSIE");a.b.i=(new n).getTime();a.b.protocol=function(){var a;try{a=window.location.protocol}catch(b){a=document.createElement("a"),
a.href="",a=a.protocol}return a}();a.b.j=("https:"===a.b.protocol?"z":"js")+".moatads.com";a.b.k=window!=window.parent;var g=h(window.parent);a.b.l=a.b.k&&!g;a.b.a=g?!1:!h(window.top);a.b.c=a.b.a?window.top:a.b.l?window.parent:window;a.b.b=a.b.c.document.referrer})(m);(function(a){function h(a){return function(){var b=!1;return function(d){try{a(d)}catch(e){if(!b){b=!0;d=e.name+" in callback: "+e.message+", stack="+e.stack;try{var l="//v3.moatads.com/pixel.gif?e=24&d=data%3Adata%3Adata%3Adata&i="+
escape("USATODAYSMG1")+"&ac=1&k="+escape(d)+"&ar="+escape("099702a-clean")+"&j="+escape(document.referrer)+"&cs="+(new n).getTime();(new Image(1,1)).src=l}catch(f){}}}}}()}a.c={};var g={};a.c.a=g;a.c.b=function(a,b,d,e){d=h(d);a.addEventListener?a.addEventListener(b,d,!1):a.attachEvent("on"+b,d);!1!==e&&(g[b+e]=d)};a.c.c=function(a,b,d,e){var l=b+e;d=!1!==e?g[l]:d;try{a&&a.removeEventListener?a.removeEventListener(b,d,!1):a&&a.detachEvent&&a.detachEvent("on"+b,d)}catch(f){}delete g[l]};a.c.d=
function(a,b){a=h(a);var d=setInterval(a,b);O.push(d);return d};a.c.e=function(a,b){a=h(a);var d=setTimeout(a,b);N.push(d);return d};a.c.f=function(c,b,d,e){var l=0,f=function(){l+=1;!0!==c()&&(l<b?a.c.e(f,d):"function"===typeof e&&e())};f()};a.c.g=h})(m);(function(a){function h(){this.height=this.width=this.absTop=this.absLeft=0;this.update=function(a){this.absLeft=a.left+e("left",a.win);this.absTop=a.top+e("top",a.win);this.width=a.width;this.height=a.height}}function g(b,d){var c=b.zr;f.hasOwnProperty(c)||
(f[c]=new h);var e=d||new a.d.h(b.aa);f[c].update(e)}function c(a,b){for(var d=[],c=0;c<b.length;c++)d.push(a(b[c]));return d}function b(b){var d,e=a.f.b(b.el,b.win),e=c(function(b){return new a.d.h(b)},e);e.unshift(b);var f=e.length;b=new a.d.h(b.el,a.b.c);for(var l=0;l<f;l++){var g=e[l];0===l?d=g:(d.changeReferenceFrame(g),b.changeReferenceFrame(g));g=g.getViewportRect(l<f-1?e[l+1]:!1);d=a.d.j(d,g)}return{visibleRect:d,cumulRect:b,parentArea:e[e.length-1].calcArea()}}function d(a,b,d,c){a=q.max(a,
d);b=q.min(b,c);return b>a?[a,b]:[0,0]}function e(a,b){b||(b=window);var d=b.document.documentElement,c=b.document.body;return"left"===a?b.pageXOffset||d&&d.scrollLeft||c&&c.scrollLeft:b.pageYOffset||d&&d.scrollTop||c&&c.scrollTop}a.d={};var l=a.b.a,f={};a.d.a=0.5;a.d.b=0.3;a.d.c=236425;a.d.d=function(d,c){if(1==d.ao.skin){var e=a.b.c.scrollY||a.b.c.document.documentElement.scrollTop;return"width"==a.e.a&&a.e.b<=d.adContent&&45<e?{isVisible:!1}:{isVisible:!0}}e=new a.d.h(d.aa,c);g(d,e);var f=e.height,
l=e.width,h=e.calcArea();if(0===h)e={area:h,percv:0};else{var r=b(e),K=r.visibleRect.calcArea(),G=K/h,m;b:{var w=r.cumulRect,x=r.cumulRect.getViewportRect();if(0>w.top&&0<w.bottom)m=-w.top;else if(0<=w.top&&w.top<=x.height)m=0;else{m={yMin:-1,yMax:-1};break b}if(0<=w.bottom&&w.bottom<=x.height)w=w.height;else if(w.bottom>x.height&&w.top<x.height)w=w.height-(w.bottom-x.height);else{m={yMin:-1,yMax:-1};break b}m={yMin:m,yMax:w}}e={area:h,visibleArea:K,percv:G,yMinMax:m,elGeo:{elHeight:f,elWidth:l,foldTop:r.cumulRect.top,
totalArea:r.parentArea},rect:e.rect}}f=a.d.e(e,d);e.isVisible=e.percv>=f;e.elGeo&&(e.elGeo.threshold=f);return e};a.d.e=function(b,d){return b.area>=a.d.c?(d.viewstats.isBigAd=!0,a.d.b):a.d.a};a.d.f=function(){return l};a.d.g=function(a,b){l&&f.hasOwnProperty(b)||g(a);return f[b]};a.d.i=function(a){var b,d,c,e=0,f=0;try{b=a.document,d=b.documentElement,c=b.body}catch(r){return{width:e,height:f,left:0,right:e,top:0,bottom:f}}"undefined"!==typeof a.innerWidth?(e=a.innerWidth,f=a.innerHeight):"CSS1Compat"===
b.compatMode&&5!==b.documentMode||!c||"undefined"===typeof c.clientWidth?d&&"undefined"!==typeof d.clientWidth&&(e=d.clientWidth,f=d.clientHeight):(e=c.clientWidth,f=c.clientHeight);return{width:e,height:f,left:0,right:e,top:0,bottom:f}};a.d.h=function(b,d,c){this.rect=c||b.getBoundingClientRect();c=["left","right","top","bottom"];for(var e=0;e<c.length;e++){var f=c[e];this[f]=this.rect[f]}this.width=this.right-this.left;this.height=this.bottom-this.top;this.el=b;this.win=d||b&&a.f.a(b);this.changeReferenceFrame=
function(a){this.left+=a.left;this.right+=a.left;this.top+=a.top;this.bottom+=a.top};this.calcArea=function(){return(this.right-this.left)*(this.bottom-this.top)};this.getViewportRect=function(b){var d=a.d.i(this.win);b&&(b.width<d.width&&(d.width=b.width,d.right=d.left+d.width),b.height<d.height&&(d.height=b.height,d.bottom=d.top+d.height));return d}};a.d.j=function(b,c){var e=d(b.left,b.right,c.left,c.right),f=d(b.top,b.bottom,c.top,c.bottom);return new a.d.h(void 0,void 0,{left:e[0],right:e[1],
top:f[0],bottom:f[1]})}})(m);(function(a){function h(b){a.focus.pageIsVisible(!0)&&((new n).getTime()-f>=F&&e?(a.g.k(),a.g.i(t[G])):k||(k=!0,a.c.e(function(){k=!1;h()},r)))}function g(){a.g.o=(new n).getTime();a.c.f(function(){var b=d.getElementById("moatPx"+G),r=d.getElementById("moatPxEmbed"+G);c(b)?(e=b,l=b.parentNode):c(r)&&(e=r,l=b.parentNode);if(!1!==e){a.g.g?a.g.d=e.setConfig(w):a.g.f?a.g.d=e.setConfig(w):e.setConfig(P);a.g.b&&(a.g.b="off"===a.g.d);if(8===A&&"iescope"===a.g.d){var f=function(){try{var b=
parseInt(e.style.top,10);e.style.top=0>b?b+1E4+"px":b-1E4+"px";a.c.e(f,100)}catch(d){}};a.c.e(f,16)}return!0}},v,Q)}function c(a){try{return a&&(a.getStats||"undefined"!==typeof a.getStats||a.getStats())&&!0}catch(b){return!1}}function b(a,b,d){var c=document.createElement("param");c.setAttribute("name",b);c.setAttribute("value",d);a.appendChild(c)}a.g={};a.g.a=function(){function a(b){b=b.match(/[\d]+/g);b.length=3;return b.join(".")}var b=!1,d="";if(navigator.plugins&&navigator.plugins.length){var c=
navigator.plugins["Shockwave Flash"];c&&(b=!0,c.description&&(d=a(c.description)));navigator.plugins["Shockwave Flash 2.0"]&&(b=!0,d="2.0.0.11")}else if(navigator.mimeTypes&&navigator.mimeTypes.length)(b=(c=navigator.mimeTypes["application/x-shockwave-flash"])&&c.enabledPlugin)&&(d=a(c.enabledPlugin.description));else try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),b=!0,d=a(c.GetVariable("$version"))}catch(e){try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),b=!0,d="6.0.21"}catch(r){try{c=
new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),b=!0,d=a(c.GetVariable("$version"))}catch(f){}}}return b?d:"0"}();a.g.b=!1;a.g.c="";a.g.d="default";var d,e=!1,l,f=0,k=!1,A=a.a.e(),s=null!==A,m=-1!==navigator.userAgent.indexOf("Chrome"),z=6.2<=function(){var a=navigator.appVersion.match(/Windows NT (\d\.\d)/);return a?parseFloat(a[1]):-1}(),F=1E3,r=200,K=a.b.protocol+"//"+a.b.j,G=!1;a.g.e=0<Object.prototype.toString.call(window.HTMLElement).indexOf("Constructor");a.g.f=!1;a.g.g=!1;var P={"default":{targetVersion:"*",
lo:""}},w={iescope:{targetVersion:"*",lo:">="}};try{var x=a.a.e();if(7==x||8==x||9==x||10==x||11==x)a.g.g=!0}catch(q){}var Q=10,v=500,L=!0,y;a.g.h=function(){if(e&&e.getStats)try{"iescope"===a.g.d&&(L&&(L=!1,y=e.style.width),e.style.width=y!==e.style.width?y:parseInt(y,10)+1+"px");var b=e&&e.getStats();if(b&&b.ok)return"off"!==a.g.d&&(a.g.b=!0),a.g.c=b.rev,b}catch(d){}return!1};a.g.i=function(c){if(a.g.j()){var e=c.zr;try{var r=K+"/swf/p5.v1e.swf",l,k;k=s?l=2:l=1;var w=a.d.g(c,e),m="position: absolute; width: "+
l+"px; height: "+k+"px; z-index: -9999;";a.g.f&&(m+="-webkit-transform: translate3d(0, 0, 0);");var Y=m+"left: "+w.absLeft+"px; top: "+(w.absTop+w.height/2)+"px;",m=m+"left: 0px; top: 0px;";c.ed.x=w.absLeft;c.ed.y=w.absTop;w="ym"+e;G=e;u.yl||(u.yl={});u.yl[w]=function(){g()};var x=c.aa.ownerDocument;("defaultView"in x?x.defaultView:x.parentWindow)[a.b.d]=u;var P="ol="+a.b.d+".yl."+w+"&db=false";d=x;if(z&&s&&10<=A)var F=function(){var a="moatPx"+e,d=x.createElement("OBJECT");d.setAttribute("data",
r);d.setAttribute("id",a);d.setAttribute("name",a);d.setAttribute("style",Y);d.setAttribute("width",l+"");d.setAttribute("height",k+"");b(d,"flashvars",P);b(d,"wmode","transparent");b(d,"bgcolor","");b(d,"allowscriptaccess","always");var a=x.body,c=x.createElement("div");c.id="moatPxDiv"+e;c.style.width="0px";c.style.height="0px";a.insertBefore(c,a.firstChild);c.appendChild(d);return!0};else var q='<object type="application/x-shockwave-flash" classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0" width="'+
l+'" height="'+k+'" style="'+Y+'" id="moatPx'+e+'"><param name="allowScriptAccess" value="always" /><param name="allowFullScreen" value="false" /><param name="movie" value="'+r+'" /><param name="quality" value="low" /><param name="hasPriority" value="true" /><param name="FlashVars" value="'+P+'" /><param name="bgcolor" value="" /><param name="wmode" value="transparent" /><embed type="application/x-shockwave-flash" src="'+r+'" quality="low" flashvars="'+P+'" bgcolor="" wmode="transparent" width="'+
l+'" height="'+k+'" id="moatPxEmbed'+e+'" name="moatPx'+e+'" style="'+m+'" hasPriority="true" allowscriptaccess="always" allowFullScreen="false" type="application/x-shockwave-flash" pluginspage="http://www.adobe.com/go/getflashplayer" /></object>',F=function(){var b=x.createElement("div");b.id="moatPxDiv"+e;b.style.width="0px";b.style.height="0px";if(!0===a.a.p(b,d)){b.innerHTML=q;try{b.getElementsByTagName("object")}catch(c){}return!0}return!1};f=(new n).getTime();a.c.f(F,10,100);z&&s&&10<=A&&a.focus.supportsPageVisAPI()&&
a.c.b(d,a.focus.visibilitychange,h,e)}catch(t){}}};a.g.l=function(b,d){var c=a.g.m,e=b.aa.ownerDocument.getElementById("moatPx"+d);if(e){var r=e.parentNode;if(0!==r.id.indexOf("moatPxDiv")){var f=document.getElementById("moatPxDiv"+d);r.removeChild(e);f.appendChild(e)}r=a.d.g(b,d);r={left:r.absLeft+r.width/2,top:r.absTop+r.height/2};c(r,b.ed)&&(e.style.left=r.left+"px",e.style.top=r.top+"px",b.ed.x=r.left,b.ed.y=r.top)}};a.g.k=function(){l&&l.parentNode&&(a.c.c(d,a.focus.visibilitychange,h,G),e.parentNode.removeChild(e),
l.parentNode.removeChild(l),d=l=e=!1)};a.g.n=function(b){a.g.l(b,b.zr);isVisible=(b=a.g.h())?b.iv:!1;return{isVisible:isVisible}};a.g.j=function(){return s||a.b.k&&!a.b.l&&m||a.g.f};a.g.m=function(a,b){return a&&(a.left!==b.x||a.top!==b.y)}})(m);(function(a){function h(a,b,d){a.IR5.MIN[d]=q.min(b,a.IR5.MIN[d])||b||1;a.IR5.MAX[d]=q.max(b,a.IR5.MAX[d])||b}function g(a,b){b.be=q.max("undefined"!==typeof b.be?b.be:0,a-b.bf);"undefined"===typeof b.by&&b.be>=F&&(b.by=b.bk)}function c(b){b.az===a.h.a.d.a?
b.az=a.h.a.d.b:b.az===a.h.a.d.b&&(b.az=a.h.a.d.a)}function b(b){b.ba===a.h.a.d.a?b.ba=a.h.a.d.b:b.ba===a.h.a.d.b&&(b.ba=a.h.a.d.a)}function d(b){b.ax===a.h.a.b.a?b.ax=a.h.a.b.b:b.ax===a.h.a.b.b&&(b.ax=a.h.a.b.a)}function e(b){b.ay===a.h.a.c.a?b.ay=a.h.a.c.b:b.ay===a.h.a.c.b&&(b.ay=a.h.a.c.a)}function l(a,b){"undefined"===typeof b.bk&&(b.bk=0);b.bk+=a-b.bo;b.bo=a}function f(a,b){"undefined"===typeof b.bl&&(b.bl=0);b.bl+=a-b.bp;b.bp=a}function k(a,b){"undefined"===typeof b.bg&&(b.bg=0);"undefined"===
typeof b.bc&&(b.bc=0);b.bu=a-b.bs;b.bu>b.bc&&(b.bc=b.bu);b.bg+=a-b.bq;b.bc>=z&&"undefined"===typeof b.bw&&(b.bk+=a-b.bo,b.bw=b.bk);b.bq=a}function A(a,b){"undefined"===typeof b.bh&&(b.bh=0);"undefined"===typeof b.bd&&(b.bd=0);b.bv=a-b.bt;b.bv>b.bd&&(b.bd=b.bv);b.bh+=a-b.br;b.bd>=z&&"undefined"===typeof b.bx&&(b.bl+=a-b.bp,b.bx=b.bl);b.br=a}a.h={};var s=500,m=3E3,z=500,F=500;a.h.a={};a.h.a.a={};a.h.a.a.a=0;a.h.a.a.b=1;a.h.a.b={};a.h.a.b.a=0;a.h.a.b.b=1;a.h.a.c={};a.h.a.c.a=0;a.h.a.c.b=1;a.h.a.d={};
a.h.a.d.a=0;a.h.a.d.b=1;a.h.a.e={};a.h.a.e.a=0;a.h.a.e.b=1;a.h.a.f={};a.h.a.f.a=0;a.h.a.f.b=1;a.h.a.f.c=2;a.h.b=function(a){h(a,a.aj,"x");h(a,a.ak,"y");a.IR5.AREA=(a.IR5.MAX.x-a.IR5.MIN.x)*(a.IR5.MAX.y-a.IR5.MIN.y)};a.h.c=function(b){function d(){(new n).getTime()-R>=s&&(a.h.d({type:"park"},b),clearInterval(e),b.au=a.h.a.a.a)}var c=b.au;if(c===a.h.a.a.a){R=(new n).getTime();var e=a.c.d(d,50);b.au=a.h.a.a.b}else c===a.h.a.a.b&&(R=(new n).getTime())};a.h.e=function(b){function d(){(new n).getTime()-
S>=m&&(a.h.f({type:"park"},b),clearInterval(e),b.av=a.h.a.a.a)}var c=b.av;if(c===a.h.a.a.a){S=(new n).getTime();var e=a.c.d(d,50);b.av=a.h.a.a.b}else c===a.h.a.a.b&&(S=(new n).getTime())};a.h.g=function(b,d){var e=b.type;if(d.az===a.h.a.d.a){if("mouseover"===e||"mousemove"===e)d.bo=(new n).getTime(),c(d)}else if(d.az===a.h.a.d.b){"mousemove"===e&&l((new n).getTime(),d);if("mouseout"===e||"blur"===e)l((new n).getTime(),d),c(d);"scooper"===e&&l((new n).getTime(),d)}};a.h.h=function(d,c){var e=d.type;
if(c.ba===a.h.a.d.a){if("mouseover"===e||"mousemove"===e)c.bp=(new n).getTime(),b(c)}else if(c.ba===a.h.a.d.b){"mousemove"===e&&f((new n).getTime(),c);if("mouseout"===e||"blur"===e)f((new n).getTime(),c),b(c);"scooper"===e&&f((new n).getTime(),c)}};a.h.d=function(b,c){if(2!=c.an){var e=b.type;if(c.ax===a.h.a.b.a){if("mouseover"===e||"mousemove"===e)c.bq=(new n).getTime(),c.bs=(new n).getTime(),d(c)}else c.ax===a.h.a.b.b&&("mousemove"!==e&&"mouseout"!==e||k((new n).getTime(),c),"park"===e&&k((new n).getTime()-
s,c),"mouseout"!==e&&"park"!==e||d(c))}};a.h.f=function(b,d){if(2!=d.an){var c=b.type;if(d.ay===a.h.a.c.a){if("mouseover"===c||"mousemove"===c)d.br=(new n).getTime(),d.bt=(new n).getTime(),e(d)}else d.ay===a.h.a.c.b&&("mousemove"!==c&&"mouseout"!==c||A((new n).getTime(),d),"park"===c&&A((new n).getTime()-m,d),"mouseout"!==c&&"park"!==c||e(d))}};a.h.i=function(b,d){var c=b.type;if(d.bb==a.h.a.e.a){if("mouseover"==c||"mousemove"==c)d.bf=(new n).getTime(),d.bb=a.h.a.e.b}else d.bb==a.h.a.e.b&&("mouseout"==
c?(g((new n).getTime(),d),d.bb=a.h.a.e.a):"mousemove"!=c&&"scooper"!=c||g((new n).getTime(),d))}})(m);(function(a){function h(b){if(!a.focus.pageIsPrerendered()){a.c.c(document,k,h,"pr");for(var d in t)t.hasOwnProperty(d)&&a.f.c(t[d])}}function g(a){"undefined"==typeof e&&(e=a)}a.focus={};var c=navigator.userAgent,c=-1<c.indexOf("Safari")&&-1==c.indexOf("Chrome")&&-1==c.indexOf("Chromium")&&!I,b=(eval("/*@cc_on!@*/false")||document.documentMode)&&!I,d="undefined"!==typeof document.hasFocus,e,l={visible:0,
hidden:1,prerender:2},f,k,A,s;"undefined"!==typeof document.hidden?(f="hidden",k="visibilitychange"):"undefined"!==typeof document.mozHidden?(f="mozHidden",k="mozvisibilitychange"):"undefined"!==typeof document.msHidden?(f="msHidden",k="msvisibilitychange"):"undefined"!==typeof document.webkitHidden&&(f="webkitHidden",k="webkitvisibilitychange");for(var m=["v","mozV","msV","webkitV"],z=0;z<m.length;z++){var F=m[z]+"isibilityState";if("undefined"!==typeof document[F]){A=F;break}}s="undefined"!==typeof f;
var r,K;"undefined"!==typeof window.requestAnimationFrame?r="requestAnimationFrame":"undefined"!==typeof window.webkitRequestAnimationFrame&&(r="webkitRequestAnimationFrame");K=c&&"string"==typeof r&&!s;var G=(new n).getTime();K&&function x(){G=(new n).getTime();window[r](x)}();a.focus.getFocusMethod=function(){return e};a.focus.visibilitychange=k;a.focus.setFocusListeners=function(){"Microsoft Internet Explorer"===navigator.appName?(a.c.b(y.document,"focusout",function(){u.yd()},!1),a.c.b(y.document,
"focusin",function(){u.ye()},!1)):(a.c.b(y,"blur",function(){u.yd()},!1),a.c.b(y,"focus",function(){u.ye()},!1))};a.focus.getQueryString=function(a){a={};a.em=e;q&&(a.eo=1);"undefined"!=typeof A&&(a.en=l[document[A]]);return a};a.focus.supportsPageVisAPI=function(){return s};a.focus.pageIsVisible=function(){if(a.focus.supportsPageVisAPI())return g(0),!document[f];if(K)return g(1),100>(new n).getTime()-G;if(b&&d)return g(2),document.hasFocus();g(3);return!0};a.focus.pageIsPrerendered=function(){return"undefined"!==
typeof A?"prerender"==document[A]:!1};a.focus.pageIsVisible();a.focus.pageIsPrerendered()&&a.c.b(document,k,h,"pr");var q=a.focus.pageIsPrerendered();a.focus.windowHasFocus=function(){return u.v}})(m);(function(a){function h(b,d,c,e,f){("remove"===f?a.c.c:a.c.b)(b,d,function(d){d=d||this.event;var e=d.currentTarget||b,f=t[e[T]];if(f){var l;l=d;var k=e.getBoundingClientRect();l=-1!=l.type.indexOf("touch")?{x:parseInt(l.changedTouches[0].clientX-k.left,10),y:parseInt(l.changedTouches[0].clientY-k.top,
10)}:{x:parseInt(l.clientX-k.left,10),y:parseInt(l.clientY-k.top,10)};f.aj=l.x;f.ak=l.y;f.dm||(f.cb=2==a.focus.getFocusMethod()?f.counters.laxDwell.tCur:f.counters.strictDwell.tCur,f.dm=1);c.call(b,d,e,f)}},e)}function g(a,e,f){h(a,"click",s,e,f);h(a,"mousedown",b,e,f);I?h(a,"touchstart",d,e,f):(h(a,"mousemove",c,e,f),h(a,"mouseover",k,e,f),h(a,"mouseout",A,e,f))}function c(b,d,c){b=b||window.event;d=b.target||b.srcElement;1==c.ao.skin&&a.e.c(d,c.adContent,b)||(I||c.aj===c.al&&c.ak===c.am||(a.h.d(b,
c),a.h.f(b,c),a.h.g(b,c),a.h.i(b,c),a.h.h(b,c),a.h.b(c),a.h.c(c),a.h.e(c),0===c.ar.length&&(c.ai=z(c)),c.ar.push(c.aj),c.as.push(c.ak),c.at.push(a.a.g(c)),c.al=c.aj,c.am=c.ak),c.ai!==z(c)&&1<c.ar.length&&m(c,"onMouseMove"))}function b(b,c,d){b=b||window.event;c=b.target||b.srcElement;1==d.ao.skin&&a.e.c(c,d.adContent,b)||(b={e:2},b.q=d.aq[2]++,b.x=d.aj,b.y=d.ak,a.j.a(d,b))}function d(b,c,d){b={e:23};b.q=d.aq[23]++;b.x=d.aj;b.y=d.ak;c=(new n).getTime();if("undefined"===typeof d.ct)d.ct=c;else{var e=
c-d.ct;d.ct=c;d.cu=q.min(d.cu,e)||e}b.bz=void 0;a.j.a(d,b)}function e(b,d,c){if(2==b.an){var e=d.e,k=b.ck;k==a.h.a.f.a&&6===e?(l(b,0),b.cl=a.a.g(b),b.ck=a.h.a.f.b):k==a.h.a.f.b?22===e?(f(b,d),l(b,c),b.cl=a.a.g(b)):7===e&&(1E3<a.a.g(b)-b.cl?(clearTimeout(b.cm),d.e=22,f(b,d),b.cn=0,b.ck=a.h.a.f.a):b.ck=a.h.a.f.c):k==a.h.a.f.c&&(6==e?(1E3<a.a.g(b)-b.cl&&(clearTimeout(b.cm),b.cn=0,b.cl=a.a.g(b),l(b,0)),b.ck=a.h.a.f.b):22==e&&(f(b,d),b.ck=a.h.a.f.a,b.cn=0))}}function l(b,d){var c=5>b.cn?1E3:2*d,f={e:22};
b.cm=a.c.e(function(){e(b,f,c)},c)}function f(b,d){d.q=b.aq[d.e]++;d.m=a.a.g(b);b.cl=d.m;a.j.a(b,d);b.cn++}function k(b,d,c){b=b||window.event;d=b.target||b.srcElement;1==c.ao.skin&&a.e.c(d,c.adContent,b)||(a.h.d(b,c),a.h.f(b,c),a.h.g(b,c),a.h.i(b,c),a.h.h(b,c),e(c,{e:6},0))}function A(b,d,c){b=b||window.event;d=b.target||b.srcElement;1==c.ao.skin&&a.e.c(d,c.adContent,b)||(a.h.d(b,c),a.h.f(b,c),a.h.g(b,c),a.h.i(b,c),a.h.h(b,c),e(c,{e:7},0))}function s(b,d,c){b=b||window.event;d=b.target||b.srcElement;
1==c.ao.skin&&a.e.c(d,c.adContent,b)||(b={e:3},b.q=c.aq[3]++,b.x=c.aj,b.y=c.ak,a.j.a(c,b))}function m(b,c){b.ai=z(b);var d={e:1};d.q=b.aq[1]++;d.x=b.ar.join("a");d.y=b.as.join("a");for(var e=a.a.g(b),f=b.at,l=[],k=0;k<f.length;k++)isNaN(f[k])||l.push(q.abs(f[k]-e));d.c=l.join("a");d.m=e;a.j.a(b,d);b.ar=[];b.as=[];b.at=[]}function z(b){return q.floor(a.a.g(b)/F)}a.i={};var F=1E3;a.i.a=function(a,b){if(!0===a.isSkin)for(var d=0;d<a.elements.length;d++)g(a.elements[d],a.zr+"-"+d,b);else g(a.aa,a.zr,
b)};a.i.b=function(b){for(var d in t)t.hasOwnProperty(d)&&(b=t[d])&&(a.h.g({type:"scooper"},b),a.h.i({type:"scooper"},b),a.h.h({type:"scooper"},b),1<b.ar.length&&b.ai!==z(b)&&m(b,"scooper"))}})(m);(function(a){a.k={};var h="undefined"!==typeof window.devicePixelRatio,g=h&&q.round(1E3*window.devicePixelRatio),c=a.b.a&&h&&"undefined"!==typeof window.innerHeight&&"undefined"!==typeof window.outerHeight&&q.round(window.devicePixelRatio*(a.b.c.outerHeight-a.b.c.innerHeight)),b="undefined"!==typeof window.mozInnerScreenX&&
"undefined"!==typeof window.screenX;a.k.a=function(b,c){var l;try{var f,k=b.aa.getBoundingClientRect(),g=c||b.WINDOW||a.f.a(b.aa),s=a.d.i(g),m=a.d.j(k,s),n=g.mozInnerScreenX,q=g.mozInnerScreenY,r=window.screenX,t=window.screenY,u=a.d.j({left:m.left+n,right:m.right+n,top:m.top+q,bottom:m.bottom+q},{left:r,right:r+window.outerWidth,top:t+117/(h?window.devicePixelRatio:1),bottom:t+window.outerHeight}),v=k.width*k.height;f={area:v,percv:(u.right-u.left)*(u.bottom-u.top)/v};var w=a.d.e(f,b);l=f.percv>=
w}catch(x){l=!1}return{isVisible:l}};a.k.b=function(){return b};a.k.c=function(){var a={};a.dl=Number(b);"number"!==typeof g||isNaN(g)||(a.dm=g);"number"!==typeof c||isNaN(c)||(a.dn=c);return a}})(m);(function(a){function h(a){var b=0,l;return function(){var f=(new n).getTime();f-b>c&&(l=a.apply(this,arguments),b=f);return l}}function g(b,c,l,f){var k=0,g=0,h=0,m=(new n).getTime(),z=!1,u=!1,r,t,v,y=0,w=0,x=0,C=0,Q=!1,I=a.b.a,L;if(0===f)var B="as",D="ag",E="an",J="ck",M="kw",N="ah",O="aj",R="pg",S=
"pf",Q=!0;else 1===f?(B="cc",D="bw",E="bx",J="ci",M="jz",N="bu",O="dj"):2===f&&(B="cg",D="ce",E="cf",J="cj",M="ts",N="ah",O="dk");this.hadOTS=function(){return u};this.hadVideo2SecOTS=function(){return _hadVideo2SecOts};this.getInViewTime=function(){return k};this.visible=function(){return z};this.update=function(g){var A=!1,C=b(g);g.elementRect=C.rect;var B=C.isVisible,D=c(g),E=(new n).getTime(),H=q.max(q.min(E-m,1E3),0);m=E;E=!l||a.focus.pageIsVisible(2===f);if((B=B&&E&&!D)&&z)k+=H,h+=H;else if(B||
z)H=q.round(H/2),k+=H,h+=H;!u&&1E3<=h&&(A=u=!0,t=k,this.timeToView=r=g.counters.query()[N]);"undefined"===typeof v&&(1E3>=g.counters.query().bu?B&&(v=!0):v=!1);if((g.FOLDMEASURABLE=I)&&"undefined"===typeof L&&2!==f&&C.elGeo){var H=a.b.c,D=H.document,J=C.elGeo.threshold*C.elGeo.elHeight;_isBTFCheck=(void 0!==H.pageYOffset?H.pageYOffset:(D.documentElement||D.body.parentNode||D.body).scrollTop)+C.elGeo.foldTop>a.l.a()-J;0<C.elGeo.totalArea&&(L=_isBTFCheck,g.BELOWTHEFOLDAD=L)}g=C.yMinMax;Q&&E&&"undefined"!==
typeof g&&C.elGeo&&0<=g.yMax&&0<=g.yMin&&0<C.visibleArea&&(y=q.max(g.yMax,y),w=q.min(g.yMin,w),x=q.min(1,q.max((y-w)/C.elGeo.elHeight,x)));B||(h=0);z=B;return A};this.getQS=function(a){g>k&&(g=k);a[B]=Number(u);a[D]=k;a[E]=g;"undefined"!==typeof t&&(a[J]=t);"undefined"!==typeof r&&(a[M]=r);"undefined"!==typeof v&&(a[O]=Number(v));if(!0===Q){var b=q.round(100*x),c=q.round(100*C);a[R]=b;a[S]=c;C=x}"undefined"!==typeof L&&(a.ib=Number(L));g=k}}a.l={};var c=150,b={};a.l.a=function(){return I?a.d.i(a.b.c).height:
750};a.l.b=function(c){var e=c.zr;b[e]={};c.viewstats={isBigAd:!1};if(a.d.f()){var l=h(a.d.d),f;f=new g(l,a.f.d,!0,0);b[e].strict=f;l=new g(l,a.f.d,!1,1);b[e].lax=l}!0!==c.isSkin&&a.k&&a.k.b()?(c=new g(a.k.a,a.f.d,!0,2),b[e].pscope=c):a.g&&a.g.j()&&(c=new g(a.g.n,a.f.d,!0,2),b[e].pscope=c)};a.l.c=function(c){var e=b[c.zr],l,f;for(f in e)e.hasOwnProperty(f)&&e[f].update(c)&&(l=!0);l&&a.f.e(c);"width"==a.e.a&&a.e.d();a.m.a(c)&&a.f.f(c)};a.l.d=function(b,c,l){"unefined"==typeof l&&(l=!1);var f=a.l&&
a.l.e(b.zr);b=(a.k&&a.k.b()||a.g&&a.g.b)&&f&&f.pscope.getInViewTime()>=c;c=l?a.d&&a.d.f()&&f&&f.strict&&f.strict.getInViewTime()>=c:a.d&&a.d.f()&&f&&f.lax&&f.lax.getInViewTime()>=c;return a.b.a?c:b};a.l.f=function(a){delete b[a]};a.l.e=function(a){return b[a]};a.l.g=function(a){var c={},l=b[a],f;for(f in l)l.hasOwnProperty(f)&&l[f].getQS(c);(a=t[a])&&a.viewstats.isBigAd&&(c.el=1);return c}})(m);(function(a){a.n={};a.n.a=function(a,g){var c;g.outerHTML?c=g.outerHTML:(c=document.createElement("div"),
c.appendChild(g.cloneNode(!0)),c=c.innerHTML);c=[/flashvars\s*=\s*(".*?"|'.*?')/i.exec(c),/name\s*=\s*["']flashvars["']\s*value\s*=\s*(".*?"|'.*?')/i.exec(c),/value\s*=\s*(".*?"|'.*?')\s*name\s*=\s*["']flashvars["']/i.exec(c),a];for(var b,d,e={},l=0;l<c.length;l++){if((b=c[l])&&"object"===typeof b&&b[1])b=b[1].replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/^"/g,"").replace(/"$/g,"").replace(/^'/g,"").replace(/'$/g,"");else if("string"===typeof b)b=b.split("?")[1];else continue;if(b){b=b.split("&");
for(var f=0;f<b.length;f++)d=b[f].split("="),2>d.length||"function"==d[0].slice(0,8)||(e[d[0]]=[d[1]])}}return e}})(m);(function(a){a.e={};a.e.e={};a.e.a="divs";a.e.e.a=function(h){if(h=a.a.getElementsByClassName("wrapper-holder","*",h))return[h[0]]};a.e.d=function(){var h=a.b.c,g=document,c=g.documentElement,g=g.getElementsByTagName("body")[0];a.e.b=h.innerWidth||c.clientWidth||g.clientWidth};a.e.c=function(h,g,c){if("divs"==a.e.a){if(h._Mt_wIC)return!0;if(h._Mt_wOC)return!1;var b=c.currentTarget,
d=h;for(c=0;1E3>c&&!a.a.f(g,d);c++){if(d==b||null==d)return h._Mt_wOC=!0,!1;d=d.parentElement}return h._Mt_wIC=!0}if("width"==a.e.a){h=g/2;b=a.e.b/2;d=c.clientX;c=c.clientY;var e=a.b.c.scrollY||a.b.c.document.documentElement.scrollTop;return a.e.b>g&&(d>b+h||d<b-h)||90>c+e?!1:!0}}})(m);(function(a){function h(b){var c={window:0,transparent:1,opaque:2,direct:3,gpu:4};if("EMBED"===b.tagName)var e=a.a.getAttribute(b,"wmode");else if("OBJECT"===b.tagName){b=b.getElementsByTagName("param");for(var l=0;l<
b.length;l++){var f=b[l],k=a.a.getAttribute(f,"name"),f=a.a.getAttribute(f,"value");if("wmode"===k){e=f;break}}}return e&&c[e.toLowerCase()]||5}function g(b){var d=b.el,e=b.url,l=b.flashVars,f=b.adIds,k=b.opt_props;this.adContent=b.adContent;(new n).getTime();this.ao=f;this.FIND_AD_TRIES=f.numTries||0;var g;try{if(d){var s=d,m;"DIV"===s.tagName&&((s=d.getElementsByTagName("EMBED")[0])||(s=d.getElementsByTagName("OBJECT")[0]),s||(s=d.getElementsByTagName("IMG")[0]),s||(s=d));if("OBJECT"===s.tagName){for(var q=
0;q<s.children.length;q++)if("movie"===s.children[q].name||"Movie"===s.children[q].name)m=s.children[q].value;s.object&&s.object.Movie?m=s.object.Movie:s.data&&-1!==s.data.indexOf("swf")&&(m=s.data)}"EMBED"!==s.tagName&&"IMG"!==s.tagName||!s.src||(m=s.src);var v=a.n.a(m,s);g={adURL:m,flashVars:v}}else g=!1}catch(r){g=!1}if(g&&g.adURL&&l)for(p in g.flashVars)g.flashVars.hasOwnProperty(p)&&(l[p]=g.flashVars[p]);g&&g.flashVars&&(l=g.flashVars);if("string"!==typeof e||"DIV"===e)e=g&&g.adURL||"-";e&&0!==
e.toLowerCase().indexOf("http:")&&0!==e.toLowerCase().indexOf("https:")&&("/"===e[0]?e=window.location.protocol+"//"+window.location.host+e:(g=window.location.pathname.split("/").slice(0,-1).join("/"),e=window.location.protocol+"//"+window.location.host+"/"+g+(g?"/":"")+e));"IFRAME"!==d.tagName&&"IMG"!==d.tagName&&-1===e.indexOf("googlesyndication")&&(e=e.split("?")[0]);this.zr=f.adNum;t[this.zr]=this;a.m.d(this.zr,[d]);this.ae=e;this.aa=d;this.WINDOW=a.f.a(this.aa);this.INITIAL_WIDTH=d.offsetWidth;
this.INITIAL_HEIGHT=d.offsetHeight;"undefined"===typeof l&&(l={});u.i[D]=!0;this.eg=[];this.ee={};k&&k.IS_PAGE_LEVEL||(this.ed={},a.g.i(this));a.f.g(this);this.ag=l;this.ah=void 0;this.ai=0;this.an=this.am=this.al=this.ak=this.aj=void 0;this.ar=[];this.as=[];this.at=[];this.av=this.au=a.h.a.a.a;this.ax=a.h.a.b.a;this.ay=a.h.a.c.a;this.ba=this.az=a.h.a.d.a;this.bb=a.h.a.e.a;this.by=this.bx=this.bw=this.bv=this.bu=this.bt=this.bs=this.br=this.bq=this.bp=this.bo=this.bm=this.bl=this.bk=this.bi=this.bh=
this.bg=this.bf=this.be=this.bd=this.bc=void 0;this.ca=this.bz=!1;this.cb=this.cu=this.ct=void 0;this.cc=+new n+12E4;this.BEACON_LAST_SENT_AT=+new n;this.cl=this.cm=void 0;this.cn=0;this.ck=a.h.a.f.a;this.cd=!1;this.cy=void 0;this.dt=!1;this.db=void 0;this.cf=this.ce=!1;this.af=Number(this.ef);this.eq=!1;this.ds=this.ch=this.dr=this.cg=0;this.dq=this.bn=void 0;this.IR5={MIN:{x:void 0,y:void 0},MAX:{x:void 0,y:void 0},AREA:0};a.l.b(this);this.dm=0;this.ep=this.dd=!1;this.aq={};this.aq.g=0;this.aq[1]=
0;this.aq[2]=0;this.aq[3]=0;this.aq[13]=0;this.aq[0]=0;this.aq[4]=0;this.aq[5]=0;this.aq[6]=0;this.aq[7]=0;this.aq[9]=0;this.aq[8]=0;this.aq[15]=0;this.aq[16]=0;this.aq[21]=0;this.aq[22]=0;this.aq[23]=0;this.INVIEW_TIME_THRESHHOLDS=[5,10,15,30,60];this.DWELL_TIME_THRESHHOLDS=[5,10,15,30,60];this.an=b.adType||c(d);0===this.an&&(this.WMODE=h(d));a.m.c(this)}function c(a){return"IFRAME"===a.tagName?2:"IMG"===a.tagName?1:"EMBED"===a.tagName||"OBJECT"===a.tagName?0:3}a.m={};a.m.b=function(b,d,e,l,f,k,
m){var s;s=1==arguments.length?arguments[0]:{el:b,url:d,flashVars:l,adIds:f,opt_props:m};if(a.e.e.a&&1==f.skin){var q;q=a.e.e.a(b);s.adContent=q}if(k){if("function"===typeof k)return k(b,d,l,f);new n;k.em=!0;t[k.zr]=k;b[T]=k.zr;b[v]=!0;k.aa=b;k.INITIAL_WIDTH=b.offsetWidth;k.INITIAL_HEIGHT=b.offsetHeight;k.ae=d;k.an=c(b);0===k.an&&(k.WMODE=h(b));k.ag=l||{};a.i.a(k);s={e:0};s.q=k.aq[0]++;a.j.a(k,s);return k}return new g(s)};a.m.c=function(b){b.de=b.ao.startTime;b.RAND=b.ao.rand;(new n).getTime();b.dd=
!0;a.l.c(b);var c={e:0};c.q=b.aq[0]++;a.j.a(b,c);a.i.a(b)};a.m.a=function(b){var c=+new n,e=c-b.BEACON_LAST_SENT_AT;if(0<b.DWELL_TIME_THRESHHOLDS.length){var l=1E3*b.DWELL_TIME_THRESHHOLDS[0];if(b.counters.strictDwell.tCur>=l){b.DWELL_TIME_THRESHHOLDS.shift();var f=b.INVIEW_TIME_THRESHHOLDS.length?b.INVIEW_TIME_THRESHHOLDS[0]:60;if(l<f)return!1;if(5E3<e)return!0}}return 0<b.INVIEW_TIME_THRESHHOLDS.length&&(f=1E3*b.INVIEW_TIME_THRESHHOLDS[0],a.l.d(b,f))?(b.INVIEW_TIME_THRESHHOLDS.shift(),!0):0===b.DWELL_TIME_THRESHHOLDS.length&&
c>b.cc?(b.cc*=2,!0):!1};a.m.d=function(a,c){for(var e=0;e<c.length;e++){var l=c[e];l[T]=a;l[v]=!0}}})(m);(function(a){function h(b,c,l){if(!b)return!1;var f=a.a.e(),f=null!==f&&11>f;if(!f)for(var k=b.getElementsByTagName("embed"),g=0;g<k.length;g++){var h=k[g];if(!0!==h[v]&&-1===h.id.indexOf("moatPx")&&a.a.n(h)&&h.getAttribute("src")){var m=h.getAttribute("src"),f=a.n.a(m,h);return a.m.b(h,m,!1,f,c,l)}}h=b.getElementsByTagName("object");for(g=0;g<h.length;g++)if(k=h[g],a.a.n(k)&&("undefined"===typeof k[v]||
!0!==k[v])&&-1==k.id.indexOf("moatPx")){for(b=0;b<k.children.length;b++)if("movie"===k.children[b].name||"Movie"===k.children[b].name)for(m=k.children[b].value,g=0;g<k.children.length;g++){if(!f&&"EMBED"===k.children[g].tagName){h=k.children[g];if("undefined"!==typeof h[v]&&!0===h[v]||-1!=h.id.indexOf("moatPx"))continue;if(a.a.n(h))return f=a.n.a(m,h),a.m.b(h,m,!1,f,c,l)}if("OBJECT"===k.children[g].tagName&&(h=k.children[g],a.a.n(h)&&!0!==h[v]&&-1===h.id.indexOf("moatPx")))return a.m.b(h,void 0,!1,
void 0,c,l)}k.object&&k.object.Movie?m=k.object.Movie:k.data&&(m=k.data);f=a.n.a(m,k);return a.m.b(k,m,!1,f,c,l)}if(m=a.o.g(b,c,l))return m;m=b.getElementsByTagName("img");for(g=0;g<m.length;g++)if(f=m[g],"undefined"===typeof f[v]||!0!==f[v]){if(a.a.n(f)&&""!==f.src&&-1===document.location.href.indexOf(f.src))return a.m.b(f,f.getAttribute("src"),!1,void 0,c,l);E["1"]=f.offsetWidth+"x"+f.offsetHeight+":"+f.src}return!1}function g(d,e){for(var l=[],f=d.getElementsByTagName("iframe"),g,h=0;h<f.length;h++)if(g=
f[h],!g[v]&&a.a.n(g)){var m=a.p.b(g)?!1:!0;(e===c&&m||e===b&&!m)&&l.push(g)}return l}a.o={};var c=1,b=2;a.o.a=function(b,c,g,f,k){var h=a.o.b,m=a.o.c,n=0,q=function(){c.numTries=n++;return h(b,c,g,f)&&!0},u="format"in c&&"Wallpaper"==c.format;if("skin"in c&&1==c.skin||u){var r=a.b.c.document.body;if(a.b.k&&!a.b.a)return!1;"width"==a.e.a&&a.e.d();c.skin=1;a.g.j=function(){return!1};q=function(){c.numTries++;if(a.e.e.a(r))return a.m.b(r,r.nodeName,!1,void 0,c,g)&&!0}}a.c.f(q,m,500,k)};a.o.g=function(b,
e,l){b=g(b,c);if(b[0])return a.m.b(b[0],b[0].src,!1,void 0,e,l)};a.o.f=function(b,c,g){var f;b=a.o.e(b,a.o.h);for(var k=0;k<b.length;k++)if(f=b[k],f=a.p.b(f))if(f=h(f.documentElement,c,g))return f};a.o.i=function(b,c,g){var f,k;b=a.o.e(b,a.o.h);for(var m=0;m<b.length;m++)if(k=b[m],k=a.p.b(k)){if(f=k.getElementById("flite-1"))if(f=a.m.b(f,f.nodeName,!1,void 0,c,g))return f;if(f=h(k.documentElement,c,g))return f}};a.o.d=h;a.o.b=function(b,c,g,f){var k=a.o.d;if("undefined"===typeof b)return!1;if("HEAD"===
b.tagName){var h=b.parentNode;"HTML"===h.tagName&&(h=h.getElementsByTagName("body"),0<h.length&&(b=h[0]))}return(h=k(b,c,g))||(h=a.o.f(b,c,g))||(ca||f)&&(f=f||a.p.a(b))&&(!a.b.a||"BODY"!==f.nodeName||a.f.a(f)!=a.b.c)&&(h=k(f,c,g))?h:!1};a.o.e=g;a.o.j=c;a.o.h=b;a.o.k=500;a.o.c=20;a.o.l={object:1,embed:1,img:1,iframe:1}})(m);(function(a){function h(a,c){for(var b={},d=a.split("&"),e=0;e<d.length;e++){var l=d[e].split("=");if("string"===typeof l[1]){var f=l,k,h=k=l[1];try{for(var m=0;100>m&&(k=decodeURIComponent(k),
h!=k);m++)h=k}catch(n){}k=k.replace(/(^\s+|\s+$)/g,"");f[1]=k}else l[1]="";b[l[0]]=l[1]}"undefined"!==typeof c&&(b.clientZone="undefined"!==c?c:"");return b}a.q={};a.q.a=function(a){"undefined"===typeof a.startTime&&(a.startTime=(new n).getTime());"undefined"===typeof a.rand&&(a.rand=q.floor(q.random()*q.pow(10,8)));a.adNum=u.zr;u.zr++};a.q.b=function(g){try{var c=g.className,b=g.getAttribute("src");c.split("\n").join(" ");if(-1!==c.indexOf("moatfooter"))return!1;var d=b.split("?");1==d.length&&(d=
b.split("#"));if(1<d.length){var e=h(d[1],"undefined"),c=e,l,f;try{var k=a.p.c(g);if(k&&k.id&&-1<k.id.indexOf("google_ads_iframe")){var m=k.id.match("/[0-9]*/(.*)");m||(m=k.id.match(/google_ads_iframe_[^\/]*\/(.*)/));f=m[1].split(/_[0-9]*$/)[0]}}catch(s){}if(l=f)l=l.split("/"),c.moatClientSlicer2=l[1]||c.moatClientSlicer2;return c}return!1}catch(n){return!1}};a.q.c=function(a){try{var c=a&&a.className.replace("amp;","").split("?")[1];return c&&h(c)}catch(b){return!1}};a.q.d=function(a){try{var c=
zoneRegEx.exec(a.innerHTML);0<c.length&&(zone=c[1]);return zone}catch(b){}};a.q.e=function(a){return(a=unescape(unescape(unescape(unescape(a.innerHTML)))).match(/~fdr=(\d*).*?\/.*?;(\d*)/))?{adid:a&&a[1]||"-",cid:a&&a[2]||"-"}:!1};a.q.f=function(a,c){return c||{}}})(m);(function(a){function h(c,b){var d,e=[],g,f=a.a.d()?2048:7750,k=b||{};g={};for(d in c)c.hasOwnProperty(d)&&(1!=c.e||"x"!==d&&"y"!==d&&"c"!==d?e.push(encodeURIComponent(d)+"="+encodeURIComponent(c[d])):g[d]=c[d].split("a"));d=e.join("&");
var e=f-d.length,h=0;if("undefined"!==typeof g.x){for(var m=0,n=0;n<g.x.length;n++)if(m+=g.x[n].length+(g.y[n]?g.y[n].length:0)+(g.c[n]?g.c[n].length:0),m<e)h++;else break;0<h&&(d+="&x="+g.x.slice(0,h-1).join("a"),d+="&y="+g.y.slice(0,h-1).join("a"),d+="&c="+g.c.slice(0,h-1).join("a"))}for(var q in k)k.hasOwnProperty(q)&&(g="&"+encodeURIComponent(q)+"="+encodeURIComponent(k[q]),g.length+d.length<f&&(d+=g));return d}function g(a,b){for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d])}a.j={};a.j.b=function(c,
b){a.q.a(b);var d={};d.e=c;d.i=J;d.cm=U;if(11===c){var e=[],l;for(l in E)E.hasOwnProperty(l)&&e.push(l+"="+E[l]);d.k=e.join("&")}d.e in Z||(d.bq=a.b.e,d.f=Number(!M),d.j=a.b.b,d.o=3,d.t=b.startTime,d.de=b.rand,d.m=0,d.ar=$,a.a.t(d,"ai",u.z),d.q=u.m++,d.cb=I?1:0,d.cu=V,d.r=a.g.a,g(d,a.focus.getQueryString()),a.q.f(b,d),"undefined"!==typeof b&&(d.d=b.moatClientLevel1+":"+b.moatClientLevel2+":"+b.moatClientLevel3+":"+b.moatClientLevel4,d.bo=b.moatClientSlicer1,d.bd=b.moatClientSlicer2),d.ac=1,d.it=a.o.k,
d=h(d),u.yh.yi(d+"&cs=0",W,aa))};a.j.c=function(c){!0!==c.em&&(delete t[c.zr],clearTimeout(c.cc),a.o.a(B.parentNode,c.ao,c))};a.j.a=function(c,b){if(!c||!0===c.ep)return!1;if(!a.f.h(c))return a.f.i(c),!1;if("undefined"!==typeof c.ao&&(2!==c.an||1!==b.e&&3!==b.e)&&!(b.e in Z)){b.lo=c.FIND_AD_TRIES;b.ak=c.ae;c.ah&&(b.a=c.ah);var d=c.ag,e={};if(9===b.e&&2===b.q||25===b.e){for(var l in d)d.hasOwnProperty(l)&&""!==l&&"undefined"!==typeof d[l]&&-1===l.indexOf("dvContains")&&-1===l.indexOf("indexOf")&&-1===
l.toLowerCase().indexOf("clicktag")&&(e["z"+l]=d[l]);b.e=25}0===c.an&&(b.dc=c.WMODE);0!==b.e&&a.f.j(c);c.bi>c.bg&&(c.bg=c.bi);c.bm>c.bk&&(c.bk=c.bm);b.i=J;b.bq=a.b.e;b.g=c.aq.g++;d=c.INITIAL_WIDTH;b.h=c.INITIAL_HEIGHT;b.w=d;b.cm=U;b.f=Number(!M);b.j=a.b.b;b.o=3;b.t=c.de;b.de=c.RAND;b.cu=V;b.m=b.m||a.a.g(c);b.ar=$;b.cb=I?1:0;b.r=a.g.a;g(b,a.k.c());a.k&&a.k.b()?b.ch=1:a.g&&a.g.b?(b.ch=1,b.ct=a.g.c,"undefined"!==typeof a.g.o&&c&&c.ao&&c.ao.startTime&&!isNaN(c.ao.startTime)&&(d=a.g.o-c.ao.startTime,b.fg=
0<=d?d:0)):b.ch=0;g(b,a.l.g(c.zr));g(b,a.focus.getQueryString());g(b,c.counters.getQs());a.a.t(b,"ai",u.z);a.a.t(b,"ap",c.cb);a.a.t(b,"ax",c.bg);a.a.t(b,"ay",c.bi);a.a.t(b,"az",c.bk);a.a.t(b,"ba",c.bm);a.a.t(b,"aw",c.bc);a.a.t(b,"bg",c.bd);a.a.t(b,"be",c.be);a.a.t(b,"bc",c.bw);a.a.t(b,"bf",c.by);a.a.t(b,"bh",c.bx);a.a.t(b,"bz",c.cu);b.cl=q.round(100*c.IR5.AREA/(b.w*b.h));b.au=c.aq[2]-1;b.av=c.aq[3]-1;b.by=c.aq[23]-1;b.at=c.dm;a.q.f(c.ao,b);b.d=c.ao.moatClientLevel1+":"+c.ao.moatClientLevel2+":"+c.ao.moatClientLevel3+
":"+c.ao.moatClientLevel4;b.bo=c.ao.moatClientSlicer1;b.bd=c.ao.moatClientSlicer2;b.ab=c.an;b.ac=1;b.it=a.o.k;c.bi=c.bg;c.bm=c.bk;e=h(b,e);u.yh.yi(e+"&cs=0",W,aa)}};a.j.d=function(a,b){if(2!==a.an||1!==b.e&&3!==b.e){var d=da;(new Image(1,1)).src=d}};a.j.e=function(a,b){return h(a,b)};a.j.f=function(c){var b={e:16};b.q=c.aq[16]++;a.j.a(c,b)}})(m);(function(a){function h(a,b,d,e){var g=(new n).getTime();this.tLast=this.tCur=0;this.update=function(b){var d=(new n).getTime();a(b)&&(b=q.min(d-g,1E3),this.tCur+=
b,"number"===typeof e&&this.tCur>e&&(this.tCur=e));g=d};this.getQs=function(a){data=this.query(a);this.tLast=this.tCur;return data};this.query=function(a){a=a||{};this.tLast>this.tCur&&(this.tLast=this.tCur);a[b]=this.tCur;a[d]=this.tLast;return a}}function g(){if(a.focus.pageIsVisible()&&"undefined"===typeof u.z){u.z=new n-V;a:{var c=void 0,b;for(b in t)if(t.hasOwnProperty(b)&&(c=t[b])&&"undefined"!==typeof c.ao){if(c.ce)break a;var d={e:4};d.q=c.aq[4]++;d.ai=u.z;a.j.a(c,d);c.ce=!0}a.c.c(y,"scroll",
g,"onScroll")}}}a.f={};a.f.k=function(){a.c.b(y,"scroll",g,"onScroll");a.focus.setFocusListeners()};a.f.h=function(c,b){try{var d=c.aa;b=b||c.WINDOW||a.f.a(d);return d&&b&&(d.parentNode||d.parentElement)?!0:!1}catch(e){return!1}};a.f.j=function(){var c,b;for(b in t)t.hasOwnProperty(b)&&(c=t[b],a.f.h(c,c.WINDOW)?c.counters.update(c):a.f.i(c))};a.f.i=function(c){clearTimeout(c.cc);c.ep=!0;delete t[c.zr];a.i.a(c,"remove");a.l.f(c.zr);c.aa=null};a.f.e=function(c){c.eq||(c.eq=!0);var b={e:5};b.q=c.aq[5]++;
a.j.a(c,b)};a.f.d=function(c){var b;if(1==c.ao.skin)return!1;c.elementRect?(b=c.elementRect.right-c.elementRect.left,c=c.elementRect.bottom-c.elementRect.top):(b=c.aa.offsetWidth,c=c.aa.offsetHeight);return 3>b||3>c||a.focus.pageIsPrerendered()?!0:!1};a.f.l=function(a){var b=1;screen.deviceXDPI?b=screen.deviceXDPI/screen.systemXDPI:a.devicePixelRatio&&"undefined"!==typeof a.mozInnerScreenX&&(b=a.devicePixelRatio);return{w:b*screen.width,h:b*screen.height}};a.f.a=function(a){try{var b=a&&a.ownerDocument;
return b&&(b.defaultView||b.parentWindow)}catch(d){return!1}};a.f.g=function(c){c.counters={};c.counters.laxDwell=new h(function(){return!a.focus.pageIsPrerendered()},"bu","cd");c.counters.strictDwell=new h(a.focus.pageIsVisible,"ah","am");c.counters.query=function(){var a={},c;for(c in this)if(this.hasOwnProperty(c)){var e=this[c];"function"===typeof e.query&&e.query(a)}return a};c.counters.getQs=function(){var a={},c;for(c in this)if(this.hasOwnProperty(c)){var e=this[c];"function"===typeof e.getQs&&
e.getQs(a)}return a};c.counters.update=function(a){for(var c in this)if(this.hasOwnProperty(c)){var e=this[c];"function"===typeof e.update&&e.update(a)}}};a.f.b=function(c,b){for(var d=[],e,g=0;g<ea;g++)if(b!=b.parent){if(e=a.p.c(c,b))d.push(e);else break;b=b.parent;c=e}else break;return d};a.f.m=function(){for(var c in t)if(t.hasOwnProperty(c)){var b=t[c];if(b){var d={e:21};d.q=b.aq[21]++;a.j.a(b,d)}}};a.f.f=function(c){var b={e:9};b.q=c.aq[9]++;c.BEACON_LAST_SENT_AT=+new n;a.j.a(c,b)}})(m);(function(a){a.p=
{};a.p.b=function(h){try{if(h.moatHostileIframe)return null;if(h.src&&h.src.slice&&"http"===h.src.slice(0,4)&&a.a.h(h.src)!=a.a.h(y.location.toString()))return h.moatHostileIframe=!0,null;var g=h&&(h.contentDocument||h.contentWindow&&h.contentWindow.document);if(g&&"string"===typeof g.location.toString())return g;h.moatHostileIframe=!0;return null}catch(c){return h.moatHostileIframe=!0,null}};a.p.c=function(h,g){g=g||a.f.a(h);try{return g&&g.frameElement}catch(c){return!1}};a.p.a=function(h){return(h=
a.p.c(h))?h.parentNode:null}})(m);(function(a){a.r={};a.r.a=function(h){h[a.b.d]=h[a.b.d]||{zs:!1,zr:0,h:0,m:0,i:{}};var g=h[a.b.d];"undefined"===typeof g.v&&(g.v=M?"undefined"===typeof h.document.hasFocus||I?!0:h.document.hasFocus():!0);g.ye||(g.ye=function(){this.v=!0});g.yd||(g.yd=function(){this.v=!1})}})(m);(function(a){var h=function(a,c){function b(a,b,c){a&&f.push({qs:a,jsd:b,fld:c});if(0===k&&0<f.length)if(k+=1,a=f.shift(),a.fld&&q&&n&&n.sendMessage)try{n.sendMessage(a)}catch(d){q=!1,e(a)}else e(a)}
function d(){try{return new u(1,1)}catch(a){var b=window.document.createElement("img");b.height=1;b.width=1;return b}}function e(a){var b=d();b.toSend=a;b.onerror=function(){var a=this.toSend;m+=1;var b=(a.jsd+"/pixel.gif?"+a.qs).length;2>m?e(a):v&&b>y&&h()};b.onload=function(){h()};b.src=a.jsd+"/pixel.gif?"+a.qs}function h(){0<k&&(k-=1,b())}var f=[],k=0,m=0,n=!1,q=!1,u,t=c[a];t.yh={};t=t.yh;u=c.Image;t.yi=function(a,c,d){b(a,c,d)};t.yk=function(b){n=!0;var c=a+".yh.",d={},e;try{e=window.location.protocol}catch(f){e=
document.createElement("a"),e.href="",e=e.protocol}d.src="https:"===e?"https://z.moatads.com/swf/MessageSenderV2.swf":"http://s.moatads.com/swf/MessageSenderV2.swf";d.flashVars="r="+c+"zb&s="+c+"zc&e="+c+"zd&td="+b;return d};t.yj=function(){return!1===n};t.zb=function(){try{if(!0===n){var a=c.document.getElementById("moatMessageSender");a&&!a.sendMessage&&(a=c.document.getElementById("moatMessageSenderEmbed"));a&&a.sendMessage&&(q=!0,n=a)}}catch(b){}};t.zc=function(){try{h()}catch(a){}};t.zd=function(a){try{q=
!1,a&&a.jsd&&f.push(a),h()}catch(b){}};var r,v,y=2083;try{r=document.createElement("div"),r.innerHTML="\x3c!--[if IE 8]>x<![endif]--\x3e",v="x"===r.innerHTML}catch(B){v=!1}}.toString();a.s={};a.s.a=function(g){if(!u.yh)if("undefined"!==typeof g.eval)g.eval("("+h+")('"+a.b.d+"',window)");else{var c=g.document.createElement("script");c.type="text/javascript";c.text="("+h+")('"+a.b.d+"',window)";g.document.body.insertBefore(c,g.document.body.childNodes[0])}}})(m);if(m.a.l())return!1;var J="USATODAYSMG1",
ba="usatodaysportsmediagroup156759167425",$="099702a-clean",V=m.b.i,v="moatFound"+J,T="__moat__"+J,U=function(a,h){for(var g=[a],c=1;c<=h;c++)g.push(a+c),g.push(a-c);return g[q.floor(q.random()*g.length)]}(16,2);if(0!=q.floor(q.random()*U))return!1;var da="",ca=m.b.l,M=m.b.a,aa="afs.moatads.com",W,D=0,R,S,E={},ea=50,N=[],O=[],t={},Z={15:"",12:"",6:"",7:""};W="//v3.moatads.com";var y=m.b.c;m.r.a(y);var u=y[m.b.d];window[m.b.d]=u;m.s.a(y);m.a.h(M?y.location.href:y.document.referrer)||m.a.h(window.location.href);
var B=m.a.q();if(!B)return!1;m.t=B;m.a.r(B);var I=m.a.i();(function(a){D=u.h;u.h++;u.i[D]=!1;!1===u.zs&&(m.f.k(),u.zs=!0);m.c.d(function(){m.f.j();for(var a in t)t.hasOwnProperty(a)&&m.l.c(t[a])},200);var h=!1;m.c.b(window,"unload",function(){h||(m.f.m(),h=!0)},!1);m.c.b(window,"beforeunload",function(){h||(m.f.m(),h=!0)},!1);m.c.d(m.i.b,100);m.a.d()&&m.c.e(X,3E5);"undefined"===typeof a&&(a=m.q.b(B));var g=B.parentNode;m.c.e(function(){!1===u.i[D]&&(m.j.b(11,a),X())},1E4);m.j.b(17,a);m.o.a(g,a)})()})(Date,
Math)}catch(e$$49){var msg=e$$49.name+" in closure: "+e$$49.message+", stack="+e$$49.stack;try{var pxSrc="//v3.moatads.com/pixel.gif?e=24&d=data%3Adata%3Adata%3Adata&i="+escape("USATODAYSMG1")+"&ac=1&k="+escape(msg)+"&ar="+escape("099702a-clean")+"&j="+escape(document.referrer)+"&cs="+(new Date).getTime(),px=new Image(1,1);px.src=pxSrc}catch(e$$50){}};
