(function(){if(typeof GEL.remoting!="undefined")GEL.log("It appears as if the GEL.remoting namespace has all ready loaded");else{var i=GEL.namespace("remoting"),f=document.getElementsByTagName("HEAD")[0],h=GEL.Element.Base.prototype;h.contentCacheTime=0;h.contentLastUpdate=null;h.setContentProvider=function(b){this.contentProvider=b;this.contentProvider.on("dataReady",function(c){return function(){c.contentReadyHandler(this)}}(this)).on("ready",function(c){return function(){c.isfetching=false;c.fire("contentReady",
c);c.forceRender()}}(this));return this};h.setContentUrl=function(){function b(a){a=new i.Fetcher.Ajax({url:a});a=new i.Provider.DOM(a);a.filter=new i.Provider.DOM.DOMFilter.TagExtractor(a.filter,{SCRIPT:f,STYLE:f});a.filter=new i.Provider.DOM.DOMFilter.BannerFinder(a.filter);return a}function c(a,e){a=new i.Fetcher.DocumentOverwriter({url:e,attachTo:a});a=new i.Provider.DOM(a);a.filter=new i.Provider.DOM.DOMFilter.TagStripper(a.filter,["SCRIPT"]);a.filter=new i.Provider.DOM.DOMFilter.TagExtractor(a.filter,
{STYLE:f});return a}return function(a,e){e=e||"";var d=null;d=a.endsWith(".js")||e.toLowerCase()=="script"?c(this,a):b(a);this.setContentProvider(d);return d}}();h.updateRemoteContent=function(){if(!(typeof this.contentProvider=="undefined"||!this.contentProvider||this.isfetching)){var b=0;if(this.contentCacheTime<=0&&this.contentLastUpdate)return false;if(this.contentLastUpdate)b=(new Date).getTime()-this.contentLastUpdate.getTime();if(!(b>0&&b/1E3<this.contentCacheTime)){this.fire("preContentUpdate",
this);this.contentProvider.fetcher.attach();return this.isfetching=true}}};h.contentReadyHandler=function(b){this.appendChild(b.getData());this.contentLastUpdate=new Date;this.fire("contentUpdated",this)};GEL.remoting.Provider=function(b){GEL.remoting.Provider.superclass.constructor.apply(this,arguments);this.setDataHandlers(this);typeof b!="undefined"&&b&&this.setFetcher(b);this.data=null};GEL.extend(GEL.remoting.Provider,GEL.event.Publisher,{getFetcher:function(){return this.fetcher},setFetcher:function(b){this.fetcher=
b;this.addContentHandlers()},addContentHandlers:function(){this.fetcher.on("dataAvailable",this.onDataAvailable);this.fetcher.on("ready",this.onDataComplete)},onDataAvailable:function(){this.fire("dataReady",this)},onDataComplete:function(){this.fire("ready",this)},getData:function(){return this.data},setData:function(b){return this.data=b}});GEL.remoting.Provider.Json=function(){var b=GEL.remoting.Provider.Json.superclass;GEL.remoting.Provider.Json.superclass.constructor.apply(this,arguments);this.data=
{};this._superObj=b};GEL.extend(GEL.remoting.Provider.Json,GEL.remoting.Provider,{setDataHandlers:function(b){this.onDataAvailable=function(){var c=this.getContent();if(!(typeof c=="undefined"||!c))try{b.data=eval(c)}catch(a){throw new Error('Error interpreting data "'+c+'" as JSON: "'+a.message+'"');}};this.onDataComplete=function(){return b.onDataAvailable.apply(this,arguments)}}});GEL.remoting.Provider.DOM=function(){var b=GEL.remoting.Provider.DOM.superclass;GEL.remoting.Provider.DOM.superclass.constructor.apply(this,
arguments);this._superObj=b;this.data=document.createDocumentFragment();this.filter=new GEL.remoting.Provider.DOM.DOMFilter};GEL.extend(GEL.remoting.Provider.DOM,GEL.remoting.Provider,{setDataHandlers:function(b){this.onDataAvailable=function(){var c=this.getData(),a=document.createDocumentFragment(),e=document.createElement("DIV");c=b.filter.filterHTML(c);if(GEL.env.ua.ie){e.style.display="none";e.style.visibility="hidden";document.body.appendChild(e)}e.innerHTML=c;for(b.filter.filterDOM(e);e.childNodes.length>
0;)a.appendChild(e.childNodes[0]);b.setData(a);e.parentNode&&e.parentNode.removeChild(e);b.fire("dataReady",b);b.filter.filterPostAttach(a)};this.onDataComplete=function(){this.off(arguments[0],arguments.callee);b.fire("ready",b);return b}},addFilter:function(b){this.filter=new b(this.filter)}});GEL.remoting.Provider.DOM.DOMFilter=function(){this.filterHTML=function(b){return b};this.filterDOM=function(b){return b};this.filterPostAttach=function(b){return b}}}})();
(function(){var i={},f=function(h){h in i||(i[h]=new RegExp("<(/?)s*"+h,"ig"));return i[h]};GEL.remoting.Provider.DOM.DOMFilter.TagStripper=function(h,b){this.decorating=h;var c={};for(h=0;h<b.length;h++)c[b[h]]=true;this.addTag=function(a){c[a]=true};this.removeTag=function(a){delete c[a]};this.filterPostAttach=function(a){return this.decorating.filterPostAttach(a)};this.filterHTML=function(){if(!GEL.env.ua.ie)return function(a){return this.decorating.filterHTML(a)};return function(a){a=a;var e,
d;for(e in c){d=f(e);a=a.replace(d,"<$1COMMENT")}return this.decorating.filterHTML(a)}}();this.filterDOM=function(a){var e=null,d="",j;for(d in c){d=GEL.env.ua.ie?"COMMENT":d;for(e=a.getElementsByTagName(d);e.length>0;){j=e[0];if(j.parentNode)j.parentNode.removeChild(j);else"removeChild"in a&&a.removeChild(j)}}return this.decorating.filterDOM(a)}}})();
GEL.remoting.Provider.DOM.DOMFilter.BannerFinder=function(i){function f(){GEL.use("widget.AdBanner",function(){b=GEL.thepage.bannerLocator});return{findBanners:function(){return[]}}}var h=[],b=GEL.thepage.bannerLocator||f();this.decorating=i;this.filterHTML=function(c){return this.decorating.filterHTML(c)};this.filterDOM=function(c){var a;a=b.findBanners(c);c=this.decorating.filterDOM(c);for(var e=0;e<a.length;e++)h.push(a[e]);return c};this.filterPostAttach=function(){for(var c;c=h.shift();)c.loadBanner()}};
GEL.remoting.Provider.DOM.DOMFilter.TagExtractor=function(i,f){function h(b,c,a){b=b.getElementsByTagName(c);for(var e=0,d=null;b.length>0;){d=b[0];d.parentNode.removeChild(d);if(!GEL.env.ua.gecko&&c.toUpperCase()=="SCRIPT"){_newNode=d.cloneNode(false);_newNode.text=d.innerHTML;d=_newNode}a.appendChild(d);e++}return e}this.decorating=i;this.filterHTML=function(){if(!GEL.env.ua.ie)return function(){return this.decorating.filterHTML.apply(this.decorating,arguments)};return function(b){b='<span style="display:none">p</span>'+
b;return this.decorating.filterHTML.apply(this.decorating,arguments)}}();this.filterDOM=function(b){var c,a;GEL.env.ua.ie&&b.removeChild(b.childNodes[0]);for(a in f){c=f[a];h(b,a,c)}return this.decorating.filterDOM(b)};this.filterPostAttach=function(b){return this.decorating.filterPostAttach(b)}};
(function(){if(!(typeof GEL.remoting.Fetcher!="undefined"&&GEL.remoting.Fetcher)){GEL.remoting.Fetcher=function(i,f){function h(){var a,e;for(a in c){e=c[a];switch(a){case "onComplete":b.on("ready",e);break;case "onError":b.on("error",e);break;case "url":b.setUrl(e);break;default:break}}}var b=this,c=f||{};GEL.remoting.Fetcher.superclass.constructor.apply(this,arguments);h();this._content=""};GEL.extend(GEL.remoting.Fetcher,GEL.Element.Base,{setUrl:function(i){this._url=i},getUrl:function(){var i=
typeof this._url;if(i=="string")return this._url;else if(i=="function")return this._url();else if(i=="object"&&this._url.getUrl)return this._url.getUrl()},getContent:function(){return this._content},getData:function(){return this.getContent()},setData:function(){return this.setContent.apply(this,arguments)},setContent:function(i){return this._content=i},appendContent:function(i){this._content+=i;return this._content}})}})();
(function(){var i=["MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"];GEL.remoting.Fetcher.Ajax=function(f){var h=GEL.remoting.Fetcher.Ajax.superclass.constructor,b="";this.config={};this.transitionMapOverrides={attach:GEL.Element.StateManager.Attached.XHR,preattach:GEL.Element.StateManager.PreAttach.Null};h.call(this,null,f);this.on("ready",function(c){return function(){c.fire("dataAvailable",c)}}(this));this.attacher=new GEL.Element.XHRAttacher;this.config.method=f.method||"POST";this.config.async=
"async"in f?f.async:true;this.getSendData=function(){return b};this.setSendData=function(c){if(typeof c=="string")b=c;else if(c instanceof Array)b=c.join("\r\n");else if(typeof c=="object")b=GEL.objectUtil.join(c,"=","\r\n");return this}};GEL.extend(GEL.remoting.Fetcher.Ajax,GEL.remoting.Fetcher,{setAttacher:function(){},isLocal:function(){return false},makeElement:function(){if(typeof window.XMLHttpRequest!="undefined")_el=new XMLHttpRequest;else{for(var f=0;f<i.length;f++)try{_el=new ActiveXObject(i[f]);
break}catch(h){}if(!_el)throw new Error("Unable to create XML HTTP Request");}return _el}});GEL.Element.register("XHR",GEL.remoting.Fetcher.Ajax);GEL.Element.StateManager.Attached.XHR=function(){GEL.Element.StateManager.Attached.XHR.superclass.constructor.apply(this,arguments)};GEL.extend(GEL.Element.StateManager.Attached.XHR,GEL.Element.StateManager.Attached,{installTransitionDetector:function(){var f=this,h=this.gelement.getElement();h.onreadystatechange=function(){this.readyState<4||f.stateTransitionHandler(h)}},
stateTransitionHandler:function(f){this.isready=this.isattach=true;this.gelement.setContent(f.responseText);f.onreadystatechange=null;this.fire("loadstatetransition",this,{oldstate:"attach",newstate:"ready",element:f,gelement:this.gelement});this.gelement.setStateManager(new GEL.Element.StateManager.Ready(this.gelement))}});GEL.Element.XHRAttacher=function(){GEL.Element.XHRAttacher.superclass.constructor.apply(this,arguments)};GEL.extend(GEL.Element.XHRAttacher,GEL.Element.Attacher,{attachNodeToDOM:function(f){var h=
f.getElement();if(!(f instanceof GEL.remoting.Fetcher.Ajax))throw new Error("give me a good gelement");h.open(f.config.method,f.getUrl(),f.config.async);h.send(f.getSendData());if(!f.config.async)for(;!f.isready;)f.stateManager.stateTransitionHandler(h);return h}})})();
(function(){GEL.remoting.Fetcher.IFrame=function(i){var f=GEL.remoting.Fetcher.IFrame.superclass.constructor,h=null;h=document.createElement("IFRAME");f.call(this,h,i);this.on("ready",function(){var b="",c=this.getElement();if(c.contentDocument)b=c.contentDocument.body.innerHTML;else if(c.contentWindow)b=c.contentWindow.document.body.innerHTML;this.setContent(b)});this.setStateManager(new GEL.Element.StateManager.Attached(this));this.hide()};GEL.extend(GEL.remoting.Fetcher.IFrame,GEL.remoting.Fetcher,
{isLocal:function(){return false}})})();
(function(){function i(){i.superclass.constructor.call(this);GEL.namespace("config.overwriter");var a=[],e=null,d=null,j=null,o=this;this.begin=function(){e=b.write;d=b.writeln;j=new f;b.write=function(m){m=m instanceof Array?m:m.split("");var k=null;k=j.findTags(m);if(k.length>0)a[a.length]=k;if(j.tags.length>0){o.fire("tagFound",o,{tags:j.tags});j.tags=[]}m.length>0&&b.write(m)};b.writeln=function(m){return b.write(m+"\n")}};this.finish=function(){b.write=e;b.writeln=d;o=j=null};this.read=function(){return function(m){for(var k=
m.length,n=[],g,l=0;l<k;l++){g=m[l];n[n.length]=g instanceof Array?arguments.callee(g):g}return n.join("")}(a)};this.flush=function(){var m=function(k){for(var n=k.length,g=[],l,q=0;q<n;q++){l=k[q];g[g.length]=l instanceof Array?arguments.callee(l):l}return g.join("")}(a);a=[];return m}}function f(){function a(k){var n=j.tag.tagName.toUpperCase(),g=0,l=0;if(j.tag.close&&d&&n===d.tagName){g=k.length+3+j.tag.tagName.length;l=d.body.length;d.body=d.body.substr(0,l-g);k=d.tagAttributeObj=f.parseAttributes(d.tagAttributes);
if("src"in k&&(!k.src||!k.src.match(m))){d=null;return false}o.tags.push(d);d=null;return true}else if(!d&&!j.tag.close){d=GEL.objectUtil.copy(j.tag);d.body=k.join("");return false}}var e=GEL.namespace("config.overwriter"),d=null,j=this.finder=new f.tagfinder,o=this,m=/[A-Z]/i;(function(){for(var k="img,area,base,basefont,br,hr,input,img,link,meta".split(","),n=k.length,g=0,l={};g<n;g++)l[k[g].toUpperCase()]=true;return l})();this.tags=[];this.findTags=function(k){var n=[],g=[];if(d)d.body+=k.join("");
do{n=j.find(k);g[g.length]=n;if(j.tag.complete&&a(k)){if(e.debug){k=this.tags[0];GEL.log("Found complete tag "+GEL.objectUtil.join(k,"= ","\n\t")+GEL.objectUtil.join(k.tagAttributeObj," -=-= ","\n\t\t"))}j.reset();return g}else j.tag.complete&&j.reset()}while(k.length>0);return g}}function h(a){function e(){x=false;r.fire("ready",r);j()}function d(s){this.off("ready",arguments.callee);this.off("error",arguments.callee);document.getElementById=document._getElById;u.finish();if(s!=="ready"){GEL.log(r+
" <-- Script ( "+this+" ) finished in shameful "+s);r.fire("error",r);return false}else{o();w&&t.attach()}}function j(){t.off("ready",e);l=t=u=r=null}function o(){var s=u.flush();r.setContent(s);return r.fire("dataAvailable",r)}function m(s,p){s=p.tags;var v=p=null;for(p=null;p=s.shift();)if(p.tagName.toLowerCase()==="script"){v=GEL.ement("SCRIPT",p.tagAttributeObj);v.attachToElement=y;if(v.getElement().defer)q(window,"load",function(z){return function(){GEL.log("attaching defered script");z.attach()}}(v));
else if(v.isLocal()){v.setScriptText(p.body);v.executeScript()}else{p=(new h({element:v,attachTo:y})).on("dataAvailable",k);t.addElement(p)}}v=p=p=null}function k(){r.fire("dataAvailable",this)}var n=h.superclass.constructor,g=GEL.namespace("config.overwriter"),l=a.element||GEL.ement("SCRIPT",{}),q=GEL.elementUtil.attachEventListener,w="autoAttachChildren"in a?a.autoAttachChildren:"autoAttach"in g?g.autoAttach:true,t=new GEL.MetaElement,y=a.attachTo||c,x=false,r=this,u=null;this.transitionMapOverrides=
{preattach:GEL.Element.StateManager.PreAttach.Null};l.attachToElement=y;this.gelScript=l;n.call(this);"url"in a&&this.setUrl(a.url);t.setAttacher("sync");t.on("ready",e);this.loadScripts=function(){t.attach()};this.fetch=function(){if(x)return true;x=true;u=new i;if(this.getUrl()){l.isLocal(false);l.setSource(this.getUrl())}document._getElById=document.getElementById;document.getElementById=function(s){var p=document._getElById(s);if(p)return p;o();return document._getElById(s)};u.on("tagFound",m);
u.name="Overwriter:"+this.toString();this.fire("preattach",this);u.begin();l.on("ready",d);l.on("error",d);l.executeScript()};this.toString=function(){return l.toString()}}if(typeof GEL.remoting.Fetcher.DocumentOverwriter!="function"){var b=document,c=b.getElementsByTagName("HEAD")[0];window.Overwriter=i;GEL.extend(i,GEL.event.Publisher);window.TagParser=f;f.tagfinder=window.tagfinder=function(){function a(){function o(){this.tag={tagName:"",tagAttributes:"",started:false,tagComplete:false,close:false,
complete:false};m=false}GEL.namespace("config.overwriter");var m=false,k="";this.reset=o;this.reset();this.find=function(n){var g=null,l=k,q="",w=false,t=false,y=false,x=false,r="";w=0;var u=k.length;g=0;l+=n.join("");for(d.lastIndex=0;g=d.exec(l);){y=g[1];q=g[2].toUpperCase();r=g[4];x=g[5];t=g[5];w=g[3]||g[5];if(!w||w.match(j)&&!t){if(g[0].length==g[4].length+1)return n.splice(0,g.index+g.length);k=l.substr(g.index,g[0].length);m=true;return n.splice(0,n.length)}else if(x&&q){k="";m=false;w=g[0].length;
g=g.index+w-u;if(q in e){if(y){this.tag.tagName=q;this.tag.close=true}else{this.tag.tagName=q;this.tag.tagAttributes=r}this.tag.complete=true;return n.splice(0,g)}}else if(g[0].length>2&&!q)return n.splice(0,g.index+1);else if(q)m=true}if(m)k=l;return n.splice(0,n.length)}}var e={SCRIPT:true,IFRAME:true},d=new RegExp("<(/?)([A-Za-z]*)(\\s*)([^>]*)(>)?","mg"),j=/[A-Z]/i;return a}();f.parseAttributes=function(){var a=/([^=\s]+)(\s*=\s*((\"([^\"]*)\")|(\'([^\']*)\')|[^>\s]+))?/gm;return function(e){var d,
j="";d="";var o={};for(a.lastIndex=0;d=a.exec(e);){j=d[1].toLowerCase();d=d[7]||d[6]||d[5]||d[4]||d[3];o[j]=d}return o}}();GEL.extend(h,GEL.event.Publisher,{attach:function(){return this.fetch()},setUrl:function(a){this._url=a},getUrl:function(){var a=typeof this._url;if(a=="string")return this._url;else if(a=="function")return this._url();else if(a=="object"&&this._url.getUrl)return this._url.getUrl()},getContent:function(){return this._content},getData:function(){return this.getContent()},setData:function(){return this.setContent.apply(this,
arguments)},setContent:function(a){return this._content=a},appendContent:function(a){this._content+=a;return this._content}});(function(){function a(){if(!e){var o=d.shift();if(o){e=true;o.on("ready",function(){this.off(arguments[0],arguments.callee);e=false;setTimeout(a,10)});j.setLoadHandlerQueueing(true);o.attach()}else{j.fireLoadHandlers();j.setLoadHandlerQueueing(false)}}}var e=false,d=[],j=GEL.thepage;GEL.remoting.Fetcher.DocumentOverwriter=function(){var o=GEL.remoting.Fetcher.DocumentOverwriter.superclass;
GEL.remoting.Fetcher.DocumentOverwriter.superclass.constructor.apply(this,arguments);this.attach=function(){this.attach=o.attach;d.push(this);e||a()}};GEL.extend(GEL.remoting.Fetcher.DocumentOverwriter,h)})()}})();