/*{"k":"1.7.2","created":"2014-03-24T16:05:06Z","version":"24883181","mac":"1:202e7c5998760fbe03e05c7c48e5a161d38b460e442ef7adf13ea3fd4b822500"}*/
/*
 * For font license information, see the CSS file loaded by this JavaScript.
 */
;(function(window,document,undefined){
var j=!0,k=null,l=!1;function m(a){return function(){return this[a]}}var ba=this;function ca(a,b){var c=a.split("."),d=ba;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&void 0!==b?d[e]=b:d=d[e]?d[e]:d[e]={}}function da(a,b,c){return a.call.apply(a.bind,arguments)}
function ea(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function n(a,b,c){n=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?da:ea;return n.apply(k,arguments)}var fa=Date.now||function(){return+new Date};
function ga(a,b){this.Y=a;this.P=b||a;this.D=this.P.document}ga.prototype.createElement=function(a,b,c){a=this.D.createElement(a);if(b)for(var d in b)b.hasOwnProperty(d)&&("style"==d?a.style.cssText=b[d]:a.setAttribute(d,b[d]));c&&a.appendChild(this.D.createTextNode(c));return a};function q(a,b,c){a=a.D.getElementsByTagName(b)[0];a||(a=document.documentElement);a&&a.lastChild&&a.insertBefore(c,a.lastChild)}function ha(a,b){function c(){a.D.body?b():setTimeout(c,0)}c()}
function r(a,b){for(var c=a.className.split(/\s+/),d=0,e=c.length;d<e;d++)if(c[d]==b)return;c.push(b);a.className=c.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}function s(a,b){for(var c=a.className.split(/\s+/),d=[],e=0,f=c.length;e<f;e++)c[e]!=b&&d.push(c[e]);a.className=d.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}function ia(a,b){for(var c=a.className.split(/\s+/),d=0,e=c.length;d<e;d++)if(c[d]==b)return j;return l}
function ja(a){var b=a.P.location.protocol;"about:"==b&&(b=a.Y.location.protocol);return"https:"==b?"https:":"http:"}
function ka(a,b,c){var d=a.D.getElementsByTagName("head")[0];if(d){var e=a.createElement("script",{src:b}),f=l;e.onload=e.onreadystatechange=function(){if(!f&&(!this.readyState||"loaded"==this.readyState||"complete"==this.readyState))f=j,c&&c(k),e.onload=e.onreadystatechange=k,"HEAD"==e.parentNode.tagName&&d.removeChild(e)};d.appendChild(e);window.setTimeout(function(){f||(f=j,c&&c(Error("Script load timeout")))},5E3)}}function t(a,b,c){this.Oa=a;this.aa=b;this.Na=c}
ca("internalWebfont.BrowserInfo",t);t.prototype.Ba=m("Oa");t.prototype.hasWebFontSupport=t.prototype.Ba;t.prototype.Ca=m("aa");t.prototype.hasWebKitFallbackBug=t.prototype.Ca;t.prototype.Da=m("Na");t.prototype.hasWebKitMetricsBug=t.prototype.Da;function u(a,b,c,d){this.e=a!=k?a:k;this.m=b!=k?b:k;this.C=c!=k?c:k;this.j=d!=k?d:k}var la=/^([0-9]+)(?:[\._-]([0-9]+))?(?:[\._-]([0-9]+))?(?:[\._+-]?(.*))?$/;
function v(a,b){return a.e>b.e||a.e===b.e&&a.m>b.m||a.e===b.e&&a.m===b.m&&a.C>b.C?1:a.e<b.e||a.e===b.e&&a.m<b.m||a.e===b.e&&a.m===b.m&&a.C<b.C?-1:0}function w(a,b){return 0===v(a,b)||1===v(a,b)}u.prototype.toString=function(){return[this.e,this.m||"",this.C||"",this.j||""].join("")};
function x(a){a=la.exec(a);var b=k,c=k,d=k,e=k;a&&(a[1]!==k&&a[1]&&(b=parseInt(a[1],10)),a[2]!==k&&a[2]&&(c=parseInt(a[2],10)),a[3]!==k&&a[3]&&(d=parseInt(a[3],10)),a[4]!==k&&a[4]&&(e=/^[0-9]+$/.test(a[4])?parseInt(a[4],10):a[4]));return new u(b,c,d,e)}function y(a,b,c,d,e,f,g,h,p,L,E){this.Q=a;this.n=b;this.Ma=c;this.u=d;this.z=e;this.ra=f;this.k=g;this.h=h;this.Ia=p;this.N=L;this.t=E}ca("internalWebfont.UserAgent",y);y.prototype.getName=m("Q");y.prototype.getName=y.prototype.getName;
y.prototype.Aa=m("Ma");y.prototype.getVersion=y.prototype.Aa;y.prototype.wa=m("u");y.prototype.getEngine=y.prototype.wa;y.prototype.xa=m("ra");y.prototype.getEngineVersion=y.prototype.xa;y.prototype.ya=m("k");y.prototype.getPlatform=y.prototype.ya;y.prototype.za=m("Ia");y.prototype.getPlatformVersion=y.prototype.za;y.prototype.va=m("N");y.prototype.getDocumentMode=y.prototype.va;y.prototype.ua=m("t");y.prototype.getBrowserInfo=y.prototype.ua;function ma(a,b){this.c=a;this.M=b}
var na=new y("Unknown",new u,"Unknown","Unknown",new u,"Unknown","Unknown",new u,"Unknown",void 0,new t(l,l,l));
ma.prototype.parse=function(){var a;if(-1!=this.c.indexOf("MSIE")||-1!=this.c.indexOf("Trident/")){a=z(this);var b=A(this),c=x(b),d=k,e=k,f=k,g=k,h=B(this.c,/Trident\/([\d\w\.]+)/,1),p=C(this.M),d=-1!=this.c.indexOf("MSIE")?B(this.c,/MSIE ([\d\w\.]+)/,1):B(this.c,/rv:([\d\w\.]+)/,1),e=x(d);""!=h?(f="Trident",g=x(h)):(f="Unknown",g=new u,h="Unknown");a=new y("MSIE",e,d,f,g,h,a,c,b,p,new t("Windows"==a&&6<=e.e||"Windows Phone"==a&&8<=c.e,l,l))}else if(-1!=this.c.indexOf("Opera"))a:if(a="Unknown",b=
B(this.c,/Presto\/([\d\w\.]+)/,1),c=x(b),d=A(this),e=x(d),f=C(this.M),c.e!==k?a="Presto":(-1!=this.c.indexOf("Gecko")&&(a="Gecko"),b=B(this.c,/rv:([^\)]+)/,1),c=x(b)),-1!=this.c.indexOf("Opera Mini/"))g=B(this.c,/Opera Mini\/([\d\.]+)/,1),h=x(g),a=new y("OperaMini",h,g,a,c,b,z(this),e,d,f,new t(l,l,l));else{if(-1!=this.c.indexOf("Version/")&&(g=B(this.c,/Version\/([\d\.]+)/,1),h=x(g),h.e!==k)){a=new y("Opera",h,g,a,c,b,z(this),e,d,f,new t(10<=h.e,l,l));break a}g=B(this.c,/Opera[\/ ]([\d\.]+)/,1);
h=x(g);a=h.e!==k?new y("Opera",h,g,a,c,b,z(this),e,d,f,new t(10<=h.e,l,l)):new y("Opera",new u,"Unknown",a,c,b,z(this),e,d,f,new t(l,l,l))}else/OPR\/[\d.]+/.test(this.c)?a=qa(this):/AppleWeb(K|k)it/.test(this.c)?a=qa(this):-1!=this.c.indexOf("Gecko")?(a="Unknown",b=new u,c="Unknown",d=A(this),e=x(d),f=l,-1!=this.c.indexOf("Firefox")?(a="Firefox",c=B(this.c,/Firefox\/([\d\w\.]+)/,1),b=x(c),f=3<=b.e&&5<=b.m):-1!=this.c.indexOf("Mozilla")&&(a="Mozilla"),g=B(this.c,/rv:([^\)]+)/,1),h=x(g),f||(f=1<h.e||
1==h.e&&9<h.m||1==h.e&&9==h.m&&2<=h.C||g.match(/1\.9\.1b[123]/)!=k||g.match(/1\.9\.1\.[\d\.]+/)!=k),a=new y(a,b,c,"Gecko",h,g,z(this),e,d,C(this.M),new t(f,l,l))):a=na;return a};function z(a){var b=B(a.c,/(iPod|iPad|iPhone|Android|Windows Phone|BB\d{2}|BlackBerry)/,1);if(""!=b)return/BB\d{2}/.test(b)&&(b="BlackBerry"),b;a=B(a.c,/(Linux|Mac_PowerPC|Macintosh|Windows|CrOS)/,1);return""!=a?("Mac_PowerPC"==a&&(a="Macintosh"),a):"Unknown"}
function A(a){var b=B(a.c,/(OS X|Windows NT|Android) ([^;)]+)/,2);if(b||(b=B(a.c,/Windows Phone( OS)? ([^;)]+)/,2))||(b=B(a.c,/(iPhone )?OS ([\d_]+)/,2)))return b;if(b=B(a.c,/(?:Linux|CrOS) ([^;)]+)/,1))for(var b=b.split(/\s/),c=0;c<b.length;c+=1)if(/^[\d\._]+$/.test(b[c]))return b[c];return(a=B(a.c,/(BB\d{2}|BlackBerry).*?Version\/([^\s]*)/,2))?a:"Unknown"}
function qa(a){var b=z(a),c=A(a),d=x(c),e=B(a.c,/AppleWeb(?:K|k)it\/([\d\.\+]+)/,1),f=x(e),g="Unknown",h=new u,p="Unknown",L=l;/OPR\/[\d.]+/.test(a.c)?g="Opera":-1!=a.c.indexOf("Chrome")||-1!=a.c.indexOf("CrMo")||-1!=a.c.indexOf("CriOS")?g="Chrome":/Silk\/\d/.test(a.c)?g="Silk":"BlackBerry"==b||"Android"==b?g="BuiltinBrowser":-1!=a.c.indexOf("PhantomJS")?g="PhantomJS":-1!=a.c.indexOf("Safari")?g="Safari":-1!=a.c.indexOf("AdobeAIR")&&(g="AdobeAIR");"BuiltinBrowser"==g?p="Unknown":"Silk"==g?p=B(a.c,
/Silk\/([\d\._]+)/,1):"Chrome"==g?p=B(a.c,/(Chrome|CrMo|CriOS)\/([\d\.]+)/,2):-1!=a.c.indexOf("Version/")?p=B(a.c,/Version\/([\d\.\w]+)/,1):"AdobeAIR"==g?p=B(a.c,/AdobeAIR\/([\d\.]+)/,1):"Opera"==g?p=B(a.c,/OPR\/([\d.]+)/,1):"PhantomJS"==g&&(p=B(a.c,/PhantomJS\/([\d.]+)/,1));h=x(p);L="AdobeAIR"==g?2<h.e||2==h.e&&5<=h.m:"BlackBerry"==b?10<=d.e:"Android"==b?2<d.e||2==d.e&&1<d.m:526<=f.e||525<=f.e&&13<=f.m;return new y(g,h,p,"AppleWebKit",f,e,b,d,c,C(a.M),new t(L,536>f.e||536==f.e&&11>f.m,"iPhone"==
b||"iPad"==b||"iPod"==b||"Macintosh"==b))}function B(a,b,c){return(a=a.match(b))&&a[c]?a[c]:""}function C(a){if(a.documentMode)return a.documentMode}function ra(a){this.Ga=a||"-"}ra.prototype.j=function(a){for(var b=[],c=0;c<arguments.length;c++)b.push(arguments[c].replace(/[\W_]+/g,"").toLowerCase());return b.join(this.Ga)};function sa(a,b,c){this.g=a;this.l=b;this.T=c;this.p="wf";this.o=new ra("-")}
function ta(a){s(a.l,a.o.j(a.p,"loading"));ia(a.l,a.o.j(a.p,"active"))||r(a.l,a.o.j(a.p,"inactive"));F(a,"inactive")}function F(a,b,c){if(a.T[b])if(c)a.T[b](c.getName(),G(c));else a.T[b]()}function H(a,b){this.Q=a;this.ba=4;this.R="n";var c=(b||"n4").match(/^([nio])([1-9])$/i);c&&(this.R=c[1],this.ba=parseInt(c[2],10))}H.prototype.getName=m("Q");function G(a){return a.R+a.ba}function J(a,b){this.g=a;this.I=b;this.w=this.g.createElement("span",{"aria-hidden":"true"},this.I)}
function ua(a,b){var c;c=[];for(var d=b.Q.split(/,\s*/),e=0;e<d.length;e++){var f=d[e].replace(/['"]/g,"");-1==f.indexOf(" ")?c.push(f):c.push("'"+f+"'")}c=c.join(",");d="normal";e=b.ba+"00";"o"===b.R?d="oblique":"i"===b.R&&(d="italic");a.w.style.cssText="position:absolute;top:-999px;left:-999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;white-space:nowrap;font-family:"+c+";"+("font-style:"+d+";font-weight:"+e+";")}
function va(a){q(a.g,"body",a.w)}J.prototype.remove=function(){var a=this.w;a.parentNode&&a.parentNode.removeChild(a)};function wa(a,b,c,d,e,f,g,h){this.ca=a;this.Ea=b;this.g=c;this.v=d;this.I=h||"BESbswy";this.t=e;this.J={};this.Z=f||5E3;this.la=g||k;this.H=this.G=k;a=new J(this.g,this.I);va(a);for(var p in K)K.hasOwnProperty(p)&&(ua(a,new H(K[p],G(this.v))),this.J[K[p]]=a.w.offsetWidth);a.remove()}var K={Va:"serif",Ua:"sans-serif",Ra:"monospace"};
wa.prototype.start=function(){this.G=new J(this.g,this.I);va(this.G);this.H=new J(this.g,this.I);va(this.H);this.Ka=fa();ua(this.G,new H(this.v.getName()+",serif",G(this.v)));ua(this.H,new H(this.v.getName()+",sans-serif",G(this.v)));xa(this)};function ya(a,b,c){for(var d in K)if(K.hasOwnProperty(d)&&b===a.J[K[d]]&&c===a.J[K[d]])return j;return l}
function xa(a){var b=a.G.w.offsetWidth,c=a.H.w.offsetWidth;b===a.J.serif&&c===a.J["sans-serif"]||a.t.aa&&ya(a,b,c)?fa()-a.Ka>=a.Z?a.t.aa&&ya(a,b,c)&&(a.la===k||a.la.hasOwnProperty(a.v.getName()))?za(a,a.ca):za(a,a.Ea):setTimeout(n(function(){xa(this)},a),25):za(a,a.ca)}function za(a,b){a.G.remove();a.H.remove();b(a.v)}function M(a,b,c,d){this.g=b;this.A=c;this.V=0;this.oa=this.ka=l;this.Z=d;this.t=a.t}
M.prototype.$=function(a,b,c,d){if(0===a.length&&d)ta(this.A);else{this.V+=a.length;d&&(this.ka=d);for(d=0;d<a.length;d++){var e=a[d],f=b[e.getName()],g=this.A,h=e;r(g.l,g.o.j(g.p,h.getName(),G(h).toString(),"loading"));F(g,"fontloading",h);(new wa(n(this.sa,this),n(this.ta,this),this.g,e,this.t,this.Z,c,f)).start()}}};
M.prototype.sa=function(a){var b=this.A;s(b.l,b.o.j(b.p,a.getName(),G(a).toString(),"loading"));s(b.l,b.o.j(b.p,a.getName(),G(a).toString(),"inactive"));r(b.l,b.o.j(b.p,a.getName(),G(a).toString(),"active"));F(b,"fontactive",a);this.oa=j;Aa(this)};M.prototype.ta=function(a){var b=this.A;s(b.l,b.o.j(b.p,a.getName(),G(a).toString(),"loading"));ia(b.l,b.o.j(b.p,a.getName(),G(a).toString(),"active"))||r(b.l,b.o.j(b.p,a.getName(),G(a).toString(),"inactive"));F(b,"fontinactive",a);Aa(this)};
function Aa(a){0==--a.V&&a.ka&&(a.oa?(a=a.A,s(a.l,a.o.j(a.p,"loading")),s(a.l,a.o.j(a.p,"inactive")),r(a.l,a.o.j(a.p,"active")),F(a,"active")):ta(a.A))}function N(a,b){this.Ja=a;this.ga=b}function Ba(a){for(var b=a.Ja.join(","),c=[],d=0;d<a.ga.length;d++){var e=a.ga[d];c.push(e.name+":"+e.value+";")}return b+"{"+c.join("")+"}"}function Ca(a){this.g=a}Ca.prototype.toString=function(){return encodeURIComponent(this.g.P.location.hostname||this.g.Y.location.hostname)};
function Da(a,b){this.q=a;this.s=b}Da.prototype.toString=function(){for(var a=[],b=0;b<this.s.length;b++)for(var c=this.s[b],d=c.B(),c=c.B(this.q),e=0;e<d.length;e++){var f;a:{for(f=0;f<c.length;f++)if(d[e]===c[f]){f=j;break a}f=l}a.push(f?1:0)}a=a.join("");a=a.replace(/^0+/,"");b=[];for(d=a.length;0<d;d-=4)c=a.slice(0>d-4?0:d-4,d),b.unshift(parseInt(c,2).toString(16));return b.join("")};function O(a){this.La=a}
O.prototype.j=function(a,b){var c=b||{},d=this.La.replace(/\{\/?([^*}]*)(\*?)\}/g,function(a,b,d){return d&&c[b]?"/"+c[b].join("/"):c[b]||""});d.match(/^\/\//)&&(d=(a?"https:":"http:")+d);return d.replace(/\/*\?*($|\?)/,"$1")};function P(a,b,c,d){this.F=a;this.O=b;this.Ya=c;this.Za=d;this.ia={};this.ha={}}P.prototype.B=function(a){return a?(this.ia[a]||this.O).slice(0):this.O.slice(0)};P.prototype.$=function(a,b,c){var d=[],e={};Ea(this,b,d,e);a(d,e,c)};
function Ea(a,b,c,d){c.push(a.F);d[a.F]=a.B(b);a=a.ha[b]||[];for(b=0;b<a.length;b++){for(var e=a[b],f=e.F,g=l,h=0;h<c.length;h++)c[h]==f&&(g=j);g||(c.push(f),d[f]=e.B())}}function Fa(a,b){this.F=a;this.O=b}Fa.prototype.B=m("O");function Ga(){this.qa=this.Pa=this.K=this.W=this.Fa=j}function Q(a){return"Windows"===a.k}function R(a){return Q(a)&&0===v(a.h,new u(5,1))||Q(a)&&0===v(a.h,new u(5,2))||Q(a)&&0===v(a.h,new u(6,0))||Q(a)&&w(a.h,new u(6,1))}
function S(a){return"Macintosh"===a.k&&(w(a.h,new u(10,4))||a.h.e===k)}function Ha(a,b){return b.Fa&&("iPhone"===a.k||"iPod"===a.k)}function Ia(a,b){return Ha(a,b)&&w(a.h,new u(4,2))&&-1===v(a.h,new u(5))}function Ja(a,b){return b.W&&"iPad"===a.k&&w(a.h,new u(4,2))&&-1===v(a.h,new u(5))}function U(a,b){return b.K&&"Android"===a.k}function Ka(a,b){return U(a,b)&&w(a.h,new u(2,2))&&-1===v(a.h,new u(3,1))}function La(a,b){return U(a,b)&&w(a.h,new u(3,1))&&-1===v(a.h,new u(4,1))}
function V(a){return"Linux"===a.k||"Ubuntu"===a.k}function Ma(a){return"Gecko"===a.u&&0===v(a.z,new u(1,9,1))&&!/^b[1-3]$/.test(a.z.j||"")}function Na(a){return"Safari"===a.getName()&&"AppleWebKit"===a.u||"Unknown"===a.getName()&&"AppleWebKit"===a.u&&("iPhone"===a.k||"iPad"===a.k||"iPod"===a.k)}function Oa(a){return"Safari"===a.getName()&&"AppleWebKit"===a.u&&w(a.z,new u(525,13))&&-1===v(a.z,new u(534,50))}function Pa(a){return"Opera"===a.getName()&&w(a.n,new u(10,54))&&-1===v(a.n,new u(11,10))}
function Qa(a){return"BuiltinBrowser"===a.getName()}function Ra(a){this.na=a}function Ta(a,b){return b}
var Ua={Sa:"a",Ta:"b",Xa:"d",Wa:"f",Qa:"i"},Va={a:function(a,b){return Oa(a)&&R(a)||Qa(a)&&(Ka(a,b)||U(a,b)&&w(a.h,new u(4,1)))||b.K&&"Silk"===a.getName()&&-1===v(a.n,new u(2))&&(Ka(a,b)||S)||b.K&&"Silk"===a.getName()&&w(a.n,new u(2))&&U(a,b)&&w(a.h,new u(4,1))||Na(a)&&(Ja(a,b)||Ia(a,b))||Ma(a)&&(R(a)||V(a))||Pa(a)&&(R(a)||V(a))||("Chrome"===a.getName()&&1===v(a.n,new u(4,0,249))&&-1===v(a.n,new u(6))||0===v(a.n,new u(4,0,249))&&(a.n.j===k||4<=a.n.j))&&(R(a)||V(a)||S(a))||"Chrome"===a.getName()&&
w(a.n,new u(6))&&(Ja(a,b)||Ia(a,b))||"AdobeAIR"===a.getName()&&w(a.n,new u(2,5))&&(Q(a)&&a.h.e===k||V(a))},b:function(a){return Ma(a)&&S(a)||Oa(a)&&S(a)||Pa(a)&&S(a)||"AdobeAIR"===a.getName()&&w(a.n,new u(2,5))&&S(a)},d:function(a,b){return"Chrome"===a.getName()&&w(a.n,new u(6))&&(R(a)||V(a)||S(a)||U(a,b)||"CrOS"===a.k||b.W&&"iPad"===a.k&&w(a.h,new u(5))||Ha(a,b)&&w(a.h,new u(5)))||"Gecko"===a.u&&1===v(a.z,new u(1,9,1))&&(R(a)||V(a)||S(a)||U(a,b))||"Safari"===a.getName()&&("AppleWebKit"===a.u&&w(a.z,
new u(534,50)))&&(R(a)||S(a))||Na(a)&&(b.W&&"iPad"===a.k&&w(a.h,new u(5))||Ha(a,b)&&w(a.h,new u(5)))||"Opera"===a.getName()&&w(a.n,new u(11,10))&&(R(a)||V(a)||S(a)||U(a,b))||"MSIE"===a.getName()&&9<=a.N&&(Q(a)&&w(a.h,new u(6,1))||Q(a)&&0===v(a.h,new u(6,0)))||"MSIE"===a.getName()&&b.Pa&&"Windows Phone"===a.k&&w(a.h,new u(8))||Qa(a)&&b.qa&&"BlackBerry"===a.k&&w(a.h,new u(10))},f:function(a,b){return Qa(a)&&La(a,b)||b.K&&"Silk"===a.getName()&&w(a.n,new u(2))&&(La(a,b)||V(a))},i:function(a){return"MSIE"===
a.getName()&&(w(a.n,new u(6,0))&&(void 0===a.N||9>a.N))&&R(a)}};function Wa(a,b){var c=b||new Ga,d;for(d in Ua){var e=Ua[d];if(Va[e](a,c))return e}return k}var Xa={};
Xa.i=new Ra(function(a,b,c){for(var d=0;d<b.length;d+=1){var e=b[d],f=a.replace(/(-1|-2)$/,"").slice(0,28)+"-"+e;c.push(new Fa(f,[e]))}a={};for(e=0;e<b.length;e++)c=b[e],d=c.charAt(1),(a[d]||(a[d]=[])).push(c);c=[[4,3,2,1,5,6,7,8,9],[7,8,9,6,5,4,3,2,1]];d=[];for(e=0;e<c.length;e++)for(var f=c[e],g=0;g<f.length;g++){var h=f[g];if(a[h]){d=d.concat(a[h]);break}}c=d;d={};a=[];for(e=0;e<c.length;e++)f=c[e],d[f]||(d[f]=j,a.push(f));c=[];for(d=0;d<b.length;d++){e=b[d];for(f=0;f<a.length;f++)g=a[f],g==e&&
c.push(g)}return c});var W={};W.a=W.b=W.d=function(){return[]};W.f=function(a){return[new Ca(a)]};W.i=function(a,b,c){return[new Ca(a),new Da(b,c)]};function X(a){this.g=a;this.ea=this.c=this.q=k;this.s=[];this.L=[];this.pa=this.U=k}function Y(a){Z.s.push(a)}function $(a){Z.L.push(a)}X.prototype.supportsConfiguredBrowser=function(){return!!this.q};
X.prototype.init=function(){if(0<this.L.length){for(var a=[],b=0;b<this.L.length;b++)a.push(Ba(this.L[b]));var b=this.g,a=a.join(""),c=this.g.createElement("style");c.setAttribute("type","text/css");c.styleSheet?c.styleSheet.cssText=a:c.appendChild(document.createTextNode(a));q(b,"head",c)}};
X.prototype.load=function(a,b,c){if(this.q){for(var d=Xa[this.q]||new Ra(Ta),e=0;e<this.s.length;e++){for(var f=this.s[e],g=this.q,h=d,p=[],L=f.F.split(",")[0].replace(/"|'/g,""),E=f.B(),T=p,D=void 0,I=[],Sa={},oa=0;oa<E.length;oa++)D=E[oa],0<D.length&&!Sa[D]&&(Sa[D]=j,I.push(D));E=I;h=h.na?h.na(L,E,T):E;f.ia[g]=h;f.ha[g]=p}if(this.U){d=W[this.q](this.g,this.q,this.s);e=this.q;f=[];for(g=0;g<d.length;g++)f.push(d[g].toString());d={format:e,extras:f};c&&(d.contextPath=c);d=this.U.j("https:"===ja(this.g),
d);c=this.g;var d=c.createElement("link",{rel:"stylesheet",href:d}),aa=l;d.onload=function(){aa||(aa=j)};d.onerror=function(){aa||(aa=j)};q(c,"head",d)}if(a){var pa=this,hb=this.q;ha(this.g,function(){for(var c=0;c<pa.s.length;c++)pa.s[c].$(a,hb,b&&c==pa.s.length-1)})}}};X.prototype.collectFontFamilies=function(a,b){if(this.q)for(var c=0;c<this.s.length;c++)Ea(this.s[c],this.q,a,b)};
X.prototype.performOptionalActions=function(){if(this.X){var a=this,b=this.c,c=this.g;ha(this.g,function(){var d=a.X;if(d.ma){var e=window.__adobewebfontsappname__,e=e?e.toString().substr(0,20):"",d=d.ma.j("https:"===ja(c),{host:encodeURIComponent(c.P.location.hostname||c.Y.location.hostname),app:encodeURIComponent(e),_:(+new Date).toString()}),f=new Image(1,1);f.src=d;f.onload=function(){f.onload=k}}d=a.X;d.da&&(d=d.da.j(b,c),q(c,"body",d))})}};
function Ya(a,b,c,d){this.Ha=a;this.fa=k;this.g=b;this.c=c;this.l=d;this.r=[]}Ya.prototype.S=function(a){this.r.push(a)};Ya.prototype.load=function(a,b){var c=a,d=b||{};if("string"==typeof c)c=[c];else if(!c||!c.length)d=c||{},c=[];if(c.length)for(var e=this,f=c.length,g=0;g<c.length;g++){var h=this.Ha.j("https:"===ja(this.g),{id:encodeURIComponent(c[g])});ka(this.g,h,function(){0==--f&&Za(e,d)})}else Za(this,d)};
function Za(a,b){if(0!=a.r.length){a.fa=b.contextPath||k;for(var c=new sa(a.g,a.l,b),d=l,e=0;e<a.r.length;e++)a.r[e].init(),d=d||a.r[e].supportsConfiguredBrowser();if(d){r(c.l,c.o.j(c.p,"loading"));F(c,"loading");for(var f=new M(a.c,a.g,c,b.timeout),c=function(a,b,c){for(var d=[],e=0;e<a.length;e+=1){var T=a[e];if(b[T])for(var D=b[T],I=0;I<D.length;I+=1)d.push(new H(T,D[I]));else d.push(new H(T))}f.$(d,{},k,c)},d=0;d<a.r.length;d++)e=a.r[d],e.supportsConfiguredBrowser()&&(e.load(c,d==a.r.length-1,
a.fa),e.performOptionalActions(window))}else ta(c);a.r=[]}}function $a(a){this.ja=a;this.r=[]}$a.prototype.S=function(a){this.r.push(a)};
$a.prototype.load=function(){var a=this.ja.__webfonttypekitmodule__;if(a)for(var b=0;b<this.r.length;b++){var c=this.r[b],d=a[c.pa];d&&d(function(a,b,d){a=[];b={};var h=(new ma(navigator.userAgent,document)).parse(),p=c;p.c=h;p.q=Wa(p.c,p.ea);c.supportsConfiguredBrowser()&&(c.init(),c.load(k),c.collectFontFamilies(a,b),c.performOptionalActions(window));d(c.supportsConfiguredBrowser(),a,b)})}};var ab=(new ma(navigator.userAgent,document)).parse();window.Typekit||(window.Typekit={});
if(!window.Typekit.load){var bb=new Ya(new O("//typeface.nytimes.com/{id}.js"),new ga(window),ab,document.documentElement),cb=new $a(window);window.Typekit.load=function(){bb.load.apply(bb,arguments)};window.Typekit.addKit=function(){bb.S.apply(bb,arguments)}}var db=k,eb,Z,db=new O("//p.typekit.net/p.gif?a=82618&f=387.388.389.390.391.392.397.399.401.403.404.405.413.18469.21702.22116.22117.22118&h={host}&ht=sh&k=zam5nzz&s=1&_={_}");eb=new function(){var a=db;this.da=k;this.ma=a};Z=new X(new ga(window));
Z.pa="zam5nzz";Z.U=new O("//typeface.nytimes.com/k/zam5nzz-{format}.css?3bb2a6e53c9684ffdc9a98f01c5b2a6283172bd2d28e6d8521eb4185e6659f40f839011d6f9ba09a1aedcb02428b4708bdab7203bd845c2d227ec97b9a7c05847d7fed063fb32df3dcacb969477c0fd6e0349ffc6eed4a558c4637a7f13bd6419fddae9376984af20caa2c2964800b0dbc2c80d7868a5f7588cbd174387af10ea724c0e29d9a45b70f6223bbc9ca3bc879fbea75f3abf70aa56b9bd7bda8191e12e9c57c5a0da1451da6a2e261e29da5736591d509a3754c9b6226acb30bc49ff19fa85c2d1e04193c634e34788dcc351fec4a9511eef8a44e6e9988a8c73d87367a9b12c2a8ffb6fab185b0082561b56921f761d74ef19c39323cb93ff37c5028df41420a44b1e65815");
Z.X=eb;Y(new P("nyt-franklin","n3 i3 n5 i5 n7 i7".split(" ")));Y(new P("nyt-cheltenham","n2 n3 n4 n5 n7 i7".split(" ")));Y(new P("nyt-karnak-display-130124",["n4"]));Y(new P("nyt-stymie",["n7"]));Y(new P("nyt-cheltenham-extra-cn-bd",["n7"]));Y(new P("nyt-cheltenham-sh",["n4","i4","n7"]));$(new N([".tk-nyt-franklin"],[{name:"font-family",value:'"nyt-franklin",sans-serif'}]));$(new N([".tk-nyt-cheltenham"],[{name:"font-family",value:'"nyt-cheltenham",sans-serif'}]));
$(new N([".tk-nyt-karnak-display-130124"],[{name:"font-family",value:'"nyt-karnak-display-130124",sans-serif'}]));$(new N([".tk-nyt-stymie"],[{name:"font-family",value:'"nyt-stymie",sans-serif'}]));$(new N([".tk-nyt-cheltenham-extra-cn-bd"],[{name:"font-family",value:'"nyt-cheltenham-extra-cn-bd",serif'}]));$(new N([".tk-nyt-cheltenham-sh"],[{name:"font-family",value:'"nyt-cheltenham-sh",sans-serif'}]));var fb;if(fb=cb)fb=!!cb.ja.__webfonttypekitmodule__;
if(fb)cb.S(Z),cb.load();else{var gb=Z;gb.c=ab;gb.q=Wa(gb.c,gb.ea);window.Typekit.addKit(Z)};
})(this,document);