(function(z){
var sJ=function(a,b,c){b="new"===(b||a.dd);return c?(a=a.d.v.w().get(z.V.Zo),b?-1:-a):a.Nm+(b?-1:1)};var tJ=function(a){z.xu.call(this,a);this.Nm=0;this.dd="new"};var uJ=function(a,b){a.mV=b};var vJ=function(a){return a.get(a.j.fp)};
var wJ=function(a){return'\x3cdiv class\x3d"fyre '+(a.$d?"fyre-liveblog ":"")+(a.Qg?"fyre-livechat ":"")+(a.UR?"fyre-bootstrap":"")+'"\x3e\x3cdiv class\x3d"fyre-widget '+(a.Ka?"fyre-avatar-disabled":"")+'"\x3e'+(a.Hu?(0,z.Kr)(a):"")+'\x3cdiv class\x3d"fyre-featured-content-wrapper" style\x3d"display: none"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-stream-stats"\x3e\x3cdiv class\x3d"fyre-comment-count"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-help"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-auth"\x3e\x3cdiv class\x3d"fyre-login-bar"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-live-container"\x3e\x3cdiv class\x3d"fyre-livecount"\x3e\x3c/div\x3e'+(a.Ka?
"":'\x3cdiv class\x3d"fyre-listener-avatars"\x3e\x3c/div\x3e')+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-editor"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-input-box-collapsed"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-comment-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-top-content-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-thread-breakout-stream"\x3e\x3c/div\x3e'+(a.Fn?'\x3cdiv class\x3d"fyre-archive-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-archive-stream"\x3e\x3c/div\x3e':
"")+'\x3cdiv class\x3d"fyre-stream-menu-container"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e'};var xJ=function(a){return'\x3ca href\x3d"'+(0,z.Ml)(a.Aa)+'" title\x3d"'+(0,z.R)(a.Y)+'" data-id\x3d"'+a.id+'" class\x3d"fyre-follower fyre-follower-'+a.CR+'"\x3e\x3cimg src\x3d"'+(0,z.Ml)(a.sd)+'" alt\x3d"'+(0,z.R)(a.Y)+'" onerror\x3d"javascript:this.src\x3d\''+(0,z.R)(a.Vb)+"';\" /\x3e\x3c/a\x3e"};
var yJ=function(a){return(0,z.Sp)(a)+'\x3cdiv class\x3d"fyre-archive-stream-sort fyre-stream-sort"\x3e\x3ch3\x3e\x3cstrong\x3e\x3c/strong\x3e'+(0,z.R)(a.k.pM)+'\x3c/h3\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+(0,z.R)(a.k.dx)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+(0,z.R)(a.k.oo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+(0,z.R)(a.k.ex)+"\x3c/a\x3e\x3c/div\x3e\x3c/div\x3e"};
var zJ=function(a){return'\x3cdiv class\x3d"tooltip"\x3e'+(0,z.R)(a.message)+'\x3c/div\x3e\x3cdiv class\x3d"arrow-down"\x3e\x3c/div\x3e'};var AJ=function(){};var BJ=function(a,b){z.Aj.call(this,b,a)};var CJ=function(a,b){z.rE.call(this,a,b)};var DJ=function(a,b){var c=a.d.Bb;c.bh[4]&&((0,z.Ox)(c,4,(0,z.u)(function(a){b.e(a,"threadBreakout",this.Zq)},a)),(0,z.Qx)(c,4,(0,z.u)(function(a){b.Va(a,"threadBreakout",this.Zq)})))};
var EJ=function(a,b){var c=[a.Rl,a.py];a.pg&&c.push(a.pg);a.xs&&c.push(a.xs);a.qy&&c.push(a.qy);(0,z.y)(c,function(a){(0,z.$h)(a,"fyre-stream-sort-selected")});(0,z.I)(b,"fyre-stream-sort-selected")};var FJ=function(a,b){z.rE.call(this,a,b)};var GJ=function(a,b){z.rw.call(this,a,b);this.ll=!1;this.Ma=new z.zw;this.Ma.kc(this);this.yt="archiveShowMore"};var HJ=function(a,b){z.pE.call(this,a,b)};var IJ=function(a,b,c){z.Ws.call(this,a,b,c);this.Hy=b||"";this.mg(zJ(this.s()))};
var JJ=function(a,b,c){z.Qs.call(this,a,b||3,c)};var KJ=function(a,b){z.U.call(this,b);this.m=a};var LJ=function(a,b){z.U.call(this,b);this.Yb=a};var MJ=function(a,b){LJ.call(this,a,b)};var NJ=function(a,b,c,d,f){z.qE.call(this,a,b,c,d,f)};var OJ=function(a,b){z.zE.call(this,a,b);var c=a.v.Hb(),d=a.v.w();this.fg=new NJ(a,c,a.vl.Ia,d.Qg()||z.Yf);this.D(this.fg);a.V.Ka||(this.bn=new MJ(c),this.D(this.bn));this.er=new z.oE;this.D(this.er)};var PJ=function(a){var b=z.K.gb();return!a.u.$d()||b};
var QJ=function(a){z.Ux.call(this,a);this.wm=1};var RJ=function(a){z.Nr.call(this,a);(0,z.$t)(a.v);this.Qb=new OJ(a);this.pq.start();this.kl(this.Qb);(0,z.Rr)(this)};var SJ=function(a,b){this.hC=BJ;this.pI=RJ;z.X.so(b.strings||{});z.pl.call(this,a,b)};var TJ=function(a){a.Yj&&(a.Yj.r(),delete a.Yj)};(0,z.w)(tJ,z.xu);z.e=tJ.prototype;z.e.Zk=(0,z.l)(68);z.e.AE=(0,z.l)(70);z.e.BE=(0,z.l)(69);z.e.AE=(0,z.O)(70,function(a){this.Fa||(this.Wn[a]=!1,(0,z.yu)(this,a,function(a){a.M(a.ta.tm)}))});
z.e.BE=(0,z.O)(69,function(a,b){if(!this.Fa){var c=this.d.v.w(),d=(0,z.wt)(a,b),f=c.get(z.V.Ts);c.set(z.V.Zo,d.cT);(0,z.D)(d.Ya,(0,z.u)(this.d.O.M,this.d.O,"bootstrap_author_received"));d.content=(0,z.ej)(d.content,function(a,b){return!(0,z.Qa)(f,b)});(0,z.D)(d.content,function(a){(0,z.E)(d.content,(0,z.Au)(this,a))},this);(0,z.E)(this.uc,(0,z.dj)(d.content,(0,z.zb)(a)));this.Od(a,d.content);(0,z.yu)(this,a,function(b){b.M(b.ta.nk,{zd:a});b.set(b.j.Ye,!0)})}});
z.e.Zk=(0,z.O)(68,function(a,b){this.Nm=a;this.dd=b||this.dd;var c=this.Ad[a]=new z.tu;z.Qt.C();var d=this.d.v.w(),f=(0,z.u)(this.BE,this,a),g=(0,z.u)(this.AE,this,a),h=this.d.V.Dk,d=d.get(z.V.zc),h=z.x.Zt(d,h)+String(a)+".json";(0,z.Rt)(0,h,f,g);return c});z.VE.prototype.Zk=(0,z.O)(67,function(a,b){this.Bk||(this.Bk=new tJ(this.J));var c=this.Bk,d=sJ(c,a,b);return c.Zk(d,a)});
z.Qt.prototype.Fh=(0,z.O)(59,function(a,b,c){a=(0,z.ua)("%s%scollection/%s/hot/",z.x.K.td,z.x.Ve,a.la);(new z.Fe({url:a,va:b,oa:c})).send()});z.Ru.prototype.Fh=(0,z.O)(58,function(a){var b={la:this.d.v.w().id},c=z.Qt.C().Fh;(0,z.Su)(this,c,b,a);return a});z.VE.prototype.Fh=(0,z.O)(57,function(){(0,z.Xu)(this);this.ri=new z.Ru(this.J,void 0);var a=new z.tu;this.ri.Fh(a);return a});
z.Qt.prototype.Ch=(0,z.O)(56,function(a,b,c){a=(0,z.ua)("%s%scollection/%s/top/%s/",z.x.K.td,z.x.Ve,a.la,a.jM);(new z.Fe({url:a,va:b,oa:c})).send({format:"stream"})});z.Ru.prototype.Ch=(0,z.O)(55,function(a,b){var c={la:this.d.v.w().id,jM:a},d=z.Qt.C().Ch;(0,z.Su)(this,d,c,b);return b});z.VE.prototype.Ch=(0,z.O)(54,function(a){(0,z.Xu)(this);this.ri=new z.Ru(this.J,void 0);var b=new z.tu;this.ri.Ch(a,b);return b});z.U.prototype.KF=(0,z.O)(53,function(){return this.aa});
z.xj.prototype.Fn=(0,z.O)(52,function(){return this.get(this.j.Yo)});(0,z.w)(AJ,z.vl);(0,z.ba)(AJ);
AJ.prototype.xF=function(a){var b={};b.Dk=a[z.gF.bz];var c=a[z.gF.AI];c&&(b.rM=c);if(c=a[z.gF.cz])b.uM=c;if(c=a[z.gF.dz]||z.Yf&&(0,z.da)(z.bF.sp))b.lC=c;b.Gm=a[z.gF.gz]?!0:!1;c=a[z.gF.QB];b.XL=c?c:!1;if(c=a[z.gF.jz])b.ga=c;if(c=a[z.gF.Jf])b.Ji=c;if(c=a[z.gF.mz])b.nu=c;b.Oi=(0,z.wl)(this,a[z.gF.rz]);if(c=a[z.gF.zz])b.Sk=c;if(c=a[z.gF.MA])b.Yn=c;if(c=a[z.gF.cB])b.cy=c;c=a[z.gF.jB];null!=c&&(b.ky=c);if(c=a[z.gF.sz]||!1)b.Ka=c;b.readOnly=a[z.gF.READ_ONLY]||!1;if(c=a[z.gF.JB])b.kI=c;if(c=a[z.gF.wz])b.tq=
c;b.Cf=a[z.gF.zc];b.aj=(0,z.xl)(a[z.gF.Yy]);c=a[z.gF.$y];b.Nf=(0,z.fa)(c)?c:!0;c=a[z.gF.Tz];b.yq=(0,z.fa)(c)?c:!0;b.mj=a[z.gF.kA]||[];b.Bu=a[z.gF.tz]||!1;b.Xw=a[z.gF.pK]||null;return b};(0,z.w)(BJ,z.Aj);BJ.prototype.Zx=function(a){this.mi=new z.Mt(this);this.Jt=new z.Ip(this,a);this.Bc=new z.Bf(this);this.Za=new z.iu(this,a);this.vl=new z.pu(this);this.v=new z.Yt(this,a);this.tb=new z.VE(this,a);new z.jf;this.wo=new z.iv(this,a);this.Bb=new z.Ex(this)};(0,z.w)(CJ,z.rE);z.e=CJ.prototype;z.e.s=function(){var a={},b=this.d.v,c=b.w();a.Sw=b.w().$d();a.$S=!z.K.get(z.K.j.Zc);a.ol=b.ol(z.K.id);a.nN=2===c.get(z.V.rk);a.mN=3===c.get(z.V.rk);a.k={jS:z.X.get(z.X.g.kt),mS:z.X.get(z.X.g.lt),zR:z.X.get(z.X.g.lA),dx:z.X.get(z.X.g.qt),ex:z.X.get(z.X.g.rt),oo:z.X.get(z.X.g.pB),Go:z.X.get(z.X.g.wp),zV:z.X.get(z.X.g.FB)};return a};
z.e.F=function(a){CJ.b.F.call(this,a);a=this.c;var b;b=this.s();var c=(0,z.Sp)(b),d;d=b.Sw?'\x3ca class\x3d"fyre-follow-conversation"\x3e'+(b.$S?b.ol?(0,z.R)(b.k.mS):(0,z.R)(b.k.jS):"")+"\x3c/a\x3e":"";b=c+d+'\x3cdiv class\x3d"fyre-stream-sort"\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+(0,z.R)(b.k.dx)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+(0,z.R)(b.k.oo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
(0,z.R)(b.k.ex)+"\x3c/a\x3e"+(b.nN?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+(0,z.R)(b.k.oo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-top-comments"\x3e'+(0,z.R)(b.k.zV)+"\x3c/a\x3e":"")+(b.mN?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+(0,z.R)(b.k.oo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-hot-threads"\x3e'+(0,z.R)(b.k.zR)+"\x3c/a\x3e":"")+'\x3c/div\x3e\x3ca class\x3d"fyre-stream-sort-back"\x3e\x3c/a\x3e\x3c/div\x3e';a.innerHTML=b;this.Yk=this.n("fyre-follow-conversation");this.xs=
this.n("fyre-stream-sort-hot-threads")||null;this.qy=this.n("fyre-stream-sort-top-comments")||null;this.pg=this.n("fyre-stream-sort-back");this.Rl=this.n("fyre-stream-sort-newest");this.py=this.n("fyre-stream-sort-oldest");this.yH=this.n("fyre-stream-sort-options");this.Vc=this.n("fyre-content-loading");this.xd()};z.e.l=function(){CJ.b.l.call(this);var a=this.o();z.K.on(z.K.ta.Xe,this.xn,this);a.e(this.c,"click",this.Xa);(0,z.y)([3,4,5],function(b){(0,z.sE)(this,a,b)},this);DJ(this,a)};
z.e.Xa=function(a){a.preventDefault();a=a.target;if(!(0,z.Zh)(a,"fyre-stream-sort-selected")&&"A"===a.tagName&&a!==this.pg)if(a===this.Yk)this.zE();else switch(EJ(this,a),this.Ql(),a){case this.xs:this.sD();break;case this.qy:this.dispatchEvent({type:"sortTopComments",Cb:(0,z.u)(this.xd,this)});break;case this.Rl:this.Sm("new");break;case this.py:this.Sm("old")}};z.e.hi=function(a,b){a&&this.$x(b);(0,z.Rm)(this.yH,"display",a?"none":"block");(0,z.Rm)(this.pg,"display",a?"block":"none")};
z.e.$x=function(a){var b=this.Rl,c=this.Sm,d=z.X.get(z.X.g.Us);4===a&&(b=this.xs,c=this.sD,d=z.X.get(z.X.g.DI));this.pg.innerHTML=d;this.o().dg(this.pg,"click",(0,z.u)(function(a){a.stopPropagation();this.hi(!1);EJ(this,b);c.apply(this)},this))};z.e.un=function(a){a.stopPropagation();this.hi(!1);EJ(this,this.Rl);this.Sm()};z.e.Zq=function(a){var b=a.Cb;(0,z.E)(a,{Cb:(0,z.u)(function(){b();this.hi(!0,4)},this)})};
z.e.Sm=function(a){this.dispatchEvent({type:"sortOrderChanged",direction:a||"new",Cb:(0,z.u)(this.xd,this)})};z.e.sD=function(){this.dispatchEvent({type:"sortHotThreads",Cb:(0,z.u)(this.xd,this)})};z.e.zE=function(){var a=this.d.v;a.w();var b=z.K.j;z.K.id?(b=a.ol(z.K.get(b.$)),a.dj(!b),a=b?z.X.get(z.X.g.kt):z.X.get(z.X.g.lt),this.Yk.innerHTML=a):(0,z.Kh)(this.d.Bc,(0,z.u)(this.zE,this))};
z.e.xn=function(){var a=this.d.v,b=a.w(),c=z.K.j,b=!b.$d()||z.K.get(c.Zc);this.Yk&&(b?(0,z.S)(this.Yk,!1):(a=a.ol(z.K.id)?z.X.get(z.X.g.lt):z.X.get(z.X.g.kt),this.Yk.innerHTML=a,(0,z.S)(this.Yk,!0)))};z.e.h=function(){CJ.b.h.call(this);z.K.off(null,null,this)};(0,z.w)(FJ,CJ);FJ.prototype.F=function(a){this.c=a;(0,z.Bl)(a,yJ,this.s());this.Rl=this.n("fyre-stream-sort-newest");this.py=this.n("fyre-stream-sort-oldest");this.yH=this.n("fyre-stream-sort-options");this.Vc=this.n("fyre-content-loading");this.xd()};FJ.prototype.Sm=function(a){this.dispatchEvent({type:"archiveSortOrderChanged",ki:this.mV.ki,direction:a,Cb:(0,z.u)(this.xd,this)})};
FJ.prototype.s=function(){return{k:{pM:z.X.get(z.X.g.xI),dx:z.X.get(z.X.g.qt),ex:z.X.get(z.X.g.rt),oo:z.X.get(z.X.g.pB),Go:z.X.get(z.X.g.wp)}}};(0,z.w)(GJ,z.rw);z.e=GJ.prototype;z.e.Im=function(a){this.clear();(0,z.S)(this.c,!0);this.dd=a};z.e.clear=function(){this.bd.Bd();this.ob={};this.nj=[];this.dh=this.Fk=null;for(this.ys=[];this.ia&&0!=this.ia.length;)this.co(0).r()};z.e.F=function(a){GJ.b.F.call(this,a);(0,z.Bl)(this.c,z.Tp,this.s());this.Sj=this.n("fyre-stream-content");this.ii=this.n("fyre-stream-more");this.Ma.P(this.ii);(0,z.S)(this.ii,!1)};z.e.h=function(){this.Ma&&this.Ma.r();this.Ma=null;GJ.b.h.call(this)};
z.e.l=function(){GJ.b.l.call(this);this.o().e(this.Ma,"showMore",this.cw)};z.e.s=function(){return{qd:z.x.K.rb,tD:!!this.Ma,k:{gy:z.X.get(z.X.g.yI)}}};z.e.dw=function(){this.Ma.us()};z.e.vx=function(){this.dispatchEvent({type:this.yt,direction:this.dd,target:this,Cb:(0,z.u)(this.dw,this),cj:(0,z.u)(this.YE,this)})};z.e.vo=function(){var a=this.J.tb.Bk,b=this.dd,c=a.d.v.w(),b="old"===b,c=c.get(z.V.Zo),c=!b&&a.Nm>-c;b&&-1>a.Nm||c?this.Ma.show():this.Ma.kb()};
z.e.start=function(){this.ll||(this.vx(),this.ll=!0)};(0,z.w)(HJ,z.pE);HJ.prototype.s=function(){var a=this.m.get(z.V.Mc),b,c;this.m.$d()?(b=z.X.get(z.X.g.dK),c=z.X.get(z.X.g.qA)):(b=z.X.get(z.X.g.Kf),c=z.X.get(z.X.g.gm));(0,z.Ea)(b,"%s")||(b="%s "+b);(0,z.Ea)(c,"%s")||(c="%s "+c);switch(a){case 1:b=(0,z.ua)(b,a);break;default:b=(0,z.ua)(c,a)}return{k:{pu:b}}};HJ.prototype.Py=function(){var a=this.c,b;b=this.s();b="\x3cspan\x3e"+(0,z.R)(b.k.pu)+"\x3c/span\x3e";a.innerHTML=b};(0,z.w)(IJ,z.Ws);IJ.prototype.yo=200;IJ.prototype.Hh=function(){return new JJ(this.Ac)};IJ.prototype.s=function(){var a={};a.message=this.Hy;return a};(0,z.w)(JJ,z.Qs);
JJ.prototype.Hc=function(a,b,c){var d=(0,z.rn)(this.element),d=new z.sh(d.width,d.height+25);b=(0,z.Ls)(this.element,this.rh,a,b,d,c,9);(0,z.Ym)(a.lastChild,0);b&&(d=new z.sh(0,-5),(0,z.Ls)(this.element,2,a,1,d,c,5),(0,z.Ym)(a.lastChild,a.offsetWidth-(this.element.offsetParent.offsetWidth-this.element.offsetLeft+this.element.offsetWidth/2)))};(0,z.w)(KJ,z.U);z.e=KJ.prototype;z.e.q=function(){this.c=(0,z.El)(xJ,this.s())};z.e.l=function(){KJ.b.l.call(this);this.Ra=new IJ(this.c,this.m.get("displayName"));this.o().e(this.c,"click",this.Xa)};z.e.h=function(){KJ.b.h.call(this);this.Ra&&this.Ra.r()};z.e.s=function(){var a=z.Od,b={};b.sd=this.m.get(a.qb);b.Vb=this.m.get(a.ck);b.Y=this.m.get(a.sa);b.id=this.m.id;b.CR=this.m.id.replace(/[@.]/g,"-");b.Aa=this.m.get(a.Sb);return b};
z.e.Xa=function(a){a.preventDefault();a.stopPropagation();this.dispatchEvent({t:this.m,type:"author_click"})};(0,z.w)(LJ,z.U);z.e=LJ.prototype;z.e.uA=10;z.e.h=function(){LJ.b.h.call(this);delete this.Yb};z.e.Q=function(){LJ.b.Q.call(this);this.Yb.off(null,null,this)};z.e.iE=function(a){a=new KJ(a);var b=this.Qc();if(b===this.uA){var c=this.co(b-1);c&&(c.r(),b--)}0<b?this.qe(a,0,!0):this.D(a,!0)};z.e.HQ=function(a){var b;this.gd(function(c){a.id===c.m.id&&(b=c)});b&&(this.removeChild(b),b.r())};
z.e.Lh=function(){this.Yb.on(this.Yb.ta.Ss,this.iE,this);this.Yb.on(this.Yb.ta.vt,this.HQ,this);var a=this.Yb.Lb.reverse().slice(0,this.uA);(0,z.y)(a,this.iE,this)};(0,z.w)(MJ,LJ);(0,z.w)(NJ,z.qE);NJ.prototype.F=function(a){NJ.b.F.call(this,a);this.Ij()};NJ.prototype.Ij=function(){this.c.innerHTML=(0,z.Xp)(this.s())};(function(a,b){function c(){var a=A.elements;return"string"==typeof a?a.split(" "):a}function d(a){var b={},d=a.createElement,f=a.createDocumentFragment,g=f();a.createElement=function(a){A.TU||d(a);var c;c=b[a]?b[a].cloneNode():k.test(a)?(b[a]=d(a)).cloneNode():d(a);return c.canHaveChildren&&!h.test(a)?g.appendChild(c):c};a.createDocumentFragment=Function("h,f","return function(){var n\x3df.cloneNode(),c\x3dn.createElement;h.shivMethods\x26\x26("+c().join().replace(/\w+/g,function(a){b[a]=d(a);g.createElement(a);
return'c("'+a+'")'})+");return n}")(A,g)}function f(a){var b;if(a.rN)return a;if(A.SU&&!m){b=a.createElement("p");var c=a.getElementsByTagName("head")[0]||a.documentElement;b.innerHTML="x\x3cstyle\x3earticle,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}audio{display:none}canvas,video{display:inline-block;*display:inline;*zoom:1}[hidden]{display:none}audio[controls]{display:inline-block;*display:inline;*zoom:1}mark{background:#FF0;color:#000}\x3c/style\x3e";b=!!c.insertBefore(b.lastChild,
c.firstChild)}r||(b=!d(a));b&&(a.rN=b);return a}var g={},h=/^<|^(?:button|form|map|select|textarea|object|iframe)$/i,k=/^<|^(?:a|b|button|code|div|fieldset|form|h1|h2|h3|h4|h5|h6|i|iframe|img|input|label|li|link|ol|option|p|param|q|script|select|span|strong|style|table|tbody|td|textarea|tfoot|th|thead|tr|ul)$/i,m,r;(function(){var c=b.createElement("a");c.innerHTML="\x3cxyz\x3e\x3c/xyz\x3e";(m="hidden"in c)&&"function"==typeof a.OR&&a.OR("#modernizr{}",function(b){b.hidden=!0;m="none"==(a.getComputedStyle?
a.getComputedStyle(b,null):b.currentStyle).display});r=1==c.childNodes.length||function(){try{b.createElement("a")}catch(a){return!0}var c=b.createDocumentFragment();return"undefined"==typeof c.cloneNode||"undefined"==typeof c.createDocumentFragment||"undefined"==typeof c.createElement}()})();var A={elements:g.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",shivCSS:!1!==g.SU,shivMethods:!1!==
g.TU,type:"default",shivDocument:f};f(b)})(z.v.window,z.v.document);(0,z.w)(OJ,z.zE);
OJ.prototype.TG=function(a,b){if(!this.Fa){this.u=b;var c=b.get(z.V.wg),d=b.get(z.V.Kd);this.Ms=new z.wE(c,d,a.V.Ka);this.D(this.Ms);this.Yp=new HJ(a.v.w());this.D(this.Yp);this.Hr=null;b.Fn()&&(this.Tt=new FJ(a),this.D(this.Tt),this.Ck=new GJ(a),this.D(this.Ck),uJ(this.Tt,{ki:this.Ck}));this.$g=new CJ(a);this.D(this.$g);this.Ar((0,z.u)(function(a){this.Gb=a;this.D(this.Gb);a=this.Gb;this.aa&&a&&a.P(this.xe,!0)},this));b.get(z.V.mm)&&!z.Yf&&vJ(this.u)&&(this.u.Qg()||this.u.$d()||this.Hv())}};
OJ.prototype.s=function(){var a=!this.d.V.Gm&&!z.x.Au&&!this.d.V.Bu;return{SH:z.x.K.Iy,TH:(0,window.encodeURIComponent)(String(window.location.href)),Ka:this.d.V.Ka,Qg:this.u.Qg(),$d:this.u.$d(),Hu:a,UR:this.d.V.Gm,Fn:this.u.Fn()}};z.Fw={bW:"fyre-archive-stream",cW:"fyre-archive-stream-header",wZ:"fyre-top-content-stream",OZ:"fyre-widget",mm:"fyre-featured-content-wrapper"};(0,z.E)(z.Fw,z.bI);z.e=OJ.prototype;
z.e.q=function(){this.c=(0,z.El)(wJ,this.s());var a=this.u.get(z.V.rk);if(1!==a){var b=this.d.Bb,a=2===a?3:4,c=this.n("fyre-top-content-stream");(0,z.Fx)(b,a,c,this)}this.er.P(this.n(z.Fw.QJ));this.Ck&&(b=this.n("fyre-archive-stream-header"),this.Tt.P(b),this.Ck.P(this.n("fyre-archive-stream")));this.sh(1);this.xe=this.n(z.Fw.ih);b=PJ(this);(0,z.S)(this.xe,b)};
z.e.l=function(){OJ.b.l.call(this);var a=this.Gb;this.aa&&a&&a.P(this.xe,!0);this.d.O.Io("stream_data_received",this.FP,this);this.o().e(this,"request_content_context",this.fP).e(this,"request_content_reply",this.JQ);this.Ck&&this.Ck.start()};z.e.Lh=function(){this.bn&&this.bn.Lh();this.fg.Lh()};z.e.FP=function(){var a=this.u,b=a.get(z.V.fk);z.mh||b||(b=(0,z.u)(function(){this.Hr=new z.UJ(this.d,a.get(z.V.Kd));this.D(this.Hr,!0)},this),(0,z.oc)(z.x.K.rb+z.x.uf.Hr,null,null,b))};
z.e.Hv=function(){var a=new z.hD(this.KF,this);a.wG=(0,z.u)(this.qU,this);var b=(0,z.u)(function(){a.start(0,2E3)},this);(0,z.oc)(z.x.K.rb+z.x.uf.SN,null,null,b)};z.e.qU=function(){var a=this.n("fyre-featured-content-wrapper");this.Uu=new z.rI(this.d);this.D(this.Uu);this.Uu.P(a);this.Uu.Pg()};z.e.Ar=function(a){if(!this.d.V.readOnly){var b=this.d.v.w();(0,z.Dv)(z.Av.C(),"main",a,{J:this.d,ci:"new"},b);z.K.on(z.K.dc(z.K.j.$),this.Rc,this)}};z.e.Rc=function(){var a=PJ(this);(0,z.S)(this.xe,a)};
z.e.Kh=function(){0<(0,z.Hn)(this,this.Gb)&&(this.removeChild(this.Gb),this.Gb.r());this.Ar((0,z.u)(function(a){this.Gb=a;this.D(this.Gb);a=this.Gb;this.aa&&a&&a.P(this.xe,!0);(0,z.S)(this.xe,!0)},this))};z.e.Oh=function(a){null!=a&&(this.d.Bb.dl(1),(0,window.setTimeout)((0,z.u)(function(){this.Fa||(0,z.AE)(this,a)},this),3E3))};z.e.fP=function(a){(0,z.AE)(this,a.Hk)};z.e.JQ=function(a){(0,z.AE)(this,a.Hk,function(a){(0,z.zv)(a.Nb)})};
z.e.h=function(){OJ.b.h.call(this);z.K.off(z.K.dc(z.K.j.$),this.Rc,this);this.u&&(this.u.off(null,null,this),this.u=null)};(0,z.w)(QJ,z.Ux);z.e=QJ.prototype;z.e.Xd=function(a,b){QJ.b.Xd.call(this,a,b);a.e(b,"repliesExpanded",this.wE);a.e(b,"sortHotThreads",this.SQ);a.e(b,"sortOrderChanged",this.aF);a.e(b,"sortTopComments",this.TQ);a.e(b,"archiveShowMore",this.QO);a.e(b,"archiveSortOrderChanged",this.RO)};
z.e.QO=function(a){var b=a.Cb||z.n;a=(0,z.u)(this.Ce,this,a.target);var c=this.d.tb;c.Bk||(c.Bk=new tJ(c.J));var c=c.Bk,d=sJ(c),f=c.he[d];f&&(c.Nm=d);if(f)b(),a(f);else{c=this.d.tb.Zk();d=c.j.Ye;if(c.get(d))b();else c.on(c.dc(d),b,this);(0,z.Vx)(this,c,a)}};z.e.Cv=function(a,b){var c=2===b.pd,d=1!==b.pd;switch(b.type){case 0:var f=this.d.v.w(),f=(0,z.pk)(b,f),g=f.get(z.Ck),g=this.d.v.Ya().get(g);f.set(z.qk,g);a.Uv(f,c,d)}};
z.e.TE=function(a){if(1!==this.wm){var b=this.gV.$g;b.hi(!1);EJ(b,b.Rl);(0,z.E)(a,{direction:"new",Cb:z.n});this.aF(a)}};z.e.RO=function(a){(0,z.Wx)(this);a.ki.Im(a.direction);var b=this.d.tb.Zk(a.direction,!0),c=(0,z.u)(function(b){a.Cb();this.Ce(a.ki,b)},this);(0,z.Vx)(this,b,c,a.cj)};z.e.aF=function(a){var b=(0,z.Yx)(this,1);(0,z.Xu)(this.d.tb);b.Im(a.direction);var c=(0,z.Wu)(this.d.tb,a.direction),d=(0,z.u)(function(c){a.Cb();this.Ce(b,c)},this);(0,z.Vx)(this,c,d,a.cj)};
z.e.TQ=function(a){var b=(0,z.Yx)(this,3),c=this.d.tb.Ch("likes");(0,z.Vx)(this,c,(0,z.u)(function(c){a.Cb();(0,z.sb)(c)?(0,z.qw)(b):this.Ce(b,c)},this))};z.e.SQ=function(a){var b=(0,z.Yx)(this,4),c=this.d.tb.Fh();(0,z.Vx)(this,c,(0,z.u)(function(c){a.Cb();(0,z.sb)(c)?(0,z.qw)(b):this.Ce(b,c)},this))};(0,z.w)(RJ,z.Nr);z.e=RJ.prototype;z.e.c=null;z.e.h=function(){RJ.b.h.call(this);this.As.r();this.KC.r();this.Qb.aa&&this.Qb.r();this.If&&this.If.r();delete this.If};z.e.kl=function(a){RJ.b.kl.call(this,a);this.As=new QJ(this.d);this.As.handle(a);this.KC=new z.Tx(this.d);this.KC.handle(a)};z.e.xy=function(){this.d.mi.stop()};z.e.lV=function(){this.d.vl.stop()};z.e.Pj=function(){this.d.mi.start()};z.e.jV=function(){this.d.vl.start()};
z.e.pa=function(){this.If&&this.If.r();this.Qb.pa(this.c);var a=(0,z.Pr)(this);this.Qb.Oh(a);this.d.O.M("render_complete")};(0,z.w)(SJ,z.pl);SJ.prototype.$B=AJ.C();SJ.prototype.h=function(){SJ.b.h.call(this);this.stop();delete this.V;delete this.ka;TJ(this);(0,z.ul)(this);this.bj&&(this.bj.r(),delete this.bj)};SJ.prototype.Ey=function(){this.stop();TJ(this);SJ.b.Ey.call(this)};z.fg.main.uh.ga(SJ);})(fyre.conv);
