/*Copyright (c) 2011-2013 Moat Inc. All Rights Reserved.*/
try{(function(){function S(){for(var a in m)m.hasOwnProperty(a)&&h.e.i(m[a]);for(a=0;a<I.length;a++)window.clearTimeout(I[a]);for(a=0;a<M.length;a++)window.clearInterval(M[a]);h.f.k()}var h={};(function(a){function j(a){var c=RegExp("(^| )"+a+"($| )");return function(a){return a&&a.className&&a.className.match(c)}}a.a={};a.a.a=3E3;a.a.b=function(){var a=/Firefox\/(\d+)/.exec(navigator.userAgent);return a?14<parseInt(a[1],10):!1}();a.a.c=function(){var g=a.a.d();return 5===g||6===g||7===g};a.a.d=function(){if(!navigator)return null;
var a=navigator.userAgent;return"Microsoft Internet Explorer"==navigator.appName?parseInt(a.replace(/^.*MSIE (\d+).*$/,"$1"),10):"Netscape"==navigator.appName&&(a=a.match(/Trident\/.*rv:(\d+)/))?parseInt(a[1],10):null};a.a.e=function(a,c){for(var b=0;b<a.length;b++)if(a[b]===c)return!0;return!1};a.a.getElementsByClassName=function(a,c,b){c=c||"*";b=b||document;if(b.getElementsByClassName){var d=[],e=b.getElementsByClassName(a);if("*"!==c){a=0;for(b=e.length;a<b;a++){var f=e[a];f.tagName===c&&d.push(f)}return d}return e}e=
[];c=b.getElementsByTagName(c);b=j(a);f=c.length;for(a=0;a<f;a++)d=c[a],b(d)&&e.push(d);return e};a.a.f=function(a){return new Date-a.de};a.a.g=function(a){return a.replace(/^http:/,"").replace(/^\/\//,"").replace(/^www[^.]*\./,"").split("/")[0]};a.a.h=function(){return null!==/iPad|iPhone|iPod|Silk|Kindle|Android|BlackBerry|PlayBook|BB10|Windows Phone/.exec(navigator.userAgent)};a.a.i=function(){var a=window;try{return"undefined"!==typeof a.external&&"undefined"!==typeof a.external.InPrivateFilteringEnabled&&
a.external.InPrivateFilteringEnabled()||"undefined"!==typeof a.external&&"undefined"!==typeof a.external.msTrackingProtectionEnabled&&a.external.msTrackingProtectionEnabled()||"undefined"!==typeof a._gaUserPrefs&&a._gaUserPrefs.ioo&&a._gaUserPrefs.ioo()||"undefined"!==typeof navigator.doNotTrack&&("yes"===navigator.doNotTrack||!0===navigator.doNotTrack)||"undefined"!==typeof a._gaUserPrefs&&!0===a._gaUserPrefs}catch(c){return!1}};a.a.getAttribute=function(a,c){return a[c]||a.getAttribute(c)};a.a.j=
function(a){var c=0,b;for(b in a)a.hasOwnProperty(b)&&(c+=1);return c};a.a.k=function(g){return!a.a.l(g)||!0===g[t]?!1:!0};a.a.l=function(g){return g.offsetWidth*g.offsetHeight>=a.a.a};a.a.m=function(a,c){var b=!1,d=c.body,e=d&&d.firstChild;d&&e&&(d.insertBefore(a,e),b=!0);return b};a.a.n=function(){for(var a=document.getElementsByTagName("script"),c,b=a.length-1;-1<b;b--)if((c=a[b])&&(c.src&&c.src.indexOf&&-1!==c.src.indexOf(X+"/moatad.js"))&&!("undefined"!==typeof c[t]&&!0===c[t]))return c[t]=!0,
c;return null};a.a.o=function(a){try{return-1!==(a.src||a.getAttribute("src")).indexOf("psd=1")}catch(c){return!1}};a.a.p=function(a){for(var c=[],b=0;b<a.length;b++)c.push(a[b]);return c};a.a.previousElementSibling=function(a){if(a.previousElementSibling)return a.previousElementSibling;for(;a=a.previousSibling;)if(1===a.nodeType)return a};a.a.q=function(a,c,b){"undefined"!==typeof b&&(a[c]=b)};a.a.filter=function(a,c){for(var b=[],d=0;d<a.length;d++)c(a[d])&&b.push(a[d]);return b};a.a.r=function(a,
c){for(var b=[],d=0;d<c.length;d++)b.push(a(c[d]));return b}})(h);(function(a){function j(a){try{var b=typeof a.location.toString;if("undefined"===b||"unknown"===b)return!0;var d=typeof a.document;return"undefined"===d||"unknown"===d?!0:!1}catch(e){return!0}}a.b={};a.b.a="MoatSuperV4";a.b.b=0;a.b.c=-1!==navigator.userAgent.toLowerCase().indexOf("firefox");a.b.d=-1!==navigator.userAgent.indexOf("MSIE");a.b.e=(new Date).getTime();a.b.protocol=function(){var a;try{a=window.location.protocol}catch(b){a=
document.createElement("a"),a.href="",a=a.protocol}return a}();a.b.f=("https:"===a.b.protocol?"z":"js")+".moatads.com";a.b.g=window!=window.parent;var g=j(window.parent);a.b.h=a.b.g&&!g;a.b.i=g?!1:!j(window.top);a.b.j=a.b.i?window.top:a.b.h?window.parent:window;a.b.k=a.b.j.document.referrer})(h);(function(a){function j(a){return function(){var b=!1;return function(d){try{a(d)}catch(e){if(!b){b=!0;d=e.name+" in callback: "+e.message+", stack="+e.stack;try{var f="//v3.moatads.com/pixel.gif?e=24&d=data%3Adata%3Adata%3Adata&i="+
escape("USATODAYSMG1")+"&ac=1&k="+escape(d)+"&ar="+escape("622c351-clean")+"&j="+escape(document.referrer)+"&cs="+(new Date).getTime();(new Image(1,1)).src=f}catch(i){}}}}}()}a.c={};var g={};a.c.a=function(a,b,d,e){d=j(d);a.addEventListener?a.addEventListener(b,d,!1):a.attachEvent("on"+b,d);!1!==e&&(g[b+e]=d)};a.c.b=function(a,b,d,e){var f=b+e,d=!1!==e?g[f]:d;try{a&&a.removeEventListener?a.removeEventListener(b,d,!1):a&&a.detachEvent&&a.detachEvent("on"+b,d)}catch(i){}delete g[f]};a.c.c=function(a,
b){var a=j(a),d=setInterval(a,b);M.push(d);return d};a.c.d=function(a,b){var a=j(a),d=setTimeout(a,b);I.push(d);return d};a.c.e=function(c,b,d,e){var f=0,i=function(){f+=1;!0!==c()&&(f<b?a.c.d(i,d):"function"===typeof e&&e())};i()}})(h);(function(a){function j(){this.height=this.width=this.absTop=this.absLeft=0;this.update=function(a){this.absLeft=a.left+e("left",a.win);this.absTop=a.top+e("top",a.win);this.width=a.width;this.height=a.height}}function g(b,d){var c=b.zr;i.hasOwnProperty(c)||(i[c]=
new j);var e=d||new a.d.h(b.aa);i[c].update(e)}function c(a,b){for(var d=[],c=0;c<b.length;c++)d.push(a(b[c]));return d}function b(b){var d,e=a.e.b(b.el,b.win),e=c(function(b){return new a.d.h(b)},e);e.unshift(b);for(var f=e.length,b=new a.d.h(b.el,a.b.j),i=0;i<f;i++){var g=e[i];0===i?d=g:(d.changeReferenceFrame(g),b.changeReferenceFrame(g));g=g.getViewportRect(i<f-1?e[i+1]:!1);d=a.d.j(d,g)}return{visibleRect:d,cumulRect:b,parentArea:e[e.length-1].calcArea()}}function d(a,b,d,c){a=Math.max(a,d);b=
Math.min(b,c);return b>a?[a,b]:[0,0]}function e(a,b){var d=b.document.documentElement,c=b.document.body;return"left"===a?b.pageXOffset||d&&d.scrollLeft||c&&c.scrollLeft:b.pageYOffset||d&&d.scrollTop||c&&c.scrollTop}a.d={};var f=a.b.i,i={};a.d.a=0.5;a.d.b=0.3;a.d.c=236425;a.d.d=function(d,c){if(1==d.ao.skin)return{isVisible:!0};var e;e=new a.d.h(d.aa,c);g(d,e);var f=e.height,i=e.width,j=e.calcArea();if(0===j)e={area:j,percv:0};else{var o=b(e),x=o.visibleRect.calcArea(),B=x/j,h;b:{var r=o.cumulRect,
v=o.cumulRect.getViewportRect();if(0>r.top&&0<r.bottom)h=-r.top;else if(0<=r.top&&r.top<=v.height)h=0;else{h={yMin:-1,yMax:-1};break b}if(0<=r.bottom&&r.bottom<=v.height)r=r.height;else if(r.bottom>v.height&&r.top<v.height)r=r.height-(r.bottom-v.height);else{h={yMin:-1,yMax:-1};break b}h={yMin:h,yMax:r}}e={area:j,visibleArea:x,percv:B,yMinMax:h,elGeo:{elHeight:f,elWidth:i,foldTop:o.cumulRect.top,totalArea:o.parentArea},rect:e.rect}}f=a.d.e(e,d);e.isVisible=e.percv>=f;e.elGeo&&(e.elGeo.threshold=f);
return e};a.d.e=function(b,d){return b.area>=a.d.c?(d.viewstats.isBigAd=!0,a.d.b):a.d.a};a.d.f=function(){return f};a.d.g=function(a,b){(!f||!i.hasOwnProperty(b))&&g(a);return i[b]};a.d.i=function(a){var b,d,c,e=0,f=0;try{b=a.document,d=b.documentElement,c=b.body}catch(o){return{width:e,height:f,left:0,right:e,top:0,bottom:f}}"undefined"!==typeof a.innerWidth?(e=a.innerWidth,f=a.innerHeight):("CSS1Compat"!==b.compatMode||5===b.documentMode)&&c&&"undefined"!==typeof c.clientWidth?(e=c.clientWidth,
f=c.clientHeight):d&&"undefined"!==typeof d.clientWidth&&(e=d.clientWidth,f=d.clientHeight);return{width:e,height:f,left:0,right:e,top:0,bottom:f}};a.d.h=function(b,d,c){this.rect=c||b.getBoundingClientRect();for(var c=["left","right","top","bottom"],e=0;e<c.length;e++){var f=c[e];this[f]=this.rect[f]}this.width=this.right-this.left;this.height=this.bottom-this.top;this.el=b;this.win=d||b&&a.e.a(b);this.changeReferenceFrame=function(a){this.left+=a.left;this.right+=a.left;this.top+=a.top;this.bottom+=
a.top};this.calcArea=function(){return(this.right-this.left)*(this.bottom-this.top)};this.getViewportRect=function(b){var d=a.d.i(this.win);if(b&&(b.width<d.width&&(d.width=b.width,d.right=d.left+d.width),b.height<d.height))d.height=b.height,d.bottom=d.top+d.height;return d}};a.d.j=function(b,c){var e=d(b.left,b.right,c.left,c.right),f=d(b.top,b.bottom,c.top,c.bottom);return new a.d.h(void 0,void 0,{left:e[0],right:e[1],top:f[0],bottom:f[1]})}})(h);(function(a){function j(){a.focus.pageIsVisible(!0)&&
((new Date).getTime()-i>=s&&e?(a.f.k(),a.f.i(m[B])):k||(k=!0,a.c.d(function(){k=!1;j()},o)))}function g(){a.c.e(function(){var b=d.getElementById("moatPx"+B),o=d.getElementById("moatPxEmbed"+B);c(b)?(e=b,f=b.parentNode):c(o)&&(e=o,f=b.parentNode);if(!1!==e){a.f.g?a.f.d=e.setConfig(r):a.f.f?a.f.d=e.setConfig(r):e.setConfig(K);a.f.b&&(a.f.b="off"===a.f.d);if(8===u&&"iescope"===a.f.d){var x=function(){try{var b=parseInt(e.style.top,10);e.style.top=b<0?b+1E4+"px":b-1E4+"px";a.c.d(x,100)}catch(d){}};a.c.d(x,
16)}return!0}},t,L)}function c(a){try{return a&&(a.getStats||"undefined"!==typeof a.getStats||a.getStats())&&!0}catch(b){return!1}}function b(a,b,d){var c=document.createElement("param");c.setAttribute("name",b);c.setAttribute("value",d);a.appendChild(c)}a.f={};a.f.a=function(){function a(b){b=b.match(/[\d]+/g);b.length=3;return b.join(".")}var b=!1,d="";if(navigator.plugins&&navigator.plugins.length){var c=navigator.plugins["Shockwave Flash"];c&&(b=!0,c.description&&(d=a(c.description)));navigator.plugins["Shockwave Flash 2.0"]&&
(b=!0,d="2.0.0.11")}else if(navigator.mimeTypes&&navigator.mimeTypes.length)(b=(c=navigator.mimeTypes["application/x-shockwave-flash"])&&c.enabledPlugin)&&(d=a(c.enabledPlugin.description));else try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),b=!0,d=a(c.GetVariable("$version"))}catch(o){try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),b=!0,d="6.0.21"}catch(e){try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),b=!0,d=a(c.GetVariable("$version"))}catch(x){}}}return b?parseFloat(d,
10):"0"}();a.f.b=!1;a.f.c="";a.f.d="default";var d,e=!1,f,i=0,k=!1,u=a.a.d(),A=null!==u,h=-1!==navigator.userAgent.indexOf("Chrome"),p=6.2<=function(){var a=navigator.appVersion.match(/Windows NT (\d\.\d)/);return a?parseFloat(a[1]):-1}(),s=1E3,o=200,x=a.b.protocol+"//"+a.b.f,B=!1;a.f.e=0<Object.prototype.toString.call(window.HTMLElement).indexOf("Constructor");a.f.f=!1;a.f.g=!1;var K={"default":{targetVersion:"*",lo:""}},r={iescope:{targetVersion:"*",lo:">="}};try{var v=a.a.d();if(7==v||8==v||9==
v||10==v||11==v)a.f.g=!0}catch(J){}var L=10,t=500,q=!0,w;a.f.h=function(){if(e&&e.getStats)try{"iescope"===a.f.d&&(q&&(q=!1,w=e.style.width),e.style.width=w!==e.style.width?w:parseInt(w,10)+1+"px");var b=e&&e.getStats();if(b&&b.ok)return"off"!==a.f.d&&(a.f.b=!0),a.f.c=b.rev,b}catch(d){}return!1};a.f.i=function(c){if(a.f.j()){var o=c.zr;try{var e=x+"/swf/p5.v1e.swf",f,k;k=A?f=2:f=1;var r=a.d.g(c,o),h="position: absolute; width: "+f+"px; height: "+k+"px; z-index: -9999;";a.f.f&&(h+="-webkit-transform: translate3d(0, 0, 0);");
var v=h+"left: "+r.absLeft+"px; top: "+(r.absTop+r.height/2)+"px;",h=h+"left: 0px; top: 0px;";c.ed.x=r.absLeft;c.ed.y=r.absTop;r="ym"+o;B=o;l.yl||(l.yl={});l.yl[r]=function(){g()};var n=c.aa.ownerDocument;("defaultView"in n?n.defaultView:n.parentWindow)[a.b.a]=l;var s="ol="+a.b.a+".yl."+r+"&db=false";d=n;if(p&&A&&10<=u)var K=function(){var a="moatPx"+o,d=n.createElement("OBJECT");d.setAttribute("data",e);d.setAttribute("id",a);d.setAttribute("name",a);d.setAttribute("style",v);d.setAttribute("width",
f+"");d.setAttribute("height",k+"");b(d,"flashvars",s);b(d,"wmode","transparent");b(d,"bgcolor","");b(d,"allowscriptaccess","always");var a=n.body,c=n.createElement("div");c.id="moatPxDiv"+o;c.style.width="0px";c.style.height="0px";a.insertBefore(c,a.firstChild);c.appendChild(d);return true};else var m='<object type="application/x-shockwave-flash" classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0" width="'+
f+'" height="'+k+'" style="'+v+'" id="moatPx'+o+'"><param name="allowScriptAccess" value="always" /><param name="allowFullScreen" value="false" /><param name="movie" value="'+e+'" /><param name="quality" value="low" /><param name="hasPriority" value="true" /><param name="FlashVars" value="'+s+'" /><param name="bgcolor" value="" /><param name="wmode" value="transparent" /><embed type="application/x-shockwave-flash" src="'+e+'" quality="low" flashvars="'+s+'" bgcolor="" wmode="transparent" width="'+
f+'" height="'+k+'" id="moatPxEmbed'+o+'" name="moatPx'+o+'" style="'+h+'" hasPriority="true" allowscriptaccess="always" allowFullScreen="false" type="application/x-shockwave-flash" pluginspage="http://www.adobe.com/go/getflashplayer" /></object>',K=function(){var b=n.createElement("div");b.id="moatPxDiv"+o;b.style.width="0px";b.style.height="0px";if(a.a.m(b,d)===true){b.innerHTML=m;try{b.getElementsByTagName("object")}catch(c){}return true}return false};i=(new Date).getTime();a.c.e(K,10,100);p&&
(A&&10<=u)&&a.focus.supportsPageVisAPI()&&a.c.a(d,a.focus.visibilitychange,j,o)}catch(L){}}};a.f.l=function(b,d){var c=a.f.m,o=b.aa.ownerDocument.getElementById("moatPx"+d);if(o){var e=o.parentNode;if(0!==e.id.indexOf("moatPxDiv")){var x=document.getElementById("moatPxDiv"+d);e.removeChild(o);x.appendChild(o)}e=a.d.g(b,d);e={left:e.absLeft+e.width/2,top:e.absTop+e.height/2};c(e,b.ed)&&(o.style.left=e.left+"px",o.style.top=e.top+"px",b.ed.x=e.left,b.ed.y=e.top)}};a.f.k=function(){f&&f.parentNode&&
(a.c.b(d,a.focus.visibilitychange,j,B),e.parentNode.removeChild(e),f.parentNode.removeChild(f),d=f=e=!1)};a.f.n=function(b){a.f.l(b,b.zr);isVisible=(b=a.f.h())?b.iv:!1;return{isVisible:isVisible}};a.f.j=function(){return A||h||a.f.f};a.f.m=function(a,b){return a&&(a.left!==b.x||a.top!==b.y)}})(h);(function(a){function j(a,b,d){a.IR5.MIN[d]=Math.min(b,a.IR5.MIN[d])||b||1;a.IR5.MAX[d]=Math.max(b,a.IR5.MAX[d])||b}function g(a,b){b.be=Math.max("undefined"!==typeof b.be?b.be:0,a-b.bf);"undefined"===typeof b.by&&
b.be>=s&&(b.by=b.bk)}function c(b){b.az===a.g.a.d.a?b.az=a.g.a.d.b:b.az===a.g.a.d.b&&(b.az=a.g.a.d.a)}function b(b){b.ba===a.g.a.d.a?b.ba=a.g.a.d.b:b.ba===a.g.a.d.b&&(b.ba=a.g.a.d.a)}function d(b){b.ax===a.g.a.b.a?b.ax=a.g.a.b.b:b.ax===a.g.a.b.b&&(b.ax=a.g.a.b.a)}function e(b){b.ay===a.g.a.c.a?b.ay=a.g.a.c.b:b.ay===a.g.a.c.b&&(b.ay=a.g.a.c.a)}function f(a,b){"undefined"===typeof b.bk&&(b.bk=0);b.bk+=a-b.bo;b.bo=a}function i(a,b){"undefined"===typeof b.bl&&(b.bl=0);b.bl+=a-b.bp;b.bp=a}function k(a,
b){"undefined"===typeof b.bg&&(b.bg=0);"undefined"===typeof b.bc&&(b.bc=0);b.bu=a-b.bs;b.bu>b.bc&&(b.bc=b.bu);b.bg+=a-b.bq;b.bc>=p&&"undefined"===typeof b.bw&&(b.bk+=a-b.bo,b.bw=b.bk);b.bq=a}function u(a,b){"undefined"===typeof b.bh&&(b.bh=0);"undefined"===typeof b.bd&&(b.bd=0);b.bv=a-b.bt;b.bv>b.bd&&(b.bd=b.bv);b.bh+=a-b.br;b.bd>=p&&"undefined"===typeof b.bx&&(b.bl+=a-b.bp,b.bx=b.bl);b.br=a}a.g={};var A=500,h=3E3,p=500,s=500;a.g.a={};a.g.a.a={};a.g.a.a.a=0;a.g.a.a.b=1;a.g.a.b={};a.g.a.b.a=0;a.g.a.b.b=
1;a.g.a.c={};a.g.a.c.a=0;a.g.a.c.b=1;a.g.a.d={};a.g.a.d.a=0;a.g.a.d.b=1;a.g.a.e={};a.g.a.e.a=0;a.g.a.e.b=1;a.g.a.f={};a.g.a.f.a=0;a.g.a.f.b=1;a.g.a.f.c=2;a.g.b=function(a){j(a,a.aj,"x");j(a,a.ak,"y");a.IR5.AREA=(a.IR5.MAX.x-a.IR5.MIN.x)*(a.IR5.MAX.y-a.IR5.MIN.y)};a.g.c=function(b){function d(){(new Date).getTime()-N>=A&&(a.g.d({type:"park"},b),clearInterval(e),b.au=a.g.a.a.a)}var c=b.au;if(c===a.g.a.a.a){N=(new Date).getTime();var e=a.c.c(d,50);b.au=a.g.a.a.b}else c===a.g.a.a.b&&(N=(new Date).getTime())};
a.g.e=function(b){function d(){(new Date).getTime()-O>=h&&(a.g.f({type:"park"},b),clearInterval(e),b.av=a.g.a.a.a)}var c=b.av;if(c===a.g.a.a.a){O=(new Date).getTime();var e=a.c.c(d,50);b.av=a.g.a.a.b}else c===a.g.a.a.b&&(O=(new Date).getTime())};a.g.g=function(b,d){var e=b.type;if(d.az===a.g.a.d.a){if("mouseover"===e||"mousemove"===e)d.bo=(new Date).getTime(),c(d)}else if(d.az===a.g.a.d.b){"mousemove"===e&&f((new Date).getTime(),d);if("mouseout"===e||"blur"===e)f((new Date).getTime(),d),c(d);"scooper"===
e&&f((new Date).getTime(),d)}};a.g.h=function(d,c){var e=d.type;if(c.ba===a.g.a.d.a){if("mouseover"===e||"mousemove"===e)c.bp=(new Date).getTime(),b(c)}else if(c.ba===a.g.a.d.b){"mousemove"===e&&i((new Date).getTime(),c);if("mouseout"===e||"blur"===e)i((new Date).getTime(),c),b(c);"scooper"===e&&i((new Date).getTime(),c)}};a.g.d=function(b,c){if(2!=c.an){var e=b.type;if(c.ax===a.g.a.b.a){if("mouseover"===e||"mousemove"===e)c.bq=(new Date).getTime(),c.bs=(new Date).getTime(),d(c)}else c.ax===a.g.a.b.b&&
(("mousemove"===e||"mouseout"===e)&&k((new Date).getTime(),c),"park"===e&&k((new Date).getTime()-A,c),("mouseout"===e||"park"===e)&&d(c))}};a.g.f=function(b,d){if(2!=d.an){var c=b.type;if(d.ay===a.g.a.c.a){if("mouseover"===c||"mousemove"===c)d.br=(new Date).getTime(),d.bt=(new Date).getTime(),e(d)}else d.ay===a.g.a.c.b&&(("mousemove"===c||"mouseout"===c)&&u((new Date).getTime(),d),"park"===c&&u((new Date).getTime()-h,d),("mouseout"===c||"park"===c)&&e(d))}};a.g.i=function(b,d){var c=b.type;if(d.bb==
a.g.a.e.a){if("mouseover"==c||"mousemove"==c)d.bf=(new Date).getTime(),d.bb=a.g.a.e.b}else d.bb==a.g.a.e.b&&("mouseout"==c?(g((new Date).getTime(),d),d.bb=a.g.a.e.a):("mousemove"==c||"scooper"==c)&&g((new Date).getTime(),d))}})(h);(function(a){function j(){if(!a.focus.pageIsPrerendered()){a.c.b(document,k,j,"pr");for(var b in m)m.hasOwnProperty(b)&&a.e.c(m[b])}}function g(a){"undefined"==typeof e&&(e=a)}a.focus={};var c=navigator.userAgent,c=-1<c.indexOf("Safari")&&-1==c.indexOf("Chrome")&&-1==c.indexOf("Chromium")&&
!w,b=(eval("/*@cc_on!@*/false")||document.documentMode)&&!w,d="undefined"!==typeof document.hasFocus,e,f={visible:0,hidden:1,prerender:2},i,k,u,h;"undefined"!==typeof document.hidden?(i="hidden",k="visibilitychange"):"undefined"!==typeof document.mozHidden?(i="mozHidden",k="mozvisibilitychange"):"undefined"!==typeof document.msHidden?(i="msHidden",k="msvisibilitychange"):"undefined"!==typeof document.webkitHidden&&(i="webkitHidden",k="webkitvisibilitychange");for(var n=["v","mozV","msV","webkitV"],
p=0;p<n.length;p++){var s=n[p]+"isibilityState";if("undefined"!==typeof document[s]){u=s;break}}h="undefined"!==typeof i;var o,x;"undefined"!==typeof window.requestAnimationFrame?o="requestAnimationFrame":"undefined"!==typeof window.webkitRequestAnimationFrame&&(o="webkitRequestAnimationFrame");x=c&&"string"==typeof o&&!h;var B=(new Date).getTime();x&&function v(){B=(new Date).getTime();window[o](v)}();a.focus.getFocusMethod=function(){return e};a.focus.visibilitychange=k;a.focus.setFocusListeners=
function(){if(navigator.appName==="Microsoft Internet Explorer"){a.c.a(q.document,"focusout",function(){l.yd()},false);a.c.a(q.document,"focusin",function(){l.ye()},false)}else{a.c.a(q,"blur",function(){l.yd()},false);a.c.a(q,"focus",function(){l.ye()},false)}};a.focus.getQueryString=function(){var a={};a.em=e;K&&(a.eo=1);typeof u!="undefined"&&(a.en=f[document[u]]);return a};a.focus.supportsPageVisAPI=function(){return h};a.focus.pageIsVisible=function(){if(a.focus.supportsPageVisAPI()){g(0);return!document[i]}if(x){g(1);
return(new Date).getTime()-B<100}if(b&&d){g(2);return document.hasFocus()}g(3);return true};a.focus.pageIsPrerendered=function(){return typeof u!=="undefined"?document[u]=="prerender":false};a.focus.pageIsVisible();a.focus.pageIsPrerendered()&&a.c.a(document,k,j,"pr");var K=a.focus.pageIsPrerendered();a.focus.windowHasFocus=function(){return l.v}})(h);(function(a){function j(b,d,c,e,f){("remove"===f?a.c.b:a.c.a)(b,d,function(d){var d=d||this.event,e=d.currentTarget||b,f=m[e[P]];if(f){var i;i=d;var k=
e.getBoundingClientRect();i=-1!=i.type.indexOf("touch")?{x:parseInt(i.changedTouches[0].clientX-k.left,10),y:parseInt(i.changedTouches[0].clientY-k.top,10)}:{x:parseInt(i.clientX-k.left,10),y:parseInt(i.clientY-k.top,10)};f.aj=i.x;f.ak=i.y;f.dm||(f.cb=2==a.focus.getFocusMethod()?f.counters.laxDwell.tCur:f.counters.strictDwell.tCur,f.dm=1);c.call(b,d,e,f)}},e)}function g(a,e,f){j(a,"click",h,e,f);j(a,"mousedown",b,e,f);w?j(a,"touchstart",d,e,f):(j(a,"mousemove",c,e,f),j(a,"mouseover",k,e,f),j(a,"mouseout",
u,e,f))}function c(b,d,c){b=b||window.event;d=b.target||b.srcElement;if(!(1==c.ao.skin&&a.i.a(d,c.adContent,b.currentTarget))){if(!w&&(c.aj!==c.al||c.ak!==c.am))a.g.d(b,c),a.g.f(b,c),a.g.g(b,c),a.g.i(b,c),a.g.h(b,c),a.g.b(c),a.g.c(c),a.g.e(c),0===c.ar.length&&(c.ai=p(c)),c.ar.push(c.aj),c.as.push(c.ak),c.at.push(a.a.f(c)),c.al=c.aj,c.am=c.ak;c.ai!==p(c)&&1<c.ar.length&&n(c,"onMouseMove")}}function b(b,c,d){b=b||window.event;c=b.target||b.srcElement;1==d.ao.skin&&a.i.a(c,d.adContent,b.currentTarget)||
(b={e:2},b.q=d.aq[2]++,b.x=d.aj,b.y=d.ak,a.j.a(d,b))}function d(b,d,c){b={e:23};b.q=c.aq[23]++;b.x=c.aj;b.y=c.ak;var e;d=(new Date).getTime();if("undefined"===typeof c.ct)c.ct=d,e=void 0;else{var f=d-c.ct;c.ct=d;c.cu=Math.min(c.cu,f)||f}b.bz=e;a.j.a(c,b)}function e(b,c,d){if(2==b.an){var e=c.e,k=b.ck;k==a.g.a.f.a&&6===e?(f(b,0),b.cl=a.a.f(b),b.ck=a.g.a.f.b):k==a.g.a.f.b?22===e?(i(b,c),f(b,d),b.cl=a.a.f(b)):7===e&&(1E3<a.a.f(b)-b.cl?(clearTimeout(b.cm),c.e=22,i(b,c),b.cn=0,b.ck=a.g.a.f.a):b.ck=a.g.a.f.c):
k==a.g.a.f.c&&(6==e?(1E3<a.a.f(b)-b.cl&&(clearTimeout(b.cm),b.cn=0,b.cl=a.a.f(b),f(b,0)),b.ck=a.g.a.f.b):22==e&&(i(b,c),b.ck=a.g.a.f.a,b.cn=0))}}function f(b,c){var d=5>b.cn?1E3:2*c,f={e:22};b.cm=a.c.d(function(){e(b,f,d)},d)}function i(b,c){c.q=b.aq[c.e]++;c.m=a.a.f(b);b.cl=c.m;a.j.a(b,c);b.cn++}function k(b,c,d){b=b||window.event;c=b.target||b.srcElement;1==d.ao.skin&&a.i.a(c,d.adContent,b.currentTarget)||(a.g.d(b,d),a.g.f(b,d),a.g.g(b,d),a.g.i(b,d),a.g.h(b,d),e(d,{e:6},0))}function u(b,c,d){b=
b||window.event;c=b.target||b.srcElement;1==d.ao.skin&&a.i.a(c,d.adContent,b.currentTarget)||(a.g.d(b,d),a.g.f(b,d),a.g.g(b,d),a.g.i(b,d),a.g.h(b,d),e(d,{e:7},0))}function h(b,c,d){b=b||window.event;c=b.target||b.srcElement;1==d.ao.skin&&a.i.a(c,d.adContent,b.currentTarget)||(b={e:3},b.q=d.aq[3]++,b.x=d.aj,b.y=d.ak,a.j.a(d,b))}function n(b){b.ai=p(b);var d={e:1};d.q=b.aq[1]++;d.x=b.ar.join("a");d.y=b.as.join("a");for(var c=a.a.f(b),e=b.at,f=[],i=0;i<e.length;i++)isNaN(e[i])||f.push(Math.abs(e[i]-
c));d.c=f.join("a");d.m=c;a.j.a(b,d);b.ar=[];b.as=[];b.at=[]}function p(b){return Math.floor(a.a.f(b)/s)}a.h={};var s=1E3;a.h.a=function(a,b){if(!0===a.isSkin)for(var d=0;d<a.elements.length;d++)g(a.elements[d],a.zr+"-"+d,b);else g(a.aa,a.zr,b)};a.h.b=function(){for(var b in m)if(m.hasOwnProperty(b)){var d=m[b];d&&(a.g.g({type:"scooper"},d),a.g.i({type:"scooper"},d),a.g.h({type:"scooper"},d),1<d.ar.length&&d.ai!==p(d)&&n(d,"scooper"))}}})(h);(function(a){a.k={};var j="undefined"!==typeof window.devicePixelRatio,
g=j&&Math.round(1E3*window.devicePixelRatio),c=a.b.i&&j&&"undefined"!==typeof window.innerHeight&&"undefined"!==typeof window.outerHeight&&Math.round(window.devicePixelRatio*(a.b.j.outerHeight-a.b.j.innerHeight)),b="undefined"!==typeof window.mozInnerScreenX&&"undefined"!==typeof window.screenX;a.k.a=function(b,c){var f;try{var i,k=b.aa.getBoundingClientRect(),g=c||b.WINDOW||a.e.a(b.aa),h=a.d.i(g),n=a.d.j(k,h),p=g.mozInnerScreenX,s=g.mozInnerScreenY,o=window.screenX,m=window.screenY,l=a.d.j({left:n.left+
p,right:n.right+p,top:n.top+s,bottom:n.bottom+s},{left:o,right:o+window.outerWidth,top:m+117/(j?window.devicePixelRatio:1),bottom:m+window.outerHeight}),t=k.width*k.height;i={area:t,percv:(l.right-l.left)*(l.bottom-l.top)/t};var r=a.d.e(i,b);f=i.percv>=r}catch(v){f=!1}return{isVisible:f}};a.k.b=function(){return b};a.k.c=function(){var a={};a.dl=Number(b);"number"===typeof g&&!isNaN(g)&&(a.dm=g);"number"===typeof c&&!isNaN(c)&&(a.dn=c);return a}})(h);(function(a){function j(a){var b=0,f;return function(){var i=
(new Date).getTime();i-b>c&&(f=a.apply(this,arguments),b=i);return f}}function g(b,c,f,i){var k=0,g=0,j=0,h=(new Date).getTime(),p=!1,s=!1,o,m,l,t=0,r=0,v=0,q=0,L=!1,w=a.b.i,D;if(0===i)var z="as",y="ag",E="an",F="ck",G="kw",H="ah",I="aj",M="pg",N="pf",L=!0;else 1===i?(z="cc",y="bw",E="bx",F="ci",G="jz",H="bu",I="dj"):2===i&&(z="cg",y="ce",E="cf",F="cj",G="ts",H="ah",I="dk");this.hadOTS=function(){return s};this.getInViewTime=function(){return k};this.visible=function(){return p};this.update=function(g){var u=
!1,q=b(g);g.elementRect=q.rect;var J=q.isVisible,z=c(g),y=(new Date).getTime(),C=Math.max(Math.min(y-h,1E3),0);h=y;y=!f||a.focus.pageIsVisible(2===i);if((J=J&&y&&!z)&&p)k+=C,j+=C;else if(J||p)C=Math.round(C/2),k+=C,j+=C;!s&&1E3<=j&&(u=s=!0,m=k,o=g.counters.query()[H]);"undefined"===typeof l&&(1E3>=g.counters.query().bu?J&&(l=!0):l=!1);w&&("undefined"===typeof D&&2!==i&&q.elGeo)&&(g=a.b.j,C=g.document,z=q.elGeo.threshold*q.elGeo.elHeight,_isBTFCheck=(void 0!==g.pageYOffset?g.pageYOffset:(C.documentElement||
C.body.parentNode||C.body).scrollTop)+q.elGeo.foldTop>a.l.a()-z,0<q.elGeo.totalArea&&(D=_isBTFCheck));g=q.yMinMax;L&&(y&&"undefined"!==typeof g&&q.elGeo)&&(0<=g.yMax&&0<=g.yMin&&0<q.visibleArea)&&(t=Math.max(g.yMax,t),r=Math.min(g.yMin,r),v=Math.min(1,Math.max((t-r)/q.elGeo.elHeight,v)));J||(j=0);p=J;return u};this.getQS=function(a){g>k&&(g=k);a[z]=Number(s);a[y]=k;a[E]=g;"undefined"!==typeof m&&(a[F]=m);"undefined"!==typeof o&&(a[G]=o);"undefined"!==typeof l&&(a[I]=Number(l));if(!0===L){var b=Math.round(100*
v),d=Math.round(100*q);a[M]=b;a[N]=d;q=v}"undefined"!==typeof D&&(a.ib=Number(D));g=k}}a.l={};var c=150,b={};a.l.a=function(){return w?650:750};a.l.b=function(d){var c=d.zr;b[c]={};d.viewstats={isBigAd:!1};if(a.d.f()){var f=j(a.d.d),i=new g(f,a.e.d,!0,0);b[c].strict=i;f=new g(f,a.e.d,!1,1);b[c].lax=f}!0!==d.isSkin&&a.k&&a.k.b()?(d=new g(a.k.a,a.e.d,!0,2),b[c].pscope=d):a.f&&a.f.j()&&(d=new g(a.f.n,a.e.d,!0,2),b[c].pscope=d)};a.l.c=function(c){var e=b[c.zr],f,i;for(i in e)e.hasOwnProperty(i)&&e[i].update(c)&&
(f=!0);f&&a.e.e(c);a.m.a(c)&&a.e.f(c)};a.l.d=function(b,c){var f=a.l&&a.l.e(b.zr),i=(a.k&&a.k.b()||a.f&&a.f.b)&&f&&f.pscope.getInViewTime()>=c,f=a.d&&a.d.f()&&f&&f.lax&&f.lax.getInViewTime()>=c;return a.b.i?f:i};a.l.f=function(a){delete b[a]};a.l.e=function(a){return b[a]};a.l.g=function(a){var c={},f=b[a],i;for(i in f)f.hasOwnProperty(i)&&f[i].getQS(c);(a=m[a])&&a.viewstats.isBigAd&&(c.el=1);return c}})(h);(function(a){a.n={};a.n.a=function(a,g){var c;g.outerHTML?c=g.outerHTML:(c=document.createElement("div"),
c.appendChild(g.cloneNode(!0)),c=c.innerHTML);c=[/flashvars\s*=\s*(".*?"|'.*?')/i.exec(c),/name\s*=\s*["']flashvars["']\s*value\s*=\s*(".*?"|'.*?')/i.exec(c),/value\s*=\s*(".*?"|'.*?')\s*name\s*=\s*["']flashvars["']/i.exec(c),a];for(var b,d,e={},f=0;f<c.length;f++){if((b=c[f])&&"object"===typeof b&&b[1])b=b[1].replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/^"/g,"").replace(/"$/g,"").replace(/^'/g,"").replace(/'$/g,"");else if("string"===typeof b)b=b.split("?")[1];else continue;if(b){b=b.split("&");
for(var i=0;i<b.length;i++)d=b[i].split("="),2>d.length||"function"==d[0].slice(0,8)||(e[d[0]]=[d[1]])}}return e}})(h);(function(a){a.i={};a.i.b={};a.i.b.a=function(j){if(j=a.a.getElementsByClassName("wrapper-holder","*",j))return[j[0]]};a.i.a=function(j,g,c){if(j._Mt_wIC)return!0;if(j._Mt_wOC)return!1;for(var b=j,d=0;1E3>d&&!a.a.e(g,b);d++){if(b==c||null==b)return j._Mt_wOC=!0,!1;b=b.parentElement}return j._Mt_wIC=!0}})(h);(function(a){function j(b){var c={window:0,transparent:1,opaque:2,direct:3,
gpu:4};if("EMBED"===b.tagName)var e=a.a.getAttribute(b,"wmode");else if("OBJECT"===b.tagName)for(var b=b.getElementsByTagName("param"),f=0;f<b.length;f++){var i=b[f],k=a.a.getAttribute(i,"name"),i=a.a.getAttribute(i,"value");if("wmode"===k){e=i;break}}return e&&c[e.toLowerCase()]||5}function g(b){var d=b.el,e=b.url,f=b.flashVars,i=b.adIds;this.adContent=b.adContent;(new Date).getTime();this.ao=i;this.FIND_AD_TRIES=i.numTries||0;var k;try{if(d){var g=d,h;"DIV"===g.tagName&&((g=d.getElementsByTagName("EMBED")[0])||
(g=d.getElementsByTagName("OBJECT")[0]),g||(g=d.getElementsByTagName("IMG")[0]),g||(g=d));if("OBJECT"===g.tagName){for(var n=0;n<g.children.length;n++)if("movie"===g.children[n].name||"Movie"===g.children[n].name)h=g.children[n].value;g.object&&g.object.Movie?h=g.object.Movie:g.data&&-1!==g.data.indexOf("swf")&&(h=g.data)}if(("EMBED"===g.tagName||"IMG"===g.tagName)&&g.src)h=g.src;var p=a.n.a(h,g);k={adURL:h,flashVars:p}}else k=!1}catch(s){k=!1}k&&k.adURL&&(e=k.adURL);k&&k.flashVars&&(f=k.flashVars);
e&&(0!==e.toLowerCase().indexOf("http:")&&0!==e.toLowerCase().indexOf("https:"))&&("/"===e[0]?e=window.location.protocol+"//"+window.location.host+e:(k=window.location.pathname.split("/").slice(0,-1).join("/"),e=window.location.protocol+"//"+window.location.host+"/"+k+(k?"/":"")+e));"string"!==typeof e&&(e="-");"IFRAME"!==d.tagName&&("IMG"!==d.tagName&&-1===e.indexOf("googlesyndication"))&&(e=e.split("?")[0]);this.zr=i.adNum;m[this.zr]=this;a.m.d(this.zr,[d]);this.ae=e;this.aa=d;this.WINDOW=a.e.a(this.aa);
"undefined"===typeof f&&(f={});l.i[z]=!0;this.eg=[];this.ee={};if(!("skin"in i)||1!=i.skin)this.ed={},a.f.i(this);a.e.g(this);this.ag=f;this.ah=void 0;this.ai=0;this.an=this.am=this.al=this.ak=this.aj=void 0;this.ar=[];this.as=[];this.at=[];this.av=this.au=a.g.a.a.a;this.ax=a.g.a.b.a;this.ay=a.g.a.c.a;this.ba=this.az=a.g.a.d.a;this.bb=a.g.a.e.a;this.by=this.bx=this.bw=this.bv=this.bu=this.bt=this.bs=this.br=this.bq=this.bp=this.bo=this.bm=this.bl=this.bk=this.bi=this.bh=this.bg=this.bf=this.be=this.bd=
this.bc=void 0;this.ca=this.bz=!1;this.cb=this.cu=this.ct=void 0;this.cc=+new Date+12E4;this.BEACON_LAST_SENT_AT=+new Date;this.cl=this.cm=void 0;this.cn=0;this.ck=a.g.a.f.a;this.cd=!1;this.cy=void 0;this.dt=!1;this.db=void 0;this.cf=this.ce=!1;this.af=Number(this.ef);this.eq=!1;this.ds=this.ch=this.dr=this.cg=0;this.dq=this.bn=void 0;this.IR5={MIN:{x:void 0,y:void 0},MAX:{x:void 0,y:void 0},AREA:0};a.l.b(this);this.eo=this.en=this.dm=0;this.ep=this.dd=!1;this.aq={};this.aq.g=0;this.aq[1]=0;this.aq[2]=
0;this.aq[3]=0;this.aq[13]=0;this.aq[0]=0;this.aq[4]=0;this.aq[5]=0;this.aq[6]=0;this.aq[7]=0;this.aq[9]=0;this.aq[8]=0;this.aq[15]=0;this.aq[16]=0;this.aq[21]=0;this.aq[22]=0;this.aq[23]=0;this.INVIEW_TIME_THRESHHOLDS=[5,10,15,30,60];this.DWELL_TIME_THRESHHOLDS=[5,10,15,30,60];this.an=b.adType||c(d);0===this.an&&(this.WMODE=j(d));a.m.c(this)}function c(a){return"IFRAME"===a.tagName?2:"IMG"===a.tagName?1:"EMBED"===a.tagName||"OBJECT"===a.tagName?0:3}a.m={};a.m.b=function(b,d,e,f,i,k){var h;h=1==arguments.length?
arguments[0]:{el:b,url:d,flashVars:f,adIds:i};if(a.i.b.a&&1==i.skin){var A;A=a.i.b.a(b);h.adContent=A}if(!k)return new g(h);if("function"===typeof k)return k(b,d,f,i);k.em=!0;m[k.zr]=k;b[P]=k.zr;b[t]=!0;k.aa=b;k.ae=d;k.an=c(b);0===k.an&&(k.WMODE=j(b));k.ag=f||{};a.h.a(k);h={e:0};h.q=k.aq[0]++;a.j.a(k,h);return k};a.m.c=function(b){b.de=b.ao.startTime;b.RAND=b.ao.rand;(new Date).getTime();b.dd=!0;a.l.c(b);var c={e:0};c.q=b.aq[0]++;a.j.a(b,c);a.h.a(b)};a.m.a=function(b){var c=+new Date,e=c-b.BEACON_LAST_SENT_AT;
if(0<b.DWELL_TIME_THRESHHOLDS.length){var f=1E3*b.DWELL_TIME_THRESHHOLDS[0];if(b.counters.strictDwell.tCur>=f){b.DWELL_TIME_THRESHHOLDS.shift();var i=b.INVIEW_TIME_THRESHHOLDS.length?b.INVIEW_TIME_THRESHHOLDS[0]:60;if(f<i)return!1;if(5E3<e)return!0}}return 0<b.INVIEW_TIME_THRESHHOLDS.length&&(i=1E3*b.INVIEW_TIME_THRESHHOLDS[0],a.l.d(b,i))?(b.INVIEW_TIME_THRESHHOLDS.shift(),!0):0===b.DWELL_TIME_THRESHHOLDS.length&&c>b.cc?(b.cc*=2,!0):!1};a.m.d=function(a,c){for(var e=0;e<c.length;e++){var f=c[e];f[P]=
a;f[t]=!0}}})(h);(function(a){function j(b,c,f){if(!b)return!1;var i=a.a.d(),i=null!==i&&11>i;if(!i)for(var g=b.getElementsByTagName("embed"),j=0;j<g.length;j++){var h=g[j];if(!0!==h[t]&&(-1===h.id.indexOf("moatPx")&&a.a.k(h))&&h.getAttribute("src")){var n=h.getAttribute("src"),i=a.n.a(n,h);return a.m.b(h,n,!1,i,c,f)}}h=b.getElementsByTagName("object");for(j=0;j<h.length;j++)if(g=h[j],a.a.k(g)&&!("undefined"!==typeof g[t]&&!0===g[t]||-1!=g.id.indexOf("moatPx"))){for(b=0;b<g.children.length;b++)if("movie"===
g.children[b].name||"Movie"===g.children[b].name){n=g.children[b].value;for(j=0;j<g.children.length;j++){if(!i&&"EMBED"===g.children[j].tagName){h=g.children[j];if("undefined"!==typeof h[t]&&!0===h[t]||-1!=h.id.indexOf("moatPx"))continue;if(a.a.k(h))return i=a.n.a(n,h),a.m.b(h,n,!1,i,c,f)}if("OBJECT"===g.children[j].tagName&&(h=g.children[j],a.a.k(h)&&!0!==h[t]&&-1===h.id.indexOf("moatPx")))return a.m.b(h,void 0,!1,void 0,c,f)}}g.object&&g.object.Movie?n=g.object.Movie:g.data&&-1!==g.data.indexOf("swf")&&
(n=g.data);i=a.n.a(n,g);return a.m.b(g,n,!1,i,c,f)}if(n=a.o.g(b,c,f))return n;n=b.getElementsByTagName("img");for(j=0;j<n.length;j++)if(i=n[j],!("undefined"!==typeof i[t]&&!0===i[t])){if(a.a.k(i)&&""!==i.src&&-1===document.location.href.indexOf(i.src))return a.m.b(i,i.getAttribute("src"),!1,void 0,c,f);y["1"]=i.offsetWidth+"x"+i.offsetHeight+":"+i.src}return!1}function g(d,e){for(var f=[],g=d.getElementsByTagName("iframe"),j,h=0;h<g.length;h++)if(j=g[h],!j[t]&&a.a.k(j)){var l=a.p.c(j)?!1:!0;(e===
c&&l||e===b&&!l)&&f.push(j)}return f}a.o={};var c=1,b=2;a.o.a=function(b,c,f,g,j){var h=a.o.b,l=a.o.c,n=0,p=function(){c.numTries=n++;return h(b,c,f,g)&&!0};if("skin"in c&&1==c.skin){var m;if(a.b.g)if(a.b.i)if(p=a.p.a(b),p=a.e.a(p))m=p.document.body;else return!1;else return!1;else m=b.ownerDocument.body;c.skin=1;p=function(){c.numTries++;if(a.i.b.a(m))return a.m.b(m,m.nodeName,!1,void 0,c,f)&&!0}}a.c.e(p,l,500,j)};a.o.g=function(b,e,f){b=g(b,c);if(b[0])return a.m.b(b[0],b[0].src,!1,void 0,e,f)};
a.o.f=function(b,c,f){for(var g,b=a.o.e(b,a.o.h),h=0;h<b.length;h++)if(g=b[h],g=a.p.c(g))if(g=j(g.documentElement,c,f))return g};a.o.i=function(b,c,f){for(var g,h,b=a.o.e(b,a.o.h),u=0;u<b.length;u++)if(h=b[u],h=a.p.c(h)){if(g=h.getElementById("flite-1"))if(g=a.m.b(g,g.nodeName,!1,void 0,c,f))return g;if(g=j(h.documentElement,c,f))return g}};a.o.d=j;a.o.b=function(b,c,f,g){var h=a.o.d;if("undefined"===typeof b)return!1;if("HEAD"===b.tagName){var j=b.parentNode;"HTML"===j.tagName&&(j=j.getElementsByTagName("body"),
0<j.length&&(b=j[0]))}if((j=h(b,c,f))||(j=a.o.f(b,c,f)))return j;if(Y||g)if((g=g||a.p.b(b))&&(!a.b.i||!("BODY"===g.nodeName&&a.e.a(g)==a.b.j)))if(j=h(g,c,f))return j;return!1};a.o.e=g;a.o.j=c;a.o.h=b;a.o.k=500;a.o.c=20;a.o.l={object:1,embed:1,img:1,iframe:1}})(h);(function(a){function j(a,c){for(var b={},d=a.split("&"),e=0;e<d.length;e++){var f=d[e].split("=");f[1]="string"===typeof f[1]?f[1].replace(/(^\s+|\s+$)/g,""):"";b[f[0]]=f[1]}"undefined"!==typeof c&&(b.clientZone="undefined"!==c?c:"");return b}
a.q={};a.q.a=function(a){"undefined"===typeof a.startTime&&(a.startTime=(new Date).getTime());"undefined"===typeof a.rand&&(a.rand=Math.floor(Math.random()*Math.pow(10,8)));a.adNum=l.zr;l.zr++};a.q.b=function(g){try{var c=g.className,b=g.getAttribute("src");c.split("\n").join(" ");if(-1!==c.indexOf("moatfooter"))return!1;var d=b.split("?");1==d.length&&(d=b.split("#"));if(1<d.length){var e=j(d[1],"undefined"),c=e,f,i;try{var h=a.p.a(g);if(h&&h.id&&-1<h.id.indexOf("google_ads_iframe")){var l=h.id.match("/[0-9]*/(.*)");
l||(l=h.id.match(/google_ads_iframe_[^\/]*\/(.*)/));i=l[1].split(/_[0-9]*$/)[0]}}catch(m){}if(f=i)f=f.split("/"),c.moatClientSlicer2=f[1]||c.moatClientSlicer2;return c}return!1}catch(n){return!1}};a.q.c=function(a){try{var c=a&&a.className.replace("amp;","").split("?")[1];return c&&j(c)}catch(b){return!1}};a.q.d=function(a){try{var c=zoneRegEx.exec(a.innerHTML);0<c.length&&(zone=c[1]);return zone}catch(b){}};a.q.e=function(a){return(a=unescape(unescape(unescape(unescape(a.innerHTML)))).match(/~fdr=(\d*).*?\/.*?;(\d*)/))?
{adid:a&&a[1]||"-",cid:a&&a[2]||"-"}:!1};a.q.f=function(a,c){return c||{}}})(h);(function(a){function h(c,b){var d,e=[],f,g=a.a.c()?2048:7750,j=b||{};f={};for(d in c)c.hasOwnProperty(d)&&(1==c.e&&("x"===d||"y"===d||"c"===d)?f[d]=c[d].split("a"):e.push(encodeURIComponent(d)+"="+encodeURIComponent(c[d])));d=e.join("&");var e=g-d.length,l=0;if("undefined"!==typeof f.x){for(var m=0,n=0;n<f.x.length;n++)if(m+=f.x[n].length+(f.y[n]?f.y[n].length:0)+(f.c[n]?f.c[n].length:0),m<e)l++;else break;0<l&&(d+="&x="+
f.x.slice(0,l-1).join("a"),d+="&y="+f.y.slice(0,l-1).join("a"),d+="&c="+f.c.slice(0,l-1).join("a"))}for(var p in j)j.hasOwnProperty(p)&&(f="&"+encodeURIComponent(p)+"="+encodeURIComponent(j[p]),f.length+d.length<g&&(d+=f));return d}function g(a,b){for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d])}a.j={};a.j.b=function(c,b){a.q.a(b);var d={};d.e=c;d.i=E;d.cm=Q;if(11===c){var e=[],f;for(f in y)y.hasOwnProperty(f)&&e.push(f+"="+y[f]);d.k=e.join("&")}d.e in T||(d.bq=a.b.b,d.f=Number(!F),d.j=a.b.k,d.o=3,
d.t=b.startTime,d.de=b.rand,d.m=0,d.ar=U,a.a.q(d,"ai",l.z),d.q=l.m++,d.cb=w?1:0,d.cu=R,g(d,a.focus.getQueryString()),a.q.f(b,d),"undefined"!==typeof b&&(d.d=b.moatClientLevel1+":"+b.moatClientLevel2+":"+b.moatClientLevel3+":"+b.moatClientLevel4,d.bo=b.moatClientSlicer1,d.bd=b.moatClientSlicer2),d.ac=1,d.it=a.o.k,d=h(d),l.yh.yi(d+"&cs=0",V,W))};a.j.c=function(c){!0!==c.em&&(delete m[c.zr],clearTimeout(c.cc),a.o.a(D.parentNode,c.ao,c))};a.j.a=function(c,b){if(!c||!0===c.ep)return!1;if(!a.e.h(c))return a.e.i(c),
!1;if("undefined"!==typeof c.ao&&!(2===c.an&&(1===b.e||3===b.e))&&!(b.e in T)){b.lo=c.FIND_AD_TRIES;b.ak=c.ae;c.ah&&(b.a=c.ah);var d=c.ag,e={};if(9===b.e&&2===b.q||25===b.e){for(var f in d)d.hasOwnProperty(f)&&""!==f&&("undefined"!==typeof d[f]&&-1===f.indexOf("dvContains")&&-1===f.indexOf("indexOf")&&-1===f.toLowerCase().indexOf("clicktag"))&&(e["z"+f]=d[f]);b.e=25}0===c.an&&(b.dc=c.WMODE);0!==b.e&&a.e.j(c);c.bi>c.bg&&(c.bg=c.bi);c.bm>c.bk&&(c.bk=c.bm);b.i=E;b.bq=a.b.b;b.g=c.aq.g++;b.h=0<c.aa.offsetHeight?
c.aa.offsetHeight:c.aa.parentNode.offsetHeight;b.cm=Q;b.f=Number(!F);b.j=a.b.k;b.o=3;b.t=c.de;b.de=c.RAND;b.cu=R;b.m=b.m||a.a.f(c);b.ar=U;b.w=0<c.aa.offsetWidth?c.aa.offsetWidth:c.aa.parentNode.offsetWidth;b.cb=w?1:0;b.r=a.f.a;g(b,a.k.c());a.k&&a.k.b()?b.ch=1:a.f&&a.f.b?(b.ch=1,b.ct=a.f.c):b.ch=0;g(b,a.l.g(c.zr));g(b,a.focus.getQueryString());g(b,c.counters.getQs());a.a.q(b,"ai",l.z);a.a.q(b,"ap",c.cb);a.a.q(b,"ax",c.bg);a.a.q(b,"ay",c.bi);a.a.q(b,"az",c.bk);a.a.q(b,"ba",c.bm);a.a.q(b,"aw",c.bc);
a.a.q(b,"bg",c.bd);a.a.q(b,"be",c.be);a.a.q(b,"bc",c.bw);a.a.q(b,"bf",c.by);a.a.q(b,"bh",c.bx);a.a.q(b,"bz",c.cu);b.cl=Math.round(100*c.IR5.AREA/(b.w*b.h));b.au=c.aq[2]-1;b.av=c.aq[3]-1;b.by=c.aq[23]-1;b.at=c.dm;a.q.f(c.ao,b);b.d=c.ao.moatClientLevel1+":"+c.ao.moatClientLevel2+":"+c.ao.moatClientLevel3+":"+c.ao.moatClientLevel4;b.bo=c.ao.moatClientSlicer1;b.bd=c.ao.moatClientSlicer2;b.ab=c.an;b.ac=1;b.it=a.o.k;c.bi=c.bg;c.bm=c.bk;d=h(b,e);l.yh.yi(d+"&cs=0",V,W)}};a.j.d=function(a,b){if(!(2===a.an&&
(1===b.e||3===b.e))){var d=Z;(new Image(1,1)).src=d}};a.j.e=function(c){var b={e:16};b.q=c.aq[16]++;a.j.a(c,b)}})(h);(function(a){function h(a,b,d,e){var f=(new Date).getTime();this.tLast=this.tCur=0;this.update=function(b){var d=(new Date).getTime();a(b)&&(this.tCur+=Math.min(d-f,1E3),"number"===typeof e&&this.tCur>e&&(this.tCur=e));f=d};this.getQs=function(a){data=this.query(a);this.tLast=this.tCur;return data};this.query=function(a){a=a||{};this.tLast>this.tCur&&(this.tLast=this.tCur);a[b]=this.tCur;
a[d]=this.tLast;return a}}function g(){if("undefined"===typeof l.z){l.z=new Date-R;a:{var c=void 0,b;for(b in m)if(m.hasOwnProperty(b)&&(c=m[b])&&"undefined"!==typeof c.ao){if(c.ce)break a;var d={e:4};d.q=c.aq[4]++;d.ai=l.z;a.j.a(c,d);c.ce=!0}a.c.b(q,"scroll",g,"onScroll")}}}a.e={};a.e.k=function(){a.c.a(q,"scroll",g,"onScroll");a.focus.setFocusListeners()};a.e.h=function(c,b){try{var d=c.aa,b=b||c.WINDOW||a.e.a(d);return!d||!b||!d.parentNode?!1:!0}catch(e){return!1}};a.e.j=function(){var c,b;for(b in m)m.hasOwnProperty(b)&&
(c=m[b],a.e.h(c,c.WINDOW)?c.counters.update(c):a.e.i(c))};a.e.i=function(c){clearTimeout(c.cc);c.ep=!0;delete m[c.zr];a.h.a(c,"remove");a.l.f(c.zr);c.aa=null};a.e.e=function(c){c.eq||(c.eq=!0);var b={e:5};b.q=c.aq[5]++;a.j.a(c,b)};a.e.d=function(c){var b;if(1==c.ao.skin)return!1;c.elementRect?(b=c.elementRect.right-c.elementRect.left,c=c.elementRect.bottom-c.elementRect.top):(b=c.aa.offsetWidth,c=c.aa.offsetHeight);return 3>b||3>c||a.focus.pageIsPrerendered()?!0:!1};a.e.a=function(a){try{var b=a&&
a.ownerDocument;return b&&(b.defaultView||b.parentWindow)}catch(d){return!1}};a.e.g=function(c){c.counters={};c.counters.laxDwell=new h(function(){return!a.focus.pageIsPrerendered()},"bu","cd");c.counters.strictDwell=new h(a.focus.pageIsVisible,"ah","am");c.counters.query=function(){var a={},c;for(c in this)if(this.hasOwnProperty(c)){var e=this[c];"function"===typeof e.query&&e.query(a)}return a};c.counters.getQs=function(){var a={},c;for(c in this)if(this.hasOwnProperty(c)){var e=this[c];"function"===
typeof e.getQs&&e.getQs(a)}return a};c.counters.update=function(a){for(var c in this)if(this.hasOwnProperty(c)){var e=this[c];"function"===typeof e.update&&e.update(a)}}};a.e.b=function(c,b){for(var d=[],e,f=0;f<$;f++)if(b!=b.parent){if(e=a.p.a(c,b))d.push(e);else break;b=b.parent;c=e}else break;return d};a.e.l=function(){for(var c in m)if(m.hasOwnProperty(c)){var b=m[c];if(b){var d={e:21};d.q=b.aq[21]++;a.j.a(b,d)}}};a.e.f=function(c){var b={e:9};b.q=c.aq[9]++;c.BEACON_LAST_SENT_AT=+new Date;a.j.a(c,
b)}})(h);(function(a){a.p={};a.p.c=function(h){try{if(h.moatHostileIframe)return null;if(h.src&&(h.src.slice&&"http"===h.src.slice(0,4))&&a.a.g(h.src)!=a.a.g(q.location.toString()))return h.moatHostileIframe=!0,null;var g=h&&(h.contentDocument||h.contentWindow&&h.contentWindow.document);if(g&&"string"===typeof g.location.toString())return g;h.moatHostileIframe=!0;return null}catch(c){return h.moatHostileIframe=!0,null}};a.p.a=function(h,g){return(g=g||a.e.a(h))&&g.frameElement};a.p.b=function(h){return(h=
a.p.a(h))?h.parentNode:null}})(h);(function(a){a.r={};a.r.a=function(h){h[a.b.a]=h[a.b.a]||{zs:!1,zr:0,h:0,m:0,i:{}};var g=h[a.b.a];"undefined"===typeof g.v&&(g.v=F?"undefined"!==typeof h.document.hasFocus&&!w?h.document.hasFocus():!0:!0);g.ye||(g.ye=function(){this.v=true});g.yd||(g.yd=function(){this.v=false})}})(h);(function(a){var h=function(a,c){function b(a,b,c){a&&h.push({qs:a,jsd:b,fld:c});if(0===j&&0<h.length)if(j+=1,a=h.shift(),a.fld&&n&&m&&m.sendMessage)try{m.sendMessage(a)}catch(d){n=
!1,e(a)}else e(a)}function d(){try{return new p(1,1)}catch(a){var b=window.document.createElement("img");b.height=1;b.width=1;return b}}function e(a){var b=d();b.toSend=a;b.onerror=function(){var a=this.toSend;l+=1;var b=(a.jsd+"/pixel.gif?"+a.qs).length;2>l?e(a):q&&b>t&&f()};b.onload=function(){f()};b.src=a.jsd+"/pixel.gif?"+a.qs}function f(){0<j&&(j-=1,b())}var h=[],j=0,l=0,m=!1,n=!1,p,s=c[a];s.yh={};s=s.yh;p=c.Image;s.yi=function(a,c,d){b(a,c,d)};s.yk=function(b){m=!0;var c=a+".yh.",d={},e;try{e=
window.location.protocol}catch(f){e=document.createElement("a"),e.href="",e=e.protocol}d.src="https:"===e?"https://z.moatads.com/swf/MessageSenderV2.swf":"http://s.moatads.com/swf/MessageSenderV2.swf";d.flashVars="r="+c+"zb&s="+c+"zc&e="+c+"zd&td="+b;return d};s.yj=function(){return!1===m};s.zb=function(){try{if(!0===m){var a=c.document.getElementById("moatMessageSender");a&&!a.sendMessage&&(a=c.document.getElementById("moatMessageSenderEmbed"));a&&a.sendMessage&&(n=!0,m=a)}}catch(b){}};s.zc=function(){try{f()}catch(a){}};
s.zd=function(a){try{n=!1,a&&a.jsd&&h.push(a),f()}catch(b){}};var o,q,t=2083;try{o=document.createElement("div"),o.innerHTML="<\!--[if IE 8]>x<![endif]--\>",q="x"===o.innerHTML}catch(w){q=!1}}.toString();a.s={};a.s.a=function(g){if(!l.yh)if("undefined"!==typeof g.eval)g.eval("("+h+")('"+a.b.a+"',window)");else{var c=g.document.createElement("script");c.type="text/javascript";c.text="("+h+")('"+a.b.a+"',window)";g.document.body.insertBefore(c,g.document.body.childNodes[0])}}})(h);if(h.a.i())return!1;
for(var E="USATODAYSMG1",X="usatodaysportsmediagroup156759167425",U="622c351-clean",R=h.b.e,t="moatFound"+E,P="__moat__"+E,G=[16],H=1;2>=H;H++)G.push(16+H),G.push(16-H);var Q=G[Math.floor(Math.random()*G.length)];if(0!=Math.floor(Math.random()*Q))return!1;var Z="",W="afs.moatads.com",V="//v3.moatads.com",Y=h.b.h,F=h.b.i,q=h.b.j;h.a.g(F?q.location.href:q.document.referrer)||h.a.g(window.location.href);var D=h.a.n();if(!D)return!1;h.a.o(D);var w=h.a.h(),z=0,N,O,y={},$=50,I=[],M=[],m={},T={15:"",
12:"",6:"",7:""};h.r.a(q);var l=q[h.b.a];window[h.b.a]=l;h.s.a(q);(function(a){z=l.h;l.h++;l.i[z]=!1;!1===l.zs&&(h.e.k(),l.zs=!0);h.c.c(function(){h.e.j();for(var a in m)m.hasOwnProperty(a)&&h.l.c(m[a])},200);var j=!1;h.c.a(window,"unload",function(){if(!j){h.e.l();j=true}},!1);h.c.a(window,"beforeunload",function(){if(!j){h.e.l();j=true}},!1);h.c.c(h.h.b,100);h.a.c()&&h.c.d(S,3E5);"undefined"===typeof a&&(a=h.q.b(D));var g=D.parentNode;h.c.d(function(){if(l.i[z]===false){h.j.b(11,a);S()}},1E4);h.j.b(17,
a);h.o.a(g,a)})()})()}catch(e$$42){var msg=e$$42.name+" in closure: "+e$$42.message+", stack="+e$$42.stack;try{var pxSrc="//v3.moatads.com/pixel.gif?e=24&d=data%3Adata%3Adata%3Adata&i="+escape("USATODAYSMG1")+"&ac=1&k="+escape(msg)+"&ar="+escape("622c351-clean")+"&j="+escape(document.referrer)+"&cs="+(new Date).getTime(),px=new Image(1,1);px.src=pxSrc}catch(e$$43){}};
